import test from 'node:test';import assert from 'node:assert/strict';import {existsSync} from 'node:fs';import {build} from 'esbuild';import {chromium} from 'playwright';import {defaults} from '../src/shared/preferences';import {serializeExport} from '../src/shared/exports';
const browserPath=existsSync('/usr/bin/chromium')?'/usr/bin/chromium':chromium.executablePath();
test('built activity filters, exports metadata without inputs, and cancels only still-running reviewed IDs',{skip:!existsSync(browserPath)},async()=>{
 const operations=Array.from({length:25},(_,index)=>({id:`owned-${index}`,commandId:`fixture task ${index}`,status:index<3?'running':'succeeded',startedAt:new Date(Date.UTC(2026,9,8,12,index)).toISOString(),stdout:index===0?'matching output':'',stderr:'',exitCode:index<3?undefined:0,args:['private input'],inputs:{token:'not exported'}}));
 const bundle=await build({stdin:{contents:"import './src/renderer/activity-records.ts';",resolveDir:process.cwd()},bundle:true,write:false,format:'iife',platform:'browser',logLevel:'silent'}),browser=await chromium.launch({headless:true,executablePath:browserPath,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:950,height:900}}),errors:string[]=[],exports:{data:unknown;format:string}[]=[];page.on('pageerror',error=>errors.push(error.message));
 try{
  await page.exposeFunction('activityExport',(data:unknown,format:string)=>{serializeExport(data,format as any);exports.push({data,format});return true;});await page.setContent('<mg-activity-records></mg-activity-records>');await page.addScriptTag({content:'window.__name=value=>value;window.material={exportData:(data,format)=>window.activityExport(data,format)};window.cancelled=[];window.addEventListener("cancel-operation",event=>window.cancelled.push(event.detail));'});await page.addScriptTag({content:bundle.outputFiles[0].text});await page.evaluate(({operations,settings})=>Object.assign(document.querySelector('mg-activity-records')!,{operations,settings}),{operations,settings:defaults});
  const activity=page.locator('mg-activity-records');await activity.getByRole('checkbox',{name:/Select /}).first().waitFor();assert.equal(await activity.getByRole('checkbox',{name:/Select /}).count(),20);await activity.getByRole('button',{name:'Select this page (20)',exact:true}).click();await activity.getByRole('button',{name:'Next',exact:true}).click();await activity.getByRole('button',{name:'Select this page (5)',exact:true}).click();assert.equal(await page.evaluate(()=>(document.querySelector('mg-activity-records') as any).selected.size),25);
  const menu=activity.locator('mg-export-menu').first();await menu.getByRole('button',{name:'CSV',exact:true}).click();await menu.getByRole('button',{name:'Choose destination and export',exact:true}).click();assert.equal(exports[0].format,'csv');assert.equal((exports[0].data as unknown[]).length,25);assert.ok(!JSON.stringify(exports[0].data).includes('private input'));assert.ok(!JSON.stringify(exports[0].data).includes('matching output'));
  await activity.getByRole('button',{name:'running (3)',exact:true}).click();await activity.getByRole('button',{name:'Review cancelling 3 running tasks',exact:true}).click();await page.evaluate(()=>{const activity=document.querySelector('mg-activity-records') as any;activity.operations=activity.operations.map((operation:any)=>operation.id==='owned-1'?{...operation,status:'succeeded'}:operation);});await activity.getByRole('button',{name:'Cancel reviewed running tasks',exact:true}).click();assert.deepEqual(await page.evaluate(()=>(window as any).cancelled),['owned-2','owned-0']);assert.equal(await page.evaluate(()=>(document.querySelector('mg-activity-records') as any).operations.find((operation:any)=>operation.id==='owned-0').status),'running');
  await activity.getByRole('textbox',{name:'Search commands, status and session output',exact:true}).fill('matching output');await page.waitForFunction(()=>(document.querySelector('mg-activity-records') as any).filtered().length===1);await page.evaluate(()=>{const activity=document.querySelector('mg-activity-records') as any;activity.operations=[...activity.operations,{id:'owned-new',commandId:'another task',status:'running',startedAt:'2026-10-08T14:00:00.000Z',stdout:'matching output',stderr:''}];});await page.waitForFunction(()=>(document.querySelector('mg-activity-records') as any).filtered().length===2);
  await page.evaluate(settings=>{(document.querySelector('mg-activity-records') as any).settings={...settings,language:'both'};},defaults);await activity.getByRole('textbox',{name:'Search commands, status and session output · 搜尋指令、狀態同工作階段輸出',exact:true}).waitFor();assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
