import {chromium} from 'playwright';
import {build} from 'esbuild';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createServer} from 'node:http';
const directory=await mkdtemp(join(tmpdir(),'material-git-api-controls-'));
await build({entryPoints:[fileURLToPath(new URL('../src/renderer/api-explorer.ts',import.meta.url))],bundle:true,format:'esm',platform:'browser',outfile:join(directory,'api.js')});
const server=createServer(async(request,response)=>{if(request.url==='/api.js'){response.setHeader('Content-Type','text/javascript');response.end(await readFile(join(directory,'api.js')));}else{response.setHeader('Content-Type','text/html');response.end('<!doctype html><html lang="en"><meta charset="utf-8"><title>API component verification</title><body><script type="module" src="/api.js"></script></body></html>');}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const url=`http://127.0.0.1:${server.address().port}`;
const executablePath=process.env.MATERIAL_GIT_CHROMIUM||(existsSync('/usr/bin/chromium')?'/usr/bin/chromium':chromium.executablePath());
let browser;
try {
browser=await chromium.launch({headless:true,executablePath,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
page.setDefaultTimeout(15000);
page.on('pageerror',error=>errors.push(error.message));
await page.goto(url);
await page.waitForFunction(()=>customElements.get('mg-api-explorer'));
await page.evaluate(()=>{
 window.externalLinks=[];window.material={exportData:async()=>true,openExternal:async url=>{window.externalLinks.push(url);}};
 const explorer=document.createElement('mg-api-explorer');
 const operation={operationId:'test/read',method:'GET',path:'/test/{owner}',category:'verification',summary:'Read-only verification fixture',description:'Component transport fixture, not live provider evidence.',deprecated:false,mutating:false,binary:false,parameters:[{name:'owner',in:'path',required:true,description:'Target owner',schema:{type:'string'}},{name:'enabled',in:'query',schema:{type:'boolean',default:false}},{name:'state',in:'query',schema:{type:'string',enum:['open','closed']}}],requestBody:{content:{'application/json':{schema:{type:'object',additionalProperties:false,properties:{}}}}},responses:{'200':{description:'Fixture response'}},references:{},referencesTruncated:false};
 const mutation={...operation,operationId:'test/change',summary:'Mutation gate verification fixture',method:'DELETE',mutating:true};window.calls=[];window.workStates=[];window.addEventListener('api-work-state',event=>window.workStates.push(event.detail));
 explorer.transport=async(action,payload)=>{window.calls.push([action,payload]);if(action==='catalogue')return {operations:[operation,mutation],total:2,page:1,pageSize:25,categories:['verification'],sources:{},counts:{restOperations:2,graphqlTypes:1,graphqlFields:1}};if(action==='describe')return payload==='test/read'?operation:mutation;if(action==='graphqlCatalogue')return {types:[],total:0,page:1,pageSize:25,queryType:'Query',mutationType:'Mutation',sources:{},counts:{}};if(action==='graphqlDescribe')return {name:payload,kind:'OBJECT',description:'Component fixture type',fields:[]};if(action==='execute')return {ok:true,status:200,headers:{'content-type':'application/json'},data:[{name:'component fixture',count:0,enabled:false}],text:'',truncated:false,method:'GET',endpoint:'/test/fixture'};throw Error('Unexpected verification action '+action);};document.body.append(explorer);
});
await page.getByRole('button',{name:'Read-only verification fixture',exact:true}).click();
const remoteRequests=[];page.on('request',request=>{if(!request.url().startsWith(url))remoteRequests.push(request.url());});
await page.evaluate(()=>{const description=document.createElement('mg-api-markdown');description.setAttribute('data-verification','malicious-markdown');description.content='# Provider notes\n\n> A readable blockquote with **strong text**.\n\n[Docs](https://docs.github.com/en/rest)\n\n[Unsafe](javascript:alert(1)) [Plain HTTP](http://example.com) [Relative](/rest) [Credentials](https://user:pass@example.com)\n\n<script>window.apiInjected=true</script><style>body{display:none}</style><iframe src="https://example.com/frame"></iframe><img src="https://example.com/image" onerror="window.apiInjected=true"><p onclick="window.apiInjected=true">Safe paragraph</p>';document.body.append(description);});
const markdown=page.locator('mg-api-markdown[data-verification="malicious-markdown"]');await markdown.getByRole('heading',{name:'Provider notes',exact:true}).waitFor();
if(await markdown.locator('blockquote').count()!==1||await markdown.locator('strong').count()!==1)throw Error('Provider Markdown did not render rich structure');
if(await markdown.locator('script,style:not([data-lit]),iframe,img').filter({visible:true}).count())throw Error('Unsafe embedded content survived');
const security=await markdown.evaluate(element=>({injected:window.apiInjected===true,forbidden:element.shadowRoot.querySelector('.prose').querySelectorAll('script,style,iframe,img,object,embed').length,events:[...element.shadowRoot.querySelector('.prose').querySelectorAll('*')].flatMap(node=>[...node.attributes].filter(attribute=>attribute.name.startsWith('on'))).length,links:[...element.shadowRoot.querySelectorAll('a')].map(anchor=>anchor.getAttribute('href'))}));
if(security.injected||security.forbidden||security.events||security.links.length!==1||security.links[0]!=='https://docs.github.com/en/rest')throw Error('Markdown sanitization failed: '+JSON.stringify(security));
await markdown.getByRole('link',{name:'Docs',exact:true}).click();if(page.url()!==url+'/'||await page.evaluate(()=>window.externalLinks.at(-1))!=='https://docs.github.com/en/rest')throw Error('Provider link bypassed main-process navigation');
await page.evaluate(()=>{const limited=document.createElement('mg-api-markdown');limited.setAttribute('data-verification','bounded-markdown');limited.content='x'.repeat(33000);document.body.append(limited);});
const bounded=page.locator('mg-api-markdown[data-verification="bounded-markdown"]');await bounded.getByText('Description display limit reached.',{exact:true}).waitFor();if(await bounded.locator('.prose').evaluate(node=>node.textContent.length)>32769)throw Error('Markdown input exceeded display bound');
await page.evaluate(()=>document.querySelectorAll('mg-api-markdown[data-verification]').forEach(element=>element.remove()));if(remoteRequests.length)throw Error('Provider description triggered external resource requests');

const categorySelect=page.locator('md-filled-select[label="Category"]');await categorySelect.evaluate(select=>select.updateComplete);if(await categorySelect.evaluate(select=>select.displayText)!=='All categories')throw Error('Initial category label is blank');const contentSelect=page.locator('md-filled-select[label="Content type"]');await contentSelect.evaluate(select=>select.updateComplete);if(await contentSelect.evaluate(select=>select.displayText)!=='application/json')throw Error('Initial content type label is blank');
const owner=page.getByRole('textbox',{name:'owner',exact:true});await owner.fill('fixture-owner');
await page.getByRole('button',{name:'Send request',exact:true}).click();
await page.getByRole('heading',{name:'Response · HTTP 200'}).waitFor();
const sent=await page.evaluate(()=>window.calls.find(([action])=>action==='execute')[1]);
if(sent.path.owner!=='fixture-owner'||sent.query.enabled!==false)throw Error('Typed draft request lost values');
await page.getByRole('button',{name:'Mutation gate verification fixture',exact:true}).click();await owner.fill('mutation-fixture');await page.getByRole('button',{name:'Review request',exact:true}).click();
const confirm=page.getByRole('button',{name:'Confirm and send',exact:true});if(await confirm.isEnabled())throw Error('Untouched gate enabled');
await page.getByRole('checkbox',{name:'I checked the target and affected data',exact:true}).click();if(await confirm.isEnabled())throw Error('One-key gate enabled');
await page.getByRole('checkbox',{name:'I understand this may be irreversible',exact:true}).click();if(await confirm.isEnabled())throw Error('Partial slider gate enabled');
const slider=page.getByRole('slider',{name:'Server change authorization, 0 to 100',exact:true});await slider.focus();await slider.press('End');if(!(await confirm.isEnabled()))throw Error('Full gate not enabled');
await page.getByRole('button',{name:'Emergency exit',exact:true}).click();if(await page.evaluate(()=>window.calls.filter(([action])=>action==='execute').length)!==1)throw Error('Mutation sent during review/cancel');
await page.getByRole('button',{name:'Read-only verification fixture',exact:true}).click();if(await owner.inputValue()!=='fixture-owner')throw Error('Draft lost');
const graphqlTab=page.getByRole('tab',{name:'GraphQL',exact:true}),restTab=page.getByRole('tab',{name:'REST',exact:true});
await restTab.focus();await restTab.press('ArrowRight');await graphqlTab.waitFor();if(await graphqlTab.getAttribute('aria-selected')!=='true'||!(await graphqlTab.evaluate(tab=>tab===tab.getRootNode().activeElement)))throw Error('GraphQL tab lacks active focus after arrow navigation');await graphqlTab.press('Home');await page.getByRole('button',{name:'Read-only verification fixture',exact:true}).click();
await page.getByRole('button',{name:'Discard current draft',exact:true}).click();await page.getByRole('button',{name:'Keep drafts',exact:true}).click();if(await owner.inputValue()!=='fixture-owner')throw Error('Discard cancellation lost draft');
await page.getByRole('button',{name:'Discard current draft',exact:true}).click();await page.getByRole('button',{name:'Discard and reset',exact:true}).click();if(await owner.inputValue()!=='')throw Error('Current draft reset retained edited values');if(!(await page.evaluate(()=>window.workStates.at(-1).dirty)))throw Error('Other dirty draft was incorrectly cleared');
await page.getByRole('button',{name:'Discard all session drafts',exact:true}).click();await page.getByRole('button',{name:'Discard and reset',exact:true}).click();await page.waitForFunction(()=>window.workStates.at(-1)?.dirty===false);
await owner.fill('deferred-fixture');
await page.evaluate(()=>{const explorer=document.querySelector('mg-api-explorer');const original=explorer.transport;window.fixtureTransport=original;explorer.transport=(action,payload)=>action==='execute'?new Promise(resolve=>window.finishRequest=()=>original(action,payload).then(resolve)):original(action,payload);});
await page.getByRole('button',{name:'Send request',exact:true}).click();await page.waitForFunction(()=>typeof window.finishRequest==='function');
await page.evaluate(()=>{document.querySelector('mg-api-explorer').remove();const replacement=document.createElement('mg-api-explorer');replacement.transport=window.fixtureTransport;document.body.append(replacement);});
await page.getByRole('button',{name:'Read-only verification fixture',exact:true}).waitFor();await page.evaluate(()=>document.querySelector('mg-api-explorer').updateComplete);if(!(await page.evaluate(()=>window.workStates.at(-1).busy)))throw Error('Remount masked pending request');
await page.getByRole('button',{name:'Read-only verification fixture',exact:true}).click();if(await page.getByRole('button',{name:'Send request',exact:true}).isEnabled())throw Error('Remounted submit ignores old pending request');
await page.evaluate(()=>window.finishRequest());await page.waitForFunction(()=>window.workStates.at(-1)?.busy===false);if(await page.getByRole('heading',{name:'Response · HTTP 200'}).count())throw Error('Old response appeared in remounted instance');
await page.getByRole('button',{name:'Discard all session drafts',exact:true}).click();await page.getByRole('button',{name:'Discard and reset',exact:true}).click();await page.waitForFunction(()=>window.workStates.at(-1)?.dirty===false);
// New controls use bounded fixtures; no provider mutation is sent.
await page.evaluate(()=>{
 const field=document.createElement('mg-api-field');field.setAttribute('data-verification','json-value');field.label='Flexible value';field.required=true;field.schema={};field.value='';field.addEventListener('value-change',event=>{event.stopPropagation();field.value=event.detail.value;});document.body.append(field);
 const recursive=document.createElement('mg-api-field');recursive.setAttribute('data-verification','recursive-input');recursive.label='Recursive input';recursive.required=true;recursive.schema={$ref:'Filter'};window.inputLoads=0;recursive.referenceLoader=async()=>{window.inputLoads++;return {type:'object',additionalProperties:false,properties:{name:{type:'string'},child:{$ref:'Filter'}}};};recursive.addEventListener('value-change',event=>{event.stopPropagation();recursive.value=event.detail.value;});document.body.append(recursive);
});
const flexible=page.locator('[data-verification="json-value"]');
for(const [type,label] of [['number','Number'],['boolean','Boolean'],['object','Object'],['array','List'],['null','Null']]){await flexible.getByRole('combobox',{name:'JSON value type',exact:true}).click();await flexible.locator(`md-select-option[value="${type}"]`).click();await page.waitForTimeout(250);const value=await flexible.evaluate(field=>field.value);if(type==='number'&&value!==0||type==='boolean'&&value!==false||type==='object'&&(typeof value!=='object'||Array.isArray(value))||type==='array'&&!Array.isArray(value)||type==='null'&&value!==null)throw Error('Typed JSON selector failed '+type);}
const recursive=page.locator('[data-verification="recursive-input"]');await recursive.getByRole('button',{name:'Edit properties (2)',exact:true}).waitFor();if(await page.evaluate(()=>window.inputLoads)!==1)throw Error('Recursive input eagerly expanded');await recursive.getByRole('button',{name:'Edit properties (2)',exact:true}).click();const child=recursive.locator('mg-api-field').filter({has:page.locator('.label').filter({hasText:'child'})}).first();await child.getByRole('switch',{name:'child: include in request',exact:true}).click();await child.getByRole('button',{name:'Edit properties (2)',exact:true}).waitFor();if(await page.evaluate(()=>window.inputLoads)!==2)throw Error('Recursive child was not lazily loaded');await child.getByRole('button',{name:'Edit properties (2)',exact:true}).click();await child.getByRole('switch',{name:'name: include in request',exact:true}).click();await child.getByRole('textbox',{name:'name',exact:true}).fill('nested');if((await recursive.evaluate(field=>field.value))?.child?.name!=='nested')throw Error('Recursive input lost nested typed value');
await page.evaluate(()=>document.querySelectorAll('[data-verification]').forEach(element=>element.remove()));
await page.evaluate(()=>{
 const explorer=document.querySelector('mg-api-explorer'),original=explorer.transport;
 const field=(name,type,args=[])=>({name,type,args,description:'Fixture '+name,deprecated:false});
 window.schemaTypes={Query:{name:'Query',kind:'OBJECT',description:'Query fixture',fields:[field('items','Connection',[{name:'first',type:'Int',description:'Page count',defaultValue:2},{name:'after',type:'String',description:'Cursor'}])]},Connection:{name:'Connection',kind:'OBJECT',description:'Connection fixture',fields:[field('nodes','[Item!]!'),field('pageInfo','PageInfo!')]},Item:{name:'Item',kind:'OBJECT',description:'Item fixture',fields:[field('id','ID!')]},PageInfo:{name:'PageInfo',kind:'OBJECT',description:'Page information fixture',fields:[field('hasNextPage','Boolean!'),field('endCursor','String')]},Choice:{name:'Choice',kind:'ENUM',description:'Choice fixture',enumValues:[{name:'FIRST',description:'First enum choice documentation',deprecated:false}]}};
 window.graphqlCalls=[];
 explorer.transport=async(action,payload)=>{
 if(action==='graphqlCatalogue')return {types:Object.values(window.schemaTypes).filter(type=>!payload.query||type.name.includes(payload.query)),total:5,page:1,pageSize:25,queryType:'Query',mutationType:null,sources:{},counts:{}};
 if(action==='graphqlDescribe')return window.schemaTypes[payload]||{name:payload,kind:'SCALAR',description:'Scalar fixture'};
 if(action==='graphqlBuild')return {document:JSON.stringify(payload),operation:'query',mutating:false};
 if(action==='graphqlExecute'){window.graphqlCalls.push(payload);const after=payload.selections[0].args.after;return {ok:true,status:200,headers:{},data:{data:{items:{nodes:[{id:after?'2':'1'}],pageInfo:{hasNextPage:!after,endCursor:after?'cursor-2':'cursor-1'}}}},text:'',truncated:false,method:'POST',endpoint:'/graphql'};}
 return original(action,payload);
 };
});
await page.getByRole('tab',{name:'GraphQL',exact:true}).click();await page.getByRole('checkbox',{name:'Select field items',exact:true}).click();await page.getByRole('checkbox',{name:'Select field nodes',exact:true}).click();await page.getByRole('checkbox',{name:'Select field id',exact:true}).click();await page.getByRole('button',{name:'Run query',exact:true}).click();await page.getByRole('button',{name:'Load next server page',exact:true}).waitFor();const firstGraphql=await page.evaluate(()=>window.graphqlCalls[0]);if(!firstGraphql.selections[0].selections.find(selection=>selection.field==='pageInfo'))throw Error('Guided query omitted page metadata');await page.getByRole('button',{name:'Load next server page',exact:true}).click();await page.waitForFunction(()=>window.graphqlCalls.length===2);if((await page.evaluate(()=>window.graphqlCalls[1])).selections[0].args.after!=='cursor-1')throw Error('Next query did not use returned cursor');if(await page.getByRole('button',{name:'Load next server page',exact:true}).count())throw Error('Finished GraphQL connection still advances');
await page.getByRole('button',{name:'Browse all GraphQL types',exact:true}).click();await page.getByRole('button',{name:'Choice · ENUM',exact:true}).click();await page.getByText('First enum choice documentation',{exact:true}).waitFor();
await page.getByRole('button',{name:'Browse all GraphQL types',exact:true}).click();await page.getByRole('button',{name:'Discard all session drafts',exact:true}).click();await page.getByRole('button',{name:'Discard and reset',exact:true}).click();
await page.setViewportSize({width:420,height:900});await page.screenshot({path:join(directory,'component-narrow.png'),fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('Narrow overflow');
console.log(JSON.stringify({route:'isolated Chromium component transport fixture',typedReadRequest:sent,mutationSent:false,draftPreserved:true,draftDiscardVerified:true,remountBusyVerified:true,accessibleTabsVerified:true,initialSelectLabelsVerified:true,providerMarkdownSecurityVerified:true,typedJsonSelectorVerified:true,lazyRecursiveInputsVerified:true,graphqlCursorButtonVerified:true,graphqlTypeBrowserVerified:true,narrowOverflow:false,pageErrors:errors}));if(errors.length)throw Error(errors.join('\n'));
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));await rm(directory,{recursive:true,force:true});}
