import{_electron as electron}from'playwright';import{build}from'esbuild';import{mkdtemp,writeFile,readFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import assert from'node:assert/strict';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),root=resolve('.'),dir=await mkdtemp(join(tmpdir(),'appearance-component-'));
const entry=`import{drawVector}from ${JSON.stringify(join(root,'src/renderer/appearance-vector-render.ts'))};window.fixtureDrawVector=drawVector;import {installAppearanceRoutes} from ${JSON.stringify(join(root,'src/renderer/appearance-routes.ts'))};import{appearanceTargetId}from ${JSON.stringify(join(root,'src/renderer/appearance-targets.ts'))};import{restoreAppearance}from ${JSON.stringify(join(root,'src/renderer/appearance.ts'))};import{defaults}from ${JSON.stringify(join(root,'src/shared/preferences.ts'))};window.testTargetId=appearanceTargetId;window.testSettings={...defaults};window.testRoutes=installAppearanceRoutes(document,{settings:()=>window.testSettings});window.testRestore=restoreAppearance;restoreAppearance();`;
const bundle=await build({stdin:{contents:entry,resolveDir:root,loader:'ts'},bundle:true,format:'esm',platform:'browser',write:false});
await writeFile(join(dir,'harness.cjs'),`const{app,BrowserWindow}=require('electron');app.setPath('userData',${JSON.stringify(join(dir,'profile'))});app.whenReady().then(()=>{const w=new BrowserWindow({width:1000,height:760,frame:false,webPreferences:{contextIsolation:true}});w.loadFile(${JSON.stringify(join(dir,'fixture.html'))});});`);
await writeFile(join(dir,'fixture.html'),'<html><body style="margin:24px;font-family:sans-serif;--md-ref-typeface-plain:Arial;--md-ref-typeface-brand:Arial;--md-sys-color-surface:#ffffff;--md-sys-color-surface-container:#f3f0f5;--md-sys-color-surface-container-high:#ece6f0;--md-sys-color-on-surface:#1d1b20"><h1>Appearance component fixture</h1><button id="fixture-target">Fixture action</button><p id="plain-target">Plain fixture text</p></body></html>');
const vectorModule=await build({entryPoints:[join(root,'src/shared/appearance-vector.ts')],bundle:true,format:'esm',platform:'node',write:false});await writeFile(join(dir,'vector.mjs'),vectorModule.outputFiles[0].text);const{validateVector,vectorSvg}=await import('file://'+join(dir,'vector.mjs'));const{PNG}=require('pngjs');
const app=await electron.launch({executablePath:require('electron'),args:['--no-sandbox','--ozone-platform=headless',join(dir,'harness.cjs')],env:{...process.env}});const page=await app.firstWindow();page.setDefaultTimeout(8000);const failures=[];page.on('pageerror',e=>failures.push(e.message));
try{
 await page.setViewportSize({width:1000,height:800});
 // This fixture saves exact export payloads to owned temporary files. It is not the production save-dialog bridge.
 await page.exposeFunction('fixtureVectorExport',async payload=>{const doc=validateVector(payload.document);if(payload.format==='svg')await writeFile(join(dir,'vector.svg'),vectorSvg(doc));else await writeFile(join(dir,'vector.png'),Buffer.from(payload.png.split(',')[1],'base64'));return{saved:true,name:'vector.'+payload.format};});
 await page.evaluate(()=>{window.material={preferencesAdvanced:async()=>({fontFamilies:['system-ui']}),exportAppearance:payload=>window.fixtureVectorExport(payload),exportData:async data=>{window.exportedVectorJson=data;return true;}};});
 await page.addScriptTag({content:bundle.outputFiles[0].text,type:'module'});await page.waitForFunction(()=>window.testRoutes);
 await page.evaluate(()=>window.addEventListener('appearance-work-state',e=>window.lastAppearanceWork=e.detail));
 await page.locator('#fixture-target').focus();await page.keyboard.press('Control+Alt+a');
 const panel=page.locator('[data-appearance-panel]'),editor=panel.locator('mg-appearance'),vector=editor.locator('mg-appearance-vector');
 await vector.getByRole('button',{name:'Vector shapes and paths',exact:true}).click();await vector.getByRole('button',{name:'Add rectangle',exact:true}).click();
 await vector.locator('md-outlined-text-field[label="Shape name"] input').focus();await page.keyboard.press('Control+Alt+a');assert.equal(await panel.count(),2);await page.waitForFunction(()=>window.lastAppearanceWork?.dirty===true);await panel.last().getByRole('button',{name:'Close Esc',exact:true}).click();assert.equal(await panel.count(),1);assert.equal(await page.evaluate(()=>window.lastAppearanceWork.dirty),true);
 const before=await vector.evaluate(el=>el.document.shapes[0].commands[0].x);assert.equal(before,25.6);
 const handle=vector.locator('[data-vector-handle="0-x"]');await handle.focus();await page.keyboard.press('ArrowRight');assert.equal(await vector.evaluate(el=>el.document.shapes[0].commands[0].x),26.6);
 await vector.getByRole('button',{name:'Undo vector edit',exact:true}).click();assert.equal(await vector.evaluate(el=>el.document.shapes[0].commands[0].x),before);
 await handle.scrollIntoViewIfNeeded();const box=await handle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+20,box.y+box.height/2+10,{steps:4});await page.mouse.up();assert.ok(await vector.evaluate(el=>el.document.shapes[0].commands[0].x)>before);
 await vector.getByRole('button',{name:'Undo vector edit',exact:true}).click();assert.equal(await vector.evaluate(el=>el.document.shapes[0].commands[0].x),before);
 await vector.getByRole('button',{name:'Add curve',exact:true}).click();const control=vector.locator('[data-vector-handle="1-x1"]');await control.focus();await page.keyboard.press('ArrowUp');assert.equal(await vector.evaluate(el=>el.shape.commands[1].y1),24.6);
 await vector.getByRole('button',{name:'Undo vector edit',exact:true}).click();await vector.getByRole('button',{name:'Undo vector edit',exact:true}).click();assert.equal(await vector.evaluate(el=>el.document.shapes.length),1);
 // Switching appearance states preserves unapplied previews within the mounted editor.
 assert.equal(await editor.evaluate(el=>el.focusProperty('hover','padding')),true);assert.equal(await vector.evaluate(el=>el.document.shapes.length),0);assert.equal(await editor.evaluate(el=>el.focusProperty('default','padding')),true);assert.equal(await vector.evaluate(el=>el.document.shapes.length),1);
 await panel.getByRole('button',{name:'Close Esc',exact:true}).click();await editor.getByRole('button',{name:'Keep editing',exact:true}).click();assert.equal(await panel.count(),1);
 await vector.getByRole('button',{name:'Export SVG',exact:true}).click();await page.waitForFunction(()=>document.querySelector('mg-appearance').shadowRoot.querySelector('mg-appearance-vector').status==='Export saved.');
 await vector.getByRole('button',{name:'Export PNG',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('mg-appearance').shadowRoot.querySelector('mg-appearance-vector').busy);
 const actual=PNG.sync.read(await readFile(join(dir,'vector.png')));assert.equal(actual.width,128);assert.equal(actual.height,128);const offset=(64*128+64)*4;assert.deepEqual([...actual.data.slice(offset,offset+4)],[103,80,164,255]);assert.match(await readFile(join(dir,'vector.svg'),'utf8'),/<path d="M 25.6 25.6 L /);
 const svgPixels=await page.evaluate(async text=>{const url=URL.createObjectURL(new Blob([text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);return[...ctx.getImageData(64,64,1,1).data];}finally{URL.revokeObjectURL(url);}},await readFile(join(dir,'vector.svg'),'utf8'));assert.deepEqual(svgPixels,[103,80,164,255]);
 const translucent=await vector.evaluate(el=>{const d=structuredClone(el.document);d.shapes[0].opacity=.5;return d;});const translucentSvg=vectorSvg(translucent);const edge=await page.evaluate(async({doc,text})=>{const canvas=document.createElement('canvas');window.fixtureDrawVector(canvas,doc);const png=[...canvas.getContext('2d').getImageData(26,64,1,1).data];const url=URL.createObjectURL(new Blob([text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const svg=document.createElement('canvas');svg.width=128;svg.height=128;const ctx=svg.getContext('2d');ctx.drawImage(image,0,0);return{png,svg:[...ctx.getImageData(26,64,1,1).data]};}finally{URL.revokeObjectURL(url);}},{doc:translucent,text:translucentSvg});assert.deepEqual(edge.png,edge.svg);assert.equal(edge.png[3],128);
 await vector.getByRole('button',{name:'Export vector JSON',exact:true}).click();assert.equal(await page.evaluate(()=>window.exportedVectorJson.schemaVersion),1);
 await vector.getByRole('button',{name:'Add rectangle',exact:true}).click();const paint=vector.locator('mg-appearance-colour');await paint.locator('md-outlined-text-field[label="HEX / HEX8"] input').fill('#00ff00ff');await paint.locator('md-outlined-text-field[label="HEX / HEX8"] input').press('Tab');const blend=vector.locator('md-outlined-select[label="Compositing"]');await blend.click();await blend.locator('md-select-option[value="multiply"]').click();assert.deepEqual(await vector.locator('canvas').evaluate(c=>[...c.getContext('2d').getImageData(64,64,1,1).data]),[0,80,0,255]);for(let i=0;i<3;i++)await vector.getByRole('button',{name:'Undo vector edit',exact:true}).click();assert.equal(await vector.evaluate(el=>el.document.shapes.length),1);
 await vector.getByRole('button',{name:'Add arc',exact:true}).click();assert.equal(await vector.evaluate(el=>el.shape.commands[1].kind),'A');const radius=vector.locator('md-outlined-text-field[label="Coordinate ry"] input');await radius.fill('30');await radius.press('Tab');const rotation=vector.locator('md-outlined-text-field[label="Coordinate rotation"] input');await rotation.fill('25');await rotation.press('Tab');await vector.locator('md-filter-chip[label="Long arc"]').click();const arcDoc=await vector.evaluate(el=>({...structuredClone(el.document),shapes:[structuredClone(el.shape)]}));assert.equal(arcDoc.shapes[0].commands[1].largeArc,true);const arcPixels=await page.evaluate(async({doc,text})=>{const a=document.createElement('canvas');window.fixtureDrawVector(a,doc);const first=a.getContext('2d').getImageData(0,0,128,128).data;const url=URL.createObjectURL(new Blob([text],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const b=document.createElement('canvas');b.width=b.height=128;const ctx=b.getContext('2d');ctx.drawImage(image,0,0);const second=ctx.getImageData(0,0,128,128).data;let painted=0,difference=0;for(let i=3;i<first.length;i+=4){if(first[i]>128)painted++;difference+=Math.abs(first[i]-second[i]);}return{painted,difference};}finally{URL.revokeObjectURL(url);}},{doc:arcDoc,text:vectorSvg(arcDoc)});assert.ok(arcPixels.painted>100);assert.ok(arcPixels.difference<2000);await vector.locator('md-list-item').filter({hasText:'Arc'}).click();await vector.locator('[data-vector-handle="1-x"]').focus();await page.keyboard.press('ArrowRight');assert.equal(await vector.evaluate(el=>el.shape.commands[1].x),103.4);await vector.getByRole('button',{name:'Undo vector edit',exact:true}).click();const arcCommand=vector.locator('md-outlined-select[label="Path command"]');await arcCommand.click();await arcCommand.locator('md-select-option[value="1"]').click();await vector.locator('.stage').scrollIntoViewIfNeeded();await page.screenshot({path:join(dir,'vector-arc-fixture.png')});await vector.getByRole('button',{name:'Replace arc with line',exact:true}).click();assert.equal(await vector.evaluate(el=>el.shape.commands[1].kind),'L');await vector.getByRole('button',{name:'Undo vector edit',exact:true}).click();assert.equal(await vector.evaluate(el=>el.shape.commands[1].kind),'A');await vector.getByRole('button',{name:'Delete shape',exact:true}).click();assert.equal(await vector.evaluate(el=>el.document.shapes.length),1);
 await vector.getByRole('button',{name:'Apply vector fill',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('mg-appearance').shadowRoot.querySelector('mg-appearance-vector').pending);
 await vector.getByRole('button',{name:'Apply vector fill',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('mg-appearance').shadowRoot.querySelector('mg-appearance-vector').pending);
 assert.equal(await editor.evaluate(el=>el.record.default.vector.shapes.length),1);assert.match(await page.locator('#fixture-target').evaluate(el=>getComputedStyle(el).backgroundImage),/^url\("data:image\/png/);
 await vector.locator('.stage').scrollIntoViewIfNeeded();await page.screenshot({path:join(dir,'vector-editor-fixture.png')});
 await panel.getByRole('button',{name:'Close Esc',exact:true}).click();assert.equal(await panel.count(),0);assert.deepEqual(failures,[]);
 console.log(JSON.stringify({fixture:true,route:'Actual Electron components; physical handles and keyboard; owned fixture export bridge',checks:17,png:join(dir,'vector.png'),svg:join(dir,'vector.svg'),arcScreenshot:join(dir,'vector-arc-fixture.png'),screenshot:join(dir,'vector-editor-fixture.png')}));
}catch(error){await page.screenshot({path:join(dir,'failure.png')}).catch(()=>{});console.log(JSON.stringify({fixture:true,evidence:dir,errors:failures}));throw error;}finally{await app.close();}
