import{_electron as electron}from'playwright';import{build}from'esbuild';import{mkdtemp,writeFile,readFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import assert from'node:assert/strict';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),root=resolve('.'),dir=await mkdtemp(join(tmpdir(),'appearance-component-'));
const entry=`import {installAppearanceRoutes} from ${JSON.stringify(join(root,'src/renderer/appearance-routes.ts'))};import{appearanceTargetId}from ${JSON.stringify(join(root,'src/renderer/appearance-targets.ts'))};import{restoreAppearance}from ${JSON.stringify(join(root,'src/renderer/appearance.ts'))};import{defaults}from ${JSON.stringify(join(root,'src/shared/preferences.ts'))};window.testTargetId=appearanceTargetId;window.testSettings={...defaults};window.testRoutes=installAppearanceRoutes(document,{settings:()=>window.testSettings});window.testRestore=restoreAppearance;restoreAppearance();`;
const bundle=await build({stdin:{contents:entry,resolveDir:root,loader:'ts'},bundle:true,format:'esm',platform:'browser',write:false});
await writeFile(join(dir,'harness.cjs'),`const{app,BrowserWindow}=require('electron');app.setPath('userData',${JSON.stringify(join(dir,'profile'))});app.whenReady().then(()=>{const w=new BrowserWindow({width:1000,height:760,frame:false,webPreferences:{contextIsolation:true}});w.loadFile(${JSON.stringify(join(dir,'fixture.html'))});});`);
await writeFile(join(dir,'fixture.html'),'<html><body style="margin:24px;font-family:sans-serif;--md-ref-typeface-plain:Arial;--md-ref-typeface-brand:Arial;--md-sys-color-surface:#ffffff;--md-sys-color-surface-container:#f3f0f5;--md-sys-color-surface-container-high:#ece6f0;--md-sys-color-on-surface:#1d1b20"><h1>Appearance component fixture</h1><button id="fixture-target">Fixture action</button><p id="plain-target">Plain fixture text</p></body></html>');
const app=await electron.launch({executablePath:require('electron'),args:['--no-sandbox','--ozone-platform=headless',join(dir,'harness.cjs')],env:{...process.env}});const page=await app.firstWindow();page.setDefaultTimeout(8000);const failures=[];page.on('pageerror',e=>failures.push(e.message));
try{
 await page.setViewportSize({width:1000,height:760});
 await page.evaluate(()=>{window.material={preferencesAdvanced:async()=>({fontFamilies:['system-ui']})};});
 await page.addScriptTag({content:bundle.outputFiles[0].text,type:'module'});await page.waitForFunction(()=>window.testRoutes);
 assert.equal(await page.evaluate(()=>{const host=document.createElement('div');document.body.append(host);const shadow=host.attachShadow({mode:'open'});shadow.innerHTML='<button>First</button><button>Second</button>';const unique=window.testTargetId(shadow.children[0])!==window.testTargetId(shadow.children[1]);host.remove();return unique;}),true);
 await page.locator('#fixture-target').focus();await page.keyboard.press('Control+Alt+a');
 const panel=page.locator('[data-appearance-panel]'),editor=panel.locator('mg-appearance');await editor.waitFor();
 assert.equal(await panel.getAttribute('aria-modal'),'false');assert.equal(await page.locator('#fixture-target').evaluate(el=>el.hasAttribute('inert')),false);
 const weight=editor.locator('md-outlined-text-field[label="Font weight"]');await weight.waitFor();await weight.locator('input').fill('650');await weight.locator('input').press('Tab');
 await page.waitForFunction(()=>getComputedStyle(document.querySelector('#fixture-target')).fontWeight==='650');
 await editor.locator('md-primary-tab').filter({hasText:'Color'}).click();const color=editor.locator('mg-appearance-colour');await color.locator('md-outlined-text-field[label="HEX / HEX8"] input').fill('#ff000080');await color.locator('md-outlined-text-field[label="HEX / HEX8"] input').press('Tab');
 const cache=await page.evaluate(()=>JSON.parse(localStorage.getItem('material-git.element-appearance.v1')));const record=Object.values(cache)[0];assert.ok(Math.abs(record.default.alpha-128/255)<.000001);assert.equal(record.default.hue,0);
 await color.locator('md-outlined-text-field[label="CSS named color"] input').fill('blue');await color.locator('md-outlined-text-field[label="CSS named color"] input').press('Tab');assert.equal(await color.locator('md-outlined-text-field[label="HEX / HEX8"] input').inputValue(),'#0000ff80');
 await color.locator('md-filter-chip').filter({hasText:'Animated rainbow'}).click();await page.waitForFunction(()=>document.querySelector('[data-appearance-panel] mg-appearance').record.default.colourMode==='rainbow');const hue=await page.locator('#fixture-target').evaluate(el=>getComputedStyle(el).color);await page.waitForTimeout(150);assert.notEqual(await page.locator('#fixture-target').evaluate(el=>getComputedStyle(el).color),hue);await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(50);const still=await page.locator('#fixture-target').evaluate(el=>getComputedStyle(el).color);await page.waitForTimeout(150);assert.equal(await page.locator('#fixture-target').evaluate(el=>getComputedStyle(el).color),still);await color.locator('md-filter-chip').filter({hasText:'Solid color'}).click();
 // Real host clicks cross Material's slots; no forced or synthetic option clicks.
 const select=color.locator('md-outlined-select');await select.click();await color.locator('md-select-option[value="oklch"]').click();await color.locator('md-outlined-text-field[label="C"] input').fill('0.4');await color.locator('md-outlined-text-field[label="C"] input').press('Tab');await color.getByRole('button',{name:'Apply clipped sRGB',exact:true}).waitFor();await color.getByRole('button',{name:'Cancel',exact:true}).click();
 await panel.getByRole('button',{name:'Close Esc',exact:true}).click();assert.equal(await page.locator('#fixture-target').evaluate(el=>document.activeElement===el),true);
 await page.evaluate(()=>{document.querySelector('#fixture-target').removeAttribute('data-mg-appearance');window.testRestore();});assert.equal(await page.locator('#fixture-target').evaluate(el=>getComputedStyle(el).fontWeight),'650');
 await page.locator('#plain-target').click({button:'right'});await panel.getByRole('button',{name:/Edit appearance/}).click();await editor.waitFor();
 await editor.locator('md-outlined-text-field[label="Font weight"] input').focus();await page.keyboard.press('Control+Alt+a');assert.equal(await panel.count(),2);await page.keyboard.press('Escape');assert.equal(await panel.count(),1);
 await page.setViewportSize({width:800,height:700});await page.waitForTimeout(300);assert.equal(await panel.evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}),true);
 await page.screenshot({path:join(dir,'appearance-narrow-fixture.png')});
 assert.equal(await editor.evaluate(el=>el.focusProperty('hover','padding')),true);assert.equal(await editor.evaluate(el=>({state:el.state,inspector:el.inspector})).then(x=>x.state==='hover'&&x.inspector==='geometry'),true);assert.equal(await editor.evaluate(el=>el.focusProperty('default','notAProperty')),false);
 await panel.getByRole('button',{name:'Close Esc',exact:true}).click();await page.evaluate(()=>window.testRoutes.dispose());
 await page.evaluate(()=>{const c=document.createElement('canvas');c.width=2;c.height=3;const ctx=c.getContext('2d');ctx.fillStyle='#ff0000';ctx.fillRect(0,0,1,1);ctx.fillStyle='#00ff00';ctx.fillRect(1,0,1,1);ctx.fillStyle='#0000ff';ctx.fillRect(0,1,2,2);window.rasterSource=c.toDataURL('image/png');const raster=document.createElement('mg-appearance-raster');raster.values={image:window.rasterSource,imageSource:window.rasterSource};raster.addEventListener('raster-apply',event=>window.rasterApplied=event.detail);document.body.append(raster);});
 const raster=page.locator('mg-appearance-raster');await raster.locator('md-outlined-text-field[label="Crop height"] input').fill('1');await raster.locator('md-outlined-text-field[label="Crop height"] input').press('Tab');await raster.locator('md-outlined-select').click();await raster.locator('md-select-option[value="90"]').click();await raster.locator('md-filter-chip').filter({hasText:'Flip horizontally'}).click();await raster.getByRole('button',{name:'Apply image transform',exact:true}).click();
 const pixels=await page.evaluate(async()=>{const result=window.rasterApplied,bytes=Uint8Array.from(atob(result.image.split(',')[1]),c=>c.charCodeAt(0)),bitmap=await createImageBitmap(new Blob([bytes],{type:'image/png'}));const c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;const ctx=c.getContext('2d');ctx.drawImage(bitmap,0,0);bitmap.close();return{width:c.width,height:c.height,pixels:[...ctx.getImageData(0,0,c.width,c.height).data],sourcePreserved:result.imageSource===window.rasterSource};});assert.deepEqual(pixels,{width:1,height:2,pixels:[0,255,0,255,255,0,0,255],sourcePreserved:true});
assert.equal(await panel.count(),0);assert.deepEqual(failures,[]);
 console.log(JSON.stringify({fixture:true,route:'Actual Electron compiled component; physical host clicks and keyboard',checks:15,screenshot:join(dir,'appearance-narrow-fixture.png')}));
}catch(error){console.log('DIAGNOSTIC',await page.locator('mg-appearance').evaluate(el=>({html:el.shadowRoot.innerHTML.slice(0,1000),tabs:[...el.shadowRoot.querySelectorAll('md-primary-tab')].map(x=>({text:x.textContent,role:x.getAttribute('role')}))})).catch(()=>({})));await page.screenshot({path:join(dir,'failure.png')});throw error;}finally{await app.close();}
