import{test}from'node:test';import assert from'node:assert/strict';
import{colourSpaces,colourChannels,channelsColour,parseColourHex,colourHex,inSrgb,colourContrast}from'../src/shared/appearance-colour.js';
import{validateAppearance,appearanceCss}from'../src/shared/appearance.js';
test('all nine color spaces round-trip RGB primaries and mixed alpha colors',()=>{for(const hex of ['#ff0000','#00ff00','#0000ff','#000000','#ffffff','#6a9d3280']){const input=parseColourHex(hex);for(const space of Object.keys(colourSpaces) as (keyof typeof colourSpaces)[]){const channels=colourChannels(space,input).map((n,i)=>Math.max(colourSpaces[space].ranges[i][0],Math.min(colourSpaces[space].ranges[i][1],n)));const out=channelsColour(space,channels,input.a);for(const k of ['r','g','b','a']as const)assert.ok(Math.abs(input[k]-out[k])<.00002,`${space} ${hex} ${k} ${out[k]}`);}}});
test('wide-gamut colors retain out-of-gamut channels until explicit clipping',()=>{const wide=channelsColour('oklch',[.7,.4,130],.3);assert.equal(inSrgb(wide),false);assert.ok(wide.r<0||wide.g<0||wide.b<0||wide.r>1||wide.g>1||wide.b>1);assert.equal(inSrgb(parseColourHex(colourHex(wide,true))),true);assert.equal(wide.a,.3);});
test('transparent contrast composites over the actual background',()=>{assert.equal(colourContrast(parseColourHex('#00000000'),parseColourHex('#ffffff')),1);assert.equal(colourContrast(parseColourHex('#000000'),parseColourHex('#ffffff')),21);assert.ok(colourContrast(parseColourHex('#00000080'),parseColourHex('#ffffff'))<4.1);});
test('channel and alpha bounds fail closed',()=>{for(const [space,values,a]of [['rgb',[999,0,0],1],['lab',[50,Infinity,0],1],['cmyk',[1,2,3],1],['hsl',[0,0,0],2]]as const)assert.throws(()=>channelsColour(space,[...values],a));assert.throws(()=>parseColourHex('red'));assert.throws(()=>parseColourHex('#123456<script>'));});
test('rich typography survives validated state history and emits scoped CSS',()=>{const record=validateAppearance({hover:{wordSpacing:3,textIndent:12,baselineOffset:4,fontVariantCaps:'small-caps',textDirection:'rtl',decorationStyle:'double',textDecoration:'overline line-through',decorationColour:'#12345680',textShadowBlur:8,textShadowColour:'#001122',fontVariationSettings:'"wght" 620, "wdth" 90'}});const css=appearanceCss(record.hover!);for(const literal of ['word-spacing:3px','vertical-align:4px','font-variant-caps:small-caps','direction:rtl','text-decoration-style:double','text-decoration-color:#12345680','font-variation-settings:"wght" 620, "wdth" 90','text-shadow:0px 0px 8px #001122'])assert.ok(css.includes(literal),literal);assert.throws(()=>validateAppearance({default:{fontVariationSettings:'"wght" 500; color:red'}}));assert.throws(()=>validateAppearance({default:{highlightColour:'url(secret)'}}));});

import{rainbowDuration,rainbowCss}from'../src/shared/appearance-rainbow.js';
test('rainbow sentinel remains separate from colors and uses one bounded global CSS clock',()=>{assert.equal(rainbowDuration(1),32);assert.equal(rainbowDuration(5),2);for(const value of [0,6,1.2,NaN,Infinity,'3'])assert.throws(()=>rainbowDuration(value));const record=validateAppearance({default:{colourMode:'rainbow',saturation:0,lightness:0,alpha:.4,backgroundColourMode:'rainbow',borderColourMode:'rainbow'}});const css=appearanceCss(record.default!);assert.match(css,/hsl\(var\(--mg-rainbow-hue,270\) 100% 50% \/ 0.4\)/);assert.equal(css.includes('animation:'),false);assert.match(rainbowCss,/prefers-reduced-motion:reduce/);assert.match(rainbowCss,/animation:none;--mg-rainbow-hue:270/);assert.throws(()=>validateAppearance({default:{hue:'rainbow'}}));});
