import{test}from'node:test';import assert from'node:assert/strict';import{validateVector,vectorPreset,vectorSvg,vectorPath,type VectorDocument}from'../src/shared/appearance-vector.js';import{validateAppearance}from'../src/shared/appearance.js';
const doc=():VectorDocument=>({schemaVersion:1,width:128,height:128,background:'none',shapes:[vectorPreset('rectangle',128,128,'shape')]});
test('structured vector source preserves numeric paths and layer composition',()=>{for(const kind of ['rectangle','ellipse','triangle','curve']as const){const d=doc();d.shapes[0]=vectorPreset(kind,128,128,'shape');d.shapes[0].blend='multiply';assert.deepEqual(validateVector(d),d);assert.equal(validateAppearance({hover:{vector:d}}).hover?.vector?.shapes[0].blend,'multiply');assert.match(vectorPath(d.shapes[0].commands),/^M /);}});
test('vector import refuses SVG markup, URLs, scripts, unsafe commands and excess geometry',()=>{const base=doc();for(const value of ['<svg><script>1</script></svg>',{...base,href:'https://example.com'},{...base,width:513},{...base,width:20.5},{...base,shapes:[{...base.shapes[0],fill:'url(https://example.com/x)'}]},{...base,shapes:[{...base.shapes[0],commands:[{kind:'M',x:0,y:0},{kind:'A',x:0,y:0}]}]},{...base,shapes:[{...base.shapes[0],commands:[{kind:'M',x:0,y:0},{kind:'L',x:Infinity,y:0}]}]},{...base,shapes:[base.shapes[0],base.shapes[0]]},{...base,shapes:Array.from({length:17},(_,i)=>({...base.shapes[0],id:'s'+i}))},JSON.parse('{"schemaVersion":1,"__proto__":{},"width":128,"height":128,"background":"none","shapes":[]}')])assert.throws(()=>validateVector(value));});
test('SVG export is regenerated from safe geometry and never embeds shape metadata',()=>{const d=doc();d.shapes[0].name='<script>alert(1)</script>';d.shapes[0].opacity=.5;const output=vectorSvg(d);assert.match(output,/xmlns="http:\/\/www.w3.org\/2000\/svg"/);assert.match(output,/opacity="0.5"/);assert.match(output,/fill="#6750a4"/);assert.equal(output.includes('<script>'),false);assert.equal(output.includes('href='),false);assert.equal(output.includes('foreignObject'),false);});
test('all closed-path and curve commands retain their distinct control coordinates',()=>{const d=doc();d.shapes[0].commands=[{kind:'M',x:0,y:0},{kind:'Q',x1:1,y1:2,x:3,y:4},{kind:'C',x1:5,y1:6,x2:7,y2:8,x:9,y:10},{kind:'Z'}];assert.equal(vectorPath(validateVector(d).shapes[0].commands),'M 0 0 Q 1 2 3 4 C 5 6 7 8 9 10 Z');});

import{convertVectorCommand}from'../src/shared/appearance-vector.js';
test('segment conversion retains endpoints and exactly elevates quadratic degree',()=>{const commands=[{kind:'M' as const,x:0,y:0},{kind:'Q' as const,x1:3,y1:6,x:9,y:0}],next=convertVectorCommand(commands,1,'C');assert.deepEqual(next[1],{kind:'C',x:9,y:0,x1:2,y1:4,x2:5,y2:4});assert.deepEqual(commands[1],{kind:'Q',x1:3,y1:6,x:9,y:0});assert.deepEqual(convertVectorCommand(next,1,'L')[1],{kind:'L',x:9,y:0});assert.throws(()=>convertVectorCommand(commands,0,'L'));});

test('elliptical arcs retain bounded radii, rotation and explicit sweep flags',()=>{const d=doc();d.shapes=[vectorPreset('arc',128,128,'arc')];const valid=validateVector(d),arc=valid.shapes[0].commands[1];assert.deepEqual(arc,{kind:'A',rx:38.4,ry:38.4,rotation:0,largeArc:false,sweep:true,x:102.4,y:64});assert.match(vectorSvg(valid),/A 38.4 38.4 0 0 1 102.4 64/);for(const patch of [{rx:-1},{ry:1025},{rotation:361},{largeArc:1},{sweep:'true'}])assert.throws(()=>validateVector({...d,shapes:[{...d.shapes[0],commands:[d.shapes[0].commands[0],{...arc,...patch}]}]}));assert.deepEqual(convertVectorCommand(valid.shapes[0].commands,1,'L')[1],{kind:'L',x:102.4,y:64});assert.throws(()=>convertVectorCommand(valid.shapes[0].commands,1,'C'));});
