import test from 'node:test';import assert from 'node:assert/strict';import {existsSync} from 'node:fs';import {mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {randomBytes,createCipheriv,createDecipheriv} from 'node:crypto';import {build} from 'esbuild';import {chromium} from 'playwright';import {createSecurityService,totp,type SecretVault} from '../src/main/security';import {parseOtpAuth} from '../src/shared/security';import {defaults} from '../src/shared/preferences';import {serializeExport} from '../src/shared/exports';
const browserPath=existsSync('/usr/bin/chromium')?'/usr/bin/chromium':chromium.executablePath();
function vault():SecretVault{const key=randomBytes(32);return{isEncryptionAvailable:()=>true,encryptString(value){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,cipher.update(value,'utf8'),cipher.final(),cipher.getAuthTag()]);},decryptString(bytes){const cipher=createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));cipher.setAuthTag(bytes.subarray(-16));return Buffer.concat([cipher.update(bytes.subarray(12,-16)),cipher.final()]).toString('utf8');}};}
test('built authenticator performs real manual enrollment, labels, grouping, redacted export and exact two-key removal in three language modes',{skip:!existsSync(browserPath)},async()=>{
 const directory=await mkdtemp(path.join(tmpdir(),'mg-authenticator-browser-')),now=1760000000000,service=createSecurityService({directory:path.join(directory,'shared'),authenticatorDirectory:path.join(directory,'auth'),vault:vault(),now:()=>now}),calls:{action:string;payload:unknown}[]=[],exports:{data:unknown;format:string}[]=[],bundle=await build({stdin:{contents:"import './src/renderer/authenticator.ts';",resolveDir:process.cwd()},bundle:true,write:false,format:'iife',platform:'browser',logLevel:'silent'}),browser=await chromium.launch({headless:true,executablePath:browserPath,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:850,height:950}}),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 try{
  await page.exposeFunction('nativeSecurity',(action:string,payload:Record<string,unknown>)=>{calls.push({action,payload});return service.handle(action,payload);});await page.exposeFunction('exportMetadata',(data:unknown,format:string)=>{serializeExport(data,format as any);exports.push({data,format});return true;});await page.setContent('<mg-authenticator></mg-authenticator>');await page.addScriptTag({content:'window.__name=value=>value;window.material={security:(action,payload)=>window.nativeSecurity(action,payload),exportData:(data,format)=>window.exportMetadata(data,format)};'});await page.addScriptTag({content:bundle.outputFiles[0].text});await page.evaluate(settings=>Object.assign(document.querySelector('mg-authenticator')!,{settings,vaultAvailable:true}),defaults);const authenticator=page.locator('mg-authenticator');
  await authenticator.getByRole('switch',{name:'Use manual base32 and parameters',exact:true}).click();await authenticator.getByRole('textbox',{name:'Pairing issuer',exact:true}).fill('Fixture');await authenticator.getByRole('textbox',{name:'Account for a new local pairing',exact:true}).fill('Owned fixture');await authenticator.getByRole('textbox',{name:'New base32 secret',exact:true}).fill('JBSW Y3DP EHPK 3PXP');
  const parameters=parseOtpAuth('otpauth://totp/Fixture%3AOwned%20fixture?secret=JBSWY3DPEHPK3PXP&issuer=Fixture');await authenticator.getByRole('textbox',{name:'Current code to confirm pairing',exact:true}).fill(totp(parameters,now));await authenticator.getByRole('button',{name:'Confirm and store enrollment',exact:true}).click();await page.waitForFunction(()=>(document.querySelector('mg-authenticator') as any).entries.length===1);assert.equal(await page.evaluate(()=>(document.querySelector('mg-authenticator') as any).secret),'');assert.equal(await authenticator.getByRole('img').count(),0);
  await authenticator.getByRole('button',{name:'Edit labels and group',exact:true}).click();await authenticator.getByRole('textbox',{name:'Entry display label',exact:true}).fill('Named fixture');await authenticator.getByRole('button',{name:'Save entry labels',exact:true}).click();await page.waitForFunction(()=>(document.querySelector('mg-authenticator') as any).entries[0].name==='Named fixture');await authenticator.getByRole('textbox',{name:'New authenticator group',exact:true}).fill('Owned group');await authenticator.getByRole('button',{name:'Create local group',exact:true}).click();await page.waitForFunction(()=>(document.querySelector('mg-authenticator') as any).groups.length===1);
  await authenticator.getByRole('button',{name:'Select all matches',exact:true}).click();await authenticator.getByRole('button',{name:'Move selected matches to group',exact:true}).click();await authenticator.getByRole('option',{name:'Owned group',exact:true}).click();await authenticator.getByRole('button',{name:'Move selected matches',exact:true}).click();await page.waitForFunction(()=>(document.querySelector('mg-authenticator') as any).entries[0].groupId!== '');await authenticator.locator('mg-export-menu').getByRole('button',{name:'Choose destination and export',exact:true}).click();assert.equal(exports.length,1);assert.ok(!JSON.stringify(exports[0].data).includes(parameters.secret));assert.ok(!JSON.stringify(exports[0].data).includes(totp(parameters,now)));assert.equal((exports[0].data as any[])[0].groupName,'Owned group');
  await authenticator.getByRole('button',{name:'Review removing selected matches',exact:true}).click();const apply=authenticator.getByRole('button',{name:'Apply reviewed action',exact:true}),slider=authenticator.getByRole('slider',{name:'Slide from zero to 100 to confirm this exact action',exact:true});assert.equal(await apply.isEnabled(),false);assert.equal(await slider.isEnabled(),false);await authenticator.getByRole('checkbox',{name:'Key one: I reviewed the exact entries',exact:true}).click();assert.equal(await slider.isEnabled(),false);await authenticator.getByRole('checkbox',{name:'Key two: I understand the irreversible or password-loss consequences',exact:true}).click();assert.equal(await slider.isEnabled(),true);await slider.press('ArrowRight');assert.equal(await apply.isEnabled(),false);assert.ok(!calls.some(call=>call.action==='authenticatorRemove'));await authenticator.getByRole('button',{name:'Emergency exit',exact:true}).click();assert.equal((await service.handle('authenticatorList') as any).entries.length,1);
  for(const language of ['yue','both'] as const){await page.evaluate(({settings,language})=>{(document.querySelector('mg-authenticator') as any).settings={...settings,language,englishHumor:1,cantoneseHumor:5};},{settings:defaults,language});const searchName=language==='yue'?'搜尋本機驗證器項目':'Search local authenticator entries · 搜尋本機驗證器項目';await authenticator.getByRole('textbox',{name:searchName,exact:true}).waitFor();assert.equal((await service.handle('authenticatorList') as any).entries[0].account,'Owned fixture');}
  await page.evaluate(settings=>{(document.querySelector('mg-authenticator') as any).settings=settings;},defaults);await authenticator.getByRole('button',{name:'Review removing selected matches',exact:true}).click();await authenticator.getByRole('checkbox',{name:'Key one: I reviewed the exact entries',exact:true}).click();await authenticator.getByRole('checkbox',{name:'Key two: I understand the irreversible or password-loss consequences',exact:true}).click();await slider.press('End');await apply.click();await page.waitForFunction(()=>(document.querySelector('mg-authenticator') as any).entries.length===0);assert.equal(calls.filter(call=>call.action==='authenticatorRemove').length,1);assert.equal((await service.handle('authenticatorList') as any).entries.length,0);assert.deepEqual(errors,[]);
 }finally{await browser.close();service.close();await rm(directory,{recursive:true,force:true});}
});
