import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {EventEmitter} from 'node:events';import {PassThrough} from 'node:stream';import {spawn,type ChildProcess} from 'node:child_process';
import {AuthService} from '../src/main/auth';import {readSshPublicKey} from '../src/main/auth-ssh';
function field(value:Buffer){const prefix=Buffer.alloc(4);prefix.writeUInt32BE(value.length);return Buffer.concat([prefix,value]);}
const key='ssh-ed25519 '+Buffer.concat([field(Buffer.from('ssh-ed25519')),field(Buffer.alloc(32,7))]).toString('base64')+' fixture';
class Child extends EventEmitter {stdout=new PassThrough();stderr=new PassThrough();stdin=new PassThrough();killed=false;kill(){this.killed=true;queueMicrotask(()=>this.emit('close',null));return true;}}
async function fixture(){const directory=await mkdtemp(join(tmpdir(),'material-git-public-key-')),path=join(directory,'id.pub');await writeFile(path,key+'\n',{mode:0o600});const calls:{args:string[];input?:string;child:Child}[]=[],guards:{action:string;hostname?:string;login?:string}[]=[];let login='octocat',id=7,reject=false,held=false,blocked=false,completed=0;
 const service=new AuthService('fixture-gh',directory,{allowedHosts:['forge.example'],pickSshPublicKey:async()=>path,authorize:async(action,payload)=>{guards.push({action,hostname:payload.hostname,login:payload.login});if(blocked&&action==='ssh-key-apply')throw Error('Fixture account lock is closed');},completed:async()=>{completed++;},spawn:(_binary,args,options)=>{assert.equal(options.shell,false);const child=new Child(),call={args,child,input:''};calls.push(call);if(args.includes('--method=POST')){child.stdin.on('data',chunk=>call.input+=String(chunk));child.stdin.on('end',()=>{if(held)return;queueMicrotask(()=>{if(!reject){const body=JSON.parse(call.input);child.stdout.end(JSON.stringify({id:101,key:body.key}));}child.stderr.end('Synthetic provider detail must not enter state');child.emit('close',reject?1:0);});});}else queueMicrotask(()=>{child.stdout.end(JSON.stringify(args[0]==='api'?{id,login}:{hosts:{'forge.example':[{login,active:true,state:'success',scopes:'repo,admin:public_key',gitProtocol:'ssh',tokenSource:'keyring'}]}}));child.emit('close',0);});return child as unknown as ChildProcess;}});
 return {service,path,directory,calls,guards,login:(value:string)=>login=value,id:(value:number)=>id=value,reject:()=>reject=true,hold:()=>held=true,lock:()=>blocked=true,completed:()=>completed,uploads:()=>calls.filter(call=>call.args.includes('--method=POST')),close:async()=>{await service.action('cancel');await rm(directory,{recursive:true,force:true});}};
}
test('public-key file receipt rejects private content, bundles, oversize and symbolic links',async()=>{const f=await fixture();try{const read=await readSshPublicKey(f.path);assert.equal(read.algorithm,'ssh-ed25519');assert.match(read.fingerprint,/^SHA256:/);for(const invalid of ['-----BEGIN OPENSSH PRIVATE KEY-----\nprivate',key+'\n'+key,'ssh-ed25519 invalid','x'.repeat(16385)]){await writeFile(f.path,invalid);await assert.rejects(readSshPublicKey(f.path));}await writeFile(f.path,key);const link=join(f.directory,'link.pub');await symlink(f.path,link);await assert.rejects(readSshPublicKey(link),/symbolic links/);}finally{await f.close();}});
test('SSH key review binds host, native public file and effective account; Apply uploads only exact reviewed bytes',async()=>{const f=await fixture();try{const states:unknown[]=[];f.service.subscribe(state=>states.push(state));const state=await f.service.action('ssh-key-review',{hostname:'forge.example',login:'octocat',title:'Reviewed key'}),review=state.sshKeyReview!;assert.ok(review.reviewId);assert.equal(review.hostname,'forge.example');assert.equal(f.uploads().length,0);assert.ok(!JSON.stringify([state,...states]).includes(f.path));assert.ok(!JSON.stringify([state,...states]).includes(key));const result=await f.service.action('ssh-key-apply',{reviewId:review.reviewId,confirmed:true});assert.equal(result.status,'authenticated');assert.match(result.message!,/SSH public key uploaded/);assert.equal(f.uploads().length,1);assert.deepEqual(JSON.parse(f.uploads()[0].input!),{title:'Reviewed key',key});assert.ok(f.uploads()[0].args.includes('--hostname=forge.example'));assert.ok(!f.uploads()[0].args.includes(key));assert.equal(f.completed(),1);assert.ok(f.guards.some(guard=>guard.action==='ssh-key-apply'&&guard.hostname==='forge.example'&&guard.login==='octocat'));assert.ok(!JSON.stringify(result).includes('Synthetic provider detail'));await assert.rejects(f.service.action('ssh-key-apply',{reviewId:review.reviewId,confirmed:true}),/expired/);}finally{await f.close();}});
test('changed native file, effective account and closed stored-action lock refuse upload',async()=>{for(const mode of ['file','account','lock'] as const){const f=await fixture();try{const review=(await f.service.action('ssh-key-review',{login:'octocat'})).sshKeyReview!;if(mode==='file')await writeFile(f.path,key+' changed');if(mode==='account')f.id(8);if(mode==='lock')f.lock();let result;try{result=await f.service.action('ssh-key-apply',{reviewId:review.reviewId,confirmed:true});}catch(error){assert.equal(mode,'lock');}if(result){assert.equal(result.status,'failed');assert.ok(!result.message);assert.match(result.error!,/changed/);}assert.equal(f.uploads().length,0);assert.equal(f.completed(),0);}finally{await f.close();}}});
test('provider refusal and cancellation remain failed outcomes and consume attempted action authorization',async()=>{for(const mode of ['reject','cancel'] as const){const f=await fixture();try{const review=(await f.service.action('ssh-key-review',{login:'octocat'})).sshKeyReview!;if(mode==='reject')f.reject();else f.hold();const operation=f.service.action('ssh-key-apply',{reviewId:review.reviewId,confirmed:true});if(mode==='cancel'){while(!f.uploads().length)await new Promise(resolve=>setImmediate(resolve));await f.service.action('cancel');}const result=await operation;assert.equal(result.status,'failed');assert.equal(result.message,undefined);assert.match(result.error!,mode==='reject'?/refused/:/cancelled.*uncertain/);assert.equal(f.completed(),1);if(mode==='cancel')assert.equal(f.uploads()[0].child.killed,true);}finally{await f.close();}}});
test('issued SSH review cleanup needs only its exact UUID behind account locks and context drift',async()=>{const f=await fixture();try{const review=(await f.service.action('ssh-key-review',{login:'octocat'})).sshKeyReview!;f.lock();f.login('changed');const reads=f.calls.length;await f.service.action('ssh-key-discard',{reviewId:review.reviewId});await f.service.action('ssh-key-discard',{reviewId:review.reviewId});assert.equal(f.calls.length,reads);assert.equal(f.service.snapshot().sshKeyReview,undefined);for(const payload of [{reviewId:'00000000-0000-4000-8000-000000000123'},{reviewId:review.reviewId,hostname:'forge.example'}])await assert.rejects(f.service.action('ssh-key-discard',payload),/issued/);await assert.rejects(f.service.action('ssh-key-apply',{reviewId:review.reviewId,confirmed:true}),/lock|expired/);}finally{await f.close();}});

test('private authentication adapter sends the reviewed public key through a real bounded native stdin process',async()=>{
 const f=await fixture(),script=join(f.directory,'provider-fixture.cjs');await writeFile(script,`const args=process.argv.slice(2);if(args[0]==='api'&&args.includes('--method=POST')){let input='';process.stdin.on('data',chunk=>input+=chunk);process.stdin.on('end',()=>{const body=JSON.parse(input);process.stdout.write(JSON.stringify({id:101,key:body.key}));});}else process.stdout.write(JSON.stringify(args[0]==='api'?{id:7,login:'octocat'}:{hosts:{'forge.example':[{login:'octocat',active:true,state:'success',tokenSource:'keyring',scopes:'repo,admin:public_key',gitProtocol:'ssh'}]}}));`);
 const calls:string[][]=[],service=new AuthService('fixture-provider',f.directory,{allowedHosts:['forge.example'],pickSshPublicKey:async()=>f.path,spawn:(_binary,args,options)=>{calls.push(args);return spawn(process.execPath,[script,...args],{...options,env:{PATH:process.env.PATH}});}});
 try{const review=(await service.action('ssh-key-review',{login:'octocat'})).sshKeyReview!;const result=await service.action('ssh-key-apply',{reviewId:review.reviewId,confirmed:true});assert.equal(result.status,'authenticated');assert.match(result.message!,/public key uploaded/);assert.ok(calls.some(args=>args.includes('--input=-')&&args.includes('--hostname=forge.example')));assert.ok(!JSON.stringify(calls).includes(key));}finally{await service.action('cancel');await f.close();}
});
