import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {randomUUID,randomBytes,createCipheriv,createDecipheriv} from 'node:crypto';
import {createSecurityService,totp,type SecretVault} from '../src/main/security';import {encryptAuthenticatorBackup,decryptAuthenticatorBackup} from '../src/main/authenticator-store';import {parseOtpAuth} from '../src/shared/security';import type {AuthenticatorEntry,AuthenticatorReview} from '../src/shared/security-authenticator';
function vault():SecretVault{const key=randomBytes(32);return{isEncryptionAvailable:()=>true,encryptString(value){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.update(value,'utf8'),c.final(),c.getAuthTag()]);},decryptString(bytes){const c=createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));c.setAuthTag(bytes.subarray(-16));return Buffer.concat([c.update(bytes.subarray(12,-16)),c.final()]).toString('utf8');}};}
const password='isolated backup password',now=1760000000000,parameters=parseOtpAuth('otpauth://totp/Fixture%3AOwned?secret=JBSWY3DPEHPK3PXP&issuer=Fixture'),gate={keyOne:true,keyTwo:true,confirmation:100};
function contents(){const group={id:randomUUID(),name:'Imported group',icon:'folder'},make=(account:string)=>{const p={...parameters,account,algorithm:'SHA256' as const,digits:8 as const,period:45};const {secret:_,...facts}=p;return{id:randomUUID(),...facts,name:'Backup '+account,icon:'book',groupId:group.id,parameters:p};};return{schema:'material-git-authenticator-contents',version:1,entries:[make('Owned'),make('New')],groups:[group]};}
test('native protected import authenticates before redacted immutable review, applies exact duplicate policy and preserves restart encryption',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'mg-auth-import-')),v=vault(),metadata:unknown[]=[],backup=contents();let picked:string|null=JSON.stringify(encryptAuthenticatorBackup(backup,password)),picks=0;const options={directory:path.join(directory,'shared'),authenticatorDirectory:path.join(directory,'auth'),vault:v,now:()=>now,chooseSensitiveImport:async()=>{picks++;return picked;},recordMutation:async(action:string,value:unknown)=>{metadata.push({action,value});}},service=createSecurityService(options);try{
 const original=await service.handle('authenticatorEnroll',{parameters,code:totp(parameters,now)}) as AuthenticatorEntry;await assert.rejects(service.handle('authenticatorImportReview',{backupPassword:password,duplicatePolicy:'overwrite',path:'/arbitrary/file'}),/Unexpected/);assert.equal(picks,0);await assert.rejects(service.handle('authenticatorImportReview',{backupPassword:'wrong backup password',duplicatePolicy:'skip'}),/authenticated/);assert.equal((await service.handle('authenticatorList') as any).entries.length,1);
 const reviewed=(await service.handle('authenticatorImportReview',{backupPassword:password,duplicatePolicy:'skip'}) as any).review as AuthenticatorReview;assert.deepEqual(reviewed.changes?.map(change=>change.decision),['skip','add']);assert.ok(!JSON.stringify(reviewed).includes(parameters.secret));assert.ok(!JSON.stringify(reviewed).includes('encrypted'));assert.equal(reviewed.entries[0].id,original.id);assert.notEqual(reviewed.entries[1].id,backup.entries[1].id);await assert.rejects(service.handle('authenticatorImport',{reviewId:reviewed.id,keyOne:true,keyTwo:false,confirmation:100}),/both/);assert.equal((await service.handle('authenticatorList') as any).entries.length,1);
 reviewed.entries[0].id=randomUUID();reviewed.changes![0].decision='replace';await service.handle('authenticatorDiscardReview',{reviewId:reviewed.id});await assert.rejects(service.handle('authenticatorImport',{reviewId:reviewed.id,...gate}),/expired/);const skip=(await service.handle('authenticatorImportReview',{backupPassword:password,duplicatePolicy:'skip'}) as any).review;assert.deepEqual(await service.handle('authenticatorImport',{reviewId:skip.id,...gate}),{imported:1,replaced:0,skipped:1});let rows=(await service.handle('authenticatorList') as any).entries;assert.equal(rows[0].algorithm,'SHA1');assert.equal(rows[1].account,'New');assert.equal(rows[1].groupId,(await service.handle('authenticatorList') as any).groups[0].id);
 const replace=(await service.handle('authenticatorImportReview',{backupPassword:password,duplicatePolicy:'replace'}) as any).review;assert.deepEqual(replace.changes.map((change:any)=>change.decision),['replace','replace']);assert.equal(replace.changes[0].before.algorithm,'SHA1');await assert.rejects(service.handle('authenticatorRemove',{reviewId:replace.id,...gate}),/exact/);assert.deepEqual(await service.handle('authenticatorImport',{reviewId:replace.id,...gate}),{imported:0,replaced:2,skipped:0});rows=(await service.handle('authenticatorList') as any).entries;assert.equal(rows[0].id,original.id);assert.equal(rows[0].name,'Backup Owned');assert.equal(rows[0].algorithm,'SHA256');await assert.rejects(service.handle('authenticatorImport',{reviewId:replace.id,...gate}),/expired/);
 assert.ok(!(await readFile(path.join(options.authenticatorDirectory,'authenticator.json'),'utf8')).includes(parameters.secret));assert.ok(!JSON.stringify(metadata).includes(parameters.secret));const reopened=createSecurityService(options);assert.deepEqual((await reopened.handle('authenticatorList') as any).entries,rows);reopened.close();picked=null;assert.deepEqual(await service.handle('authenticatorImportReview',{backupPassword:password,duplicatePolicy:'skip'}),{cancelled:true});
 }finally{service.close();await rm(directory,{recursive:true,force:true});}});
test('native protected import rejects hostile authenticated contents, excessive work parameters and stale or locked apply without writes',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'mg-auth-import-negative-'));let clock=now,picked:string|null='',picks=0;const options={directory:path.join(directory,'shared'),authenticatorDirectory:path.join(directory,'auth'),vault:vault(),now:()=>clock,chooseSensitiveImport:async()=>{picks++;return picked;}},service=createSecurityService(options);try{
 const request={backupPassword:password,duplicatePolicy:'skip'},valid=contents(),seal=(data:unknown)=>JSON.stringify(encryptAuthenticatorBackup(data,password));for(const invalid of [{...valid,extra:true},{...valid,version:2},{...valid,entries:[valid.entries[0],valid.entries[0]]},{...valid,entries:[{...valid.entries[0],parameters:{...parameters,secret:'INVALID!'}}]},{...valid,groups:[]},{...valid,entries:[{...valid.entries[0],period:30}]}]){picked=seal(invalid);await assert.rejects(service.handle('authenticatorImportReview',request),/invalid entries/);assert.equal((await service.handle('authenticatorList') as any).entries.length,0);}
 const envelope=encryptAuthenticatorBackup(valid,password);picked=JSON.stringify({...envelope,kdf:{...envelope.kdf,N:1073741824}});await assert.rejects(service.handle('authenticatorImportReview',request),/authenticated/);picked='x'.repeat(1500001);await assert.rejects(service.handle('authenticatorImportReview',request),/too large/);const reordered={...envelope,kdf:{p:1,r:8,N:16384,name:'scrypt'}};assert.equal((decryptAuthenticatorBackup(reordered as any,password) as any).entries.length,2);
 picked=seal(valid);const expired=(await service.handle('authenticatorImportReview',request) as any).review;clock+=120000;await assert.rejects(service.handle('authenticatorImport',{reviewId:expired.id,...gate}),/expired/);const stale=(await service.handle('authenticatorImportReview',request) as any).review;await service.handle('authenticatorEnroll',{parameters,code:totp(parameters,clock)});await assert.rejects(service.handle('authenticatorImport',{reviewId:stale.id,...gate}),/changed/);
 await service.handle('lockSet',{id:'security:authenticatorImport',policy:'password',password:'isolated lock password',duration:{kind:'surface'},disclosed:true});const before=picks;await assert.rejects(service.handle('authenticatorImportReview',request),/locked/);assert.equal(picks,before);await service.handle('lockVerify',{id:'security:authenticatorImport',password:'isolated lock password'});const active=(await service.handle('authenticatorImportReview',request) as any).review;assert.equal((await service.handle('lockList') as any).locks.find((lock:any)=>lock.id==='security:authenticatorImport').locked,false);await service.handle('authenticatorImport',{reviewId:active.id,...gate});assert.equal((await service.handle('lockList') as any).locks.find((lock:any)=>lock.id==='security:authenticatorImport').locked,true);
 }finally{service.close();await rm(directory,{recursive:true,force:true});}});
