import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {PDFDocument,degrees} from 'pdf-lib';import {PNG} from 'pngjs';import {createBundledEngines} from '../src/main/bundled-engines';import {serializeExport,exportFormats} from '../src/shared/exports';import {LocalToolsService} from '../src/main/local-tools';
const fixtureRoot=await mkdtemp(join(tmpdir(),'material-bundled-fixture-'));const workerPath=join(fixtureRoot,'worker.cjs');await build({entryPoints:['src/main/bundled-engines-worker.ts'],bundle:true,platform:'node',format:'cjs',outfile:workerPath});const engines=createBundledEngines({vendorDirectory:resolve('vendor/converters'),workerPath});
const request=(adapter:string,inputs:Array<{name:string;bytes:Uint8Array}>,options={})=>engines.convert({adapter,inputs,options},new AbortController().signal);
const eventually=async(f:()=>Promise<boolean>)=>{for(let i=0;i<300;i++){if(await f())return;await new Promise(r=>setTimeout(r,20));}throw new Error('Timed out');};
test('structured exports preserve JSON/YAML/XML/JSONL types and reject unsupported data; HTML and SQL escape content',async()=>{const data=[{id:1,text:'<script>alert("fixture")</script>',null:null,flag:true,nested:{sample:['a',2]}}];assert.ok(exportFormats(data).includes('sql'));for(const format of ['json','jsonl','yaml','xml']as const){const serialized=serializeExport(data,format);const result=await request('data-json',[{name:'fixture.'+format,bytes:Buffer.from(serialized.text)}],{sourceFormat:format});assert.deepEqual(JSON.parse(Buffer.from(result.outputs[0].bytes).toString()),data);}assert.ok(serializeExport(data,'html').text.includes('&lt;script&gt;'));assert.ok(serializeExport([{x:"x'); DROP TABLE test; --"}],'sql').text.includes("x''); DROP TABLE test; --"));assert.throws(()=>serializeExport(data,'sql',{table:'unsafe; DROP'}));assert.throws(()=>serializeExport({a:undefined},'json'));const csv=serializeExport([{field:'=1+1',nested:{a:1}}],'csv');assert.ok(csv.text.includes("'=1+1"));assert.ok(csv.disclosures.length);await assert.rejects(request('data-json',[{name:'fixture.yaml',bytes:Buffer.from('a: &a [1]\nb: *a')}],{sourceFormat:'yaml'}),/alias|Alias/);await assert.rejects(request('data-json',[{name:'fixture.xml',bytes:Buffer.from('<!DOCTYPE doc [<!ENTITY leak SYSTEM "file:///etc/passwd">]><doc>&leak;</doc>')}],{sourceFormat:'xml'}),/DTD/);});
test('actual PDF inspect split extract reorder rotate metadata and merge reopen correctly',async()=>{const doc=await PDFDocument.create();for(let i=0;i<3;i++){const page=doc.addPage([100+i*10,120]);page.setRotation(degrees(i*90));}doc.setTitle('Fixture original');const bytes=await doc.save();const input=[{name:'fixture.pdf',bytes}];const inspection=await request('pdf-inspect',input);assert.equal(inspection.details?.pages,3);const split=await request('pdf-split',input,{pages:[1,3]});assert.equal(split.outputs.length,2);assert.equal((await PDFDocument.load(split.outputs[1].bytes)).getPage(0).getWidth(),120);const reordered=await request('pdf-reorder',input,{pages:[3,1,2]});const reopened=await PDFDocument.load(reordered.outputs[0].bytes);assert.deepEqual(reopened.getPages().map(p=>p.getWidth()),[120,100,110]);assert.equal((await PDFDocument.load((await request('pdf-extract',input,{pages:[2]})).outputs[0].bytes)).getPageCount(),1);assert.equal((await PDFDocument.load((await request('pdf-rotate',input,{rotation:90})).outputs[0].bytes)).getPage(1).getRotation().angle,180);assert.equal((await PDFDocument.load((await request('pdf-metadata',input,{metadata:{title:'Fixture changed'}})).outputs[0].bytes)).getTitle(),'Fixture changed');assert.equal((await PDFDocument.load((await request('pdf-merge',[...input,{name:'second.pdf',bytes}])).outputs[0].bytes)).getPageCount(),6);await assert.rejects(request('pdf-extract',input,{pages:[4]}),/page numbers/);});
test('PNG/JPEG decoding and encoding runs in the built bounded worker',async()=>{const png=new PNG({width:4,height:3});png.data.fill(255);const input=[{name:'fixture.png',bytes:PNG.sync.write(png)}];const jpg=await request('isolated-jpeg',input,{quality:85});assert.equal(jpg.outputs[0].bytes[0],255);const back=await request('isolated-png',[{name:'fixture.jpeg',bytes:jpg.outputs[0].bytes}]);assert.equal(PNG.sync.read(Buffer.from(back.outputs[0].bytes)).width,4);});
test('actual ZIP codecs reopen exact bytes and refuse archive traversal',async()=>{const inputs=[{name:'first.txt',bytes:Buffer.from('Fixture one')},{name:'second.json',bytes:Buffer.from('{"fixture":2}')}];const zip=await request('zip-create',inputs,{level:6});const extracted=await request('zip-extract',[{name:'fixture.zip',bytes:zip.outputs[0].bytes}]);assert.equal(extracted.outputs.length,2);assert.equal(Buffer.from(extracted.outputs[0].bytes).toString(),'Fixture one');await assert.rejects(request('zip-create',[{name:'../unsafe',bytes:Buffer.from('fixture')}]),/unsafe/);});
test('downloaded SHA256-verified native archive and FFmpeg engines execute offline fixtures',async(t)=>{const statuses=await engines.status();if(!statuses.find(s=>s.kind==='archive')?.available||!statuses.find(s=>s.kind==='ffmpeg')?.available){t.skip('Verified native engine payloads absent; run fetch-converter-engines.mjs');return;}const archive=await request('7z-create',[{name:'fixture.txt',bytes:Buffer.from('native fixture')}],{compression:'lzma2',level:6,dictionaryMiB:8,solid:true,threads:1});const extracted=await request('7z-extract',[{name:'fixture.7z',bytes:archive.outputs[0].bytes}]);assert.equal(Buffer.from(extracted.outputs[0].bytes).toString(),'native fixture');const wav=Buffer.alloc(44+16000);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(16000,40);const mp3=await request('media-mp3',[{name:'fixture.wav',bytes:wav}],{threads:1});assert.ok(mp3.outputs[0].bytes.length>1000);const back=await request('media-wav',[{name:'fixture.mp3',bytes:mp3.outputs[0].bytes}],{threads:1});assert.ok(back.outputs[0].bytes.length>16000);});
test('service uses bundled engines via opaque grants and commits every PDF split destination only after verification',async()=>{const dir=await mkdtemp(join(tmpdir(),'material-pdf-grant-fixture-')),source=join(dir,'fixture.pdf'),destination=join(dir,'converted.pdf');const doc=await PDFDocument.create();doc.addPage();doc.addPage();await writeFile(source,await doc.save());const service=new LocalToolsService({storageDirectory:dir,engines,pickSources:async()=>[source],pickDestination:async()=>destination});try{const grants=await service.request('converter-pick')as Array<{id:string}>;const result=await service.request('converter-start',{grant:grants[0].id,adapter:'pdf-split'})as{id:string};await eventually(async()=>{const status=await service.request('converter-status')as{items:Array<{id:string;status:string}>};return status.items.some(i=>i.id===result.id&&i.status==='converted');});assert.equal((await PDFDocument.load(await readFile(join(dir,'converted-page-1.pdf')))).getPageCount(),1);assert.equal((await PDFDocument.load(await readFile(source))).getPageCount(),2);}finally{service.dispose();await rm(dir,{recursive:true,force:true});}});
test.after(async()=>{await rm(fixtureRoot,{recursive:true,force:true});});
test('native 7z encryption keeps passwords out of argv and reopens encrypted content through controlled stdin',async(t)=>{if(!(await engines.status()).find(s=>s.kind==='archive')?.available){t.skip('Bundled native archive engine unavailable');return;}const password='synthetic-fixture-only-password';const archived=await request('7z-create',[{name:'encrypted-fixture.txt',bytes:Buffer.from('synthetic encrypted bytes')}],{encryption:'content-and-headers',password,dictionaryMiB:8,threads:1});const restored=await request('7z-extract',[{name:'encrypted-fixture.7z',bytes:archived.outputs[0].bytes}],{password});assert.equal(Buffer.from(restored.outputs[0].bytes).toString(),'synthetic encrypted bytes');});
test('durable converter queue stays paused on restart, resumes granted records and cancels queued work',async()=>{const dir=await mkdtemp(join(tmpdir(),'material-queue-fixture-')),source=join(dir,'queue-fixture.json');await writeFile(source,'{"fixture":true}');let destination=join(dir,'queued.json');let service=new LocalToolsService({storageDirectory:dir,pickSources:async()=>[source],pickDestination:async()=>destination});try{const grants=await service.request('converter-pick')as Array<{id:string}>;const queued=await service.request('converter-enqueue',{grant:grants[0].id,adapter:'json-pretty'})as{id:string};assert.equal((await service.request('converter-queue')as{paused:boolean}).paused,true);service.dispose();service=new LocalToolsService({storageDirectory:dir,pickSources:async()=>[],pickDestination:async()=>destination});assert.equal((await service.request('converter-queue')as{queued:number}).queued,1);await service.request('converter-resume');await eventually(async()=>{const rows=await service.request('converter-status')as{items:Array<{id:string;status:string}>};return rows.items.some(r=>r.id===queued.id&&r.status==='converted');});assert.deepEqual(JSON.parse(await readFile(destination,'utf8')),{fixture:true});await service.request('converter-pause');destination=join(dir,'cancelled.json');const cancelled=await service.request('converter-enqueue',{grant:grants[0].id,adapter:'json-pretty'})as{id:string};await service.request('converter-cancel',{id:cancelled.id});assert.equal((await service.request('converter-queue')as{queued:number}).queued,0);assert.ok((await service.request('converter-status')as{items:Array<{id:string;status:string}>}).items.some(r=>r.id===cancelled.id&&r.status==='cancelled'));}finally{service.dispose();await new Promise(r=>setTimeout(r,20));await rm(dir,{recursive:true,force:true});}});
test('actual video preset reopens valid duration/dimensions using only owned local files',async(t)=>{if(!(await engines.status()).find(s=>s.kind==='ffmpeg')?.available){t.skip('Bundled FFmpeg engine unavailable');return;}const path=join(fixtureRoot,'tiny-video.mp4');await writeFile(path,Buffer.from(await readFile(resolve('tests/fixtures/tiny-video.base64'),'utf8'),'base64'));const converted=await request('media-webm',[{name:'tiny-video.mp4',bytes:await readFile(path)}],{threads:1});assert.ok(converted.outputs[0].bytes.length>100);assert.equal((converted.details?.output as{streams:Array<{width:number}>}).streams[0].width,16);});

test('ZIP reopening rejects CRC corruption, false expansion sizes and symlink entries before extraction',async()=>{const created=await request('zip-create',[{name:'fixture.txt',bytes:Buffer.from('synthetic '.repeat(1000))}]);const original=Buffer.from(created.outputs[0].bytes),central=original.indexOf(Buffer.from([0x50,0x4b,0x01,0x02]));assert.ok(central>0);const corrupt=Buffer.from(original);corrupt.writeUInt32LE((corrupt.readUInt32LE(central+16)^1)>>>0,central+16);await assert.rejects(request('zip-extract',[{name:'bad.zip',bytes:corrupt}]),/CRC/);const understated=Buffer.from(original);understated.writeUInt32LE(1,central+24);await assert.rejects(request('zip-extract',[{name:'bad.zip',bytes:understated}]),/limit|size|length|large/i);const symlink=Buffer.from(original);symlink.writeUInt32LE((0xa000<<16)>>>0,central+38);await assert.rejects(request('zip-extract',[{name:'bad.zip',bytes:symlink}]),/symbolic/);});

test('native archives verify empty, binary and Unicode entries; wrong passwords and cancellation refuse outputs',async(t)=>{
 if(!(await engines.status()).find(s=>s.kind==='archive')?.available){t.skip('Verified native archive payload absent');return;}
 const inputs=[{name:'empty.txt',bytes:Buffer.alloc(0)},{name:'binary.bin',bytes:Buffer.from(Array.from({length:4096},(_,i)=>i%256))},{name:'廣東話.txt',bytes:Buffer.from('Synthetic Unicode fixture')}];
 for(const adapter of ['7z-create','7z-zip']){
  const archived=await request(adapter,inputs,{encryption:'content',password:'synthetic-password',threads:1});
  const restored=await request('7z-extract',[{name:'archive.bin',bytes:archived.outputs[0].bytes}],{password:'synthetic-password'});
  for(const input of inputs)assert.deepEqual(Buffer.from(restored.outputs.find(o=>o.suffix==='-'+input.name)!.bytes),input.bytes);
  await assert.rejects(request('7z-extract',[{name:'archive.bin',bytes:archived.outputs[0].bytes}],{password:'wrong-synthetic-password'}),/failed/);
 }
 const cancelled=new AbortController();cancelled.abort();
 await assert.rejects(engines.convert({adapter:'7z-create',inputs,options:{}},cancelled.signal),/cancelled/);
 for(const name of ['CON.txt','file:stream','trailing.','unsafe '])await assert.rejects(request('7z-create',[{name,bytes:Buffer.from('fixture')}]),/safe basenames/);
});
