import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {build} from 'esbuild';
import {chromium} from 'playwright';
const browserPath=existsSync('/usr/bin/chromium')?'/usr/bin/chromium':chromium.executablePath();
test('built Codespace destination mounts reviewed scoped controls and preserves cancellation and draft discard',{skip:!existsSync(browserPath)},async()=>{
 const bundle=await build({stdin:{contents:"import './src/renderer/github-workspace.ts';import './src/renderer/scroll-surface.ts';",resolveDir:process.cwd(),sourcefile:'codespace-context-fixture.ts'},bundle:true,write:false,format:'iife',platform:'browser',logLevel:'silent'});const browser=await chromium.launch({headless:true,executablePath:browserPath,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1280,height:1000}});page.setDefaultTimeout(4000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 try{await page.setContent('<style>mg-github-workspace{display:block;height:900px}.record-list-scroll{height:240px}.native-task-scroll{height:700px}</style><mg-github-workspace></mg-github-workspace>');await page.evaluate('globalThis.__name = value => value');await page.evaluate(()=>{let listener:(operation:unknown)=>void=()=>{};let operation:Record<string,unknown>={};const calls:unknown[]=[];Object.assign(window,{fixtureCalls:calls,material:{github:async(action:string)=>action.endsWith('.list')?{items:[{id:'fixture-space',name:'fixture-space',title:'Fixture workspace',state:'Available'}],page:0,hasNext:false}:{detail:{id:'fixture-space',name:'fixture-space',title:'Fixture workspace'},items:[],page:0,hasNext:false},onOperation:(next:(operation:unknown)=>void)=>{listener=next;return()=>{};},cliWorkflows:async(action:string,payload:{commandId?:string;fields?:Record<string,unknown>;operationId?:string;hostname?:string})=>{calls.push({action,payload});if(action==='inventory')return {kind:'inventory',commands:[],copilotInstalled:false,blockers:[]};if(action==='review')return {kind:'review',reviewId:'fixture-review',commandId:payload.commandId,hostname:payload.hostname,account:'fixture',target:'fixture-space',argv:['codespace','fixture'],executable:'gh',warnings:['Fixture operation only.'],expiresAt:'2099-01-01T00:00:00Z',description:'Fixture',destructive:payload.commandId==='codespace cp'};if(action==='apply'){operation={id:'owned-fixture-operation',commandId:'codespace ssh',status:'running',startedAt:new Date().toISOString(),stdout:'Fixture session',stderr:''};return {kind:'operation',operation};}if(action==='cancel'){operation={...operation,status:'cancelled',endedAt:new Date().toISOString()};listener(operation);return {kind:'cancelled'};}return {kind:'choices',items:[],hasNext:false};},operation:async()=>operation,workspace:async()=>({ok:true}),pick:async()=>['/approved/source.txt'],openExternal:async()=>{},exportData:async()=>true}});});await page.addScriptTag({content:bundle.outputFiles[0].text});await page.evaluate(()=>{const workspace=document.querySelector('mg-github-workspace') as unknown as {domain:string;hostname:string;authenticated:boolean};workspace.domain='codespaces';workspace.hostname='github.example';workspace.authenticated=true;});
 await page.locator('[data-testid=github-record]').click();await page.locator('[data-testid=native-area-connection]').click();await page.locator('[data-testid=cloud-task-codespace-ssh]').click();const form=page.locator('mg-cli-workflows');await page.waitForTimeout(100);assert.deepEqual(errors,[]);assert.equal(await form.locator('[search-id=workflow-action-picker]').count(),0);await form.getByRole('button',{name:'Review operation',exact:true}).click();const dialog=form.locator('md-dialog').first();await dialog.getByRole('checkbox',{name:'I reviewed the executable and arguments',exact:true}).check();await dialog.getByRole('button',{name:'Run reviewed operation',exact:true}).click();await page.waitForFunction(()=>Boolean((document.querySelector('mg-github-workspace') as unknown as {nativeBusy:boolean}).nativeBusy));await page.waitForFunction(()=>Boolean((document.querySelector('[data-testid=native-task-close]') as unknown as {disabled:boolean})?.disabled));assert.ok(await page.locator('[data-testid=native-task-close]').getAttribute('disabled')!==null);await form.getByRole('button',{name:'Cancel',exact:true}).first().click();await page.locator('[data-testid=native-task-close]').click();
 await page.locator('[data-testid=native-area-files]').click();await page.locator('[data-testid=cloud-task-codespace-cp]').click();await form.getByRole('textbox',{name:'Local path',exact:true}).fill('/approved/source.txt');await form.getByRole('button',{name:'Review operation',exact:true}).click();await dialog.getByRole('checkbox',{name:'I reviewed the executable and arguments',exact:true}).check();assert.ok(await dialog.getByRole('button',{name:'Run reviewed operation',exact:true}).isDisabled());await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.locator('[data-testid=native-task-close]').click();await page.getByRole('button',{name:'Discard draft',exact:true}).click();await page.locator('[data-testid=cloud-task-codespace-cp]').click();assert.equal(await form.getByRole('textbox',{name:'Local path',exact:true}).inputValue(),'');
 const calls=await page.evaluate(()=>(window as unknown as {fixtureCalls:{action:string;payload:Record<string,unknown>}[]}).fixtureCalls);const review=calls.find(call=>call.action==='review');assert.equal(review?.payload.hostname,'github.example');assert.equal((review?.payload.fields as Record<string,unknown>).codespace,'fixture-space');assert.ok(calls.some(call=>call.action==='cancel'&&call.payload.operationId==='owned-fixture-operation'));assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
