import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,readdir,rm,writeFile,stat,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {createNativeDownloadDeps,type DownloadPrivateProcess} from '../src/main/downloads-native';
import {validateAuthHost} from '../src/main/auth-hosts';
import type {SecretVault} from '../src/main/security';
import type {StoredDownload} from '../src/main/downloads';

function vault(backend='os_crypt'):SecretVault {const key=randomBytes(32);return {isEncryptionAvailable:()=>true,getSelectedStorageBackend:()=>backend,encryptString(raw){const nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,nonce);return Buffer.concat([nonce,cipher.update(raw,'utf8'),cipher.final(),cipher.getAuthTag()]);},decryptString(raw){const decipher=createDecipheriv('aes-256-gcm',key,raw.subarray(0,12));decipher.setAuthTag(raw.subarray(-16));return Buffer.concat([decipher.update(raw.subarray(12,-16)),decipher.final()]).toString('utf8');}};}
const selection={kind:'release-asset' as const,hostname:'github.com',repository:'owner/repo',id:'42'};
function asset(host='github.com'){return {id:42,name:'release.zip',size:7,digest:'sha256:'+'a'.repeat(64),url:validateAuthHost(host).restOrigin+'/repos/owner/repo/releases/assets/42'};}
async function fixture(t:test.TestContext,overrides:Record<string,unknown>={}) {const dir=await mkdtemp(path.join(tmpdir(),'material-download-native-'));t.after(()=>rm(dir,{recursive:true,force:true}));const calls:DownloadPrivateProcess[]=[];const opts={binary:'unused',cwd:dir,directory:path.join(dir,'protected'),vault:vault(),resolveHost:validateAuthHost,pickDestination:async()=>null,fetch:(async()=>new Response(JSON.stringify({id:7,login:'fixture'}))) as typeof fetch,run:async(request:DownloadPrivateProcess)=>{calls.push(request);return JSON.stringify(request.argv.includes('user')?{id:7,login:'fixture'}:asset());},...overrides};return {dir,calls,opts,deps:createNativeDownloadDeps(opts)};}

test('native source resolver uses exact provider ID, digest and release size and rereads metadata',async t=>{let current=asset();const f=await fixture(t,{run:async()=>JSON.stringify(current)});const source=await f.deps.resolveSource(selection);assert.equal(source.name,'release.zip');assert.equal(source.size,7);assert.equal(source.sha256,'a'.repeat(64));assert.equal(source.endpoint,'/repos/owner/repo/releases/assets/42');current={...current,name:'renamed.zip'};assert.equal((await f.deps.resolveSource(selection)).name,'renamed.zip');current={...current,id:43};await assert.rejects(f.deps.resolveSource(selection),/record has changed/);});
test('artifact resolver omits uncompressed size and rejects expired or mismatched archive locations',async t=>{const s={...selection,kind:'artifact' as const};let data={id:42,name:'build',size_in_bytes:9000,expired:false,expires_at:'2099-01-01T00:00:00Z',url:'https://api.github.com/repos/owner/repo/actions/artifacts/42',archive_download_url:'https://api.github.com/repos/owner/repo/actions/artifacts/42/zip'};const f=await fixture(t,{run:async()=>JSON.stringify(data)});const source=await f.deps.resolveSource(s);assert.equal(source.size,undefined);assert.equal(source.endpoint,'/repos/owner/repo/actions/artifacts/42/zip');data={...data,expired:true};await assert.rejects(f.deps.resolveSource(s),/expired/);data={...data,expired:false,archive_download_url:'https://untrusted.example/zip'};await assert.rejects(f.deps.resolveSource(s),/expired|unavailable/);});
test('approved registry rejects a host before any private helper is launched',async t=>{const f=await fixture(t,{resolveHost:(host:string)=>{if(host!=='github.com')throw new Error('unapproved');return validateAuthHost(host);}});await assert.rejects(f.deps.resolveSource({...selection,hostname:'unknown.example'}),/unapproved/);assert.equal(f.calls.length,0);await assert.rejects(f.deps.resolveSource({...selection,id:'42;other'}));assert.equal(f.calls.length,0);});
test('Enterprise transport prefixes exact API records and preserves signed storage URLs and request headers',async t=>{const received:{url:string,headers:Headers,redirect?:RequestRedirect}[]=[];const f=await fixture(t,{run:async()=>JSON.stringify(asset('github.example')),fetch:(async(input:RequestInfo|URL,init?:RequestInit)=>{const request=new Request(input,init);received.push({url:request.url,headers:request.headers,redirect:request.redirect});return new Response('fixture');}) as typeof fetch});await f.deps.resolveSource({...selection,hostname:'github.example'});await f.deps.fetch!('https://github.example/repos/owner/repo/releases/assets/42',{redirect:'manual',headers:{Authorization:'Bearer synthetic'}});await f.deps.fetch!(new Request('https://github.example/api/v3/repos/owner/repo/releases/assets/42',{headers:{Range:'bytes=2-'},redirect:'manual'}));await f.deps.fetch!('https://github.example/repos/owner/repo/releases/assets/42?signature=fixture',{redirect:'manual'});await f.deps.fetch!('https://storage.example/signed?signature=fixture',{redirect:'manual'});assert.equal(received[0].url,'https://github.example/api/v3/repos/owner/repo/releases/assets/42');assert.equal(received[0].headers.get('authorization'),'Bearer synthetic');assert.equal(received[0].redirect,'manual');assert.equal(received[1].headers.get('range'),'bytes=2-');assert.equal(received[2].url,'https://github.example/repos/owner/repo/releases/assets/42?signature=fixture');assert.equal(received[3].url,'https://storage.example/signed?signature=fixture');});
test('credential is bound to opaque account and token effective identity with race revalidation',async t=>{const requests:DownloadPrivateProcess[]=[];let active=7,effective=7;const fetched:Request[]=[];const f=await fixture(t,{run:async(r:DownloadPrivateProcess)=>{requests.push(r);return r.argv[0]==='auth'?'synthetic_fixture_token\n':JSON.stringify({id:active,login:'fixture'});},fetch:(async(input:RequestInfo|URL,init?:RequestInit)=>{fetched.push(new Request(input,init));return new Response(JSON.stringify({id:effective}));}) as typeof fetch});const account=await f.deps.accountFingerprint('github.com');assert.match(account,/^[a-f0-9]{64}$/);assert.equal(account.includes('fixture'),false);assert.equal(await f.deps.token('github.com',account),'synthetic_fixture_token');assert.deepEqual(requests.find(r=>r.argv[0]==='auth')?.argv,['auth','token','--hostname=github.com']);assert.equal(fetched[0].url,'https://api.github.com/user');assert.equal(fetched[0].redirect,'manual');assert.equal(fetched[0].headers.get('authorization'),'Bearer synthetic_fixture_token');effective=8;await assert.rejects(f.deps.token('github.com',account),error=>!String(error).includes('synthetic_fixture_token'));effective=7;active=8;await assert.rejects(f.deps.token('github.com',account),/account has changed/);});
test('external account switch during effective-token verification fails before returning token',async t=>{let active=7;const f=await fixture(t,{run:async(r:DownloadPrivateProcess)=>r.argv[0]==='auth'?'synthetic_fixture_token':JSON.stringify({id:active,login:'fixture'}),fetch:(async()=>{active=8;return new Response(JSON.stringify({id:7}));}) as typeof fetch});const account=await f.deps.accountFingerprint('github.com');await assert.rejects(f.deps.token('github.com',account),/could not be bound/);});
test('encrypted store persists resume paths without plaintext and atomically replaces records',async t=>{const f=await fixture(t);const rows=[{version:1,destinationPath:'/private/native-picked/release.zip',partialPath:'/private/native-picked/partial',account:'opaque-fixture'}] as StoredDownload[];assert.equal(f.deps.store.durable,true);await f.deps.store.write(rows);const file=path.join(f.dir,'protected','downloads.encrypted');const bytes=await readFile(file);assert.equal(bytes.includes(Buffer.from('/private/native-picked')),false);assert.deepEqual(await f.deps.store.read(),rows);if(process.platform!=='win32')assert.equal((await stat(file)).mode&0o777,0o600);await Promise.all([f.deps.store.write(rows),f.deps.store.write([])]);assert.deepEqual(await f.deps.store.read(),[]);assert.deepEqual(await readdir(path.dirname(file)),['downloads.encrypted']);await writeFile(file,Buffer.from('corrupt'));await assert.rejects(f.deps.store.read(),/unavailable or invalid/);});
test('basic-text backend stays session-only without creating a plaintext metadata directory',async t=>{const f=await fixture(t,{vault:vault('basic_text')});assert.equal(f.deps.store.durable,false);const rows=[{destinationPath:'/private/fixture'}] as StoredDownload[];await f.deps.store.write(rows);rows[0].destinationPath='changed';assert.deepEqual(await f.deps.store.read(),[{destinationPath:'/private/fixture'}]);await assert.rejects(stat(path.join(f.dir,'protected')),{code:'ENOENT'});await assert.rejects(f.deps.store.write(Array(201).fill({})),/limit/);});
test('encrypted recovery rejects symlink and vault availability loss fails closed',async t=>{let available=true;const secure=vault();secure.isEncryptionAvailable=()=>available;const f=await fixture(t,{vault:secure});await f.deps.store.write([]);available=false;assert.equal(f.deps.store.durable,false);await assert.rejects(f.deps.store.write([]),/unavailable/);await assert.rejects(f.deps.store.read(),/unavailable/);available=true;const file=path.join(f.dir,'protected','downloads.encrypted');await rm(file);await writeFile(path.join(f.dir,'other'),'fixture');if(process.platform!=='win32'){await symlink(path.join(f.dir,'other'),file);await assert.rejects(f.deps.store.read(),/invalid/);}});
test('real private subprocess fixture uses bounded pipe capture without exposing helper errors',async t=>{const f=await fixture(t);const script=path.join(f.dir,'fixture.mjs');await writeFile(script,"process.stderr.write('synthetic_secret_in_stderr');process.stdout.write('x'.repeat(70000));");const deps=createNativeDownloadDeps({...f.opts,binary:process.execPath,run:undefined});/* Node interprets the first gh argument as an entrypoint; the fixture is named api. */await writeFile(path.join(f.dir,'api'),await readFile(script));await assert.rejects(deps.accountFingerprint('github.com'),error=>!String(error).includes('synthetic_secret_in_stderr'));});
