import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';

/** Exercise the actual shell methods without constructing privileged browser state. */
function controller(name:string,window:unknown){const source=readFileSync('src/renderer/app.ts','utf8');const tree=ts.createSourceFile('app.ts',source,ts.ScriptTarget.Latest,true);let method:ts.MethodDeclaration|undefined;const visit=(node:ts.Node)=>{if(ts.isMethodDeclaration(node)&&node.name.getText(tree)===name)method=node;ts.forEachChild(node,visit);};visit(tree);assert.ok(method?.body,`Missing shutdown controller: ${name}`);const output=ts.transpileModule(`export default async function tested()${method.body.getText(tree)}`,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;return new Function('window',`const exports={};${output};return exports.default;`)(window) as (this:unknown)=>Promise<void>;}
test('native close persistence failure stays in the app and reports fixed localized recovery text',async()=>{for(const language of ['en','yue','both']){const calls:string[]=[];const notices:string[]=[];const close=controller('closeConfirmed',{material:{window:async(action:string)=>{calls.push(action);throw Error('fixture private native failure');}}});const context={closeAppOpen:true,copy:(en:string,yue:string)=>language==='yue'?yue:language==='both'?`${en} · ${yue}`:en,notify:(message:string|{en:string;yue:string})=>notices.push(typeof message==='string'?message:language==='yue'?message.yue:language==='both'?`${message.en} · ${message.yue}`:message.en)};await close.call(context);assert.deepEqual(calls,['confirm-close']);assert.equal(context.closeAppOpen,false);assert.equal(notices.length,1);assert.equal(notices[0].includes('fixture private'),false);assert.ok(notices[0].includes(language==='yue'?'復原儲存':'recovery storage'));}});
test('native restart refusal is caught and gives a fixed recovery route',async()=>{const calls:string[]=[];const notices:string[]=[];const restart=controller('restartConfirmed',{material:{updates:async(action:string)=>{calls.push(action);throw Error('fixture private native failure');}}});await restart.call({copy:(en:string)=>en,notify:(message:string|{en:string;yue:string})=>notices.push(typeof message==='string'?message:message.en)});assert.deepEqual(calls,['restart']);assert.equal(notices.length,1);assert.match(notices[0],/active downloads, recovery storage, and update availability/);assert.equal(notices[0].includes('fixture private'),false);});
test('successful native close and restart do not announce failures or retry native calls',async()=>{for(const [method,service,action] of [['closeConfirmed','window','confirm-close'],['restartConfirmed','updates','restart']]){const calls:string[]=[];const notices:string[]=[];const command=controller(method,{material:{[service]:async(value:string)=>{calls.push(value);}}});await command.call({copy:(en:string)=>en,notify:(message:string|{en:string;yue:string})=>notices.push(typeof message==='string'?message:message.en)});assert.deepEqual(calls,[action]);assert.deepEqual(notices,[]);}});
