import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer,type IncomingMessage,type ServerResponse} from 'node:http';
import {mkdtemp,readFile,writeFile,rm,stat,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import {DownloadQueue,type DownloadDependencies,type StoredDownload} from '../src/main/downloads';
import {validateDownloadSelection,type DownloadJob} from '../src/shared/downloads';

const selection={kind:'release-asset' as const,hostname:'github.com',repository:'example/project',id:'123'};
const bytes=Buffer.alloc(96*1024,7);const digest=createHash('sha256').update(bytes).digest('hex');
async function fixture(t:test.TestContext,handler?:(req:IncomingMessage,res:ServerResponse)=>boolean){
 const requests:{authorization?:string;range?:string;ifRange?:string}[]=[];let etag='"stable"';let truncated=false;let corrupt=false;
 const server=createServer((req,res)=>{requests.push({authorization:req.headers.authorization,range:req.headers.range,ifRange:req.headers['if-range'] as string|undefined});if(handler?.(req,res))return;const offset=Number(req.headers.range?.match(/bytes=(\d+)-/)?.[1]??0);res.writeHead(offset?206:200,{'content-length':bytes.length-offset,etag,'accept-ranges':'bytes',...(offset?{'content-range':`bytes ${offset}-${bytes.length-1}/${bytes.length}`}:{})});let position=offset;const timer=setInterval(()=>{if(position>=bytes.length){clearInterval(timer);res.end();return;}if(truncated&&position>=8192){clearInterval(timer);res.destroy();return;}const chunk=Buffer.from(bytes.subarray(position,position+4096));if(corrupt)chunk[0]=1;res.write(chunk);position+=chunk.length;},5);res.on('close',()=>clearInterval(timer));});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address() as {port:number};const origin=`http://127.0.0.1:${address.port}`;
 const directory=await mkdtemp(path.join(tmpdir(),'material-download-test-'));let stored:StoredDownload[]=[];let account='account-a';let tokenAccount='account-a';let failStore=false;const destination=path.join(directory,'chosen.bin');
 const deps:DownloadDependencies={resolveSource:async selected=>({selection:selected,apiOrigin:origin,endpoint:`/repos/${selected.repository}/releases/assets/${selected.id}`,name:'release.bin',size:bytes.length,sha256:digest}),accountFingerprint:async()=>account,token:async(_host,expected)=>{assert.equal(expected,tokenAccount);return 'fixture-token';},pickDestination:async()=>destination,store:{read:async()=>structuredClone(stored),write:async records=>{if(failStore)throw Error('SECRET signed URL and token must not escape');stored=structuredClone(records);}},allowLoopbackFixture:true};
 const queue=new DownloadQueue(deps);t.after(async()=>{await queue.close().catch(()=>{});server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));await rm(directory,{recursive:true,force:true});});
 return {queue,deps,destination,requests,directory,get stored(){return stored;},set stored(value:StoredDownload[]){stored=value;},set etag(value:string){etag=value;},set truncated(value:boolean){truncated=value;},set corrupt(value:boolean){corrupt=value;},set account(value:string){account=value;},set tokenAccount(value:string){tokenAccount=value;},set failStore(value:boolean){failStore=value;}};
}
async function job(queue:DownloadQueue){return (await queue.handle({action:'list'})).items[0];}
async function waitFor(queue:DownloadQueue,predicate:(value:DownloadJob)=>boolean){for(let i=0;i<400;i++){const current=await job(queue);if(current&&predicate(current))return current;await delay(5);}assert.fail('Download did not reach the expected state');}

test('real streamed download reports bytes and completes only after exact checksum and atomic publication',async t=>{const f=await fixture(t);let progress=false;f.queue.subscribe(value=>{if(value.state==='downloading'&&value.bytes>0&&value.bytes<bytes.length)progress=true;});await f.queue.handle({action:'enqueue',selection});const result=await waitFor(f.queue,j=>j.state==='completed');assert.equal(result.bytes,bytes.length);assert.equal(result.verification,'sha256');assert.ok(progress);assert.deepEqual(await readFile(f.destination),bytes);assert.equal(f.requests[0].authorization,'Bearer fixture-token');assert.equal(JSON.stringify(result).includes(f.directory),false);assert.equal(JSON.stringify(f.stored).includes('fixture-token'),false);});
test('pause and resume use exact bytes, Range, If-Range and preserve final content',async t=>{const f=await fixture(t);await f.queue.handle({action:'enqueue',selection});const running=await waitFor(f.queue,j=>j.bytes>=8192);await f.queue.handle({action:'pause',id:running.id});const paused=await job(f.queue);assert.equal(paused.state,'paused');assert.ok(paused.resumable);await f.queue.handle({action:'resume',id:paused.id});await waitFor(f.queue,j=>j.state==='completed');assert.equal(f.requests[1].range,`bytes=${paused.bytes}-`);assert.equal(f.requests[1].ifRange,'"stable"');assert.deepEqual(await readFile(f.destination),bytes);});
test('stale ETag fails resume and fresh retry replaces only the owned partial',async t=>{const f=await fixture(t);await f.queue.handle({action:'enqueue',selection});const running=await waitFor(f.queue,j=>j.bytes>=8192);await f.queue.handle({action:'pause',id:running.id});f.etag='"changed"';await f.queue.handle({action:'resume',id:running.id});const failed=await waitFor(f.queue,j=>j.state==='failed');assert.equal(failed.issue,'source-changed');assert.equal(await stat(f.destination).catch(()=>null),null);await f.queue.handle({action:'retry',id:running.id});await waitFor(f.queue,j=>j.state==='completed');assert.deepEqual(await readFile(f.destination),bytes);});
test('truncated and corrupt network streams never publish success',async t=>{const f=await fixture(t);f.truncated=true;await f.queue.handle({action:'enqueue',selection});const failed=await waitFor(f.queue,j=>j.state==='failed');assert.equal(await stat(f.destination).catch(()=>null),null);assert.ok(failed.bytes<bytes.length);f.truncated=false;f.corrupt=true;await f.queue.handle({action:'retry',id:failed.id});const corrupt=await waitFor(f.queue,j=>j.state==='failed');assert.equal(corrupt.issue,'integrity');assert.equal(await stat(f.destination).catch(()=>null),null);});
test('cancel retains a recoverable owned partial and removal deletes only that partial',async t=>{const f=await fixture(t);await f.queue.handle({action:'enqueue',selection});const running=await waitFor(f.queue,j=>j.bytes>=8192);await f.queue.handle({action:'cancel',id:running.id});const cancelled=await job(f.queue);assert.equal(cancelled.state,'cancelled');const partial=f.stored[0].partialPath;assert.ok((await stat(partial)).size>0);await f.queue.handle({action:'remove',id:running.id});assert.equal((await f.queue.handle({action:'list'})).total,0);assert.equal(await stat(partial).catch(()=>null),null);});
test('destination collision preserves existing contents',async t=>{const f=await fixture(t);await f.queue.handle({action:'enqueue',selection});await waitFor(f.queue,j=>j.bytes>=8192);await writeFile(f.destination,'existing work');const failed=await waitFor(f.queue,j=>j.state==='failed');assert.equal(failed.issue,'destination-exists');assert.equal(await readFile(f.destination,'utf8'),'existing work');});
test('restored paused jobs validate identity and checkpoint before resuming',async t=>{const f=await fixture(t);await f.queue.handle({action:'enqueue',selection});const running=await waitFor(f.queue,j=>j.bytes>=8192);await f.queue.close();const restored=new DownloadQueue(f.deps);t.after(()=>restored.close());const paused=await job(restored);assert.equal(paused.state,'paused');assert.ok(paused.resumable);await restored.handle({action:'resume',id:running.id});await waitFor(restored,j=>j.state==='completed');assert.deepEqual(await readFile(f.destination),bytes);});
test('recovery truncates bytes beyond a durable checkpoint and rejects changed prefix',async t=>{const f=await fixture(t);await f.queue.handle({action:'enqueue',selection});await waitFor(f.queue,j=>j.bytes>=8192);await f.queue.close();const checkpoint=f.stored[0];const data=await readFile(checkpoint.partialPath);await writeFile(checkpoint.partialPath,Buffer.concat([data,Buffer.from('uncommitted')]));const restored=new DownloadQueue(f.deps);t.after(()=>restored.close());const paused=await job(restored);assert.ok(paused.resumable);assert.equal((await stat(checkpoint.partialPath)).size,paused.bytes);await restored.close();const damaged=await readFile(checkpoint.partialPath);damaged[0]=2;await writeFile(checkpoint.partialPath,damaged);const rejected=new DownloadQueue(f.deps);t.after(()=>rejected.close());assert.equal((await job(rejected)).resumable,false);});
test('account changes prohibit reuse and do not send credentials',async t=>{const f=await fixture(t);await f.queue.handle({action:'enqueue',selection});const running=await waitFor(f.queue,j=>j.bytes>=8192);await f.queue.handle({action:'pause',id:running.id});f.account='account-b';await f.queue.handle({action:'resume',id:running.id});const failed=await waitFor(f.queue,j=>j.state==='failed');assert.equal(failed.issue,'authentication');assert.equal(f.requests.length,1);});
test('redirected CDN requests never receive approved-origin Authorization',async t=>{let cdnAuthorization:string|undefined;const cdn=createServer((req,res)=>{cdnAuthorization=req.headers.authorization;res.writeHead(200,{'content-length':bytes.length,etag:'"stable"','accept-ranges':'bytes'});res.end(bytes);});await new Promise<void>(resolve=>cdn.listen(0,'127.0.0.1',resolve));t.after(async()=>{cdn.closeAllConnections();await new Promise<void>(resolve=>cdn.close(()=>resolve()));});const cdnOrigin=`http://127.0.0.1:${(cdn.address() as {port:number}).port}`;const f=await fixture(t,(_req,res)=>{res.writeHead(302,{location:`${cdnOrigin}/signed?secret=temporary`});res.end();return true;});f.deps.approveRedirect=url=>url.origin===cdnOrigin;await f.queue.handle({action:'enqueue',selection});await waitFor(f.queue,j=>j.state==='completed');assert.equal(cdnAuthorization,undefined);assert.equal(JSON.stringify(f.stored).includes('temporary'),false);assert.equal(JSON.stringify(f.stored).includes('signed?'),false);});
test('malformed renderer selection and destination payloads fail closed; storage errors are redacted',async t=>{assert.throws(()=>validateDownloadSelection({...selection,url:'https://unapproved.test'}));assert.throws(()=>validateDownloadSelection({...selection,id:'../../other'}));const f=await fixture(t);await assert.rejects(f.queue.handle({action:'enqueue',selection,destination:'/other'} as never),/Invalid download action/);f.failStore=true;await assert.rejects(f.queue.handle({action:'enqueue',selection}),error=>error instanceof Error&&!error.message.includes('SECRET'));});
test('a symlink replacing a paused partial cannot be resumed or deleted by queue ownership',async t=>{const f=await fixture(t);await f.queue.handle({action:'enqueue',selection});const running=await waitFor(f.queue,j=>j.bytes>=8192);await f.queue.handle({action:'pause',id:running.id});const partial=f.stored[0].partialPath;const other=path.join(f.directory,'other');await writeFile(other,Buffer.alloc(running.bytes,3));await rm(partial);await symlink(other,partial);await f.queue.handle({action:'resume',id:running.id});await waitFor(f.queue,j=>j.state==='failed');await assert.rejects(f.queue.handle({action:'remove',id:running.id}));assert.deepEqual(await readFile(other),Buffer.alloc(running.bytes,3));});
test('a persisted finalization receipt recovers publication after an interrupted state save',async t=>{const f=await fixture(t);await f.queue.handle({action:'enqueue',selection});await waitFor(f.queue,j=>j.state==='completed');await f.queue.close();const interrupted=structuredClone(f.stored);interrupted[0].job.state='downloading';f.stored=interrupted;const restored=new DownloadQueue(f.deps);t.after(()=>restored.close());const result=await job(restored);assert.equal(result.state,'completed');assert.equal(result.bytes,bytes.length);assert.equal(result.verification,'sha256');assert.deepEqual(await readFile(f.destination),bytes);});
test('weak ETags prohibit resume and active-operation helpers await transfer shutdown',async t=>{const f=await fixture(t);f.etag='W/"weak"';await f.queue.handle({action:'enqueue',selection});assert.equal(f.queue.activeJobs(),1);assert.equal(f.queue.activeOperations.size,1);const running=await waitFor(f.queue,j=>j.bytes>=8192);await f.queue.pauseAll();assert.equal(f.queue.activeJobs(),0);const paused=await job(f.queue);assert.equal(paused.state,'paused');assert.equal(paused.resumable,false);await assert.rejects(f.queue.handle({action:'resume',id:running.id}),/Resume is unavailable/);await f.queue.handle({action:'retry',id:running.id});await f.queue.cancelAll();assert.equal(f.queue.activeJobs(),0);assert.equal((await job(f.queue)).state,'cancelled');});
test('workflow artifact ZIP uses its exact provider endpoint',async t=>{const f=await fixture(t);const artifact={...selection,kind:'artifact' as const,id:'456'};let endpoint='';const releaseResolver=f.deps.resolveSource;f.deps.resolveSource=async selected=>{const source=await releaseResolver(selected);endpoint=`/repos/${selected.repository}/actions/artifacts/${selected.id}/zip`;return {...source,selection:selected,endpoint,name:'artifact.zip'};};await f.queue.handle({action:'enqueue',selection:artifact});await waitFor(f.queue,j=>j.state==='completed');assert.equal(endpoint,'/repos/example/project/actions/artifacts/456/zip');assert.equal((await job(f.queue)).selection.kind,'artifact');});
test('provider rename invalidates resume and retry deliberately accepts the new canonical filename',async t=>{const f=await fixture(t);await f.queue.handle({action:'enqueue',selection});const running=await waitFor(f.queue,j=>j.bytes>=8192);await f.queue.handle({action:'pause',id:running.id});const resolve=f.deps.resolveSource;f.deps.resolveSource=async selected=>({...await resolve(selected),name:'renamed.bin'});await f.queue.handle({action:'resume',id:running.id});const failed=await waitFor(f.queue,j=>j.state==='failed');assert.equal(failed.issue,'source-changed');assert.equal(f.requests.length,1);await f.queue.handle({action:'retry',id:running.id});const completed=await waitFor(f.queue,j=>j.state==='completed');assert.equal(completed.name,'renamed.bin');assert.deepEqual(await readFile(f.destination),bytes);});
test('a failed startup store read is handled immediately and remains a fixed list error later',async t=>{const f=await fixture(t);const failed=new DownloadQueue({...f.deps,store:{read:async()=>{throw Error('SECRET native storage details');},write:async()=>{}}});t.after(()=>failed.close().catch(()=>{}));await delay(25);await assert.rejects(failed.handle({action:'list'}),error=>error instanceof Error&&error.message==='The native download service could not finish this action.');});
