import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {build} from 'esbuild';
import {chromium} from 'playwright';
const browserPath=existsSync('/usr/bin/chromium')?'/usr/bin/chromium':chromium.executablePath();
test('compiled provider rows emit exact release asset and artifact IDs and reject expired files',{skip:!existsSync(browserPath)},async()=>{
 const bundled=await build({stdin:{contents:"import './src/renderer/github-workspace.ts';import './src/renderer/scroll-surface.ts';",resolveDir:process.cwd(),sourcefile:'download-rows.ts'},bundle:true,write:false,format:'iife',platform:'browser',logLevel:'silent'});const browser=await chromium.launch({headless:true,executablePath:browserPath,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1280,height:1000}});page.setDefaultTimeout(3000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 try{await page.setContent('<style>mg-github-workspace{display:block;height:900px}.record-tab-scroll{height:60px}.record-list-scroll{height:240px}.detail-content-scroll{height:300px}</style><mg-github-workspace></mg-github-workspace>');await page.evaluate('globalThis.__name = value => value');await page.evaluate(()=>{const calls:unknown[]=[];Object.assign(window,{selectedDownloads:calls,material:{github:async(action:string,payload:{tab?:string})=>action.endsWith('.list')?{items:[{id:'55',title:'Fixture record'}],page:0,hasNext:false}:payload.tab==='assets'?{items:[{id:'123',name:'fixture.bin'}],page:0,hasNext:false}:payload.tab==='artifacts'?{items:[{id:'456',name:'artifact',expired:false},{id:'789',name:'expired-artifact',expired:true}],page:0,hasNext:false}:{detail:{id:'55',title:'Fixture record'},items:[],page:0,hasNext:false},exportData:async()=>true,openExternal:async()=>{}}});document.addEventListener('github-download-selection',event=>calls.push((event as CustomEvent).detail));});
 // Execute the actual compiled provider components against fixture records.
 await page.addScriptTag({content:bundled.outputFiles[0].text});
 await page.evaluate(()=>{const workspace=document.querySelector('mg-github-workspace') as unknown as {domain:string;repository:string;authenticated:boolean};workspace.domain='releases';workspace.repository='example/project';workspace.authenticated=true;});await page.locator('[data-testid=github-record]').click();await page.locator('md-secondary-tab').filter({hasText:'Assets'}).click();await page.getByRole('button',{name:'Download fixture.bin',exact:true}).click();assert.deepEqual(await page.evaluate(()=>(window as unknown as {selectedDownloads:unknown[]}).selectedDownloads),[{selection:{kind:'release-asset',hostname:'github.com',repository:'example/project',id:'123'},name:'fixture.bin'}]);
 await page.evaluate(()=>{const workspace=document.querySelector('mg-github-workspace') as unknown as {domain:string};workspace.domain='actions';});await page.locator('[data-testid=github-record]').click();await page.locator('md-secondary-tab').filter({hasText:'Artifacts'}).click();await page.getByRole('button',{name:'Download artifact',exact:true}).click();assert.deepEqual((await page.evaluate(()=>(window as unknown as {selectedDownloads:unknown[]}).selectedDownloads))[1],{selection:{kind:'artifact',hostname:'github.com',repository:'example/project',id:'456'},name:'artifact'});assert.ok(await page.getByRole('button',{name:'Download expired-artifact',exact:true}).isDisabled());assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
