import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {existsSync} from 'node:fs';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {build} from 'esbuild';
import {chromium} from 'playwright';
import {DownloadQueue,type StoredDownload} from '../src/main/downloads';
import type {DownloadRequest} from '../src/shared/downloads';
const browserPath=existsSync('/usr/bin/chromium')?'/usr/bin/chromium':chromium.executablePath();
test('compiled Material dialogs drive a real native streaming queue and localized recovery controls',{skip:!existsSync(browserPath)},async()=>{
 const directory=await mkdtemp(path.join(tmpdir(),'material-download-render-'));const destination=path.join(directory,'chosen.bin');const bytes=Buffer.alloc(128*1024,3);let records:StoredDownload[]=[];
 const bundled=await build({entryPoints:['src/renderer/downloads.ts'],bundle:true,write:false,format:'esm',platform:'browser',logLevel:'silent'});let queue:DownloadQueue;
 const server=createServer(async(req,res)=>{if(req.url==='/bundle.js'){res.setHeader('content-type','text/javascript');res.end(bundled.outputFiles[0].text);return;}if(req.url?.startsWith('/repos/')){res.writeHead(200,{'content-length':bytes.length,etag:'"render"','accept-ranges':'bytes'});let offset=0;const timer=setInterval(()=>{if(offset===bytes.length){clearInterval(timer);res.end();return;}res.write(bytes.subarray(offset,offset+4096));offset+=4096;},80);res.on('close',()=>clearInterval(timer));return;}if(req.url==='/download'){let body='';for await(const chunk of req)body+=chunk;try{const result=await queue.handle(JSON.parse(body) as DownloadRequest);res.setHeader('content-type','application/json');res.end(JSON.stringify(result));}catch{res.writeHead(400,{'content-type':'application/json'});res.end(JSON.stringify({error:'Download action failed'}));}return;}res.setHeader('content-type','text/html');res.end(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{margin:0;font:14px system-ui;background:#fafafa;color:#18201b}mg-downloads{box-sizing:border-box;padding:16px;height:900px;--md-sys-color-primary:#006b55;--md-sys-color-on-primary:white;--md-sys-color-surface:#fafafa;--md-sys-color-on-surface:#18201b;--surface:#fafafa;--outline:#52695e}</style><script type="module" src="/bundle.js"></script></head><body><mg-downloads></mg-downloads><script>customElements.whenDefined('mg-downloads').then(()=>{const component=document.querySelector('mg-downloads');component.settings={language:'en',englishHumor:0,cantoneseHumor:0,emojis:false};const handle=async request=>{const response=await fetch('/download',{method:'POST',body:JSON.stringify(request)});if(!response.ok)throw Error('Native action failed');return response.json();};component.client={handle,subscribe:listener=>{let stopped=false,last='';const tick=async()=>{if(stopped)return;try{const result=await handle({action:'list'});for(const job of result.items){const serialized=JSON.stringify(job);if(serialized!==last){last=serialized;listener(job);}}}finally{if(!stopped)setTimeout(tick,25);}};tick();return()=>{stopped=true;};}};});</script></body></html>`);});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 queue=new DownloadQueue({resolveSource:async selection=>({selection,apiOrigin:origin,endpoint:`/repos/${selection.repository}/releases/assets/${selection.id}`,name:'fixture.bin',size:bytes.length}),accountFingerprint:async()=> 'fixture-account',token:async()=>undefined,pickDestination:async()=>destination,store:{read:async()=>records,write:async rows=>{records=structuredClone(rows);}},allowLoopbackFixture:true});
 const browser=await chromium.launch({headless:true,executablePath:browserPath,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:540,height:1000}});const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 try{await page.goto(origin);await page.waitForFunction(()=>!!(document.querySelector('mg-downloads') as unknown as {client?:unknown}).client);
 const select=()=>page.evaluate(()=>{const component=document.querySelector('mg-downloads') as unknown as {selection:unknown;sourceName:string};component.sourceName='fixture.bin';component.selection={kind:'release-asset',hostname:'github.com',repository:'example/project',id:'123'};});
 await select();await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal((await queue.handle({action:'list'})).total,0);
 await select();await page.getByRole('button',{name:'Start and choose destination',exact:true}).click();await page.getByRole('dialog',{name:'Download progress',exact:true}).waitFor();await page.waitForFunction(()=>(document.querySelector('mg-downloads') as unknown as {focused?:{bytes:number}}).focused!.bytes>=8192);await page.getByRole('button',{name:'Pause',exact:true}).last().focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Resume',exact:true}).last().waitFor();await page.getByRole('button',{name:'Resume',exact:true}).last().click();
 // The fixture responds 200 to Range, so resume must expose source-change recovery.
 await page.getByRole('button',{name:'Retry from start',exact:true}).last().waitFor();await page.getByRole('button',{name:'Retry from start',exact:true}).last().click();await page.getByRole('button',{name:'Close progress',exact:true}).waitFor();await page.getByRole('button',{name:'Close progress',exact:true}).click();await page.getByText('Download complete: fixture.bin',{exact:true}).waitFor();assert.deepEqual(await readFile(destination),bytes);
 for(const language of ['en','yue','both']){await page.evaluate(language=>{const component=document.querySelector('mg-downloads') as unknown as {settings:Record<string,unknown>};component.settings={...component.settings,language};},language);await page.getByRole('button',{name:language==='en'?'Refresh':language==='yue'?'重新整理':'Refresh · 重新整理',exact:true}).waitFor();}
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('mg-scroll').first().locator('#viewport').evaluate(element=>getComputedStyle(element).scrollbarWidth),'none');assert.deepEqual(errors,[]);
 }finally{await browser.close();await queue.close();server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));await rm(directory,{recursive:true,force:true});}
});
