import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,readdirSync,existsSync,symlinkSync,chmodSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {GitService} from '../src/main/git';import {randomUUID} from 'node:crypto';
async function fixture(format='sha1'){const owned=mkdtempSync(path.join(tmpdir(),'material-git-packs-')),source=path.join(owned,'source'),root=path.join(owned,'repository'),global=path.join(owned,'isolated-config');for(const directory of [source,root])mkdirSync(directory);writeFileSync(global,'');const env={...process.env,GIT_CONFIG_GLOBAL:global,GIT_CONFIG_NOSYSTEM:'1'};const git=(directory:string,...argv:string[])=>{const result=spawnSync('git',argv,{cwd:directory,env,shell:false,encoding:'utf8'});assert.equal(result.status,0,result.stderr);return result.stdout;};for(const directory of [source,root]){git(directory,'init','--object-format='+format,'-b','main');git(directory,'config','user.name','Fixture Author');git(directory,'config','user.email','fixture@example.invalid');}writeFileSync(path.join(source,'unique.txt'),'Packed source contents\n');git(source,'add','--','unique.txt');git(source,'commit','-m','Packed source');const object=git(source,'rev-parse','HEAD:unique.txt').trim(),head=git(source,'rev-parse','HEAD').trim(),packId=git(source,'pack-objects','--all',path.join(owned,'input')).trim(),pack=path.join(owned,'input-'+packId+'.pack'),index=path.join(owned,'input-'+packId+'.idx');writeFileSync(path.join(root,'tracked.txt'),'Target original\n');git(root,'add','--','tracked.txt');git(root,'commit','-m','Target original');writeFileSync(path.join(root,'tracked.txt'),'Independent staged\n');git(root,'add','--','tracked.txt');writeFileSync(path.join(root,'tracked.txt'),'Independent working\n');let selected=pack;const purposes:string[]=[],outputPurposes:string[]=[];let outputParent=owned;const priorGlobal=process.env.GIT_CONFIG_GLOBAL,priorSystem=process.env.GIT_CONFIG_NOSYSTEM;process.env.GIT_CONFIG_GLOBAL=global;process.env.GIT_CONFIG_NOSYSTEM='1';const service=new GitService({binary:'git',directory:root,pickWorktree:async()=>root,pickOutputDirectory:async purpose=>{outputPurposes.push(purpose);return outputParent;},pickFile:async purpose=>{purposes.push(purpose||'');return selected;}});const opened=await service.handle('open');if(opened.kind!=='snapshot')throw new Error('Expected snapshot');const worktreeId=opened.snapshot.worktreeId;const imported=async(kind:'pack'|'index')=>{selected=kind==='pack'?pack:index;const result=await service.handle('import-pack',{kind});if(result.kind!=='file')throw new Error('Expected opaque pack input');return result.fileId;};const cleanup=()=>{service.close();if(priorGlobal===undefined)delete process.env.GIT_CONFIG_GLOBAL;else process.env.GIT_CONFIG_GLOBAL=priorGlobal;if(priorSystem===undefined)delete process.env.GIT_CONFIG_NOSYSTEM;else process.env.GIT_CONFIG_NOSYSTEM=priorSystem;rmSync(owned,{recursive:true,force:true});};return {owned,source,root,git,pack,index,packId,object,head,worktreeId,service,imported,purposes,outputPurposes,chooseOutputParent:(value:string)=>{outputParent=value;},cleanup};}

test('native pack verification and paged binary index inspection use exact grants without changing repository or inputs',async()=>{const f=await fixture();try{const source=readFileSync(f.pack),index=readFileSync(path.join(f.root,'.git','index')),head=f.git(f.root,'rev-parse','HEAD'),files=readdirSync(path.join(f.root,'.git','objects','pack'));const packId=await f.imported('pack'),indexId=await f.imported('index');assert.deepEqual(f.purposes,['pack','pack']);const verified=await f.service.handle('inspect',{worktreeId:f.worktreeId,kind:'verify-pack',fields:{fileId:packId,summary:true}});if(verified.kind!=='result')throw new Error('Expected verification');assert.equal(verified.ok,true,verified.error);assert.match(verified.output,/non delta|chain length/);const verbose=await f.service.handle('inspect',{worktreeId:f.worktreeId,kind:'verify-pack',fields:{fileId:packId,summary:false}});if(verbose.kind==='result')assert.ok(verbose.output.includes(f.object));const rows=await f.service.handle('inspect',{worktreeId:f.worktreeId,kind:'pack-index',fields:{fileId:indexId}});if(rows.kind!=='rows')throw new Error('Expected binary index rows');assert.ok(rows.rows.some(row=>row.id===f.object&&row.data?.crc));const beyond=await f.service.handle('inspect',{worktreeId:f.worktreeId,kind:'pack-index',fields:{fileId:indexId},page:1});if(beyond.kind==='rows')assert.equal(beyond.rows.length,0);assert.equal(f.git(f.root,'rev-parse','HEAD'),head);assert.deepEqual(readFileSync(path.join(f.root,'.git','index')),index);assert.equal(readFileSync(path.join(f.root,'tracked.txt'),'utf8'),'Independent working\n');assert.deepEqual(readFileSync(f.pack),source);assert.deepEqual(readdirSync(path.join(f.root,'.git','objects','pack')),files);}finally{f.cleanup();}});

test('reviewed binary pack import writes new verified objects and preserves existing references, index, inputs and working contents',async()=>{const f=await fixture();try{const fileId=await f.imported('pack'),source=readFileSync(f.pack),index=readFileSync(path.join(f.root,'.git','index')),refs=f.git(f.root,'for-each-ref','--format=%(refname) %(objectname)');const review=await f.service.handle('review',{worktreeId:f.worktreeId,task:'import-pack-objects',fields:{fileId}});if(review.kind!=='review')throw new Error('Expected import review');assert.ok(review.argv.includes('--strict'));const destination=path.join(f.root,'.git','objects','pack','pack-'+f.packId+'.pack');assert.equal(existsSync(destination),false);const result=await f.service.handle('apply',{reviewId:review.reviewId,confirmed:true});if(result.kind!=='result')throw new Error('Expected import result');assert.equal(result.ok,true,result.error);assert.equal(f.git(f.root,'cat-file','-p',f.object),'Packed source contents\n');assert.equal(f.git(f.root,'cat-file','-t',f.head).trim(),'commit');assert.equal(existsSync(destination),true);assert.equal(existsSync(destination.replace(/\.pack$/,'.keep')),true);assert.deepEqual(readFileSync(f.pack),source);assert.deepEqual(readFileSync(path.join(f.root,'.git','index')),index);assert.equal(f.git(f.root,'for-each-ref','--format=%(refname) %(objectname)'),refs);assert.equal(f.git(f.root,'show',':tracked.txt'),'Independent staged\n');assert.equal(readFileSync(path.join(f.root,'tracked.txt'),'utf8'),'Independent working\n');await assert.rejects(f.service.handle('review',{worktreeId:f.worktreeId,task:'import-pack-objects',fields:{fileId}}),/already exists/);await assert.rejects(f.service.handle('apply',{reviewId:review.reviewId,confirmed:true}),/already used/);}finally{f.cleanup();}});

test('pack sources, checksums and destination changes reject before overwrite and metadata links are refused',async()=>{const f=await fixture();try{const fileId=await f.imported('pack');const reviewed=await f.service.handle('review',{worktreeId:f.worktreeId,task:'import-pack-objects',fields:{fileId}});if(reviewed.kind!=='review')throw new Error('Expected review');const occupied=path.join(f.root,'.git','objects','pack','pack-'+f.packId+'.idx');writeFileSync(occupied,'Preserved occupied destination\n');await assert.rejects(f.service.handle('apply',{reviewId:reviewed.reviewId,confirmed:true}),/storage or destination changed/);assert.equal(readFileSync(occupied,'utf8'),'Preserved occupied destination\n');rmSync(occupied);const original=readFileSync(f.pack);chmodSync(f.pack,0o600);writeFileSync(f.pack,Buffer.concat([original,Buffer.from('changed')]));await assert.rejects(f.service.handle('inspect',{worktreeId:f.worktreeId,kind:'verify-pack',fields:{fileId}}),/changed/);writeFileSync(f.pack,original);const invalid=Buffer.from(original);invalid[15]^=1;writeFileSync(f.pack,invalid);const malformed=await f.imported('pack');await assert.rejects(f.service.handle('review',{worktreeId:f.worktreeId,task:'import-pack-objects',fields:{fileId:malformed}}),/checksum/);writeFileSync(f.pack,original);const restored=await f.imported('pack');const linked=path.join(f.root,'.git','objects','pack','linked.pack');symlinkSync(f.pack,linked);await assert.rejects(f.service.handle('review',{worktreeId:f.worktreeId,task:'import-pack-objects',fields:{fileId:restored}}),/without links/);assert.equal(readFileSync(path.join(f.root,'tracked.txt'),'utf8'),'Independent working\n');assert.deepEqual(readFileSync(f.pack),original);}finally{f.cleanup();}});


test('SHA-256 repositories inspect and import matching 64-digit pack/index objects using the actual native format',async()=>{const f=await fixture('sha256');try{assert.equal(f.object.length,64);const fileId=await f.imported('pack'),indexId=await f.imported('index');const verified=await f.service.handle('inspect',{worktreeId:f.worktreeId,kind:'verify-pack',fields:{fileId,summary:true}});if(verified.kind!=='result')throw new Error('Expected verification');assert.equal(verified.ok,true,verified.error);const entries=await f.service.handle('inspect',{worktreeId:f.worktreeId,kind:'pack-index',fields:{fileId:indexId}});if(entries.kind!=='rows')throw new Error('Expected index');assert.ok(entries.rows.some(row=>row.id===f.object));const review=await f.service.handle('review',{worktreeId:f.worktreeId,task:'import-pack-objects',fields:{fileId}});if(review.kind!=='review')throw new Error('Expected review');const result=await f.service.handle('apply',{reviewId:review.reviewId,confirmed:true});if(result.kind==='result')assert.equal(result.ok,true,result.error);assert.equal(f.git(f.root,'cat-file','-p',f.object),'Packed source contents\n');assert.equal(f.git(f.root,'show',':tracked.txt'),'Independent staged\n');assert.equal(readFileSync(path.join(f.root,'tracked.txt'),'utf8'),'Independent working\n');}finally{f.cleanup();}});


test('native index intake rejects excessive fanout and malformed checksums before object inspection',async()=>{const f=await fixture();try{const original=readFileSync(f.index);chmodSync(f.index,0o600);const huge=Buffer.from(original);huge.writeUInt32BE(1000001,8);writeFileSync(f.index,huge);await assert.rejects(f.imported('index'),/fanout/);const invalid=Buffer.from(original);invalid[invalid.length-1]^=1;writeFileSync(f.index,invalid);const fileId=await f.imported('index');await assert.rejects(f.service.handle('inspect',{worktreeId:f.worktreeId,kind:'pack-index',fields:{fileId}}),/checksum/);assert.equal(f.git(f.root,'show',':tracked.txt'),'Independent staged\n');assert.equal(readFileSync(path.join(f.root,'tracked.txt'),'utf8'),'Independent working\n');}finally{f.cleanup();}});


test('native reachable-object pack export creates a fresh selected scope, verifies and reopens exact SHA-1 and SHA-256 objects',async()=>{for(const format of ['sha1','sha256']){const f=await fixture(format);try{const sourceIndex=readFileSync(path.join(f.root,'.git','index')),refs=f.git(f.root,'for-each-ref','--format=%(refname) %(objectname)'),head=f.git(f.root,'rev-parse','HEAD').trim(),blob=f.git(f.root,'rev-parse','HEAD:tracked.txt').trim();const review=await f.service.handle('review',{worktreeId:f.worktreeId,task:'export-object-pack',fields:{name:'selected-export',scope:'selected-commit',revision:'main',compression:4,window:8,depth:20}});if(review.kind!=='review')throw new Error('Expected pack export review');assert.deepEqual(f.outputPurposes,['pack-export']);assert.ok(review.warnings.some(value=>value.includes('Object manifest SHA-256')));assert.equal(existsSync(path.join(f.owned,'selected-export')),false);const result=await f.service.handle('apply',{reviewId:review.reviewId,confirmed:true});if(result.kind!=='result')throw new Error('Expected export');assert.equal(result.ok,true,result.error);assert.match(result.output,/Verified and reopened 3 exact objects/);const files=readdirSync(path.join(f.owned,'selected-export'));assert.equal(files.length,2);const pack=path.join(f.owned,'selected-export',files.find(name=>name.endsWith('.pack'))!);const reopen=path.join(f.owned,'reopen');mkdirSync(reopen);f.git(reopen,'init','--bare','--object-format='+format);const imported=spawnSync('git',['index-pack','--stdin','--strict'],{cwd:reopen,env:{...process.env,GIT_CONFIG_NOSYSTEM:'1'},input:readFileSync(pack),encoding:'utf8'});assert.equal(imported.status,0,imported.stderr);assert.equal(f.git(reopen,'cat-file','-t',head).trim(),'commit');assert.equal(f.git(reopen,'cat-file','-p',blob),'Target original\n');assert.equal(f.git(f.root,'for-each-ref','--format=%(refname) %(objectname)'),refs);assert.deepEqual(readFileSync(path.join(f.root,'.git','index')),sourceIndex);assert.equal(f.git(f.root,'show',':tracked.txt'),'Independent staged\n');assert.equal(readFileSync(path.join(f.root,'tracked.txt'),'utf8'),'Independent working\n');await assert.rejects(f.service.handle('review',{worktreeId:f.worktreeId,task:'export-object-pack',fields:{name:'selected-export'}}),/fresh export folder/);}finally{f.cleanup();}}});

test('all-reference export includes a separately tagged blob and binds source storage and native output parent before creation',async()=>{const f=await fixture();try{const fileId=await f.imported('pack'),importReview=await f.service.handle('review',{worktreeId:f.worktreeId,task:'import-pack-objects',fields:{fileId}});if(importReview.kind!=='review')throw new Error();await f.service.handle('apply',{reviewId:importReview.reviewId,confirmed:true});f.git(f.root,'update-ref','refs/tags/extra-blob',f.object);const reviewed=await f.service.handle('review',{worktreeId:f.worktreeId,task:'export-object-pack',fields:{name:'all-export',scope:'all-references',compression:0}});if(reviewed.kind!=='review')throw new Error();assert.ok(reviewed.warnings.some(value=>value.includes('Exports 4 exact reachable objects')));const result=await f.service.handle('apply',{reviewId:reviewed.reviewId,confirmed:true});if(result.kind==='result')assert.equal(result.ok,true,result.error);const index=path.join(f.owned,'all-export',readdirSync(path.join(f.owned,'all-export')).find(name=>name.endsWith('.idx'))!);const read=spawnSync('git',['show-index'],{input:readFileSync(index),encoding:'utf8'});assert.equal(read.status,0,read.stderr);assert.ok(read.stdout.includes(f.object));const stale=await f.service.handle('review',{worktreeId:f.worktreeId,task:'export-object-pack',fields:{name:'stale-export'}});if(stale.kind!=='review')throw new Error();writeFileSync(path.join(f.owned,'new-unrelated-output'),'Preserve concurrent output\n');await assert.rejects(f.service.handle('apply',{reviewId:stale.reviewId,confirmed:true}),/native destination changed/);assert.equal(existsSync(path.join(f.owned,'stale-export')),false);const changed=await f.service.handle('review',{worktreeId:f.worktreeId,task:'export-object-pack',fields:{name:'changed-source'}});if(changed.kind!=='review')throw new Error();f.git(f.root,'hash-object','-w','--','tracked.txt');await assert.rejects(f.service.handle('apply',{reviewId:changed.reviewId,confirmed:true}),/source objects/);assert.equal(existsSync(path.join(f.owned,'changed-source')),false);f.chooseOutputParent(path.join(f.root,'.git'));await assert.rejects(f.service.handle('review',{worktreeId:f.worktreeId,task:'export-object-pack',fields:{name:'metadata-output'}}),/outside Git metadata/);await assert.rejects(f.service.handle('review',{worktreeId:f.worktreeId,task:'export-object-pack',fields:{compression:'6'}}),/valid compression/);}finally{f.cleanup();}});

test('redundant loose-copy inspection and reviewed native pruning retain verified packed identities and independent staged/working contents',async()=>{for(const format of ['sha1','sha256']){const f=await fixture(format);try{const packed=f.git(f.root,'pack-objects','--all',path.join(f.root,'.git','objects','pack','pack')).trim(),packPath=path.join(f.root,'.git','objects','pack','pack-'+packed+'.pack'),pack=readFileSync(packPath),index=readFileSync(path.join(f.root,'.git','index')),head=f.git(f.root,'rev-parse','HEAD'),staged=f.git(f.root,'rev-parse',':tracked.txt').trim();const rows=await f.service.handle('inspect',{worktreeId:f.worktreeId,kind:'redundant-objects'});if(rows.kind!=='rows')throw new Error('Expected redundant copy rows');assert.equal(rows.rows.length,3);assert.match(rows.notice||'',/3 redundant/);assert.ok(!rows.rows.some(row=>row.id===staged));for(const row of rows.rows)assert.equal(existsSync(path.join(f.root,'.git','objects',row.id.slice(0,2),row.id.slice(2))),true);const review=await f.service.handle('review',{worktreeId:f.worktreeId,task:'prune-packed-copies',fields:{}});if(review.kind!=='review')throw new Error('Expected prune review');assert.equal(review.warnings.filter(warning=>warning.startsWith('Remove loose copy:')).length,3);const result=await f.service.handle('apply',{reviewId:review.reviewId,confirmed:true});if(result.kind!=='result')throw new Error('Expected native prune result');assert.equal(result.ok,true,result.error);assert.match(result.output,/Removed 3 reviewed redundant loose copies/);for(const row of rows.rows){assert.equal(existsSync(path.join(f.root,'.git','objects',row.id.slice(0,2),row.id.slice(2))),false);assert.ok(['commit','tree','blob'].includes(f.git(f.root,'cat-file','-t',row.id).trim()));}assert.equal(existsSync(path.join(f.root,'.git','objects',staged.slice(0,2),staged.slice(2))),true);assert.deepEqual(readFileSync(packPath),pack);assert.deepEqual(readFileSync(path.join(f.root,'.git','index')),index);assert.equal(f.git(f.root,'rev-parse','HEAD'),head);assert.equal(f.git(f.root,'show',':tracked.txt'),'Independent staged\n');assert.equal(readFileSync(path.join(f.root,'tracked.txt'),'utf8'),'Independent working\n');await assert.rejects(f.service.handle('review',{worktreeId:f.worktreeId,task:'prune-packed-copies',fields:{}}),/No redundant/);}finally{f.cleanup();}}});

test('packed/loose storage changes, invalid pack contents and loose metadata links prevent destructive cleanup',async()=>{const f=await fixture();try{const packId=f.git(f.root,'pack-objects','--all',path.join(f.root,'.git','objects','pack','pack')).trim();const review=await f.service.handle('review',{worktreeId:f.worktreeId,task:'prune-packed-copies',fields:{}});if(review.kind!=='review')throw new Error();f.git(f.root,'hash-object','-w','--','tracked.txt');await assert.rejects(f.service.handle('apply',{reviewId:review.reviewId,confirmed:true}),/storage changed/);const head=f.git(f.root,'rev-parse','HEAD').trim(),loose=path.join(f.root,'.git','objects',head.slice(0,2),head.slice(2));assert.equal(existsSync(loose),true);const packed=path.join(f.root,'.git','objects','pack','pack-'+packId+'.pack'),original=readFileSync(packed);chmodSync(packed,0o600);const corrupted=Buffer.from(original);corrupted[15]^=1;writeFileSync(packed,corrupted);await assert.rejects(f.service.handle('review',{worktreeId:f.worktreeId,task:'prune-packed-copies',fields:{}}),/checksum/);assert.equal(existsSync(loose),true);writeFileSync(packed,original);const saved=readFileSync(loose);rmSync(loose);symlinkSync(f.pack,loose);await assert.rejects(f.service.handle('inspect',{worktreeId:f.worktreeId,kind:'redundant-objects'}),/without links/);rmSync(loose);writeFileSync(loose,saved);assert.equal(f.git(f.root,'show',':tracked.txt'),'Independent staged\n');assert.equal(readFileSync(path.join(f.root,'tracked.txt'),'utf8'),'Independent working\n');}finally{f.cleanup();}});


test('owned export cancellation stops a resistant descendant before it can produce later effects and retains the new output folder',{skip:process.platform==='win32'},async()=>{
 const f=await fixture();let service:GitService|undefined;let pids:number[]=[];
 const running=(pid:number)=>{try{process.kill(pid,0);return !existsSync('/proc/'+pid+'/stat')||!readFileSync('/proc/'+pid+'/stat','utf8').includes(') Z ');}catch{return false;}};
 const until=async(check:()=>boolean,limit:number)=>{const deadline=Date.now()+limit;while(!check()&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,20));return check();};
 try{
  const marker=path.join(f.owned,'export-started'),lateEffect=path.join(f.owned,'descendant-effect'),binary=path.join(f.owned,'owned-git-wrapper');
  // Readiness comes from the descendant after installing its signal handler. Its
  // delayed write detects a surviving process without mutating any user files.
  const descendant=`const fs=require('node:fs');process.on('SIGTERM',()=>{});fs.writeFileSync(${JSON.stringify(marker)},String(process.ppid)+','+process.pid);setTimeout(()=>fs.writeFileSync(${JSON.stringify(lateEffect)},'Unexpected descendant effect'),10000);setInterval(()=>{},1000);`;
  writeFileSync(binary,`#!/usr/bin/env node
const {spawn}=require('node:child_process');const args=process.argv.slice(2);if(args.includes('pack-objects')){spawn(process.execPath,['-e',${JSON.stringify(descendant)}],{stdio:'ignore'});setInterval(()=>{},1000);}else{const child=spawn('git',args,{stdio:'inherit'});child.on('exit',code=>process.exit(code??1));}
`,{mode:0o700});
  service=new GitService({binary,directory:f.root,pickWorktree:async()=>f.root,pickOutputDirectory:async()=>f.owned});
  const opened=await service.handle('open');if(opened.kind!=='snapshot')throw new Error();
  const index=readFileSync(path.join(f.root,'.git','index')),refs=f.git(f.root,'for-each-ref','--format=%(refname) %(objectname)'),review=await service.handle('review',{worktreeId:opened.snapshot.worktreeId,task:'export-object-pack',fields:{name:'cancelled-export'}});
  if(review.kind!=='review')throw new Error();
  const operationId=randomUUID(),pending=service.handle('apply',{reviewId:review.reviewId,confirmed:true,operationId});
  assert.equal(await until(()=>existsSync(marker),10000),true,'Owned descendant must report readiness');
  pids=readFileSync(marker,'utf8').split(',').map(Number);assert.equal(pids.length,2);assert.ok(pids.every(pid=>Number.isSafeInteger(pid)&&pid>0));assert.ok(pids.every(running));
  await service.handle('cancel',{operationId});const result=await pending;
  if(result.kind!=='result')throw new Error('Expected cancelled native export result');
  assert.equal(result.cancelled,true);assert.equal(result.partialEffects,true);assert.match(result.error,/Export files may remain/);assert.equal(existsSync(path.join(f.owned,'cancelled-export')),true);
  // The leader's close event does not mean every group member has exited. Wait
  // for the bounded SIGKILL escalation, checking actual PIDs rather than sleeping.
  assert.equal(await until(()=>pids.every(pid=>!running(pid)),5000),true,'Owned leader and resistant descendant must stop');
  assert.equal(existsSync(lateEffect),false,'Cancelled descendant must not produce a delayed effect');
  assert.deepEqual(readFileSync(path.join(f.root,'.git','index')),index);assert.equal(f.git(f.root,'for-each-ref','--format=%(refname) %(objectname)'),refs);assert.equal(f.git(f.root,'show',':tracked.txt'),'Independent staged\n');assert.equal(readFileSync(path.join(f.root,'tracked.txt'),'utf8'),'Independent working\n');
 }finally{service?.close();for(const pid of pids)if(Number.isSafeInteger(pid)&&pid>0&&running(pid))try{process.kill(pid,'SIGKILL');}catch{}f.cleanup();}
});


test('pack export refuses promised, shallow and alternate sources before network reads or output creation',async()=>{const f=await fixture();try{const review=()=>f.service.handle('review',{worktreeId:f.worktreeId,task:'export-object-pack',fields:{name:'guarded-export'}});f.git(f.root,'config','remote.promise.url','https://example.invalid/no-contact.git');f.git(f.root,'config','remote.promise.promisor','true');await assert.rejects(review(),/complete local object storage/);f.git(f.root,'config','--unset','remote.promise.promisor');const shallow=path.join(f.root,'.git','shallow');writeFileSync(shallow,f.git(f.root,'rev-parse','HEAD'));await assert.rejects(review(),/complete local object storage/);rmSync(shallow);const alternates=path.join(f.root,'.git','objects','info','alternates');writeFileSync(alternates,path.join(f.source,'.git','objects')+'\n');await assert.rejects(review(),/complete local object storage/);assert.equal(existsSync(path.join(f.owned,'guarded-export')),false);assert.deepEqual(f.outputPurposes,[]);assert.equal(f.git(f.root,'show',':tracked.txt'),'Independent staged\n');assert.equal(readFileSync(path.join(f.root,'tracked.txt'),'utf8'),'Independent working\n');}finally{f.cleanup();}});
