import {_electron as electron} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';
const root=fileURLToPath(new URL('..',import.meta.url));const require=createRequire(import.meta.url);const executablePath=require('electron');
const dir=await fs.mkdtemp(join(tmpdir(),'material-git-guided-'));await fs.mkdir(`${dir}/gh-config`,{recursive:true});await fs.writeFile(`${dir}/body.txt`,'Verification body.');const env={...process.env,MATERIAL_GIT_TEST:'1',MATERIAL_GIT_USER_DATA:`${dir}/profile`,GH_CONFIG_DIR:`${dir}/gh-config`};for(const key of ['GH_TOKEN','GITHUB_TOKEN','GH_ENTERPRISE_TOKEN','GITHUB_ENTERPRISE_TOKEN'])delete env[key];const app=await electron.launch({executablePath,args:['--no-sandbox','--ozone-platform=headless','.'],cwd:root,env});const page=await app.firstWindow();const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const open=async(id)=>{await page.locator('.task-tab-row md-text-button[data-task-tab]').first().click();const search=page.locator('.catalog-search mg-search');await search.getByRole('textbox',{name:'Search commands',exact:true}).fill(id);await page.locator('.command-list md-list-item').filter({has:page.locator('[slot=headline]',{hasText:new RegExp(`^${id}$`)})}).click();};
try{await page.setViewportSize({width:1420,height:940});await page.locator('.command-list md-list-item').first().waitFor({timeout:45000});
await open('issue list');const exact=page.getByRole('spinbutton',{name:'--limit exact value',exact:true});await exact.fill('2147483647');assert.equal(await page.locator('mg-app').evaluate(a=>a.values.limit),2147483647);assert.equal(await page.locator('[data-design-id="field-issue list-option-limit"] md-slider').evaluate(e=>e.max),100);await page.getByRole('button',{name:'Decrease limit by one',exact:true}).click();assert.equal(await page.locator('mg-app').evaluate(a=>a.values.limit),2147483646);await exact.fill('0');assert.equal(await page.locator('mg-app').evaluate(a=>a.validate()),false);await exact.fill('30');assert.equal(await page.locator('mg-app').evaluate(a=>a.validate()),true);await page.screenshot({path:`${dir}/numeric.png`});checks.push('numeric everyday range, maximum exact value, stepper, bounds validation');
const stateSelect=page.locator('md-filled-select[label="--state"]');assert.equal(await stateSelect.evaluate(e=>e.value),'open');assert.equal(await stateSelect.locator('md-select-option[selected]').count(),1);checks.push('default enum selected explicitly');
await open('issue view');const identifier=page.getByRole('textbox',{name:'number-url · required direct identifier (optional)',exact:true});await identifier.fill('https://github.com/octocat/Hello-World/issues/1');assert.equal(await page.locator('mg-app').evaluate(a=>a.validate()),true);await identifier.fill('https://user:pass@github.com/octocat/Hello-World/issues/1');assert.equal(await page.locator('mg-app').evaluate(a=>a.validate()),false);checks.push('direct entity HTTPS identifier accepted; embedded credentials rejected locally');
await open('issue create');await page.getByRole('textbox',{name:'--title · required',exact:true}).fill('Validation only');await page.locator('mg-app').evaluate((a,path)=>{const field=a.selected.options.find(o=>o.name==='body-file');a.setValue(field,path,false);},`${dir}/body.txt`);assert.equal(await page.locator('mg-app').evaluate(a=>a.validate()),true);await page.getByRole('button',{name:'Review changes',exact:true}).click();await page.locator('md-dialog[open]').filter({hasText:'This runs gh issue create.'}).waitFor();await page.getByRole('button',{name:'Cancel',exact:true}).click();checks.push('selected body-file satisfies required body and opens review without executing; path supplied to normal field setter for native picker alternative');
await open('auth token');const blocked=page.getByRole('button',{name:'Unavailable in guided runner',exact:true});assert.equal(await blocked.isDisabled(),true);assert.ok(await page.locator('.availability').innerText().then(t=>t.includes('intentionally unavailable')));checks.push('auth token cannot run and has precise explanation');
await open('auth login');await page.getByRole('button',{name:'Open Accounts',exact:true}).click();await page.locator('mg-accounts').waitFor();checks.push('auth login routes to supported Accounts workflow');
await page.evaluate(()=>window.dispatchEvent(new CustomEvent('api-work-state',{detail:{busy:true,dirty:true}})));await page.evaluate(()=>window.material.window('close'));await page.locator('.notice').filter({hasText:'API request is still running'}).waitFor();assert.equal(await page.locator('mg-app').evaluate(a=>a.closeAppOpen),false);await page.evaluate(()=>window.dispatchEvent(new CustomEvent('api-work-state',{detail:{busy:false,dirty:true}})));await page.evaluate(()=>window.material.window('close'));await page.getByRole('button',{name:'Keep working',exact:true}).waitFor();await page.getByRole('button',{name:'Keep working',exact:true}).click();checks.push('API state event blocks close while busy and confirms dirty draft discard when idle');
assert.deepEqual(errors,[]);await fs.writeFile(`${dir}/receipt.json`,JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({dir,checks,errors}));
}catch(e){console.log(JSON.stringify({failure:e.stack,checks,errors}));await page.screenshot({path:`${dir}/failure.png`});process.exitCode=1;}finally{await page.evaluate(()=>window.material.window('confirm-close')).catch(()=>{});await app.close().catch(()=>{});}
