import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,readFile,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{EventEmitter}from'node:events';import{PassThrough}from'node:stream';import type{ChildProcess}from'node:child_process';
import{createAuthHostRegistry}from'../src/main/auth-hosts.js';import{AuthService}from'../src/main/auth.js';import{activeHostAccount}from'../src/shared/account-context.js';import type{AuthState,AuthAccount}from'../src/shared/types.js';
const account=(host:string,login:string,source:AuthAccount['tokenSource']='credential-store',state='success'):AuthAccount=>({host,login,active:true,state,tokenSource:source,scopes:['repo'],gitProtocol:'https'});
test('native approved-host selection persists, restores and migrates without inferring an arbitrary host',async()=>{const directory=await mkdtemp(join(tmpdir(),'mg-host-context-'));try{await writeFile(join(directory,'approved-hosts.json'),JSON.stringify({schemaVersion:1,hosts:['github.com','forge.example']}));const hosts=createAuthHostRegistry(directory);await hosts.load();assert.equal(hosts.selectedHost().hostname,'github.com');await assert.rejects(hosts.selectHost('evil.example'),/approved/);await hosts.selectHost('forge.example');assert.equal(hosts.resolveHost().restOrigin,'https://forge.example/api/v3');await hosts.register('other.example');const restored=createAuthHostRegistry(directory);await restored.load();assert.equal(restored.selectedHost().hostname,'forge.example');const record=JSON.parse(await readFile(join(directory,'approved-hosts.json'),'utf8'));assert.deepEqual(Object.keys(record).sort(),['hosts','schemaVersion','selectedHostname']);assert.equal(record.schemaVersion,2);assert.ok(!JSON.stringify(record).includes('token'));await writeFile(join(directory,'approved-hosts.json'),JSON.stringify({...record,selectedHostname:'evil.example'}));await assert.rejects(createAuthHostRegistry(directory).load(),/invalid/);}finally{await rm(directory,{recursive:true,force:true});}});
test('selected account context stays on the approved native host and respects invalid environment precedence',()=>{const state:AuthState={status:'authenticated',selectedHostname:'forge.example',allowedHosts:['github.com','forge.example'],allowedScopes:[],accounts:[account('github.com','public-user'),account('forge.example','saved-user'),account('forge.example','environment-user','environment','error')]};assert.equal(activeHostAccount(state)?.login,'environment-user');assert.equal(activeHostAccount(state)?.state,'error');assert.equal(activeHostAccount({...state,selectedHostname:'evil.example'}),undefined);assert.equal(activeHostAccount({...state,selectedHostname:undefined}),undefined);assert.equal(activeHostAccount({...state,accounts:state.accounts.slice(0,2)})?.login,'saved-user');});
class Child extends EventEmitter{stdout=new PassThrough();stderr=new PassThrough();kill(){return true;}}
function service(selectHost:(host:string)=>Promise<string>,blocked=false){const calls:string[][]=[];const auth=new AuthService('fixture-gh',process.cwd(),{allowedHosts:['github.com','forge.example'],selectedHostname:'github.com',selectHost,authorize:async()=>{if(blocked)throw new Error('An operation is active');},spawn:(_binary,args)=>{calls.push(args);assert.equal(args[1],'status');const child=new Child();queueMicrotask(()=>{const host=args[2].split('=')[1];child.stdout.end(JSON.stringify({hosts:{[host]:[{...account(host,host==='github.com'?'public-user':'enterprise-user'),tokenSource:'keyring',scopes:'repo'}]}}));child.emit('close',0);});return child as unknown as ChildProcess;}});return{auth,calls};}
test('host choice requires exact review and native approval, emits verified full context and runs only status',async()=>{const selected:string[]=[];const{auth,calls}=service(async host=>{selected.push(host);return host;});for(const payload of[{hostname:'evil.example',reviewedHostname:'evil.example',confirmed:true},{hostname:'forge.example',confirmed:true},{hostname:'forge.example',reviewedHostname:'github.com',confirmed:true}])await assert.rejects(auth.action('select-host',payload));assert.equal(calls.length,0);const events:AuthState[]=[];auth.subscribe(state=>events.push(state));const result=await auth.action('select-host',{hostname:'forge.example',reviewedHostname:'forge.example',confirmed:true});assert.deepEqual(selected,['forge.example']);assert.equal(result.selectedHostname,'forge.example');assert.equal(activeHostAccount(result)?.login,'enterprise-user');assert.ok(events.every(state=>state.allowedHosts.includes(state.selectedHostname!)));assert.ok(calls.every(args=>args[1]==='status'));assert.equal(result.deviceCode,undefined);assert.ok(!calls.some(args=>['login','switch','logout','token'].includes(args[1])));});
test('native operation guard and mismatched durable callback leave selected context unchanged',async()=>{const blocked=service(async host=>host,true);await assert.rejects(blocked.auth.action('select-host',{hostname:'forge.example',reviewedHostname:'forge.example',confirmed:true}),/active/);assert.equal(blocked.auth.snapshot().selectedHostname,'github.com');assert.equal(blocked.calls.length,0);const wrong=service(async()=> 'github.com');await assert.rejects(wrong.auth.action('select-host',{hostname:'forge.example',reviewedHostname:'forge.example',confirmed:true}),/verified/);assert.equal(wrong.auth.snapshot().selectedHostname,'github.com');assert.equal(wrong.calls.length,0);});

test('actual application host update clears an old same-name repository, picker state and download intent',async()=>{
 const{readFileSync}=await import('node:fs');const{default:ts}=await import('typescript');const source=readFileSync(new URL('../src/renderer/app.ts',import.meta.url),'utf8'),tree=ts.createSourceFile('app.ts',source,ts.ScriptTarget.Latest,true);let method='';const visit=(node:import('typescript').Node)=>{if(ts.isMethodDeclaration(node)&&node.name.getText(tree)==='applyAuthentication')method=node.getText(tree).replace(/^private\s+/,'');ts.forEachChild(node,visit);};visit(tree);assert.ok(method);const javascript=ts.transpileModule(`class Context{${method}};globalThis.tested=Context.prototype.applyAuthentication;`,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;const binding:{tested?:Function}={};new Function('globalThis','activeHostAccount',javascript)(binding,activeHostAccount);
 const model={data:{hostname:'github.com',account:'public-user',repository:'owner/same-name',authenticated:true},repoGeneration:1,repoTimer:undefined,repoQuery:'old query',repositories:[{value:'owner/same-name'}],repoPage:4,repoNext:true,repositoryOpen:true,downloadSelection:{kind:'release'},downloadName:'old download',querySelectorAll:()=>[],accountContextFingerprint:'',copy:(en:string)=>en,notify:()=>{}};
 const state:AuthState={status:'authenticated',selectedHostname:'forge.example',allowedHosts:['github.com','forge.example'],allowedScopes:[],accounts:[account('github.com','public-user'),account('forge.example','enterprise-user')]};binding.tested!.call(model,state);assert.equal(model.data.hostname,'forge.example');assert.equal(model.data.account,'enterprise-user');assert.equal(model.data.repository,null);assert.equal(model.repoGeneration,2);assert.equal(model.repoQuery,'');assert.deepEqual(model.repositories,[]);assert.equal(model.repositoryOpen,false);assert.equal(model.downloadSelection,undefined);
 const unchanged=structuredClone(state);unchanged.selectedHostname='unapproved.example';binding.tested!.call(model,unchanged);assert.equal(model.data.hostname,'forge.example');
});

test('host selection publishes one verified context after status, never an intermediate change during active readback',async()=>{
 const children:Child[]=[],events:AuthState[]=[];const auth=new AuthService('fixture-gh',process.cwd(),{allowedHosts:['github.com','forge.example'],selectHost:async host=>host,spawn:()=>{const child=new Child();children.push(child);return child as unknown as ChildProcess;}});auth.subscribe(state=>events.push(state));const selection=auth.action('select-host',{hostname:'forge.example',reviewedHostname:'forge.example',confirmed:true});await new Promise(resolve=>setImmediate(resolve));assert.equal(children.length,1);assert.equal(events.length,0);await assert.rejects(auth.action('select-host',{hostname:'github.com',reviewedHostname:'github.com',confirmed:true}),/Finish/);children[0].stdout.end(JSON.stringify({hosts:{'github.com':[]}}));children[0].emit('close',0);await new Promise(resolve=>setImmediate(resolve));assert.equal(children.length,2);assert.equal(events.length,0);children[1].stdout.end(JSON.stringify({hosts:{'forge.example':[]}}));children[1].emit('close',0);const state=await selection;assert.equal(state.selectedHostname,'forge.example');assert.equal(events.length,1);assert.equal(events[0].selectedHostname,'forge.example');
});

test('actual API context invalidation clears authorization and upload grants while retaining unsubmitted typed input',async()=>{
 const{readFileSync}=await import('node:fs');const{default:ts}=await import('typescript');const source=readFileSync(new URL('../src/renderer/api-explorer.ts',import.meta.url),'utf8'),tree=ts.createSourceFile('api.ts',source,ts.ScriptTarget.Latest,true),methods:string[]=[];const visit=(node:import('typescript').Node)=>{if(ts.isMethodDeclaration(node)&&['invalidateAccountContext','cancelReview'].includes(node.name.getText(tree)))methods.push(node.getText(tree).replace(/^private\s+/,''));ts.forEachChild(node,visit);};visit(tree);assert.equal(methods.length,2);const javascript=ts.transpileModule(`class Context{${methods.join('\n')}};globalThis.methods=Context.prototype;`,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;const binding:{methods?:Record<string,Function>}={};new Function('globalThis',javascript)(binding);const calls:unknown[]=[];
 const upload={handle:'old-grant',filename:'fixture.txt',size:3},draft={values:{'path:owner':'original-owner'},contentType:'application/json',body:{title:'Unsubmitted text'},bodyFile:upload},cached={...draft};const context={review:true,reviewGeneration:2,pendingRequest:{hostname:'github.com'},serverReview:{reviewId:'old-receipt'},keyOne:true,keyTwo:true,confirmation:100,result:{old:'provider response'},resultRequest:{hostname:'github.com'},graphqlDocument:'old document',responseField:'old field',draft,drafts:new Map([['fixture-operation',cached]]),transport:async(...args:unknown[])=>calls.push(args),updateComplete:Promise.resolve(),renderRoot:{querySelector:()=>null},emitWorkState:()=>{},cancelReview:()=>binding.methods!.cancelReview.call(context)};
 binding.methods!.invalidateAccountContext.call(context);await Promise.resolve();assert.equal(context.review,false);assert.equal(context.pendingRequest,undefined);assert.equal(context.serverReview,undefined);assert.equal(context.confirmation,0);assert.equal(context.result,undefined);assert.equal(context.resultRequest,undefined);assert.equal(context.draft.bodyFile,undefined);assert.equal(cached.bodyFile,undefined);assert.deepEqual(context.draft.values,{'path:owner':'original-owner'});assert.deepEqual(context.draft.body,{title:'Unsubmitted text'});assert.deepEqual(calls,[['cancelReview',{reviewId:'old-receipt'}]]);
});
