import {catalogRegex} from '../src/main/catalog-query';
import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {convertCodec,converterRegistry,inspectBytes,isolatedCodec,imageDimensions} from '../src/main/local-tools-codecs';import {LocalToolsService} from '../src/main/local-tools';import {parseCatalogPage,hardwareFit,OllamaManager,localApi} from '../src/main/ollama-manager';import type {HardwareEvidence,ChatRun,CatalogStatus,ConverterResult} from '../src/shared/local-tools';
const eventually=async(check:()=>Promise<boolean>)=>{for(let n=0;n<150;n++){if(await check())return;await new Promise(r=>setTimeout(r,20));}throw new Error('Fixture operation did not complete');};
const ndjson=(records:unknown[])=>new Response(records.map(r=>JSON.stringify(r)).join('\n')+'\n',{headers:{'Content-Type':'application/x-ndjson'}});
test('bundled codecs detect signatures, preserve bytes, bound decompression, reject unsafe JSON and bad base64',async()=>{const input=Buffer.from('fixture\r\n廣東話');assert.equal(inspectBytes(input),'text');assert.deepEqual(Buffer.from(convertCodec('gunzip',convertCodec('gzip',input))),input);assert.equal(Buffer.from(convertCodec('text-lf',input)).toString(),'fixture\n廣東話');assert.deepEqual(Buffer.from(convertCodec('base64-file',convertCodec('text-base64',input))),input);assert.throws(()=>convertCodec('json-pretty',Buffer.from('{"n":9007199254740993}')));assert.throws(()=>convertCodec('json-pretty',Buffer.from('['.repeat(101)+'0'+']'.repeat(101))));assert.throws(()=>convertCodec('base64-file',Buffer.from('YR==')));assert.equal(Buffer.from(await isolatedCodec('text-base64',input,new AbortController().signal)).toString(),input.toString('base64'));assert.throws(()=>imageDimensions(Buffer.from([137,80,78,71,13,10,26,10])));assert.ok(converterRegistry().filter(a=>a.id.startsWith('image-')).every(a=>!a.enabled));});
test('opaque native grants convert actual selected files atomically and refuse source overwrite and changed inputs',async()=>{const dir=await mkdtemp(join(tmpdir(),'material-converter-fixture-'));const source=join(dir,'fixture.json'),dest=join(dir,'output.json');await writeFile(source,'{ "fixture": true }');const service=new LocalToolsService({storageDirectory:dir,pickSources:async()=>[source],pickDestination:async()=>dest});try{const grants=await service.request('converter-pick')as Array<{id:string}>;assert.equal(JSON.stringify(grants).includes(source),false);const result=await service.request('converter-start',{grant:grants[0].id,adapter:'json-pretty'})as ConverterResult;await eventually(async()=>{const status=await service.request('converter-status')as {items:ConverterResult[]};return status.items.some(r=>r.id===result.id&&r.status==='converted');});assert.deepEqual(JSON.parse(await readFile(dest,'utf8')),{fixture:true});assert.equal(await readFile(source,'utf8'),'{ "fixture": true }');await assert.rejects(service.request('converter-start',{grant:grants[0].id,adapter:'json-pretty'}),/already exists/);await assert.rejects(service.request('converter-start',{grant:source,adapter:'json-pretty'}),/opaque/);}finally{service.dispose();await rm(dir,{recursive:true,force:true});}});
test('official HTML parser keeps every published tag and follows pagination without guessed sizes',()=>{const html='<a href="/library/alpha">Alpha</a><a href="/library/beta">Beta</a><a href="/library?page=2">Next</a>';assert.deepEqual(parseCatalogPage(html).names,['alpha','beta']);assert.deepEqual(parseCatalogPage(html).next,['/library?page=2']);const tags=parseCatalogPage('<a href="/library/alpha:small">deadbeef1234 • 1.2GB • 32K context window • Text input</a><a href="/library/alpha:other">unknown</a><a href="/library/alpha/tags?page=2">Next</a>','alpha');assert.equal(tags.variants.length,2);assert.equal(tags.variants[0].bytes,1200000000);assert.equal(tags.variants[1].bytes,undefined);assert.deepEqual(tags.next,['/library/alpha/tags?page=2']);});
test('fit is unknown with missing GPU evidence, never derives from tag names, and conservative evidence supports all verdicts',()=>{const h:HardwareEvidence={at:'fixture',ram:32*1024**3,freeRam:28*1024**3,cpu:'Fixture CPU',cpuCores:8,architecture:'x64',diskFree:100*1024**3,gpu:{status:'unknown',reason:'fixture lacks GPU evidence'}};assert.equal(hardwareFit({bytes:1e9,context:4096},h).verdict,'Unknown');assert.equal(hardwareFit({bytes:40*1024**3},h).verdict,'Unlikely');const verified={...h,gpu:{status:'verified' as const,vram:24*1024**3,backend:'fixture-only',reason:'Synthetic fixture evidence'}};assert.equal(hardwareFit({bytes:1e9,context:4096,parameterCount:1e9,quantization:'fixture-Q4',kvBytesPerToken:262144},verified).verdict,'Runs well');assert.equal(hardwareFit({bytes:1e9,context:512,parameterCount:1e9,quantization:'fixture-Q4',kvBytesPerToken:262144},verified).verdict,'Runs with limits');});
test('catalog refresh visits every family and page, retains last verified inventory offline and records response identity',async()=>{const dir=await mkdtemp(join(tmpdir(),'material-catalog-fixture-'));let offline=false;const visited:string[]=[];const fetcher:typeof fetch=async input=>{const url=String(input);visited.push(url);if(offline)throw new Error('Fixture offline');if(url.endsWith('/library'))return new Response('<a href="/library/a">a</a><a href="/library?page=2">Next</a>');if(url.endsWith('/library?page=2'))return new Response('<a href="/library/b">b</a>');if(url.endsWith('/a/tags'))return new Response('<a href="/library/a:one">1GB • 4K context window • Text input</a><a href="/library/a/tags?page=2">Next</a>');if(url.endsWith('/a/tags?page=2'))return new Response('<a href="/library/a:two">2GB</a>');if(url.endsWith('/b/tags'))return new Response('<a href="/library/b:three">3GB</a>');throw new Error('Unexpected fixture URL');};const manager=new OllamaManager({directory:dir,fetcher});try{await manager.refreshCatalog();await eventually(async()=>(await manager.status()).state==='ready');const status=await manager.status();assert.equal(status.complete,true);assert.equal(status.pages,5);assert.equal(status.variants,3);assert.match(status.revision!,/^[a-f0-9]{64}$/);assert.equal((await manager.catalogPage({})).total,3);offline=true;await manager.refreshCatalog();await eventually(async()=>(await manager.status()).state==='offline');assert.equal((await manager.catalogPage({})).total,3);assert.equal((await manager.status()).lastSuccess,status.lastSuccess);}finally{manager.dispose();await rm(dir,{recursive:true,force:true});}});
test('real protocol fixtures stream pulls, retain byte counts, persist sessions and streamed chat with cancellation',async()=>{const dir=await mkdtemp(join(tmpdir(),'material-ollama-fixture-'));let installed=false;const fetcher:typeof fetch=async(input,init)=>{const url=String(input);assert.ok(url.startsWith('http://127.0.0.1:11434'));if(url.endsWith('/api/tags'))return Response.json({models:installed?[{name:'fixture:small'}]:[]});if(url.endsWith('/api/pull')){installed=true;return ndjson([{status:'downloading',digest:'sha256:fixture',total:100,completed:50},{status:'success',total:100,completed:100}]);}if(url.endsWith('/api/chat'))return ndjson([{message:{content:'Fixture '}},{message:{content:'answer'},done:true,eval_count:2}]);throw new Error('Unexpected local fixture URL');};const manager=new OllamaManager({directory:dir,fetcher});try{await manager.startPulls({tags:['fixture:small'],confirmed:true});await eventually(async()=>!(await manager.pullStatus()).active);assert.equal((await manager.pullStatus()).items[0].status,'pulled');assert.equal((await manager.pullStatus()).items[0].completed,100);const session=await manager.createSession({model:'fixture:small'});const run=await manager.startChat({session:session.id,prompt:'fixture prompt'});await eventually(async()=>(await manager.chatStatus({id:run.id})).status==='succeeded');const saved=await manager.session(session.id);assert.equal(saved.messages.at(-1)?.content,'Fixture answer');const restored=new OllamaManager({directory:dir,fetcher});assert.equal((await restored.sessions()).length,1);restored.dispose();await assert.rejects(manager.startChat({session:session.id,prompt:'x',context:1}),/parameters/);await assert.rejects(localApi('show',{model:'x',url:'https://untrusted.invalid'},fetcher),/Unsupported/);await assert.rejects(manager.startPulls({tags:['x'],confirmed:false}),/confirm/);}finally{manager.dispose();await rm(dir,{recursive:true,force:true});}});
test('PCM WAV adapter changes stereo frames to verified mono without fabricating compressed-media support',()=>{const source=Buffer.alloc(52);source.write('RIFF');source.writeUInt32LE(44,4);source.write('WAVEfmt ',8);source.writeUInt32LE(16,16);source.writeUInt16LE(1,20);source.writeUInt16LE(2,22);source.writeUInt32LE(44100,24);source.writeUInt32LE(176400,28);source.writeUInt16LE(4,32);source.writeUInt16LE(16,34);source.write('data',36);source.writeUInt32LE(8,40);source.writeInt16LE(1000,44);source.writeInt16LE(3000,46);source.writeInt16LE(-1000,48);source.writeInt16LE(1000,50);const out=Buffer.from(convertCodec('wav-mono',source));assert.equal(out.readUInt16LE(22),1);assert.equal(out.readUInt32LE(40),4);assert.equal(out.readInt16LE(44),2000);assert.equal(out.readInt16LE(46),0);source.writeUInt16LE(3,20);assert.throws(()=>convertCodec('wav-mono',source),/PCM/);});
test('stream cancellation preserves partial saved chat, and request field/parameter bounds fail closed',async()=>{const dir=await mkdtemp(join(tmpdir(),'material-cancel-fixture-'));let release:((v?:unknown)=>void)|undefined;const fetcher:typeof fetch=async(input,init)=>{if(String(input).endsWith('/api/chat'))return new Response(new ReadableStream({start(controller){controller.enqueue(new TextEncoder().encode(JSON.stringify({message:{content:'Partial fixture'}})+'\n'));release=()=>controller.close();init?.signal?.addEventListener('abort',()=>controller.error(new Error('Fixture abort')),{once:true});}}));return Response.json({models:[]});};const manager=new OllamaManager({directory:dir,fetcher});try{const session=await manager.createSession({model:'fixture:small'});const run=await manager.startChat({session:session.id,prompt:'never transmit real user data'});await eventually(async()=>(await manager.chatStatus({id:run.id})).content==='Partial fixture');assert.equal(manager.activeJobs(),true);await manager.cancelChat({id:run.id});await eventually(async()=>(await manager.chatStatus({id:run.id})).status==='cancelled');assert.equal((await manager.session(session.id)).messages.at(-1)?.content,'Partial fixture');assert.equal(manager.activeJobs(),false);await assert.rejects(localApi('copy',{source:'one',destination:'two',options:{}},fetcher),/Unsupported/);}finally{manager.dispose();await rm(dir,{recursive:true,force:true});}});
test('local tool bridge rejects arbitrary executable, shell, endpoints and hidden payload fields before any action',async()=>{const dir=await mkdtemp(join(tmpdir(),'material-allowlist-fixture-'));const service=new LocalToolsService({storageDirectory:dir,pickSources:async()=>[],pickDestination:async()=>null});try{await assert.rejects(service.request('harness-preflight',{executable:'/bin/sh'}),/Unsupported/);await assert.rejects(service.request('harness-launch',{id:'00000000-0000-0000-0000-000000000000',confirmed:false}),/confirm/);await assert.rejects(service.request('chat-start',{session:'00000000-0000-0000-0000-000000000000',prompt:'fixture',command:'echo unsafe'}),/Unsupported/);await assert.rejects(service.request('pull-start',{tags:['fixture'],confirmed:true,url:'https://example.invalid'}),/Unsupported/);assert.equal(service.activeJobs(),false);}finally{service.dispose();await rm(dir,{recursive:true,force:true});}});

test('full inventory catalog filters reconcile installed-only tags and apply regex before paging',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'material-catalog-filter-fixture-'));
 const inventory=Array.from({length:60},(_,i)=>({tag:`fixture:v${i}`,family:'fixture',bytes:(i+1)*100000000,source:'https://ollama.com/library/fixture:v'+i,capabilities:i%2?['vision']:['text']}));
 await writeFile(join(dir,'catalog.json'),JSON.stringify({inventory,status:{state:'ready',complete:true,pages:1,families:1,variants:60}}));
 let offline=false;const fetcher:typeof fetch=async input=>{if(offline)throw new Error('Synthetic offline fixture');if(String(input).endsWith('/api/tags'))return Response.json({models:[{name:'private-fixture:local',size:900000000,details:{quantization_level:'Q4_K_M'}},{name:'fixture:v59',size:6000000000,details:{quantization_level:'Q8_0'}}]});if(String(input).endsWith('/api/ps'))return Response.json({models:[{name:'private-fixture:local',size:900000000}]});throw new Error('Unexpected fixture URL');};
 const manager=new OllamaManager({directory:dir,fetcher});try{
  assert.equal((await manager.catalogPage({})).total,61);
  const far=await manager.catalogPage({regex:true,pattern:'^fixture:v59(?: |$)',flags:'i',page:1,size:1});assert.equal(far.total,1);assert.equal(far.items[0].tag,'fixture:v59');
  assert.equal((await manager.catalogPage({state:'installed'})).total,2);
  const running=await manager.catalogPage({state:'running',quantization:'Q4_K_M'});assert.equal(running.items[0].tag,'private-fixture:local');assert.equal(running.items[0].localOnly,true);
  assert.equal((await manager.catalogPage({variant:'v59'})).total,1);
  assert.equal((await manager.catalogPage({maxBytes:100000000,fit:'Unknown'})).total,1);
  const size=await manager.catalogPage({sort:'size-desc',size:1});assert.equal(size.items[0].bytes,6000000000);
  const quantizations=(await manager.catalogPage({})).quantizations;assert.deepEqual(quantizations,['Q4_K_M','Q8_0']);
  offline=true;const unavailable=await manager.catalogPage({state:'not-installed'});assert.equal(unavailable.localState,'unavailable');assert.equal(unavailable.total,0);
  assert.equal((await manager.catalogPage({})).total,61);const restored=new OllamaManager({directory:dir,fetcher});const offlinePage=await restored.catalogPage({});assert.equal(offlinePage.total,61);assert.ok(offlinePage.localAt);restored.dispose();
  await assert.rejects(manager.catalogPage({state:'invented'}),/Unsupported/);
  await assert.rejects(manager.catalogPage({regex:true,pattern:'[',flags:'i'}),/Invalid regular/);
 }finally{manager.dispose();await rm(dir,{recursive:true,force:true});}
});
test('catalog regex worker terminates catastrophic expressions and preserves global-flag semantics',async()=>{
 assert.deepEqual(await catalogRegex(['fixture','fixture','other'],'fixture','g'),[true,true,false]);
 await assert.rejects(catalogRegex(['a'.repeat(5000)+'!'],'^(a+)+$',''),/execution budget/);
 await assert.rejects(catalogRegex([],'[','i'),/Invalid regular/);
 await assert.rejects(catalogRegex(['fixture'],'fixture','ii'),/distinct flags/);
});
