import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {OllamaManager} from '../src/main/ollama-manager';import {LocalToolsService} from '../src/main/local-tools';
const wait=async(check:()=>Promise<boolean>)=>{for(let i=0;i<150;i++){if(await check())return;await new Promise(r=>setTimeout(r,10));}throw new Error('Synthetic fixture timeout');};
test('documented generation protocol streams, persists and cancels actual response bytes without storing prompts',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'ollama-generation-fixture-'));let completion=true,release:(()=>void)|undefined;const requests:Array<Record<string,unknown>>=[];
 const fetcher:typeof fetch=async(input,init)=>{assert.ok(String(input).startsWith('http://127.0.0.1:11434/api/'));assert.equal(init?.redirect,'error');if(String(input).endsWith('/api/tags'))return Response.json({models:[{name:'synthetic:fixture',digest:'a'.repeat(64)}]});if(String(input).endsWith('/api/show'))return Response.json({capabilities:completion?['completion','vision']:['embedding'],model_info:{'fixture.context_length':4096}});if(String(input).endsWith('/api/generate')){requests.push(JSON.parse(String(init?.body)));return new Response(new ReadableStream({start(controller){controller.enqueue(new TextEncoder().encode(JSON.stringify({response:'Synthetic partial 廣東話'})+'\n'));release=()=>{controller.enqueue(new TextEncoder().encode(JSON.stringify({response:' done',done:true,eval_count:3})+'\n'));controller.close();};init?.signal?.addEventListener('abort',()=>controller.error(new Error('Synthetic cancellation')),{once:true});}}));}throw new Error('Unexpected synthetic route');};
 const manager=new OllamaManager({directory,fetcher});
 try{const evidence=await manager.modelCapabilities({model:'synthetic:fixture'});assert.equal(evidence.context,4096);assert.ok(evidence.capabilities.includes('vision'));
  await assert.rejects(manager.startGeneration({model:'synthetic:missing',prompt:'fixture'}),/not installed/);
  await assert.rejects(manager.startGeneration({model:'synthetic:fixture',prompt:'fixture',context:8192}),/reported context/);
  completion=false;await assert.rejects(manager.startGeneration({model:'synthetic:fixture',prompt:'fixture'}),/completion support/);completion=true;
  const run=await manager.startGeneration({model:'synthetic:fixture',prompt:'PRIVATE_SYNTHETIC_PROMPT',system:'PRIVATE_SYNTHETIC_SYSTEM'});await wait(async()=>(await manager.generationStatus({id:run.id})).content.includes('廣東話'));assert.equal(manager.activeJobs(),true);
  await assert.rejects(manager.startGeneration({model:'synthetic:fixture',prompt:'another'}),/Only one/);
  const session=await manager.createSession({model:'synthetic:fixture'});await assert.rejects(manager.startChat({session:session.id,prompt:'fixture'}),/Only one/);
  release!();await wait(async()=>(await manager.generationStatus({id:run.id})).status==='succeeded');assert.equal(manager.activeJobs(),false);
  const saved=await readFile(join(directory,'generations',run.id+'.json'),'utf8');assert.ok(!saved.includes('PRIVATE_SYNTHETIC'));assert.equal((await manager.generationHistory({})).items[0].tokens,3);assert.equal(requests[0].stream,true);assert.equal(requests[0].prompt,'PRIVATE_SYNTHETIC_PROMPT');
  const second=await manager.startGeneration({model:'synthetic:fixture',prompt:'cancel fixture'});await wait(async()=>(await manager.generationStatus({id:second.id})).content.length>0);await manager.cancelGeneration({id:second.id});await wait(async()=>(await manager.generationStatus({id:second.id})).status==='cancelled');
  const restored=new OllamaManager({directory,fetcher});assert.equal((await restored.generationStatus({id:second.id})).content,'Synthetic partial 廣東話');restored.dispose();
 }finally{manager.dispose();await rm(directory,{recursive:true,force:true});}
});
test('reviewed local copy refuses existing destinations and reconciles exact installed tags through the allowlisted bridge',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'ollama-copy-fixture-'));const tags=['synthetic:source'];let posts=0;const fetcher:typeof fetch=async(input,init)=>{if(String(input).endsWith('/api/tags'))return Response.json({models:tags.map(name=>({name}))});if(String(input).endsWith('/api/show'))return Response.json({capabilities:['completion']});if(String(input).endsWith('/api/copy')){const body=JSON.parse(String(init?.body));assert.deepEqual(body,{source:'synthetic:source',destination:'synthetic-copy:source'});tags.push(body.destination);posts++;return new Response(null,{status:201});}throw new Error('Unexpected synthetic route');};
 const service=new LocalToolsService({storageDirectory:directory,fetcher,pickSources:async()=>[],pickDestination:async()=>null});
 try{await assert.rejects(service.request('model-copy',{source:'synthetic:source',destination:'synthetic-copy:source'}),/confirm/);await service.request('model-copy',{source:'synthetic:source',destination:'synthetic-copy:source',confirmed:true});assert.equal(posts,1);await assert.rejects(service.request('model-copy',{source:'synthetic:source',destination:'synthetic-copy:source',confirmed:true}),/already exists/);await assert.rejects(service.request('generation-start',{model:'synthetic:source',prompt:'fixture',endpoint:'https://invalid.test'}),/Unsupported/);}
 finally{service.dispose();await rm(directory,{recursive:true,force:true});}
});
