import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,copyFile,chmod,readFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFileSync} from 'node:child_process';
import {OllamaRuntime} from '../src/main/ollama-runtime';import {LocalToolsService} from '../src/main/local-tools';import type {HarnessRuntimeReview,HarnessRuntimeRegistration} from '../src/shared/ollama-harness';
const nativeFixture=`#include <stdio.h>\n#include <string.h>\nint main(int argc,char**argv){if(argc==2&&!strcmp(argv[1],"--version")){puts("ollama version is 0.0.0-fixture");return 0;}return 2;}\n`;
test('native execution trust precedes probing, registration binds all bytes and resource profiles stay semantic',async()=>{
 if(process.platform!=='linux')return;
 const directory=await mkdtemp(join(tmpdir(),'ollama-native-trust-fixture-')),source=join(directory,'owned-runtime.c'),binary=join(directory,'owned-runtime'),script=join(directory,'script');await writeFile(source,nativeFixture);execFileSync('/usr/bin/cc',[source,'-o',binary],{timeout:10000,maxBuffer:16000});await writeFile(script,'#!/bin/sh\necho unsafe\n',{mode:0o700});let selected=binary;
 const runtime=new OllamaRuntime(directory,async()=>selected);
 try{const review=await runtime.pick()as HarnessRuntimeReview;assert.equal(review.provenance,'Execution trust required');assert.match(review.sha256,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(review).includes(directory));await assert.rejects(runtime.register({review:review.id}),/explicitly approve/);const registration=await runtime.register({review:review.id,confirmed:true})as HarnessRuntimeRegistration;assert.equal(registration.version,'0.0.0-fixture');assert.equal(registration.provenance,'User-reviewed exact bytes');assert.equal((await runtime.status()).runtime?.sha256,review.sha256);
  selected=script;await assert.rejects(runtime.pick(),/native ELF or PE/);selected=binary;const changedReview=await runtime.pick()as HarnessRuntimeReview;await writeFile(binary,Buffer.concat([await readFile(binary),Buffer.from('changed')]));await assert.rejects(runtime.register({review:changedReview.id,confirmed:true}),/changed after review/);await assert.rejects(runtime.status(),/changed/);
  selected=join(directory,'node');await copyFile(process.execPath,selected);await chmod(selected,0o700);const unrelated=await runtime.pick()as HarnessRuntimeReview;await assert.rejects(runtime.register({review:unrelated.id,confirmed:true}),/compatible Ollama version/);
  const service=new LocalToolsService({storageDirectory:join(directory,'app'),pickSources:async()=>[],pickDestination:async()=>null,pickHarnessExecutable:async()=>binary,fetcher:(async()=>new Response(JSON.stringify({error:'owned synthetic stopped API fixture'}),{status:503}))as typeof fetch});try{const profiles=await service.request('harness-profiles')as{profiles:Array<{id:string;environment:Record<string,string>}>;pickerAvailable:boolean};assert.equal(profiles.profiles.length,3);assert.equal(profiles.pickerAvailable,true);assert.equal(profiles.profiles.find(row=>row.id==='ollama-conservative')?.environment.OLLAMA_CONTEXT_LENGTH,'2048');const preflight=await service.request('harness-preflight',{profile:'ollama-balanced'})as{blockers:string[];fit:{verdict:string};environment:Record<string,string>};assert.ok(preflight.blockers.some(row=>row.includes('digest')));assert.equal(preflight.fit.verdict,'Unknown');assert.equal(preflight.environment.OLLAMA_HOST,'127.0.0.1:11434');await assert.rejects(service.request('harness-preflight',{profile:'arbitrary-script'}),/shipped/);await assert.rejects(service.request('harness-runtime-register',{review:review.id,confirmed:true,command:'echo unsafe'}),/Unsupported/);const picked=await service.request('harness-runtime-pick')as HarnessRuntimeReview;await service.request('harness-runtime-register',{review:picked.id,confirmed:true});const verified=await service.request('harness-preflight',{profile:'ollama-conservative'})as{id:string;blockers:string[]};assert.equal(verified.blockers.length,0);await service.request('harness-launch',{id:verified.id,confirmed:true});let failed:{state:string;message:string}|undefined;for(let attempt=0;attempt<100;attempt++){failed=await service.request('harness-status',{id:verified.id})as typeof failed;if(failed?.state==='failed')break;await new Promise(resolve=>setTimeout(resolve,20));}assert.equal(failed?.state,'failed');assert.match(failed!.message,/closure verified/);assert.equal(service.activeJobs(),false);assert.equal((await service.request('harness-restore',{id:verified.id})as{state:string}).state,'restored');}finally{service.dispose();}
 }finally{await rm(directory,{recursive:true,force:true});}
});
