import {_electron as electron} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const root=fileURLToPath(new URL('..',import.meta.url)),require=createRequire(import.meta.url);
const output=process.env.MATERIAL_GIT_QA_OUTPUT?resolve(process.env.MATERIAL_GIT_QA_OUTPUT):await fs.mkdtemp(join(tmpdir(),'material-git-workspace-records-'));
await fs.mkdir(`${output}/gh-config`,{recursive:true});
const env={...process.env,MATERIAL_GIT_TEST:'1',MATERIAL_GIT_USER_DATA:`${output}/user-data`,GH_CONFIG_DIR:`${output}/gh-config`};for(const key of ['GH_TOKEN','GITHUB_TOKEN','GH_ENTERPRISE_TOKEN','GITHUB_ENTERPRISE_TOKEN','GH_HOST','GITHUB_SERVER_URL'])delete env[key];
const launch=()=>electron.launch({executablePath:require('electron'),args:['--no-sandbox','--ozone-platform=headless','.'],cwd:root,env});
let app=await launch(),page=await app.firstWindow();const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const mount=async(tag,props={})=>page.evaluate(async({tag,props})=>{document.querySelector('#workspace-qa')?.remove();const region=document.createElement('div');region.id='workspace-qa';region.style.cssText='position:fixed;inset:0;background:var(--md-sys-color-surface);z-index:200;padding:24px;overflow:auto';const element=document.createElement(tag);Object.assign(element,props);region.append(element);document.body.append(region);await element.updateComplete;return true;},{tag,props});
try{
 await page.setViewportSize({width:1200,height:850});await page.waitForFunction(()=>window.material&&customElements.get('mg-workspace-tabs'));
 const initial=await page.evaluate(async()=>{const response=await window.material.workspace('status'),state={...response.state,tabs:[{id:'issues',label:'Issues',pinned:false,group:''},{id:'pulls',label:'Pull requests',pinned:false,group:''},{id:'releases',label:'Releases',pinned:false,group:''}],lane:'issues',activeTab:'issues'};await window.material.workspace('save',state);return state;});
 await mount('mg-workspace-tabs',{state:initial});await page.evaluate(()=>{const tabs=document.querySelector('mg-workspace-tabs');tabs.addEventListener('workspace-change',async e=>{const response=await window.material.workspace('save',e.detail);tabs.state=response.state;});});
 await page.getByRole('button',{name:'Manage tabs and overflow',exact:true}).click();await page.getByRole('button',{name:'Dock right',exact:true}).click();await page.getByRole('button',{name:'Pin',exact:true}).first().click();await page.getByRole('textbox',{name:'New group name',exact:true}).fill('Review');await page.getByRole('button',{name:'Create group',exact:true}).click();await page.getByRole('button',{name:'Move… into group…',exact:true}).first().click();await page.locator('mg-workspace-tabs md-dialog').last().locator('md-list-item').filter({hasText:'Review'}).click();
 const saved=await page.evaluate(()=>window.material.workspace('status'));assert.equal(saved.state.dock,'right');assert.equal(saved.state.tabs[0].pinned,true);assert.equal(saved.state.groups[0].label,'Review');assert.equal(saved.state.tabs[0].group,saved.state.groups[0].id);checks.push('native persistence from docking, pinning, group creation and moving tab');
 await page.getByRole('textbox',{name:'Search current tab strip',exact:true}).fill('Releases');await page.waitForFunction(()=>document.querySelector('mg-workspace-tabs').matchIds?.length===1);await page.getByRole('textbox',{name:'Search every open tab',exact:true}).fill('Issues');await page.waitForFunction(()=>document.querySelector('mg-workspace-tabs').masterMatches?.length===1);assert.deepEqual(await page.evaluate(()=>document.querySelector('mg-workspace-tabs').matchIds),['releases']);checks.push('strip and master search state remain independent');
 await page.screenshot({path:`${output}/tab-manager.png`});await page.getByRole('button',{name:'Close manager',exact:true}).click();
 await mount('mg-workspace-docs');await page.getByRole('textbox',{name:'Search documentation',exact:true}).fill('Workspace, tabs');await page.locator('mg-workspace-docs md-list-item').filter({hasText:'Workspace, tabs and records'}).click();await page.getByRole('link',{name:'廣東話版本',exact:true}).click();await page.waitForFunction(()=>document.querySelector('mg-workspace-docs').article==='workspace.yue.md');await page.screenshot({path:`${output}/offline-docs.png`});checks.push('offline title/body search and article-to-article navigation');
 const notices=await page.evaluate(async()=>{await window.material.workspace('notify',{kind:'success',title:'Repository refreshed'});await window.material.workspace('notify',{kind:'warning',title:'Review pending'});return window.material.workspace('status');});await mount('mg-workspace-records',{mode:'notifications',response:notices});await page.getByRole('button',{name:'Select every match (2)',exact:true}).click();await page.getByRole('button',{name:'Dismiss selected',exact:true}).click();await page.waitForFunction(()=>document.querySelector('mg-workspace-records').response.notifications.every(n=>n.dismissed));await page.getByRole('button',{name:'Restore selected notifications',exact:true}).click();await page.getByRole('button',{name:'Mark selected read',exact:true}).click();await page.waitForFunction(()=>document.querySelector('mg-workspace-records').response.notifications.every(n=>n.read&&!n.dismissed));await page.screenshot({path:`${output}/notifications.png`});checks.push('native notification select-all, dismiss, restore and mark read');
 await app.close();app=await launch();page=await app.firstWindow();await page.waitForFunction(()=>window.material);const reopened=await page.evaluate(()=>window.material.workspace('status'));assert.equal(reopened.state.dock,'right');assert.equal(reopened.state.tabs[0].pinned,true);assert.equal(reopened.state.groups[0].label,'Review');assert.equal(reopened.notifications.length,2);assert.ok(reopened.notifications.every(n=>n.read&&!n.dismissed));checks.push('real Electron restart restores tab structure and notification state');assert.deepEqual(errors,[]);
 await fs.writeFile(`${output}/results.json`,JSON.stringify({checks,errors,output,scope:'Reusable components driven against WorkspaceStore through native IPC; domain shell integration remains separately owned.'},null,2));console.log(JSON.stringify({checks,output}));
}finally{await app.close();}
