import test from 'node:test';import assert from 'node:assert/strict';import {existsSync} from 'node:fs';import {build} from 'esbuild';import {chromium} from 'playwright';import {loadCatalog} from '../src/main/catalog';import {defaults} from '../src/shared/preferences';import {defaultPreferenceDocument} from '../src/shared/preferences-advanced';import {nestedDiscoveryFields,appearanceDiscoveryFields,appearanceDiscoveryStates} from '../src/shared/workspace-discovery';
const browserPath=existsSync('/usr/bin/chromium')?'/usr/bin/chromium':chromium.executablePath();
test('built universal registry discovers off-page controls, preserves exact schemas, and focuses the hidden owning settings tab',{skip:!existsSync(browserPath)},async()=>{
 const bundle=await build({stdin:{contents:"import './src/renderer/settings.ts';import {UniversalWorkspacePalette,buildDiscoveryRegistry,focusDiscoveryResult} from './src/renderer/workspace-palette.ts';customElements.define('mg-workspace-palette',UniversalWorkspacePalette);window.registry=buildDiscoveryRegistry;window.focusResult=focusDiscoveryResult;",resolveDir:process.cwd()},bundle:true,write:false,format:'iife',platform:'browser',logLevel:'silent'});
 const browser=await chromium.launch({headless:true,executablePath:browserPath,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:800,height:850}}),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 try{
  await page.setContent('<mg-app><mg-settings></mg-settings><mg-workspace-palette></mg-workspace-palette></mg-app>');await page.addScriptTag({content:'window.__name = (value) => value;'});
  await page.evaluate(({settings,document})=>{const state={document,effective:settings,appearance:{},sources:{},connections:[],fontFamilies:['system-ui','Fixture Sans']};(window as any).saved=[];(window as any).material={settings:async(patch:unknown)=>{(window as any).saved.push(patch);settings={...settings,...patch as object};return settings;},vocabulary:async()=>({loaded:false}),preferencesAdvanced:async()=>state,onPreferencesAdvanced:()=>()=>{}};},{settings:defaults,document:defaultPreferenceDocument()});
  await page.addScriptTag({content:bundle.outputFiles[0].text});
  await page.evaluate(({settings,catalog})=>{const palette=document.querySelector('mg-workspace-palette') as any;palette.articles=[{id:'fixture.md',title:'Fixture article',body:'Offline material'}];palette.navigation=[['settings','','Settings'],['security','','Security'],['repositories','','Repositories']];palette.data={settings,catalog,persistedSettingsKeys:[]};palette.open=true;},{settings:defaults,catalog:loadCatalog()});
  await page.waitForFunction(()=>((document.querySelector('mg-workspace-palette') as any).entries?.length??0)>100);
  const ids=await page.evaluate(()=>((document.querySelector('mg-workspace-palette') as any).entries as any[]).map(entry=>entry.id));
  for(const [surface,fields] of Object.entries(nestedDiscoveryFields))for(const field of fields)assert.ok(ids.includes(`nested:${surface}:${field}`));
  for(const state of appearanceDiscoveryStates)for(const field of appearanceDiscoveryFields)assert.ok(ids.includes(`appearance:workspace-titlebar:${state}:${field}`));
  assert.ok(ids.includes('action:repositories.create-with-options'));assert.ok(ids.some(id=>id.startsWith('command-field:repo create:')));
  const palette=page.locator('mg-workspace-palette');await palette.getByRole('textbox',{name:'Find pages, settings, properties and actions',exact:true}).fill('speechRate');
  await page.waitForFunction(()=>{const palette=document.querySelector('mg-workspace-palette') as any;return palette.matchIds?.includes('setting:speechRate')&&palette.matchIds?.length<10;});
  assert.equal(await palette.getByRole('slider').count(),1);
  await palette.getByRole('slider').press('ArrowRight');await page.waitForFunction(()=>((window as any).saved?.length??0)>0);
  const saved=await page.evaluate(()=>(window as any).saved);assert.equal(typeof saved.at(-1).speechRate,'number');assert.ok(saved.at(-1).speechRate<=2);
  const invalid=await page.evaluate(async()=>{const control=(document.querySelector('mg-workspace-palette') as any).shadowRoot.querySelector('mg-workspace-preference');const before=(window as any).saved.length;await control.change(9);return {writes:(window as any).saved.length-before,error:control.error};});assert.equal(invalid.writes,0);assert.ok(invalid.error);
  await page.evaluate(()=>{(document.querySelector('mg-workspace-palette') as any).open=false;});
  const focused=await page.evaluate(async()=>{const root=document.querySelector('mg-app')!,ok=await(window as any).focusResult(root,{lane:'settings',setting:'schedules',owner:'mg-scheduled-settings',field:'timezone'});const settings=root.querySelector('mg-settings') as any;return {ok,labels:[...settings.shadowRoot.querySelector('mg-scheduled-settings').shadowRoot.querySelectorAll('[label]')].map(node=>node.getAttribute('label')),tab:settings.tab,field:settings.shadowRoot.querySelector('mg-scheduled-settings')?.shadowRoot.activeElement?.getAttribute('label')};});assert.equal(focused.ok,true,JSON.stringify(focused));assert.equal(focused.tab,'schedules');assert.equal(focused.field,'IANA timezone');
  const concealed=await page.evaluate(({settings,catalog})=>(window as any).registry({settings,catalog},[],[],true,undefined,'Focus presentation').map((entry:any)=>entry.id),{settings:defaults,catalog:loadCatalog()});for(const id of ['setting:language','setting:englishHumor','setting:cantoneseHumor','nested:vocabulary:vocabulary'])assert.ok(!concealed.includes(id));
  assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
