import test from 'node:test';import assert from 'node:assert/strict';import {existsSync,mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {build} from 'esbuild';import {chromium} from 'playwright';import {WorkspaceStore} from '../src/main/workspace';import {defaults} from '../src/shared/preferences';import {serializeExport} from '../src/shared/exports';
const browserPath=existsSync('/usr/bin/chromium')?'/usr/bin/chromium':chromium.executablePath();
test('built history and records controls operate actual native managed revisions, filter selection, formats and append-only restore',{skip:!existsSync(browserPath)},async()=>{
 const directory=mkdtempSync(join(tmpdir(),'mg-records-controls-')),store=new WorkspaceStore(directory);let restored:unknown;store.setRestorer((_kind,_id,snapshot)=>{restored=snapshot;return snapshot;});
 for(let index=0;index<45;index++)store.recordExternal(index%3?'settings':'schedules','local',index%2?'Settings changed':'Schedule changed',{theme:index%2?'light':'dark',revision:index});
 const status=store.dispatch('status'),exports:{data:unknown;format:string}[]=[],calls:{action:string;payload:unknown}[]=[];
 const bundle=await build({stdin:{contents:"import './src/renderer/workspace-records.ts';",resolveDir:process.cwd()},bundle:true,write:false,format:'iife',platform:'browser',logLevel:'silent'}),browser=await chromium.launch({headless:true,executablePath:browserPath,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:900,height:850}}),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 try{
  await page.exposeFunction('recordsNative',async(action:Parameters<typeof store.dispatch>[0],payload:unknown)=>{calls.push({action,payload});return store.dispatch(action,payload);});await page.exposeFunction('recordsExport',(data:unknown,format:string)=>{serializeExport(data,format as any);exports.push({data,format});return true;});
  await page.setContent('<mg-workspace-records></mg-workspace-records>');await page.addScriptTag({content:'window.__name=(value)=>value;window.material={workspace:(action,payload)=>window.recordsNative(action,payload),exportData:(data,format)=>window.recordsExport(data,format)};'});await page.addScriptTag({content:bundle.outputFiles[0].text});await page.evaluate(({settings,status})=>{const records=document.querySelector('mg-workspace-records') as any;records.settings=settings;records.response=status;records.mode='history';},{settings:defaults,status});
  const records=page.locator('mg-workspace-records');await records.getByRole('checkbox',{name:/Select /}).first().waitFor();assert.equal(await records.getByRole('checkbox',{name:/Select /}).count(),20);
  await records.getByRole('button',{name:'Select this page',exact:true}).click();await records.getByRole('button',{name:'Next',exact:true}).click();await records.getByRole('button',{name:'Select this page',exact:true}).click();assert.equal(await page.evaluate(()=>(document.querySelector('mg-workspace-records') as any).selected.size),40);
  await records.getByRole('button',{name:'Export format',exact:true}).click();await records.getByRole('option',{name:'CSV',exact:true}).click();await records.getByRole('button',{name:'Export selected matches (40)',exact:true}).click();assert.equal(exports.at(-1)?.format,'csv');assert.equal((exports.at(-1)?.data as unknown[]).length,40);
  await records.getByRole('button',{name:'Clear selection',exact:true}).click();await records.getByRole('button',{name:'settings (30)',exact:true}).click();await page.waitForFunction(()=>(document.querySelector('mg-workspace-records') as any).filtered().length===30);
  await records.getByRole('textbox',{name:'Search record titles, actions and source kinds',exact:true}).fill('Settings changed');await page.waitForFunction(()=>{const records=document.querySelector('mg-workspace-records') as any;return records.matchIds!==null&&records.filtered().length>0&&records.filtered().every((row:any)=>row.kind==='settings'&&row.action==='Settings changed');});
  const before=await page.evaluate(()=>(document.querySelector('mg-workspace-records') as any).filtered().length);await records.getByRole('textbox',{name:'From date',exact:true}).fill('2026-10');assert.equal(await records.getByRole('alert').count(),1);assert.equal(await page.evaluate(()=>(document.querySelector('mg-workspace-records') as any).filtered().length),before);
  await records.getByRole('textbox',{name:'From date',exact:true}).fill('');await records.getByRole('button',{name:'Choose date range',exact:true}).click();await records.getByRole('spinbutton',{name:'Year',exact:true}).fill('2026');await records.getByRole('spinbutton',{name:'Year',exact:true}).blur();assert.equal(await records.getByRole('button',{name:'Next month',exact:true}).count(),1);await records.getByRole('button',{name:'Close calendar',exact:true}).click();
  await records.getByRole('button',{name:'Clear date, action and source filters',exact:true}).click();await records.getByRole('textbox',{name:'Search record titles, actions and source kinds',exact:true}).fill('');await page.waitForFunction(()=>(document.querySelector('mg-workspace-records') as any).filtered().length===45);
  const target=status.managedRevisions!.find(row=>row.kind==='settings')!;await page.evaluate(id=>{const records=document.querySelector('mg-workspace-records') as any;records.openDetail(records.response.managedRevisions.find((row:any)=>row.id===id));},target.id);
  await records.getByRole('textbox',{name:'Revision label',exact:true}).fill('Reviewed fixture');await records.getByRole('button',{name:'Save label',exact:true}).click();await page.waitForFunction(id=>(document.querySelector('mg-workspace-records') as any).response.managedRevisions.find((row:any)=>row.id===id)?.label==='Reviewed fixture',target.id);assert.equal(store.dispatch('status').managedRevisions!.find(row=>row.id===target.id)?.label,'Reviewed fixture');
  await records.getByRole('button',{name:/Compare with another revision/}).click();await records.getByRole('option').first().click();await records.getByRole('button',{name:'Compare changed fields',exact:true}).click();await page.waitForFunction(()=>(document.querySelector('mg-workspace-records') as any).diff.length>0);assert.ok(calls.some(call=>call.action==='record-diff'));
  await records.getByRole('button',{name:'Review restoring this revision',exact:true}).click();await records.getByRole('checkbox',{name:'I reviewed the exact replacement snapshot',exact:true}).click();await records.getByRole('checkbox',{name:'I understand current saved values will be replaced',exact:true}).click();await records.getByRole('slider',{name:'Slide to confirm restoring this revision',exact:true}).press('End');await records.getByRole('button',{name:'Restore reviewed revision',exact:true}).click();await page.waitForFunction(()=>(document.querySelector('mg-workspace-records') as any).detail==='');assert.deepEqual(restored,target.snapshot);assert.equal(store.dispatch('status').managedRevisions!.length,46);assert.equal(store.dispatch('status').managedRevisions!.at(-1)?.action,'Record restored');assert.ok((await page.evaluate(()=>(document.querySelector('mg-workspace-records') as any).response.state)),'managed-only response must retain existing workspace state');
  assert.deepEqual(errors,[]);
 }finally{await browser.close();rmSync(directory,{recursive:true,force:true});}
});
