import {LitElement,html,nothing} from 'lit';
import './tool-search';
import {reportSiteEvent} from './events';
import {converterLimits,sourceFormat,conversionFormats,converterReceiptKey,validateConverterReceipts,type ConversionFormat,type SourceFormat,type ConverterReceipt} from './local-converter';
import {converterGroups,converterUnavailable,conversionLosses,queueStateNames} from './converter-copy';
type QueueItem={id:string;name:string;file:File;source:SourceFormat;target:ConversionFormat;state:keyof typeof queueStateNames;output?:Blob;error?:string};
type Review={revision:number;ids:string[];action:'run'|'cancel'|'remove'};
export class BrowserConverter extends LitElement{
 static properties={copy:{attribute:false},queue:{state:true},target:{state:true},group:{state:true},catalogMatches:{state:true},queueMatches:{state:true},state:{state:true},page:{state:true},selected:{state:true},review:{state:true},running:{state:true},paused:{state:true},admitting:{state:true},message:{state:true},receipts:{state:true},receiptMatches:{state:true},receiptPage:{state:true}};
 copy=(en:string,_yue:string)=>en;queue:QueueItem[]=[];target:ConversionFormat='json';group='all';catalogMatches:Set<string>|null=null;queueMatches:Set<string>|null=null;state='all';page=0;selected=new Set<string>();review:Review|null=null;running=false;paused=false;admitting=false;message='';receipts:ConverterReceipt[]=[];receiptMatches:Set<string>|null=null;receiptPage=0;private revision=0;private worker:Worker|null=null;private cancelWorker:(()=>void)|null=null;private anchor='';private runningIds=new Set<string>();
 createRenderRoot(){return this}
 restoreReceipts(records:ConverterReceipt[]){const receipts=validateConverterReceipts(records);localStorage.setItem(converterReceiptKey,JSON.stringify(receipts));this.receipts=receipts}
 connectedCallback(){super.connectedCallback();try{const raw=localStorage.getItem(converterReceiptKey);if(raw&&raw.length<262144)this.receipts=validateConverterReceipts(JSON.parse(raw));if(this.receipts.some(r=>r.state==='interrupted'))this.message=this.copy('An earlier conversion did not finish. File permissions and output bytes do not survive reload. Reselect the source and review it again.','之前嘅轉換未完成。檔案權限同輸出位元組唔會保留至重新載入。請重新選擇來源同檢閱。')}catch{this.message=reportSiteEvent(this,this.copy,'error','Conversion receipts could not be read. Existing files are untouched.','未能讀取轉換收據，現有檔案保持不變。')}}
 disconnectedCallback(){super.disconnectedCallback();this.paused=true;this.cancelWorker?.();this.worker?.terminate()}
 private get sourceBytes(){return this.queue.reduce((total,row)=>total+row.file.size,0)}
 private get outputBytes(){return this.queue.reduce((total,row)=>total+(row.output?.size??0),0)}
 private metadataBytes(queue:QueueItem[]){return new TextEncoder().encode(JSON.stringify(queue.map(({id,name,source,target,state})=>({id,name,source,target,state})))).length}
 private get filtered(){return this.queue.filter(row=>(!this.queueMatches||this.queueMatches.has(row.id))&&(this.state==='all'||row.state===this.state))}
 private get picked(){return this.filtered.filter(row=>this.selected.has(row.id))}
 private change(){this.revision++;this.review=null;this.queue=[...this.queue];this.page=Math.min(this.page,Math.max(0,Math.ceil(this.filtered.length/20)-1))}
 private async admit(event:Event){const input=event.target as HTMLInputElement,files=input.files;if(!files)return;this.admitting=true;let admitted=0,skipped=0,retainedBytes=this.sourceBytes,metadataBytes=this.metadataBytes(this.queue);
 try{for(let index=0;index<files.length;index++){const file=files.item(index)!;if(!file.size||file.size>converterLimits.fileBytes||file.name.length>1024||retainedBytes+file.size>converterLimits.sourceBytes){skipped++;continue}
 try{const source=sourceFormat(file.name,new Uint8Array(await file.slice(0,131072).arrayBuffer())),row:QueueItem={id:crypto.randomUUID(),name:file.name,file,source,target:['png','jpeg','webp'].includes(source)?(['png','jpeg','webp'].includes(this.target)?this.target:'png'):(['png','jpeg','webp'].includes(this.target)?'json':this.target),state:'queued'};
 const rowBytes=this.metadataBytes([row])+8;if(metadataBytes+rowBytes>converterLimits.metadataBytes){skipped++;continue}this.queue.push(row);retainedBytes+=file.size;metadataBytes+=rowBytes;this.revision++;this.review=null;admitted++;if(admitted%20===0)this.requestUpdate()}catch{skipped++}}
 this.change();this.message=reportSiteEvent(this,this.copy,skipped?'warning':'status',`Admitted ${admitted} source files; skipped ${skipped} unsupported or over-budget files. Sources were inspected sequentially.`,`已准入 ${admitted} 個來源檔案；略過 ${skipped} 個唔支援或超出配額嘅檔案。來源已逐一檢查。`)
 }finally{this.admitting=false;input.value=''}}
 private record(row:QueueItem,state:ConverterReceipt['state']){const receipt:ConverterReceipt={id:row.id,at:new Date().toISOString(),source:row.source,target:row.target,inputBytes:row.file.size,outputBytes:row.output?.size??0,state};const next=validateConverterReceipts([...this.receipts.filter(r=>r.id!==row.id),receipt].slice(-200));try{localStorage.setItem(converterReceiptKey,JSON.stringify(next));this.receipts=next;this.dispatchEvent(new CustomEvent('visitor-record-change',{detail:{label:'Updated website conversion receipts'},bubbles:true,composed:true}))}catch{this.receipts=next;this.message=reportSiteEvent(this,this.copy,'error','Browser receipt storage failed. Conversion records last for this visit only; source files remain untouched.','瀏覽器收據儲存失敗，轉換記錄只保留至今次瀏覽結束；來源檔案保持不變。')}}
 private toggle(row:QueueItem,event:Event){const selected=new Set(this.selected);if((event as MouseEvent).shiftKey&&this.anchor){const ids=this.filtered.map(r=>r.id),from=ids.indexOf(this.anchor),to=ids.indexOf(row.id);if(from>=0&&to>=0)for(const id of ids.slice(Math.min(from,to),Math.max(from,to)+1))selected.add(id)}else if(selected.has(row.id))selected.delete(row.id);else selected.add(row.id);this.selected=selected;this.anchor=row.id;this.review=null}
 private reviewAction(action:Review['action']){const rows=this.picked.filter(row=>action!=='run'||!['done','running'].includes(row.state));this.review={revision:this.revision,ids:rows.map(row=>row.id),action}}
 private confirm(){const review=this.review;if(!review)return;if(review.revision!==this.revision){this.message=this.copy('Queue changed. Review the current selection again.','佇列已改變，請重新檢閱目前選擇。');this.review=null;return}const rows=this.queue.filter(row=>review.ids.includes(row.id));this.review=null;
 if(review.action==='run'){if(this.running)return;for(const row of rows){row.state='queued';row.error='';this.runningIds.add(row.id)}this.paused=false;void this.run()}
 else if(review.action==='cancel'){for(const row of rows){this.runningIds.delete(row.id);if(row.state==='running')this.cancelWorker?.();if(row.state!=='done'){row.state='cancelled';this.record(row,'cancelled')}}this.change();reportSiteEvent(this,this.copy,'status',`Cancelled ${rows.filter(r=>r.state==='cancelled').length} reviewed tasks.`,`已取消 ${rows.filter(r=>r.state==='cancelled').length} 個已檢閱工作。`)}
 else{for(const row of rows){this.runningIds.delete(row.id);if(row.state==='running'){this.cancelWorker?.();this.record(row,'cancelled')}this.selected.delete(row.id)}this.queue=this.queue.filter(row=>!review.ids.includes(row.id));this.change();reportSiteEvent(this,this.copy,'status',`Removed ${rows.length} reviewed in-memory tasks. Source files were untouched.`,`已移除 ${rows.length} 個已檢閱記憶體工作，來源檔案保持不變。`)}
 }
 private async convert(row:QueueItem):Promise<Blob>{return new Promise((resolve,reject)=>{const worker=new Worker(new URL('./converter-worker.js',document.baseURI),{type:'module'});this.worker=worker;let done=false;const finish=(blob?:Blob,error?:string)=>{if(done)return;done=true;clearTimeout(timer);worker.terminate();this.worker=null;this.cancelWorker=null;if(blob)resolve(blob);else reject(Error(error??'Conversion failed'))};const timer=setTimeout(()=>finish(undefined,'Worker exceeded the 15 second deadline'),converterLimits.deadline);this.cancelWorker=()=>finish(undefined,'Cancelled');worker.onmessage=event=>{if(event.data.progress){row.state='running';this.requestUpdate();return}if(event.data.blob instanceof Blob&&event.data.source===row.source&&event.data.target===row.target)finish(event.data.blob);else finish(undefined,'Source or output validation failed')};worker.onerror=()=>finish(undefined,'Conversion worker unavailable');worker.postMessage({file:row.file,target:row.target})})}
 private async run(){if(this.running)return;this.running=true;let done=0,failed=0;try{while(!this.paused){const row=this.queue.find(r=>this.runningIds.has(r.id)&&r.state==='queued');if(!row)break;row.state='running';this.change();this.record(row,'interrupted');try{const output=await this.convert(row);if(!this.queue.includes(row))continue;if(this.outputBytes+output.size>converterLimits.outputBytes)throw Error('Result memory budget exceeded');row.output=output;row.state='done';this.record(row,'done');done++}catch(error){if(!this.queue.includes(row))continue;row.state=this.runningIds.has(row.id)?'failed':'cancelled';row.error=error instanceof Error&&['Worker exceeded the 15 second deadline','Conversion worker unavailable','Result memory budget exceeded'].includes(error.message)?error.message:'Source or output validation failed';this.record(row,row.state);if(row.state==='failed')failed++}finally{this.runningIds.delete(row.id);this.change()}}}
 finally{this.running=false;this.message=reportSiteEvent(this,this.copy,failed?'error':'status',`Conversion pass ended: ${done} validated outputs; ${failed} failed tasks. ${this.paused?'Paused before the next file.':''}`,`今輪轉換結束：${done} 個已驗證輸出；${failed} 個失敗工作。${this.paused?'已喺下一個檔案之前暫停。':''}`)}}
 private download(row:QueueItem){if(!row.output)return;const url=URL.createObjectURL(row.output),link=document.createElement('a');link.href=url;link.download=row.name.replace(/\.[^.]*$/,'')+'.converted.'+(row.target==='jpeg'?'jpg':row.target);link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);reportSiteEvent(this,this.copy,'status','Validated conversion output handed to the browser download manager. Disk publication is not verified by this website.','已將已驗證轉換輸出交畀瀏覽器下載管理器。網站冇驗證磁碟發佈。')}
 private get filteredReceipts(){return [...this.receipts].reverse().filter(row=>!this.receiptMatches||this.receiptMatches.has(row.id))}
 private get catalog(){return [...conversionFormats.map(format=>({id:format,group:['png','jpeg','webp'].includes(format)?'images':['html','sql','md','txt'].includes(format)?'code':'data',en:format.toUpperCase(),yue:format.toUpperCase(),reason:'',reasonYue:''})),...converterUnavailable.map(([group,en,yue,reason,reasonYue])=>({id:group,group,en,yue,reason,reasonYue}))]}
 render(){const catalog=this.catalog.filter(row=>(this.group==='all'||this.group===row.group)&&(!this.catalogMatches||this.catalogMatches.has(row.id))),filtered=this.filtered,picked=this.picked,page=filtered.slice(this.page*20,this.page*20+20),review=this.review,rows=review?this.queue.filter(row=>review.ids.includes(row.id)):[];return html`
 <p>${this.copy('Convert your local UTF-8 structured data or bounded PNG, JPEG and WebP images. Files never upload. Choose a destination, select tasks, review losses, then run.','轉換你嘅本機 UTF-8 結構資料或者有資源限制嘅 PNG、JPEG 同 WebP 圖片。檔案唔會上傳。選擇目的格式、工作，檢閱損失之後先執行。')}</p>
 <mg-site-tool-search class="converter-catalog-search" .copy=${this.copy} .label=${this.copy('Search conversion catalogue','搜尋轉換目錄')} .entries=${this.catalog.map(r=>({key:r.id,text:[r.group,r.en,r.yue,r.reason,r.reasonYue].join(' ')}))} @site-search-change=${(e:CustomEvent)=>this.catalogMatches=e.detail}></mg-site-tool-search>
 <md-outlined-select class="converter-category" label=${this.copy('Adapter category','轉換工具種類')} .value=${this.group} @change=${(e:any)=>this.group=e.target.value}>${[['all','All categories','所有種類'],...converterGroups].map(([value,en,yue])=>html`<md-select-option value=${value} .selected=${this.group===value}><span slot="headline">${this.copy(en,yue)}</span></md-select-option>`)}</md-outlined-select>
 <mg-site-layout class="converter-catalog">${catalog.map(row=>html`<mg-site-surface class="converter-adapter"><md-outlined-button ?disabled=${Boolean(row.reason)||this.running} @click=${()=>this.target=row.id as ConversionFormat}>${this.copy(row.en,row.yue)} ${row.reason?this.copy('(Unavailable)','（不可用）'):this.target===row.id?'✓':''}</md-outlined-button>${row.reason?html`<p class="small">${this.copy(row.reason,row.reasonYue)}</p>`:nothing}</mg-site-surface>`)}</mg-site-layout>
 <md-outlined-select class="converter-target" label=${this.copy('Preferred destination for new sources','新來源嘅偏好目的格式')} .value=${this.target} @change=${(e:any)=>this.target=e.target.value}>${conversionFormats.map(format=>html`<md-select-option value=${format} .selected=${format===this.target}><span slot="headline">${format.toUpperCase()}</span></md-select-option>`)}</md-outlined-select>
 <p class="small">${this.copy('New raster sources default to PNG if a text destination is selected; structured sources default to JSON if an image destination is selected. Each task retains its own destination. Unsupported source/target pairs fail validation; they never produce placeholder files.','如果選咗文字目的格式，新圖片來源預設轉成 PNG；如果選咗圖片目的格式，結構來源預設轉成 JSON。每個工作保留自己嘅目的格式。唔支援嘅來源／目的配對會驗證失敗，唔會產生假檔案。')}</p>
 <input class="converter-files" type="file" multiple hidden @change=${this.admit}><md-filled-button ?disabled=${this.admitting} @click=${()=>this.querySelector<HTMLInputElement>('.converter-files')?.click()}>${this.admitting?this.copy('Inspecting files…','正在檢查檔案…'):this.copy('Choose local source files','選擇本機來源檔案')}</md-filled-button>
 <p class="small">${this.sourceBytes} / ${converterLimits.sourceBytes} ${this.copy('source bytes','來源位元組')} · ${this.outputBytes} / ${converterLimits.outputBytes} ${this.copy('result bytes','結果位元組')}. ${this.copy('8 MiB per file, 1 MiB queue metadata, one 15 second worker, 4096 pixels per side and 8,388,608 pixels. Queue admission uses resource budgets; there is no file-count quota. Browser pickers still expose a FileList.','每個檔案 8 MiB、佇列中繼資料 1 MiB、一次一個限時 15 秒背景工具、每邊 4096 像素同總共 8,388,608 像素。佇列准入使用資源配額，冇檔案數量配額。瀏覽器選擇器仍然提供 FileList。')}</p>
 <mg-site-tool-search class="converter-queue-search" .copy=${this.copy} .label=${this.copy('Search conversion tasks','搜尋轉換工作')} .entries=${this.queue.map(row=>({key:row.id,text:[row.name,row.source,row.target,row.state,...queueStateNames[row.state]].join(' ')}))} @site-search-change=${(e:CustomEvent)=>{this.queueMatches=e.detail;this.page=0;this.review=null}}></mg-site-tool-search>
 <md-outlined-select class="converter-state" label=${this.copy('Task state','工作狀態')} .value=${this.state} @change=${(e:any)=>{this.state=e.target.value;this.page=0;this.review=null}}>${[['all','All tasks','全部工作'],...Object.entries(queueStateNames).map(([state,names])=>[state,...names])].map(([state,en,yue])=>html`<md-select-option value=${state} .selected=${state===this.state}><span slot="headline">${this.copy(en,yue)}</span></md-select-option>`)}</md-outlined-select>
 <p class="converter-count">${filtered.length} ${this.copy('matches','個符合')} · ${picked.length} ${this.copy('selected matches','個已選符合')} · ${this.selected.size-picked.length} ${this.copy('selected outside the filter, excluded','個選擇喺篩選以外，唔會處理')}</p>
 <mg-site-layout class="actions">${[['page','Select this page','選擇呢頁'],['all','Select every match','選擇每個符合'],['inverse','Invert matches','反轉符合選擇'],['clear','Clear selection','清除選擇']].map(([action,en,yue])=>html`<md-outlined-button @click=${()=>{this.selected=action==='clear'?new Set():action==='page'?new Set([...this.selected,...page.map(r=>r.id)]):action==='all'?new Set([...this.selected,...filtered.map(r=>r.id)]):new Set([...this.selected].filter(id=>!filtered.some(r=>r.id===id)).concat(filtered.filter(r=>!this.selected.has(r.id)).map(r=>r.id)));this.review=null}}>${this.copy(en,yue)}</md-outlined-button>`)}</mg-site-layout>
 ${page.map(row=>html`<mg-site-surface class="converter-task"><md-checkbox aria-label=${this.copy('Select task','選擇工作')+' '+row.name} .checked=${this.selected.has(row.id)} @click=${(e:Event)=>{e.preventDefault();this.toggle(row,e)}} @keydown=${(e:KeyboardEvent)=>{if(e.shiftKey&&e.code==='Space'){e.preventDefault();e.stopPropagation();this.toggle(row,e)}}}></md-checkbox><mg-site-layout><strong>${row.name}</strong><p>${row.source.toUpperCase()} → ${row.target.toUpperCase()} · ${this.copy(queueStateNames[row.state][0],queueStateNames[row.state][1])}</p><md-outlined-select label=${this.copy('Task destination','工作目的格式')} .value=${row.target} ?disabled=${this.runningIds.has(row.id)||row.state==='done'} @change=${(e:any)=>{row.target=e.target.value;this.change()}}>${conversionFormats.filter(format=>['png','jpeg','webp'].includes(row.source)===['png','jpeg','webp'].includes(format)).map(format=>html`<md-select-option value=${format} .selected=${row.target===format}><span slot="headline">${format.toUpperCase()}</span></md-select-option>`)}</md-outlined-select>${row.state==='running'?html`<md-circular-progress indeterminate aria-label=${this.copy('Converting one file','正在轉換一個檔案')}></md-circular-progress>`:nothing}${row.error?html`<p class="error">${this.copy('Source or output validation failed. Check the supported format and resource limits; the source is unchanged.','來源或輸出驗證失敗。請檢查支援格式同資源限制；來源保持不變。')} ${row.error==='Worker exceeded the 15 second deadline'?'15 s':row.error==='Result memory budget exceeded'?'32 MiB':''}</p>`:nothing}${row.output?html`<p>${row.output.size} ${this.copy('validated output bytes','已驗證輸出位元組')}</p><md-filled-button @click=${()=>this.download(row)}>${this.copy('Download validated output','下載已驗證輸出')}</md-filled-button>`:nothing}</mg-site-layout></mg-site-surface>`)}
 <mg-site-layout class="actions"><md-text-button ?disabled=${this.page===0} @click=${()=>this.page--}>${this.copy('Previous page','上一頁')}</md-text-button><span>${this.page+1} / ${Math.max(1,Math.ceil(filtered.length/20))}</span><md-text-button ?disabled=${(this.page+1)*20>=filtered.length} @click=${()=>this.page++}>${this.copy('Next page','下一頁')}</md-text-button></mg-site-layout>
 <mg-site-layout class="actions"><md-filled-button ?disabled=${this.running||!picked.some(row=>!['done','running'].includes(row.state))} @click=${()=>this.reviewAction('run')}>${this.copy('Review selected conversions','檢閱已選轉換')}</md-filled-button><md-outlined-button ?disabled=${!picked.length} @click=${()=>this.reviewAction('cancel')}>${this.copy('Review cancel selected','檢閱取消已選工作')}</md-outlined-button><md-outlined-button ?disabled=${!picked.length} @click=${()=>this.reviewAction('remove')}>${this.copy('Review remove selected','檢閱移除已選工作')}</md-outlined-button><md-outlined-button ?disabled=${!this.running||this.paused} @click=${()=>this.paused=true}>${this.copy('Pause before next file','下一個檔案之前暫停')}</md-outlined-button><md-outlined-button ?disabled=${this.running||!this.paused||!this.runningIds.size} @click=${()=>{this.paused=false;void this.run()}}>${this.copy('Resume reviewed queue','繼續已檢閱佇列')}</md-outlined-button></mg-site-layout>
 ${review?html`<mg-site-surface class="converter-review"><h3>${this.copy('Review exact task effects','檢閱確實工作效果')}</h3><p>${rows.length} ${this.copy('reviewed tasks','個已檢閱工作')} · ${picked.length-rows.length} ${this.copy('selected matches skipped','個已選符合略過')}</p><ul>${rows.map(row=>html`<li>${row.name}: ${row.source} → ${row.target}</li>`)}</ul>${review.action==='run'?conversionLosses.map(pair=>html`<p>${this.copy(pair[0],pair[1])}</p>`):html`<p>${this.copy('Cancel stops selected in-flight workers and pending tasks. Remove releases selected in-memory files and outputs; reselect sources to repeat. Completed receipt facts remain. Source files are untouched.','取消會停止已選執行中背景工具同等待工作。移除會釋放已選記憶體檔案同輸出；重做需要重新選擇來源。已完成收據事實保持不變，來源檔案保持不變。')}</p>`}<md-filled-button ?disabled=${!rows.length||review.revision!==this.revision} @click=${this.confirm}>${this.copy(review.action==='run'?'Run reviewed conversions':review.action==='cancel'?'Cancel reviewed tasks':'Remove reviewed tasks',review.action==='run'?'執行已檢閱轉換':review.action==='cancel'?'取消已檢閱工作':'移除已檢閱工作')}</md-filled-button><md-text-button @click=${()=>this.review=null}>${this.copy('Close review','關閉檢閱')}</md-text-button></mg-site-surface>`:nothing}
 ${this.message?html`<p role="status" class="converter-message">${this.message}</p>`:nothing}
 <h3>${this.copy('Conversion receipt history','轉換收據記錄')}</h3><p>${this.copy('Up to 200 outcome receipts survive reload. Receipts contain format, byte counts and time only. Names, paths, source contents and output files are excluded. Interrupted tasks need source reselection; durable file grants and crash-resume are unavailable.','最多 200 個結果收據保留至重新載入。收據只包含格式、位元組數量同時間。名稱、路徑、來源內容同輸出檔案唔會包含。中斷工作需要重新選擇來源；持續檔案權限同崩潰後繼續不可用。')}</p><mg-site-tool-search class="converter-receipt-search" .copy=${this.copy} .label=${this.copy('Search conversion receipts','搜尋轉換收據')} .entries=${this.receipts.map(row=>({key:row.id,text:[row.at,row.source,row.target,row.state,String(row.inputBytes),String(row.outputBytes)].join(' ')}))} @site-search-change=${(e:CustomEvent)=>{this.receiptMatches=e.detail;this.receiptPage=0}}></mg-site-tool-search><p>${this.filteredReceipts.length} ${this.copy('matching receipts','個符合收據')}</p><md-outlined-button @click=${()=>{const blob=new Blob([JSON.stringify(this.filteredReceipts,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='material-git-conversion-receipts.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>${this.copy('Export receipt facts','匯出收據事實')}</md-outlined-button>${this.filteredReceipts.slice(this.receiptPage*20,this.receiptPage*20+20).map(receipt=>html`<p class="small converter-receipt">${new Date(receipt.at).toLocaleString()} · ${Intl.DateTimeFormat().resolvedOptions().timeZone} · ${receipt.source} → ${receipt.target} · ${receipt.inputBytes} / ${receipt.outputBytes} B · ${this.copy(receipt.state,receipt.state==='interrupted'?'中斷':receipt.state==='done'?'完成':receipt.state==='failed'?'失敗':'已取消')}</p>`)}
 <mg-site-layout class="actions"><md-text-button ?disabled=${this.receiptPage===0} @click=${()=>this.receiptPage--}>${this.copy('Previous receipt page','上一頁收據')}</md-text-button><span>${this.receiptPage+1} / ${Math.max(1,Math.ceil(this.filteredReceipts.length/20))}</span><md-text-button ?disabled=${(this.receiptPage+1)*20>=this.filteredReceipts.length} @click=${()=>this.receiptPage++}>${this.copy('Next receipt page','下一頁收據')}</md-text-button></mg-site-layout>
 `}
}
customElements.define('mg-site-converter',BrowserConverter);
