import {parsePreferenceJson} from '../shared/preferences-advanced';
import {LitElement,html,nothing} from 'lit';
import {serializeExport,exportFormats,type ExportFormat} from '../shared/exports';
import {reportSiteEvent} from './events';
import {notificationCategories,notificationSearchText,emptyNotifications,validateNotifications,notificationBytes,type NotificationDocument,type SiteNotification} from './notifications';
import type {MessageCategory} from '../renderer/localization';
import {notificationNames as names,exportDisclosureYue} from './notification-copy';
class BrowserNotificationCenter extends LitElement {
 static properties={document:{attribute:false},copy:{attribute:false},facts:{attribute:false},query:{state:true},regex:{state:true},builder:{state:true},flags:{state:true},regexMatches:{state:true},error:{state:true},category:{state:true},state:{state:true},page:{state:true},selected:{state:true},review:{state:true},format:{state:true},exportReview:{state:true},importReview:{state:true}};
 document:NotificationDocument=emptyNotifications();copy=(en:string,_yue:string)=>en;facts=(en:string,yue:string)=>this.copy(en,yue);query='';regex=false;builder=false;flags='i';regexMatches:Set<string>|null=null;error='';category='all';state='all';page=0;selected=new Set<string>();review:{revision:number;ids:string[];dismissed:boolean}|null=null;format:ExportFormat='json';exportReview=false;importReview:{revision:number;document:NotificationDocument}|null=null;private worker:Worker|null=null;private sequence=0;private anchor='';
 createRenderRoot(){return this}
 disconnectedCallback(){super.disconnectedCallback();this.worker?.terminate()}
 protected updated(changed:Map<string,unknown>){if(changed.has('document')){this.selected=new Set([...this.selected].filter(id=>this.document.records.some(record=>record.id===id)));if(this.query)this.filter();if(this.page>Math.max(0,Math.ceil(this.filtered.length/20)-1))this.page=0}}
 private get filtered(){return [...this.document.records].reverse().filter(record=>(!this.regexMatches||this.regexMatches.has(record.id))&&(this.category==='all'||record.category===this.category)&&(this.state==='all'||record.dismissed===(this.state==='dismissed')))}
 private get pageRecords(){return this.filtered.slice(this.page*20,this.page*20+20)}
 private get exportRecords(){return this.filtered.filter(record=>!this.selected.size||this.selected.has(record.id)).map(record=>({...record}))}
 private async filter(){this.page=0;this.review=null;this.exportReview=false;const generation=++this.sequence;this.worker?.terminate();this.error='';if(!this.query){this.regexMatches=null;return}if(!this.regex){this.regexMatches=new Set(this.document.records.filter(record=>notificationSearchText(record).toLowerCase().includes(this.query.toLowerCase())).map(record=>record.id));return}if(this.query.length>256){this.error=this.copy('Maximum pattern length: 256 characters.','格式最多 256 個字元。');this.regexMatches=new Set();return}const worker=new Worker(new URL('./regex-worker.js',document.baseURI),{type:'module'});this.worker=worker;let done=false;const finish=(result:any)=>{if(done)return;done=true;clearTimeout(timer);worker.terminate();if(generation!==this.sequence)return;this.error=result.error?this.copy('Invalid or slow expression. Edit the pattern or use plain text.','格式無效或者太慢，請修改格式或者用文字搜尋。'):'';this.regexMatches=new Set((result.matches??[]).filter((record:any)=>record.match).map((record:any)=>String(record.key)))};const timer=setTimeout(()=>finish({error:true}),200);worker.onmessage=event=>finish(event.data);worker.onerror=()=>finish({error:true});worker.postMessage({pattern:this.query,flags:this.flags,entries:this.document.records.map(record=>({key:record.id,text:notificationSearchText(record)}))})}
 private toggle(record:SiteNotification,event:Event){const next=new Set(this.selected),shift=(event as MouseEvent).shiftKey;if(shift&&this.anchor){const ids=this.filtered.map(row=>row.id),from=ids.indexOf(this.anchor),to=ids.indexOf(record.id);if(from>=0&&to>=0)for(const id of ids.slice(Math.min(from,to),Math.max(from,to)+1))next.add(id)}else if(next.has(record.id))next.delete(record.id);else next.add(record.id);this.anchor=record.id;this.selected=next;this.review=null;this.exportReview=false}
 private reviewChange(dismissed:boolean){this.review={revision:this.document.revision,ids:this.filtered.filter(record=>this.selected.has(record.id)).map(record=>record.id),dismissed}}
 private apply(){if(!this.review)return;if(this.review.revision!==this.document.revision){this.error=this.copy('The review is outdated. Review the current selection again.','檢閱已過時，請重新檢閱目前選擇。');this.review=null;return}this.dispatchEvent(new CustomEvent('notification-change',{detail:this.review,bubbles:true,composed:true}));this.review=null}
 private exportData(){try{const data=this.exportRecords,format=exportFormats(data).includes(this.format)?this.format:'json',output=serializeExport(data,format);this.dispatchEvent(new CustomEvent('notification-export',{detail:{text:output.text,mime:output.mime,name:'material-git-notifications.'+output.extension},bubbles:true,composed:true}));this.exportReview=false}catch{this.error=reportSiteEvent(this,this.copy,'error','Notification export failed. Choose a supported format and retry.','訊息匯出失敗，請選擇支援格式後重試。')}}
 private async importData(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{if(file.size>notificationBytes)throw Error();const records=parsePreferenceJson(new Uint8Array(await file.arrayBuffer()),notificationBytes);if(!Array.isArray(records))throw Error();this.importReview={revision:this.document.revision,document:validateNotifications({schemaVersion:1,revision:this.document.revision+1,records})}}catch{this.error=reportSiteEvent(this,this.copy,'error','Invalid notification JSON. Existing messages remain unchanged. Choose an exported JSON record array and retry.','訊息 JSON 無效，現有訊息保持不變。請選擇已匯出嘅 JSON 記錄陣列後重試。')}input.value=''}
 private async copyData(){try{await navigator.clipboard.writeText(this.exportRecords.map(record=>`${record.at}\n${record.category}\n${record.en}\n${record.yue}`).join('\n\n'));reportSiteEvent(this,this.copy,'status','Selected matching notification facts copied.','已複製符合篩選嘅已選訊息事實。')}catch{this.error=reportSiteEvent(this,this.copy,'error','Clipboard permission is unavailable. Export the selected records instead.','剪貼簿權限不可用，請改為匯出已選記錄。')}}
 render(){const filtered=this.filtered,page=this.pageRecords,selected=filtered.filter(record=>this.selected.has(record.id)),review=this.review,changing=review?selected.filter(record=>record.dismissed!==review.dismissed):[],exports=this.exportRecords,formats=exportFormats(exports);return html`
 <p>${this.copy('Messages stay in this browser. Errors and warnings keep their facts until dismissed. Routine corner notices expire after 8 seconds; their records remain here.','訊息只留喺呢個瀏覽器。錯誤同警告保留至關閉。普通角落提示 8 秒後隱藏，記錄仍然留喺呢度。')}</p>
 <mg-site-surface class="search-surface" aria-label=${this.copy('Search notifications','搜尋訊息')}><mg-site-layout class="search-row"><md-outlined-text-field label=${this.copy('Search notifications','搜尋訊息')} .value=${this.query} .error=${Boolean(this.error)} .errorText=${this.error} @input=${(event:any)=>{this.query=event.target.value;this.filter()}}></md-outlined-text-field><md-outlined-button aria-expanded=${this.builder} @click=${()=>this.builder=!this.builder}>${this.copy('Regex builder','正則搜尋工具')}</md-outlined-button><md-text-button @click=${()=>{this.query='';this.filter()}}>${this.copy('Clear','清除')}</md-text-button></mg-site-layout>${this.builder?html`<mg-site-layout class="regex-panel"><label>${this.copy('Use regular expressions','使用正則表達式')}<md-switch aria-label=${this.copy('Use regular expressions','使用正則表達式')} .selected=${this.regex} @change=${(event:any)=>{this.regex=event.target.selected;this.filter()}}></md-switch></label><md-outlined-text-field label=${this.copy('Flags (i, m, s, u)','旗標 (i, m, s, u)')} .value=${this.flags} @input=${(event:any)=>{this.flags=event.target.value;this.filter()}}></md-outlined-text-field><mg-site-layout class="actions">${[['^','Start','開頭'],['$','End','結尾'],['.','Any character','任何字元'],['.*','Any text','任何文字'],['[a-z]','Character range','字元範圍'],['\\d','Digit','數字'],['(?:one|two)','Alternatives','其他選項'],['(text)','Capture','擷取'],['(?=text)','Lookahead','前瞻'],['{1,3}','Repeat','重複'],['\\b','Word boundary','字詞邊界']].map(([token,en,yue])=>html`<md-outlined-button title=${token} @click=${()=>{this.query+=token;this.regex=true;this.filter()}}>${this.copy(en,yue)}</md-outlined-button>`)}</mg-site-layout><p class="small">${this.copy('This search owns its pattern and flags. JavaScript expressions run in a worker with a 200 ms limit.','格式同旗標只屬於呢個搜尋，JavaScript 表達式喺背景工具執行，限時 200 ms。')}</p></mg-site-layout>`:nothing}</mg-site-surface>
 <mg-site-layout class="notification-filters"><md-outlined-select label=${this.copy('Category','種類')} .value=${this.category} @change=${(event:any)=>{this.category=event.target.value;this.page=0;this.review=null}}>${['all',...notificationCategories].map(category=>html`<md-select-option value=${category} .selected=${category===this.category}><mg-site-layout slot="headline">${category==='all'?this.copy('All categories','所有種類'):this.copy(...names[category as MessageCategory])} (${this.document.records.filter(record=>category==='all'||record.category===category).length})</mg-site-layout></md-select-option>`)}</md-outlined-select><md-outlined-select label=${this.copy('Message state','訊息狀態')} .value=${this.state} @change=${(event:any)=>{this.state=event.target.value;this.page=0;this.review=null}}>${[['all','All messages','全部訊息'],['active','Not dismissed','未關閉'],['dismissed','Dismissed','已關閉']].map(([value,en,yue])=>html`<md-select-option value=${value} .selected=${value===this.state}><mg-site-layout slot="headline">${this.copy(en,yue)}</mg-site-layout></md-select-option>`)}</md-outlined-select></mg-site-layout>
 <p class="small notification-count">${filtered.length} ${this.copy('matching records','個符合記錄')} · ${selected.length} ${this.copy('selected matches','個已選符合記錄')} · ${this.selected.size-selected.length} ${this.copy('selected outside the filter, excluded from actions and export','個選擇喺篩選以外，唔會加入動作或匯出')}</p>
 <mg-site-layout class="actions"><md-outlined-button @click=${()=>{this.selected=new Set([...this.selected,...page.map(record=>record.id)]);this.review=null}}>${this.copy('Select this page','選擇呢頁')}</md-outlined-button><md-outlined-button @click=${()=>{this.selected=new Set([...this.selected,...filtered.map(record=>record.id)]);this.review=null}}>${this.copy('Select every match','選擇所有符合記錄')}</md-outlined-button><md-text-button @click=${()=>{const next=new Set(this.selected);for(const record of filtered)next.has(record.id)?next.delete(record.id):next.add(record.id);this.selected=next;this.review=null}}>${this.copy('Invert matching selection','反轉符合選擇')}</md-text-button><md-text-button @click=${()=>{this.selected=new Set();this.review=null}}>${this.copy('Clear selection','清除選擇')}</md-text-button></mg-site-layout>
 <mg-site-layout class="notification-records">${page.map(record=>html`<mg-site-surface class=${'notification-record '+record.category}><md-checkbox aria-label=${this.copy('Select message from ','選擇訊息：')+record.at} .checked=${this.selected.has(record.id)} @click=${(event:Event)=>this.toggle(record,event)} @keydown=${(event:KeyboardEvent)=>{if(event.shiftKey&&event.key===' '){event.preventDefault();this.toggle(record,event)}}}></md-checkbox><mg-site-layout><strong>${this.copy(...names[record.category])}</strong><small>${record.at} · ${record.dismissed?this.copy('Dismissed','已關閉'):this.copy('Not dismissed','未關閉')}</small><p>${this.facts(record.en,record.yue)}</p><md-text-button @click=${()=>{this.selected=new Set([record.id]);this.reviewChange(!record.dismissed)}}>${record.dismissed?this.copy('Review restore','檢閱還原'):this.copy('Review dismiss','檢閱關閉')}</md-text-button>${record.action?html`<md-text-button @click=${()=>this.dispatchEvent(new CustomEvent('notification-action',{detail:{action:record.action},bubbles:true,composed:true}))}>${this.copy('Open recovery action','開啟恢復動作')}</md-text-button>`:nothing}</mg-site-layout></mg-site-surface>`)}${!page.length?html`<p class="empty">${this.copy('No messages match the current text, category and state filters.','目前文字、種類同狀態篩選冇符合訊息。')}</p>`:nothing}</mg-site-layout>
 <mg-site-layout class="actions"><md-text-button ?disabled=${this.page===0} @click=${()=>this.page--}>${this.copy('Previous page','上一頁')}</md-text-button><span>${this.page+1} / ${Math.max(1,Math.ceil(filtered.length/20))}</span><md-text-button ?disabled=${(this.page+1)*20>=filtered.length} @click=${()=>this.page++}>${this.copy('Next page','下一頁')}</md-text-button></mg-site-layout>
 <mg-site-layout class="actions"><md-outlined-button ?disabled=${!selected.length} @click=${()=>this.reviewChange(true)}>${this.copy('Review dismiss selected matches','檢閱關閉已選符合記錄')}</md-outlined-button><md-outlined-button ?disabled=${!selected.length} @click=${()=>this.reviewChange(false)}>${this.copy('Review restore selected matches','檢閱還原已選符合記錄')}</md-outlined-button><md-text-button ?disabled=${!exports.length} @click=${()=>this.copyData()}>${this.copy('Copy matching facts','複製符合事實')}</md-text-button></mg-site-layout>
 ${review?html`<mg-site-surface class="notification-review"><p>${selected.length} ${this.copy('selected matches','個已選符合記錄')} · ${changing.length} ${this.copy('will change','個將會修改')} · ${selected.length-changing.length} ${this.copy('already in the requested state, skipped','個已經係所需狀態，會跳過')}</p><ul>${selected.map(record=>html`<li>${record.at}: ${this.copy(record.en,record.yue)}</li>`)}</ul><md-filled-button ?disabled=${review.revision!==this.document.revision} @click=${()=>this.apply()}>${review.dismissed?this.copy('Dismiss reviewed records','關閉已檢閱記錄'):this.copy('Restore reviewed records','還原已檢閱記錄')}</md-filled-button><md-text-button @click=${()=>this.review=null}>${this.copy('Cancel','取消')}</md-text-button>${review.revision!==this.document.revision?html`<p class="error">${this.copy('Records changed after this review. Review the current selection again.','檢閱之後記錄有修改，請重新檢閱目前選擇。')}</p>`:nothing}</mg-site-surface>`:nothing}
 <mg-site-layout class="notification-filters"><md-outlined-select label=${this.copy('Notification export format','訊息匯出格式')} .value=${this.format} @change=${(event:any)=>{this.format=event.target.value;this.exportReview=false}}>${formats.map(format=>html`<md-select-option value=${format} .selected=${format===this.format}><mg-site-layout slot="headline">${format.toUpperCase()}</mg-site-layout></md-select-option>`)}</md-outlined-select><md-outlined-button @click=${()=>this.exportReview=true}>${this.copy('Review filtered export','檢閱篩選匯出')}</md-outlined-button></mg-site-layout>
 ${this.exportReview?html`<mg-site-surface class="notification-review"><p>${exports.length} ${this.copy('records will be exported. Selection, if present, is intersected with all current filters. UTF-8. Vocabulary, credentials and uploaded-file metadata are omitted.','個記錄將會匯出。如有選擇，只包含符合目前所有篩選嘅記錄。UTF-8。唔會包含詞彙、憑證同上載檔案資料。')}</p>${serializeExport(exports,formats.includes(this.format)?this.format:'json').disclosures.map(disclosure=>html`<p class="small">${this.copy(disclosure,exportDisclosureYue[disclosure]??disclosure)}</p>`)}<md-filled-button @click=${()=>this.exportData()}>${this.copy('Export reviewed records','匯出已檢閱記錄')}</md-filled-button><md-text-button @click=${()=>this.exportReview=false}>${this.copy('Cancel','取消')}</md-text-button></mg-site-surface>`:nothing}
 <label class="file-control">${this.copy('Import notifications JSON','匯入訊息 JSON')}<input type="file" accept="application/json,.json" @change=${this.importData}></label>
 ${this.importReview?html`<mg-site-surface class="notification-review"><p>${this.copy('Replace the current message collection with ','以匯入資料取代目前訊息集合：')}${this.importReview.document.records.length} ${this.copy('validated records. Existing records are retained in visitor history. Imported facts and dates are supplied by the file, without service verification.','個已驗證記錄。現有記錄會保留喺訪客歷史。匯入事實同日期由檔案提供，未經服務驗證。')}</p><md-filled-button ?disabled=${this.importReview.revision!==this.document.revision} @click=${()=>{if(!this.importReview)return;this.dispatchEvent(new CustomEvent('notification-import',{detail:this.importReview,bubbles:true,composed:true}));this.importReview=null}}>${this.copy('Replace reviewed collection','取代已檢閱集合')}</md-filled-button><md-text-button @click=${()=>this.importReview=null}>${this.copy('Cancel','取消')}</md-text-button>${this.importReview.revision!==this.document.revision?html`<p class="error">${this.copy('Messages changed since review. Choose the import file again.','檢閱之後訊息有修改，請重新選擇匯入檔案。')}</p>`:nothing}</mg-site-surface>`:nothing}
 <p class="small">${this.copy('Up to 200 records, limited to 1 MiB. Retention may replace dismissed or routine messages. Undismissed errors and warnings are never silently replaced. Dismiss and restore are reversible through visitor history. No irreversible delete is offered.','最多 200 個記錄，總共 1 MiB。保留規則可能取代已關閉或普通訊息，唔會靜靜取代未關閉錯誤同警告。關閉同還原可以透過訪客記錄復原，未有不可逆刪除動作。')}</p>`}
}
customElements.define('mg-site-notifications',BrowserNotificationCenter);
