import type {AdvancedGitTask} from './git-advanced';
/** Native Git workflows. Filesystem grants and executable arguments remain main-process owned. */
export type GitAction = 'open'|'open-source'|'status'|'diff'|'history'|'branches'|'remotes'|'tags'|'stashes'|'worktrees'|'submodules'|'config'|'conflict'|'object'|'inspect'|'help'|'import-patch'|'files'|'notes-conflicts'|'notes-conflict'|'review'|'apply'|'cancel';
export type GitTask = AdvancedGitTask | 'init'|'clone'|'stage'|'unstage'|'stage-hunk'|'unstage-hunk'|'discard'|'commit'|'branch-create'|'branch-switch'|'branch-rename'|'branch-delete'|'merge'|'rebase'|'cherry-pick'|'revert'|'continue'|'abort'|'skip'|'resolve'|'fetch'|'pull'|'push'|'remote-add'|'remote-remove'|'remote-rename'|'remote-url'|'tag-create'|'tag-delete'|'stash-save'|'stash-apply'|'stash-pop'|'stash-drop'|'worktree-add'|'worktree-remove'|'worktree-lock'|'worktree-unlock'|'worktree-prune'|'submodule-add'|'submodule-update'|'submodule-sync'|'submodule-deinit'|'bisect-start'|'bisect-good'|'bisect-bad'|'bisect-reset'|'patch-apply'|'patch-am'|'format-patch'|'sparse-set'|'sparse-disable'|'deepen'|'config-set'|'config-unset'|'maintenance'|'pack-refs'|'reflog-expire'|'notes-add'|'notes-remove'|'replace-create'|'replace-delete'|'update-ref'|'reset';
export interface GitPayload {worktreeId?:string;path?:string;staged?:boolean;revision?:string;revision2?:string;page?:number;query?:string;task?:GitTask;fields?:Record<string,unknown>;reviewId?:string;confirmed?:boolean;operationId?:string;kind?:string;fileId?:string;topic?:string;}
export interface GitFile {path:string;originalPath?:string;index:string;worktree:string;untracked:boolean;conflict:boolean;submodule:boolean;}
export interface GitSnapshot {worktreeId:string;name:string;root:string;gitDir:string;commonDir:string;bare:boolean;head:string;branch:string;version:string;helperVersion?:string;files:GitFile[];operation:string;trust:string[];fingerprint:string;}
export interface GitRow {id:string;label:string;detail:string;data?:Record<string,string>;}
export interface GitReview {kind:'review';reviewId:string;worktreeId:string;task:GitTask;title:string;summary:string;argv:string[];warnings:string[];expiresAt:string;fingerprint:string;}
export interface GitResult {kind:'result';ok:boolean;exitCode:number|null;output:string;error:string;cancelled:boolean;partialEffects:boolean;operationId:string;snapshot?:GitSnapshot;}
export type GitResponse = {kind:'snapshot';snapshot:GitSnapshot}|{kind:'rows';rows:GitRow[];hasNext:boolean;notice?:string}|{kind:'text';text:string}|{kind:'conflict';path:string;base:string;ours:string;theirs:string;working:string}|{kind:'file';fileId:string;name:string;preview:string}|{kind:'cancelled';partialEffects:boolean}|GitReview|GitResult;
export interface GitBridge {git(action:GitAction,payload?:GitPayload):Promise<GitResponse>;}
