export const githubDomains=['repositories','issues','pulls','actions','releases','projects','discussions','search','security','organizations','gists','codespaces'] as const;
export type GitHubDomain=typeof githubDomains[number];
export const githubMutationActions=['repositories.create','repositories.edit','repositories.delete','repositories.fork','issues.create','issues.edit','issues.comment','issues.close','issues.reopen','pulls.create','pulls.edit','pulls.comment','pulls.close','pulls.reopen','pulls.merge','pulls.review','pulls.request-review','actions.cancel','actions.rerun','actions.rerun-failed','actions.delete','actions.dispatch','actions.enable-workflow','actions.disable-workflow','actions.download-artifacts','releases.create','releases.edit','releases.delete','releases.upload','releases.download-assets','projects.create','projects.edit','projects.delete','projects.add-item','discussions.create','discussions.comment','discussions.close','discussions.reopen','gists.create','gists.edit','gists.delete','codespaces.create','codespaces.start','codespaces.stop','codespaces.delete','security.dismiss','organizations.invite','organizations.remove-member'] as const;
export type GitHubAction=import('./github-native').NativeGitHubAction|`${GitHubDomain}.list`|`${GitHubDomain}.detail`|typeof githubMutationActions[number]|'repositories.owners'|'discussions.categories'|'review'|'apply'|'choices'|'task-definition'|'actions.watch-status'|'actions.watch-cancel';
export interface GitHubPayload {hostname?:string;repository?:string;page?:number;query?:string;state?:string;id?:string|number;tab?:string;values?:Record<string,unknown>;confirmed?:boolean;action?:GitHubAction;reviewId?:string;entity?:GitHubChoiceEntity}
export interface GitHubItem extends Record<string,unknown> {id:string;title:string;subtitle?:string;url?:string;state?:string;number?:number;repository?:string}
export type GitHubChoiceEntity='labels'|'assignees'|'collaborators'|'milestones'|'branches'|'reviewers'|'projects'|'tags'|'workflows'|'discussion-categories'|'repositories'|'organizations'|'environments'|'secrets'|'variables'|'deployment-keys'|'gpg-keys'|'ssh-keys'|'rulesets'|'project-fields'|'project-items';
export interface GitHubReview {reviewId:string;action:string;repository?:string;id?:string|number;values:Record<string,unknown>;prepared?:Record<string,unknown>;expiresAt:string;warnings:string[]}
export interface GitHubResponse {items:GitHubItem[];hasNext:boolean;page:number;total?:number;detail?:Record<string,unknown>;notice?:string;review?:GitHubReview;task?:import('./github-native').NativeGitHubTask}
export interface GitHubBridge {github(action:GitHubAction,payload?:GitHubPayload):Promise<GitHubResponse>}
