import type {AppSettings} from './types.js';
import {validateSettings} from './preferences.js';
import {validateAppearance,type AppearanceRecord} from './appearance.js';
export const preferenceLimits={bytes:262144,rules:64,connections:16,refreshMin:30,refreshMax:3600,responseBytes:65536,timeoutMs:8000} as const;
export type PreferencePatch=Partial<AppSettings>;
export interface ScheduledRule {id:string;label:string;enabled:boolean;priority:number;startDate:string;endDate:string;startTime:string;endTime:string;weekdays:number[];values:PreferencePatch;appearance?:Record<string,AppearanceRecord>;source:{kind:'local'}|{kind:'https';connectionId:string}|{kind:'home-assistant';connectionId:string;entity:string}}
export interface PreferenceConnection {id:string;label:string;kind:'https'|'home-assistant';url:string;refreshSeconds:number;approved:true}
export interface PreferenceDocument {schemaVersion:1;timezone:string;rules:ScheduledRule[];connections:PreferenceConnection[]}
export interface PreferenceStatus {document:PreferenceDocument;effective:AppSettings;appearance:Record<string,AppearanceRecord>;connections:(PreferenceConnection&{secretPresent:boolean})[];sources:Record<string,string>;warnings:{code:string;ruleId?:string}[];fontFamilies?:string[]}
export type PreferenceAction='status'|'save'|'refresh'|'connect'|'disconnect'|'secret'|'fonts';
export interface PreferenceAdvancedBridge {preferencesAdvanced(action:PreferenceAction,input?:unknown):Promise<PreferenceStatus>;onPreferencesAdvanced?(callback:(status:PreferenceStatus)=>void):()=>void}
const unsafe=new Set(['__proto__','constructor','prototype']);
export function object(value:unknown,fields:readonly string[]):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Expected an object');for(const key of Object.keys(value))if(unsafe.has(key)||!fields.includes(key))throw new Error('Unexpected field');return value as Record<string,unknown>;}
function text(value:unknown,max=128):string{if(typeof value!=='string'||value.length>max||/[\u0000-\u001f]/.test(value))throw new Error('Invalid text');return value;}
function id(value:unknown):string{const result=text(value);if(!/^[a-zA-Z0-9._-]{1,128}$/.test(result)||unsafe.has(result))throw new Error('Invalid identifier');return result;}
export function validateSourceUrl(input:unknown):string {const raw=text(input,2048);let url:URL;try{url=new URL(raw);}catch{throw new Error('Invalid source URL');}if(url.protocol!=='https:'||url.username||url.password||url.hash||url.port&&url.port!=='443')throw new Error('Use HTTPS without credentials, fragments or custom ports');const host=url.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.localhost')||host.endsWith('.local')||host==='::1'||host.startsWith('[')||/^\d+(?:\.\d+){3}$/.test(host)||!host.includes('.'))throw new Error('Source must use a public DNS name');return url.href;}
export function validateConnection(input:unknown):PreferenceConnection {const v=object(input,['id','label','kind','url','refreshSeconds','approved']);if(!['https','home-assistant'].includes(String(v.kind))||v.approved!==true||!Number.isInteger(v.refreshSeconds)||Number(v.refreshSeconds)<30||Number(v.refreshSeconds)>3600)throw new Error('Invalid connection');return{id:id(v.id),label:text(v.label),kind:v.kind as PreferenceConnection['kind'],url:validateSourceUrl(v.url),refreshSeconds:Number(v.refreshSeconds),approved:true};}
function date(input:unknown):string {const s=text(input,10);if(!s)return s;if(!/^\d{4}-\d\d-\d\d$/.test(s)||new Date(s+'T00:00:00Z').toISOString().slice(0,10)!==s)throw new Error('Invalid calendar date');return s;}
function time(input:unknown):string {const s=text(input,5);if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(s))throw new Error('Invalid time');return s;}
export function validateAppearanceMap(input:unknown):Record<string,AppearanceRecord>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length>100)throw new Error('Invalid appearance map');const out:Record<string,AppearanceRecord>=Object.create(null);for(const[key,value]of Object.entries(input))out[id(key)]=validateAppearance(value);return out;}
export function validatePreferenceDocument(input:unknown):PreferenceDocument {const v=object(input,['schemaVersion','timezone','rules','connections']);if(v.schemaVersion!==1)throw new Error('Unsupported schedule schema version');const timezone=text(v.timezone,100);try{new Intl.DateTimeFormat('en',{timeZone:timezone}).format();}catch{throw new Error('Invalid IANA timezone');}if(!Array.isArray(v.rules)||v.rules.length>64||!Array.isArray(v.connections)||v.connections.length>16)throw new Error('Schedule limit exceeded');const connections=v.connections.map(validateConnection);const ids=new Set<string>();for(const c of connections){if(ids.has(c.id))throw new Error('Duplicate connection identifier');ids.add(c.id);}const ruleIds=new Set<string>();const rules=v.rules.map(input=>{const r=object(input,['id','label','enabled','priority','startDate','endDate','startTime','endTime','weekdays','values','appearance','source']);const ruleId=id(r.id);if(ruleIds.has(ruleId))throw new Error('Duplicate rule identifier');ruleIds.add(ruleId);if(typeof r.enabled!=='boolean'||!Number.isInteger(r.priority)||Math.abs(Number(r.priority))>10000)throw new Error('Invalid rule priority or state');const startDate=date(r.startDate),endDate=date(r.endDate);if(startDate&&endDate&&startDate>endDate)throw new Error('End date precedes start date');if(!Array.isArray(r.weekdays)||r.weekdays.length<1||r.weekdays.length>7||new Set(r.weekdays).size!==r.weekdays.length||r.weekdays.some(d=>!Number.isInteger(d)||d<0||d>6))throw new Error('Choose at least one unique weekday');const source=object(r.source,['kind','connectionId','entity']);if(source.kind!=='local'){if(!['https','home-assistant'].includes(String(source.kind)))throw new Error('Invalid source');const connection=connections.find(c=>c.id===source.connectionId&&c.kind===source.kind);if(!connection)throw new Error('Source requires an approved matching connection');if(source.kind==='home-assistant'&&(typeof source.entity!=='string'||!/^(binary_sensor|input_boolean)\.[a-z0-9_]{1,128}$/.test(source.entity)))throw new Error('Use a Home Assistant boolean entity');if(source.kind==='https'&&source.entity!==undefined)throw new Error('Unexpected entity');}else if(source.connectionId!==undefined||source.entity!==undefined)throw new Error('Unexpected local source field');return{id:ruleId,label:text(r.label),enabled:r.enabled,priority:Number(r.priority),startDate,endDate,startTime:time(r.startTime),endTime:time(r.endTime),weekdays:[...r.weekdays],values:validateSettings(r.values),...(r.appearance===undefined?{}:{appearance:validateAppearanceMap(r.appearance)}),source:source as ScheduledRule['source']};});const result:PreferenceDocument={schemaVersion:1,timezone,rules,connections};if(new TextEncoder().encode(JSON.stringify(result)).length>preferenceLimits.bytes)throw new Error('Schedule exceeds byte limit');return result;}
export function defaultPreferenceDocument(timezone=Intl.DateTimeFormat().resolvedOptions().timeZone):PreferenceDocument{return{schemaVersion:1,timezone,rules:[],connections:[]};}
/** Wall-clock matching: [start,end), equal times cover a whole day. Overnight windows belong to the starting date/weekday. Repeated DST times match twice; nonexistent wall times never occur. */
export function ruleMatches(rule:ScheduledRule,instant:Date,timezone:string):boolean {if(!rule.enabled||!Number.isFinite(instant.getTime()))return false;const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(instant);const part=(kind:string)=>parts.find(p=>p.type===kind)!.value;let day=`${part('year')}-${part('month')}-${part('day')}`;const now=part('hour')+':'+part('minute');const overnight=rule.startTime>rule.endTime;if(rule.startTime!==rule.endTime&&!(overnight?now>=rule.startTime||now<rule.endTime:now>=rule.startTime&&now<rule.endTime))return false;if(overnight&&now<rule.endTime)day=new Date(Date.parse(day+'T12:00:00Z')-86400000).toISOString().slice(0,10);const weekday=new Date(day+'T12:00:00Z').getUTCDay();return rule.weekdays.includes(weekday)&&(!rule.startDate||day>=rule.startDate)&&(!rule.endDate||day<=rule.endDate);}
export interface ExternalRuleValue {values?:PreferencePatch;active:boolean;appearance?:Record<string,AppearanceRecord>}
export function resolvePreferences(base:AppSettings,document:PreferenceDocument,instant:Date,external:Map<string,ExternalRuleValue>=new Map()):Pick<PreferenceStatus,'effective'|'appearance'|'sources'> {const effective={...base},appearance:Record<string,AppearanceRecord>={},sources:Record<string,string>={};const rules=document.rules.filter(r=>ruleMatches(r,instant,document.timezone)).sort((a,b)=>a.priority-b.priority||(a.id<b.id?-1:a.id>b.id?1:0));for(const rule of rules){const remote=external.get(rule.id);if(rule.source.kind!=='local'&&!remote?.active)continue;const values=rule.source.kind==='https'?remote?.values??{}:rule.values;Object.assign(effective,values);Object.assign(appearance,rule.source.kind==='https'?remote?.appearance??{}:rule.appearance??{});for(const key of Object.keys(values))sources[key]=rule.id;}return{effective,appearance,sources};}
export function validateExternalResponse(input:unknown):ExternalRuleValue {const v=object(input,['schemaVersion','settings','appearance']);if(v.schemaVersion!==1)throw new Error('Unsupported external settings version');return{active:true,values:validateSettings(v.settings),...(v.appearance===undefined?{}:{appearance:validateAppearanceMap(v.appearance)})};}
/** Duplicate-key rejecting JSON reader used at import, cache and network boundaries. */
export function parsePreferenceJson(source:Uint8Array|string,maxBytes:number=preferenceLimits.bytes):unknown {const bytes=typeof source==='string'?new TextEncoder().encode(source):source;if(bytes.length>maxBytes)throw new Error('JSON byte limit exceeded');const s=new TextDecoder('utf-8',{fatal:true}).decode(bytes);let i=0;const ws=()=>{while(i<s.length&&/[ \t\r\n]/.test(s[i]))i++;};const str=()=>{const start=i++;while(i<s.length){const c=s[i++];if(c==='\\'){i++;continue;}if(c==='"')return JSON.parse(s.slice(start,i)) as string;}throw new Error('Invalid JSON string');};const value=(depth:number):unknown=>{if(depth>16)throw new Error('JSON depth limit exceeded');ws();if(s[i]==='"')return str();if(s[i]==='{'){i++;ws();const out:Record<string,unknown>=Object.create(null);if(s[i]==='}'){i++;return out;}while(i<s.length){ws();if(s[i]!=='"')throw new Error('Invalid JSON key');const key=str();if(unsafe.has(key)||Object.hasOwn(out,key))throw new Error('Duplicate or unsafe JSON key');ws();if(s[i++]!==':')throw new Error('Invalid JSON separator');out[key]=value(depth+1);ws();const c=s[i++];if(c==='}')return out;if(c!==',')throw new Error('Invalid JSON separator');}}if(s[i]==='['){i++;ws();const out:unknown[]=[];if(s[i]===']'){i++;return out;}while(i<s.length){if(out.length>10000)throw new Error('JSON item limit exceeded');out.push(value(depth+1));ws();const c=s[i++];if(c===']')return out;if(c!==',')throw new Error('Invalid JSON separator');}}const match=/^(?:-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?|true|false|null)/.exec(s.slice(i));if(!match)throw new Error('Invalid JSON');i+=match[0].length;return JSON.parse(match[0]);};const result=value(0);ws();if(i!==s.length)throw new Error('Invalid trailing JSON');return result;}
