/** Public, credential-free workspace records. Command drafts and provider output are never stored. */
export type WorkspaceAction='status'|'save'|'notify'|'notifications'|'label'|'restore'|'prune'|'export'|'import-preview'|'import-apply'|'record-revisions'|'record-diff'|'record-restore'|'record-label'|'record-prune'|'record-appearance'|'discard';
export interface WorkspaceTab {id:string;label:string;pinned:boolean;group:string}
export interface WorkspaceGroup {id:string;label:string;color:string;collapsed:boolean;pinned:boolean}
export interface WorkspaceState {version:1;tabs:WorkspaceTab[];groups:WorkspaceGroup[];activeTab:string;lane:string;dock:'left'|'right'|'top'|'bottom';explorerWidth:number;dockHeight:number;explorerVisible:boolean;dockVisible:boolean;split:'none'|'vertical'|'horizontal';splitRatio:number;paletteSize:'card'|'window'}
export interface WorkspaceNotification {id:string;at:string;kind:'info'|'success'|'warning'|'error';title:string;read:boolean;dismissed:boolean;operationId?:string}
export interface WorkspaceRevision {id:string;at:string;action:string;label:string;state:WorkspaceState}
export interface WorkspaceEnvelope {schema:'material-git-records';version:1;encoding:'UTF-8';kind:'workspace'|'notifications'|'revisions';records:WorkspaceState|WorkspaceNotification[]|WorkspaceRevision[]}
export interface WorkspaceResponse {state?:WorkspaceState;notifications?:WorkspaceNotification[];revisions?:WorkspaceRevision[];warning?:string;managedRevisions?:ManagedRecordRevision[];diff?:{before:unknown;after:unknown};export?:WorkspaceEnvelope;preview?:{kind:WorkspaceEnvelope['kind'];count:number;state?:WorkspaceState;notifications?:WorkspaceNotification[]}}
export const workspaceDefaults:WorkspaceState={version:1,tabs:[],groups:[],activeTab:'',lane:'home',dock:'left',explorerWidth:250,dockHeight:210,explorerVisible:true,dockVisible:true,split:'none',splitRatio:50,paletteSize:'card'};
const lanes=['git','home','commands','jobs','accounts','history','api','cli-config','tools','security','updates','settings','docs','about','notifications','records','importer','integrations','assistant','downloads','repositories','issues','pull-requests','pulls','actions','releases','projects','extensions','aliases','codespaces','copilot','discussions','search','repository-security','organizations','gists'];
const object=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Expected a record.');return v as Record<string,unknown>;};
const keys=(v:Record<string,unknown>,names:string[])=>{if(Object.keys(v).some(k=>!names.includes(k)))throw Error('Unrecognized record fields; drafts and credentials cannot be imported.');};
export function safeText(v:unknown,max=160):string{if(typeof v!=='string'||v.length>max||/[\u0000-\u001f\u007f]/.test(v)||/gh[pousr]_[A-Za-z0-9_]{8,}|github_pat_|Bearer\s|(?:password|token|secret|authorization)\s*[:=]/i.test(v))throw Error('Text is invalid or may contain a credential.');return v;}
const bool=(v:unknown)=>{if(typeof v!=='boolean')throw Error('Expected a boolean.');return v;};
const number=(v:unknown,min:number,max:number)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw Error('Number outside the supported range.');return v;};
const choice=<T extends string>(v:unknown,choices:T[]):T=>{if(!choices.includes(v as T))throw Error('Unsupported choice.');return v as T;};
export function validateWorkspace(value:unknown):WorkspaceState{
 const v=object(value);keys(v,Object.keys(workspaceDefaults));if(v.version!==1)throw Error('Unsupported workspace version.');
 if(!Array.isArray(v.tabs)||v.tabs.length>100||!Array.isArray(v.groups)||v.groups.length>40)throw Error('Workspace supports at most 100 tabs and 40 groups.');
 const groups=v.groups.map(row=>{const r=object(row);keys(r,['id','label','color','collapsed','pinned']);if(typeof r.color!=='string'||!/^#[a-f0-9]{6}$/i.test(r.color))throw Error('Invalid group color.');return {id:safeText(r.id,100),label:safeText(r.label,100),color:r.color,collapsed:bool(r.collapsed),pinned:bool(r.pinned)};});
 const tabs=v.tabs.map(row=>{const r=object(row);keys(r,['id','label','pinned','group']);return {id:safeText(r.id,160),label:safeText(r.label,160),pinned:bool(r.pinned),group:safeText(r.group,100)};});
 if(groups.some(g=>!g.id||!g.label)||tabs.some(t=>!t.id||!t.label||t.group&&!groups.some(g=>g.id===t.group))||new Set(tabs.map(t=>t.id)).size!==tabs.length||new Set(groups.map(g=>g.id)).size!==groups.length)throw Error('Duplicate, empty or missing workspace identity.');
 const activeTab=safeText(v.activeTab,160);if(activeTab&&!tabs.some(t=>t.id===activeTab))throw Error('Active tab is missing.');
 return {version:1,tabs,groups,activeTab,lane:choice(v.lane,lanes),dock:choice(v.dock,['left','right','top','bottom']),explorerWidth:number(v.explorerWidth,190,380),dockHeight:number(v.dockHeight,100,360),explorerVisible:bool(v.explorerVisible),dockVisible:bool(v.dockVisible),split:choice(v.split,['none','vertical','horizontal']),splitRatio:number(v.splitRatio,20,80),paletteSize:choice(v.paletteSize,['card','window'])};
}
export function validateNotification(value:unknown):WorkspaceNotification{const v=object(value);keys(v,['id','at','kind','title','read','dismissed','operationId']);const at=safeText(v.at,40);if(!Number.isFinite(Date.parse(at)))throw Error('Invalid notification date.');return {id:safeText(v.id,100),at,kind:choice(v.kind,['info','success','warning','error']),title:safeText(v.title,240),read:bool(v.read),dismissed:bool(v.dismissed),...(v.operationId===undefined?{}:{operationId:safeText(v.operationId,100)})};}
export function validateEnvelope(value:unknown):WorkspaceEnvelope{const v=object(value);keys(v,['schema','version','encoding','kind','records']);if(v.schema!=='material-git-records'||v.version!==1||v.encoding!=='UTF-8')throw Error('Unsupported record schema or encoding.');const kind=choice(v.kind,['workspace','notifications','revisions']);if(kind==='workspace')return {schema:v.schema,version:1,encoding:'UTF-8',kind,records:validateWorkspace(v.records)};if(!Array.isArray(v.records)||v.records.length>500)throw Error('Record collection exceeds 500 items.');if(kind==='notifications'){const records=v.records.map(validateNotification);if(new Set(records.map(r=>r.id)).size!==records.length)throw Error('Duplicate notification identities.');return {schema:v.schema,version:1,encoding:'UTF-8',kind,records};}const records=v.records.map(row=>{const r=object(row);keys(r,['id','at','action','label','state']);const at=safeText(r.at,40);if(!Number.isFinite(Date.parse(at)))throw Error('Invalid revision date.');return {id:safeText(r.id,100),at,action:safeText(r.action,160),label:safeText(r.label,100),state:validateWorkspace(r.state)};});return {schema:v.schema,version:1,encoding:'UTF-8',kind,records};}
export interface ManagedRecordRevision {id:string;at:string;kind:string;recordId:string;action:string;snapshot:unknown;label:string}
/** Metadata history deliberately omits draft/content/credential fields; encrypted ciphertext may survive. */
export function sanitizeRecord(value:unknown,depth=0):unknown{
 if(depth>12)throw Error('Record nesting exceeds the history limit.');
 if(value===null||typeof value==='boolean'||typeof value==='number')return value;
 if(typeof value==='string'){if(value.length>65536)throw Error('Record text exceeds the history limit.');return /gh[pousr]_[A-Za-z0-9_]{8,}|github_pat_|Bearer\s|(?:password|token|secret|authorization)\s*[:=]/i.test(value)?'[redacted]':value;}
 if(Array.isArray(value)){if(value.length>500)throw Error('Record list exceeds the history limit.');return value.map(v=>sanitizeRecord(v,depth+1));}
 if(!value||typeof value!=='object')throw Error('Record is not serializable.');const result:Record<string,unknown>={};for(const [key,val] of Object.entries(value)){if(/secret|password|credential|authorization|private.?key|vocabulary|^entries$|^drafts?$|^args$|^values$|^stdout$|^stderr$|^content$|^body$|^prompt$|^messages$|token|^code$|recovery/i.test(key))continue;if(val!==undefined)result[key]=sanitizeRecord(val,depth+1);}return result;
}
