import {constants} from 'node:fs';import {lstat,open,realpath} from 'node:fs/promises';import {resolve} from 'node:path';import {createHash} from 'node:crypto';
/** Main-only file receipt. Public bytes are never a renderer upload authority. */
export interface SshPublicKeyFile {path:string;key:string;algorithm:string;fingerprint:string;receipt:string}
export async function readSshPublicKey(path:string):Promise<SshPublicKeyFile>{
 if(typeof path!=='string'||path.length>4096||/[\0\r\n]/.test(path))throw Error('Choose a regular SSH public-key file');
 const selected=await lstat(path).catch(()=>{throw Error('The selected public-key file is unavailable');});if(!selected.isFile()||selected.isSymbolicLink()||await realpath(path)!==resolve(path))throw Error('Choose a regular SSH public-key file without symbolic links');
 const file=await open(path,constants.O_RDONLY|(process.platform==='win32'?0:constants.O_NOFOLLOW)).catch(()=>{throw Error('The selected public-key file could not be opened');});const bytes=Buffer.alloc(16385);let length=0;
 try{const before=await file.stat();if(!before.isFile()||before.size<16||before.size>16384)throw Error('The public-key file must contain at most 16 KiB');while(length<bytes.length){const read=await file.read(bytes,length,bytes.length-length,null);if(!read.bytesRead)break;length+=read.bytesRead;}const after=await file.stat();if(length>16384||length!==before.size||before.dev!==selected.dev||before.ino!==selected.ino||before.size!==after.size||before.mtimeMs!==after.mtimeMs)throw Error('The public-key file changed while reading it');const text=bytes.subarray(0,length).toString('utf8').trim();if(/[\0\r\n]/.test(text))throw Error('Choose one OpenSSH public key, not a private key or key bundle');const match=/^(ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp(?:256|384|521)|sk-ssh-ed25519@openssh.com|sk-ecdsa-sha2-nistp256@openssh.com) ([A-Za-z0-9+/]+={0,2})(?: [^\r\n\0]*)?$/.exec(text);if(!match)throw Error('Choose an OpenSSH public-key file; private keys are never accepted');const blob=Buffer.from(match[2],'base64');if(blob.length<24||blob.length>8192||blob.toString('base64').replace(/=+$/,'')!==match[2].replace(/=+$/,''))throw Error('The SSH public-key encoding is invalid');const size=blob.readUInt32BE(0);if(size>256||size+4>=blob.length||blob.subarray(4,4+size).toString('ascii')!==match[1])throw Error('The SSH public-key algorithm does not match its encoded key');const fingerprint='SHA256:'+createHash('sha256').update(blob).digest('base64').replace(/=+$/,'');return {path,key:text,algorithm:match[1],fingerprint,receipt:createHash('sha256').update(JSON.stringify([before.dev,before.ino,before.size,before.mtimeMs])).update(bytes.subarray(0,length)).digest('hex')};}finally{bytes.fill(0);await file.close();}
}
