import {createHash,createCipheriv,createDecipheriv,scryptSync,randomBytes,randomUUID} from 'node:crypto';
import {readFile,mkdir,writeFile,rename} from 'node:fs/promises';import path from 'node:path';
import {parseOtpAuth,validateTotpParameters,otpAuthUri,type TotpParameters} from '../shared/security';
import {authenticatorIcons,validateAuthenticatorMetadata,redactedAuthenticatorRows,type AuthenticatorEntry,type AuthenticatorGroup,type AuthenticatorReview,type AuthenticatorQrCallbacks,type AuthenticatorBackupEnvelope} from '../shared/security-authenticator';
interface StoredEntry extends AuthenticatorEntry{encrypted:string}
interface State{schemaVersion:2;entries:StoredEntry[];groups:AuthenticatorGroup[]}
const uuid=(value:unknown):value is string=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const exact=(p:Record<string,unknown>,keys:string[])=>{if(Object.keys(p).some(key=>!keys.includes(key)))throw Error('Unexpected authenticator request field.');};
export function encryptAuthenticatorBackup(data:unknown,password:string):AuthenticatorBackupEnvelope{if(typeof password!=='string'||password.length<12||password.length>256)throw Error('Use a separate backup password of 12–256 characters.');const salt=randomBytes(16),iv=randomBytes(12),key=scryptSync(password,salt,32,{N:16384,r:8,p:1,maxmem:67108864}),cipher=createCipheriv('aes-256-gcm',key,iv);cipher.setAAD(Buffer.from('material-git-authenticator-backup:1'));const plaintext=Buffer.from(JSON.stringify(data),'utf8');try{if(plaintext.length>1048576)throw Error('Authenticator backup is too large.');const ciphertext=Buffer.concat([cipher.update(plaintext),cipher.final()]);return{schema:'material-git-authenticator-backup',version:1,cipher:'AES-256-GCM',kdf:{name:'scrypt',N:16384,r:8,p:1},salt:salt.toString('base64'),iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),ciphertext:ciphertext.toString('base64')};}finally{key.fill(0);plaintext.fill(0);}}
export function validateAuthenticatorBackupEnvelope(input:unknown):AuthenticatorBackupEnvelope{if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Invalid protected authenticator backup.');const envelope=input as AuthenticatorBackupEnvelope;if(Object.keys(envelope).length!==8||Object.keys(envelope).some(key=>!['schema','version','cipher','kdf','salt','iv','tag','ciphertext'].includes(key))||envelope.schema!=='material-git-authenticator-backup'||envelope.version!==1||envelope.cipher!=='AES-256-GCM'||!envelope.kdf||Object.keys(envelope.kdf).length!==4||envelope.kdf.name!=='scrypt'||envelope.kdf.N!==16384||envelope.kdf.r!==8||envelope.kdf.p!==1)throw Error('Invalid protected authenticator backup.');for(const [key,size] of [['salt',16],['iv',12],['tag',16],['ciphertext',0]] as const){const value=envelope[key];if(typeof value!=='string'||!value.length||value.length>1398104||!/^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value))throw Error('Invalid protected authenticator backup.');const bytes=Buffer.from(value,'base64');if(bytes.toString('base64')!==value||(size?bytes.length!==size:bytes.length>1048576))throw Error('Invalid protected authenticator backup.');}return structuredClone(envelope);}
/** Only protected native import/history consumers may decode a backup; never return this over IPC. */
export function decryptAuthenticatorBackup(envelope:AuthenticatorBackupEnvelope,password:string):unknown{envelope=validateAuthenticatorBackupEnvelope(envelope);if(typeof password!=='string'||password.length<12||password.length>256)throw Error('Invalid protected authenticator backup.');const decode=(value:string,size?:number)=>{if(typeof value!=='string'||value.length>1500000||!value.length||!/^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value))throw Error('Invalid protected authenticator backup.');const bytes=Buffer.from(value,'base64');if(size&&bytes.length!==size)throw Error('Invalid protected authenticator backup.');return bytes;},salt=decode(envelope.salt,16),iv=decode(envelope.iv,12),tag=decode(envelope.tag,16),key=scryptSync(password,salt,32,{N:16384,r:8,p:1,maxmem:67108864});try{const decipher=createDecipheriv('aes-256-gcm',key,iv);decipher.setAAD(Buffer.from('material-git-authenticator-backup:1'));decipher.setAuthTag(tag);const plaintext=Buffer.concat([decipher.update(decode(envelope.ciphertext)),decipher.final()]);try{return JSON.parse(plaintext.toString('utf8'));}finally{plaintext.fill(0);}}catch{throw Error('The protected backup could not be authenticated. Check its password and file.');}finally{key.fill(0);}}
interface BackupContents{schema:'material-git-authenticator-contents';version:1;entries:(AuthenticatorEntry&{parameters:TotpParameters})[];groups:AuthenticatorGroup[]}
/** Validate authenticated plaintext only inside the native issuer; never expose parameters over IPC. */
export function validateAuthenticatorBackupContents(input:unknown):BackupContents{
 try{if(!input||typeof input!=='object'||Array.isArray(input))throw Error();const data=input as BackupContents;exact(data as unknown as Record<string,unknown>,['schema','version','entries','groups']);if(data.schema!=='material-git-authenticator-contents'||data.version!==1||!Array.isArray(data.entries)||!data.entries.length||data.entries.length>100||!Array.isArray(data.groups)||data.groups.length>100)throw Error();const groupIds=new Set<string>(),entryIds=new Set<string>(),identities=new Set<string>();const groups=data.groups.map(group=>{exact(group as unknown as Record<string,unknown>,['id','name','icon']);if(!uuid(group.id)||groupIds.has(group.id))throw Error();groupIds.add(group.id);const metadata=validateAuthenticatorMetadata({groupId:group.id,name:group.name,icon:group.icon});return{id:group.id,name:metadata.name,icon:metadata.icon};});
 const entries=data.entries.map(entry=>{exact(entry as unknown as Record<string,unknown>,['id','issuer','account','algorithm','digits','period','name','icon','groupId','parameters']);if(!uuid(entry.id)||entryIds.has(entry.id))throw Error();entryIds.add(entry.id);const metadata=validateAuthenticatorMetadata({name:entry.name,icon:entry.icon,groupId:entry.groupId}),parameters=validateTotpParameters(entry.parameters);if(metadata.groupId&&!groupIds.has(metadata.groupId))throw Error();for(const key of ['issuer','account','algorithm','digits','period'] as const)if(entry[key]!==parameters[key])throw Error();const identity=JSON.stringify([parameters.issuer,parameters.account]);if(identities.has(identity))throw Error();identities.add(identity);const {secret:_,...facts}=parameters;return{id:entry.id,...facts,...metadata,parameters};});return{schema:data.schema,version:1,entries,groups};}catch{throw Error('The authenticated backup contains invalid entries or groups.');}
}
export function createAuthenticatorStore(options:AuthenticatorQrCallbacks&{directory:string;encrypt:(value:string)=>string;decrypt:(value:string)=>string;verify:(p:TotpParameters,code:string)=>boolean;totp:(p:TotpParameters,time:number)=>string;now?:()=>number;authorize:(action:string)=>Promise<void>;recordMutation?:(action:string,metadata:unknown)=>Promise<void>;completed?:(action:string)=>void}){
 const file=path.join(options.directory,'authenticator.json'),now=options.now??Date.now,reviews=new Map<string,{review:AuthenticatorReview;digest:string;importState?:State}>();
 const summary=({encrypted:_,...entry}:StoredEntry):AuthenticatorEntry=>entry;
 const digest=(state:State)=>createHash('sha256').update(JSON.stringify(state)).digest('hex');
 async function read():Promise<State>{let data:any;try{const raw=await readFile(file,'utf8');if(Buffer.byteLength(raw)>524288)throw Error();data=JSON.parse(raw);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return{schemaVersion:2,entries:[],groups:[]};throw Error('Authenticator encrypted storage is unavailable or invalid.');}try{if(![1,2].includes(data.schemaVersion)||Object.keys(data).some(key=>!['schemaVersion','entries','groups'].includes(key))||!Array.isArray(data.entries)||data.entries.length>100)throw Error();const groups:AuthenticatorGroup[]=data.schemaVersion===1?[]:data.groups;if(!Array.isArray(groups)||groups.length>100)throw Error();const groupIds=new Set<string>();for(const group of groups){if(!uuid(group.id)||groupIds.has(group.id)||Object.keys(group).some(key=>!['id','name','icon'].includes(key)))throw Error();validateAuthenticatorMetadata({name:group.name,icon:group.icon,groupId:group.id});groupIds.add(group.id);}const ids=new Set<string>(),entries:StoredEntry[]=data.entries.map((entry:any)=>{if(!uuid(entry.id)||ids.has(entry.id)||typeof entry.encrypted!=='string'||entry.encrypted.length>8192||Object.keys(entry).some(key=>!['id','issuer','account','algorithm','digits','period','encrypted',...(data.schemaVersion===2?['name','icon','groupId']:[])].includes(key)))throw Error();ids.add(entry.id);const parameters=validateTotpParameters(JSON.parse(options.decrypt(entry.encrypted)));for(const key of ['issuer','account','algorithm','digits','period'] as const)if(entry[key]!==parameters[key])throw Error();const metadata=validateAuthenticatorMetadata(data.schemaVersion===1?{name:entry.account,icon:'shield',groupId:''}:{name:entry.name,icon:entry.icon,groupId:entry.groupId});if(metadata.groupId&&!groupIds.has(metadata.groupId))throw Error();return{...entry,...metadata};});return{schemaVersion:2,entries,groups};}catch{throw Error('Authenticator encrypted storage is unavailable or invalid.');}}
 async function write(state:State,action:string,metadata:unknown){await options.recordMutation?.(action,{...metadata as object,secretsOmitted:true,codesOmitted:true});await mkdir(options.directory,{recursive:true,mode:0o700});const temporary=file+'.'+randomUUID()+'.tmp';const permission=({authenticatorEnrolled:'authenticatorEnroll',authenticatorEdited:'authenticatorEdit',authenticatorGroupChanged:'authenticatorGroup',authenticatorMoved:'authenticatorMove',authenticatorReordered:'authenticatorReorder',authenticatorRemoved:'authenticatorRemove',authenticatorImported:'authenticatorImport'} as Record<string,string>)[action];try{await writeFile(temporary,JSON.stringify(state),{mode:0o600});await rename(temporary,file);reviews.clear();}finally{if(permission)options.completed?.(permission);}}
 function ids(input:unknown,state:State):string[]{if(!Array.isArray(input)||!input.length||input.length>100||input.some(id=>!uuid(id))||new Set(input).size!==input.length||input.some(id=>!state.entries.some(entry=>entry.id===id)))throw Error('Choose exact existing authenticator entries.');return input as string[];}
 async function handle(action:string,p:Record<string,unknown>={}){if(!p||typeof p!=='object'||Array.isArray(p)||Object.keys(p).length>10||Object.values(p).some(value=>typeof value==='string'&&value.length>8192))throw Error('Invalid authenticator request.');if(action==='authenticatorCapabilities'){exact(p,[]);return{file:Boolean(options.chooseQrImage&&options.decodeQrImage),clipboard:Boolean(options.clipboardQrImage&&options.decodeQrImage),protectedExport:Boolean(options.saveSensitiveExport),protectedImport:Boolean(options.chooseSensitiveImport),camera:Boolean(options.requestCameraPermission)};}
 if(action==='authenticatorDiscardReview'){exact(p,['reviewId']);if(!uuid(p.reviewId))throw Error('Choose a valid native review.');reviews.delete(p.reviewId);return{discarded:true};}
 await options.authorize(action);
 if(action==='authenticatorQrFile'||action==='authenticatorQrClipboard'){exact(p,[]);const read=action==='authenticatorQrFile'?options.chooseQrImage:options.clipboardQrImage;if(!read||!options.decodeQrImage)throw Error('This local image import capability is unavailable.');const bytes=await read();if(!bytes)return{cancelled:true};if(!bytes.byteLength||bytes.byteLength>8388608)throw Error('QR images must contain at most 8 MiB.');const candidates=await options.decodeQrImage(bytes);if(!Array.isArray(candidates)||candidates.length!==1||typeof candidates[0]!=='string')throw Error('Choose an image containing exactly one readable authenticator QR.');const parameters=parseOtpAuth(candidates[0]);return{uri:otpAuthUri(parameters),parameters};}
 if(action==='authenticatorCameraPermit'){exact(p,[]);if(!options.requestCameraPermission)throw Error('User-scoped camera permission is unavailable.');return{allowed:await options.requestCameraPermission()};}
 const state=await read();
 if(action==='authenticatorImportReview'){
 exact(p,['backupPassword','duplicatePolicy']);if(p.duplicatePolicy!=='skip'&&p.duplicatePolicy!=='replace')throw Error('Choose whether exact issuer/account duplicates are skipped or replaced.');if(typeof p.backupPassword!=='string'||p.backupPassword.length<12||p.backupPassword.length>256)throw Error('Enter the separate backup password of 12–256 characters.');if(!options.chooseSensitiveImport)throw Error('Protected native import is unavailable.');await options.authorize('authenticatorImport');
 const raw=await options.chooseSensitiveImport();if(raw===null)return{cancelled:true};if(typeof raw!=='string'||Buffer.byteLength(raw)>1500000)throw Error('Protected authenticator backup is too large.');let contents:any;try{contents=decryptAuthenticatorBackup(validateAuthenticatorBackupEnvelope(JSON.parse(raw)),p.backupPassword);}catch{throw Error('The protected backup could not be authenticated. Check its password and file.');}
 const incoming=validateAuthenticatorBackupContents(contents);await options.authorize('authenticatorImport');const latest=await read(),next:State=structuredClone(latest),groupMap=new Map<string,string>(),changes:NonNullable<AuthenticatorReview['changes']>=[],entries:AuthenticatorEntry[]=[];
 const importGroup=(id:string)=>{if(!id)return '';if(groupMap.has(id))return groupMap.get(id)!;const source=incoming.groups.find(group=>group.id===id)!,existing=next.groups.find(group=>group.name===source.name&&group.icon===source.icon);const group=existing??{...source,id:randomUUID()};if(!existing)next.groups.push(group);groupMap.set(id,group.id);return group.id;};
 for(const source of incoming.entries){const matches=next.entries.filter(entry=>entry.issuer===source.issuer&&entry.account===source.account);if(matches.length>1)throw Error('Multiple local entries use that exact issuer/account. Manage those duplicates before importing.');const existing=matches[0];if(existing&&p.duplicatePolicy==='skip'){entries.push(summary(existing));changes.push({id:existing.id,decision:'skip'});continue;}const {parameters,...facts}=source,entry:StoredEntry={...facts,id:existing?.id??randomUUID(),groupId:importGroup(source.groupId),encrypted:options.encrypt(JSON.stringify(parameters))};if(existing)next.entries[next.entries.indexOf(existing)]=entry;else next.entries.push(entry);entries.push(summary(entry));changes.push({id:entry.id,decision:existing?'replace':'add',...(existing?{before:summary(existing)}:{})});}
 if(next.entries.length>100||next.groups.length>100)throw Error('The imported entries or groups exceed the local limit.');for(const [id,receipt] of reviews)if(receipt.review.expiresAt<=now())reviews.delete(id);if(reviews.size>=20)throw Error('Finish or cancel existing authenticator reviews.');const review:AuthenticatorReview={id:randomUUID(),operation:'import',entries,changes,groups:next.groups.filter(group=>entries.some(entry=>entry.groupId===group.id)),duplicatePolicy:p.duplicatePolicy,expiresAt:now()+120000,secretsOmitted:true};reviews.set(review.id,{review,digest:digest(latest),importState:next});return{review:structuredClone(review)};
 }
 if(action==='authenticatorImport'){
 exact(p,['reviewId','keyOne','keyTwo','confirmation']);if(!uuid(p.reviewId)||p.keyOne!==true||p.keyTwo!==true||p.confirmation!==100)throw Error('Complete both independent keys and the full confirmation slider.');const receipt=reviews.get(p.reviewId);if(!receipt||receipt.review.operation!=='import'||!receipt.importState||receipt.review.expiresAt<=now()||receipt.digest!==digest(state))throw Error('This exact authenticator review expired or changed. Review it again.');reviews.delete(p.reviewId);const changes=receipt.review.changes!;if(changes.every(change=>change.decision==='skip'))return{imported:0,replaced:0,skipped:changes.length};await write(receipt.importState,'authenticatorImported',{changes,duplicatePolicy:receipt.review.duplicatePolicy});return{imported:changes.filter(change=>change.decision==='add').length,replaced:changes.filter(change=>change.decision==='replace').length,skipped:changes.filter(change=>change.decision==='skip').length};
 }
 if(action==='authenticatorList'){exact(p,[]);return{entries:state.entries.map(summary),groups:state.groups};}
 if(action==='authenticatorCodes'){exact(p,[]);const time=now();return{clockSource:'system',clockVerified:false,groups:state.groups,entries:state.entries.map(entry=>{const parameters=validateTotpParameters(JSON.parse(options.decrypt(entry.encrypted)));return{...summary(entry),code:options.totp(parameters,time),nextCode:options.totp(parameters,time+parameters.period*1000),remaining:parameters.period-Math.floor(time/1000)%parameters.period};})};}
 if(action==='authenticatorEnroll'){exact(p,['uri','parameters','code','metadata']);if((typeof p.uri==='string')===(p.parameters!==undefined))throw Error('Choose exactly one pairing URI or manual parameter set.');const parameters=typeof p.uri==='string'?parseOtpAuth(p.uri):validateTotpParameters(p.parameters);if(typeof p.code!=='string'||!options.verify(parameters,p.code))throw Error('Current code did not match; registration was not completed.');if(state.entries.length>=100)throw Error('Authenticator entry limit reached.');const metadata=validateAuthenticatorMetadata(p.metadata??{name:parameters.account,icon:'shield',groupId:''});if(metadata.groupId&&!state.groups.some(group=>group.id===metadata.groupId))throw Error('Choose an existing authenticator group.');const {secret:_,...facts}=parameters,entry:StoredEntry={id:randomUUID(),...facts,...metadata,encrypted:options.encrypt(JSON.stringify(parameters))};state.entries.push(entry);await write(state,'authenticatorEnrolled',{...summary(entry)});return summary(entry);}
 if(action==='authenticatorEdit'){exact(p,['id','metadata','parameters','code']);const entry=state.entries.find(entry=>entry.id===p.id);if(!entry)throw Error('Choose an existing authenticator entry.');const metadata=validateAuthenticatorMetadata(p.metadata);if(metadata.groupId&&!state.groups.some(group=>group.id===metadata.groupId))throw Error('Choose an existing authenticator group.');if(p.parameters!==undefined){const parameters=validateTotpParameters(p.parameters);if(typeof p.code!=='string'||!options.verify(parameters,p.code))throw Error('Confirm replacement parameters with their current code.');const {secret:_,...facts}=parameters;Object.assign(entry,facts,{encrypted:options.encrypt(JSON.stringify(parameters))});}Object.assign(entry,metadata);await write(state,'authenticatorEdited',{...summary(entry)});return summary(entry);}
 if(action==='authenticatorGroup'){exact(p,['id','name','icon']);const metadata=validateAuthenticatorMetadata({name:p.name,icon:p.icon,groupId:''});let group=state.groups.find(group=>group.id===p.id);if(p.id!==undefined&&!group)throw Error('Choose an existing authenticator group.');if(!group){if(state.groups.length>=100)throw Error('Authenticator group limit reached.');group={id:randomUUID(),name:metadata.name,icon:metadata.icon};state.groups.push(group);}else Object.assign(group,{name:metadata.name,icon:metadata.icon});await write(state,'authenticatorGroupChanged',{id:group.id,name:group.name,icon:group.icon});return{group,groups:state.groups};}
 if(action==='authenticatorMove'){exact(p,['ids','groupId']);const selected=ids(p.ids,state);if(typeof p.groupId!=='string'||p.groupId!==''&&!state.groups.some(group=>group.id===p.groupId))throw Error('Choose an existing authenticator group.');for(const entry of state.entries)if(selected.includes(entry.id))entry.groupId=p.groupId;await write(state,'authenticatorMoved',{ids:selected,groupId:p.groupId});return{entries:state.entries.map(summary),groups:state.groups};}
 if(action==='authenticatorReorder'){exact(p,['ids']);const order=ids(p.ids,state);if(order.length!==state.entries.length)throw Error('Reorder must include every existing entry exactly once.');state.entries=order.map(id=>state.entries.find(entry=>entry.id===id)!);await write(state,'authenticatorReordered',{ids:order});return{entries:state.entries.map(summary),groups:state.groups};}
 if(action==='authenticatorExport'){exact(p,['ids']);const selected=ids(p.ids,state);return{schema:'material-git-authenticator-metadata',version:1,secretsOmitted:true,codesOmitted:true,entries:redactedAuthenticatorRows(state.entries.filter(entry=>selected.includes(entry.id)).map(summary)),groups:state.groups.filter(group=>state.entries.some(entry=>selected.includes(entry.id)&&entry.groupId===group.id))};}
 if(action==='authenticatorReview'){exact(p,['operation','ids']);if(p.operation!=='remove'&&p.operation!=='export')throw Error('Choose the exact protected authenticator action.');const selected=ids(p.ids,state);await options.authorize(p.operation==='remove'?'authenticatorRemove':'authenticatorSensitiveExport');for(const [id,receipt] of reviews)if(receipt.review.expiresAt<=now())reviews.delete(id);if(reviews.size>=20)throw Error('Finish or cancel existing authenticator reviews.');const review:AuthenticatorReview={id:randomUUID(),operation:p.operation,entries:state.entries.filter(entry=>selected.includes(entry.id)).map(summary),expiresAt:now()+120000,secretsOmitted:true};reviews.set(review.id,{review,digest:digest(state)});return{review:structuredClone(review)};}
 if(action==='authenticatorDiscardReview'){exact(p,['reviewId']);if(!uuid(p.reviewId))throw Error('Choose a valid native review.');reviews.delete(p.reviewId);return{discarded:true};}
 if(action==='authenticatorRemove'||action==='authenticatorSensitiveExport'){exact(p,['reviewId','keyOne','keyTwo','confirmation',...(action==='authenticatorSensitiveExport'?['backupPassword']:[])]);if(!uuid(p.reviewId)||p.keyOne!==true||p.keyTwo!==true||p.confirmation!==100)throw Error('Complete both independent keys and the full confirmation slider.');const receipt=reviews.get(p.reviewId);if(!receipt||receipt.review.expiresAt<=now()||receipt.digest!==digest(state)||receipt.review.operation!==(action==='authenticatorRemove'?'remove':'export'))throw Error('This exact authenticator review expired or changed. Review it again.');const selected=receipt.review.entries.map(entry=>entry.id);if(action==='authenticatorSensitiveExport'){if(!options.saveSensitiveExport)throw Error('Protected native export is unavailable.');const envelope=encryptAuthenticatorBackup({schema:'material-git-authenticator-contents',version:1,entries:state.entries.filter(entry=>selected.includes(entry.id)).map(entry=>({...summary(entry),parameters:validateTotpParameters(JSON.parse(options.decrypt(entry.encrypted)))})),groups:state.groups.filter(group=>receipt.review.entries.some(entry=>entry.groupId===group.id))},p.backupPassword as string);reviews.delete(p.reviewId);try{const saved=await options.saveSensitiveExport(JSON.stringify(envelope));return{saved,encrypted:true,requiresBackupPassword:true};}finally{options.completed?.('authenticatorSensitiveExport');}}reviews.delete(p.reviewId);state.entries=state.entries.filter(entry=>!selected.includes(entry.id));await write(state,'authenticatorRemoved',{ids:selected,count:selected.length});return{removed:selected.length};}
 throw Error('Unsupported authenticator action.');
 }
 return{handle};
}
