import type {ConverterAdapter} from '../shared/local-tools';
import type {EngineStatus,EngineKind} from '../shared/bundled-engines';
import {FILE_LIMIT} from './local-tools-codecs';
export function bundledRegistry(status:EngineStatus[]):ConverterAdapter[]{const result:ConverterAdapter[]=[];const add=(id:string,name:string,category:ConverterAdapter['category'],sourceTypes:string[],target:string,kind:EngineKind,disclosure:string)=>{const state=status.find(s=>s.kind===kind);result.push({id,name,category,sourceTypes,target,bundled:state?.available===true,enabled:state?.available===true,proof:state?.proof??'Missing bundled proof',reason:state?.available?undefined:state?.reason??'Bundled engine is not configured',disclosure,limitBytes:FILE_LIMIT,validator:kind==='ffmpeg'?'Reopen with verified FFprobe; validate duration, format and dimensions':kind==='archive'?'Native archive integrity test and reopened content names/sizes':'Decode/parse emitted format and semantic/pixel/PDF-page validation'});};
 for(const op of ['inspect','split','merge','extract','reorder','rotate','metadata'])add('pdf-'+op,'PDF: '+op,'Documents/PDF',['pdf'],op==='inspect'?'json':'pdf','worker','Up to 250 pages and 32 MiB per source. Encrypted, signed, scripted, embedded-file and form PDFs are unsupported. Split writes separate pages; merge uses selected PDF sources; page selection/order uses verified 1-based page numbers.');
 for(const format of ['json','jsonl','yaml','xml','csv','tsv','html','sql','md','txt'])add('data-'+format,'Structured data to '+format.toUpperCase(),'Structured Data/Spreadsheets',['json','text','xml','yaml','jsonl','csv'],''+format,'worker','Choose the actual source grammar. YAML aliases and XML DTD/entities are unsupported. XML uses typed JSON schema; delimited/SQL output discloses scalar-type and nested-value behavior.');
 for(const format of ['png','jpeg'])add('isolated-'+format,'Image to '+format.toUpperCase(),'Images',['png','jpeg'],format,'worker',format==='jpeg'?'Lossy JPEG with explicit quality; removes alpha, profiles and metadata. Decoding runs in bounded isolated worker.':'Lossless raster PNG pixels and alpha; removes profiles/metadata. Decoding runs in bounded isolated worker.');
 add('zip-create','Create ZIP','Archives',['*'],'zip','worker','Source basenames and exact bytes; bounded compression level. Metadata is not preserved.');add('zip-extract','Extract safe ZIP','Archives',['zip'],'bin','worker','Rejects traversal, links, encryption, ZIP64 and expansion above 64 MiB. Writes separate new flat output filenames.');add('7z-create','Create 7z archive','Archives',['*'],'7z','archive','Guided compression, level, dictionary, solid mode, threads, volume size and optional content/header encryption. Sources stay untouched. Passwords are not stored or put in arguments.');add('7z-zip','Create ZIP with native options','Archives',['*'],'zip','archive','Guided ZIP compression and optional AES256 content encryption. ZIP header encryption and solid compression are unsupported.');add('7z-extract','Extract safe 7z / ZIP','Archives',['7z','zip'],'bin','archive','Native integrity and size validation. Rejects traversal, links and expansion above 64 MiB; user supplies password through a masked control if encrypted.');
 for(const format of ['wav','mp3','flac','ogg'])add('media-'+format,'Audio to '+format.toUpperCase(),'Audio',['wav','mp3','flac','ogg','mp4','webm','mkv'],'', 'ffmpeg','');
 for(const format of ['mp4','webm','mkv'])add('media-'+format,'Video to '+format.toUpperCase(),'Video',['mp4','webm','mkv','avi','mov'],'','ffmpeg','');
 for(const adapter of result.filter(a=>a.id.startsWith('media-'))){adapter.target=adapter.id.slice(6);adapter.disclosure='Fixed codec preset; maximum 300 seconds, 32 MiB source, 64 MiB output, 4096 pixels/side and bounded threads. May be lossy; removes metadata, subtitles, data streams and additional tracks. No network protocols.';}
 return result;}
