import {spawnSync} from 'node:child_process';
import {existsSync,realpathSync,statSync,readFileSync,constants,accessSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import path from 'node:path';
import {homedir,tmpdir} from 'node:os';
import type {Catalog} from '../shared/types';
import {workflowCommandIds,type CliWorkflowAction,type CliWorkflowPayload,type CliWorkflowResponse,type WorkflowChoice,type CliWorkflowReview} from '../shared/cli-workflows';
import {Engine} from './engine';
import {readBoundedFile} from './bounded-file';
const LIMIT=65536,TTL=300000;
interface Plan {review:CliWorkflowReview;argv:string[];executable:string;cwd:string;fingerprints:{file:string;hash:string}[];timeoutMs?:number}
export interface CliWorkflowDependencies {chooseFile?:()=>Promise<string|null>;read?:(argv:string[])=>string;now?:()=>number;copilotPath?:string|null}
function text(value:unknown,label:string,required=false,max=4096):string {if(value===undefined||value===''){if(required)throw new Error(`Choose ${label}`);return '';}if(typeof value!=='string'||value.length>max||/[\0\r\n]/.test(value))throw new Error(`Invalid ${label}`);return value;}
function port(value:unknown):number {if(typeof value!=='number'||!Number.isInteger(value)||value<1||value>65535)throw new Error('Ports must be whole numbers from 1 to 65535');return value;}
function identifier(value:unknown,label:string):string {const result=text(value,label,true,100);if(!/^[a-zA-Z0-9][a-zA-Z0-9_.-]*$/.test(result))throw new Error(`Invalid ${label}`);return result;}
function redact(value:string):string {let result=value.replace(/(?:gh[pousr]_|github_pat_)[A-Za-z0-9_]+/g,'[REDACTED]');for(const [key,secret] of Object.entries(process.env))if(/TOKEN|SECRET|PASSWORD/.test(key)&&secret)result=result.split(secret).join('[REDACTED]');return result;}
function fingerprint(file:string):{file:string;hash:string}{const stat=statSync(file);if(!stat.isFile()||stat.size>LIMIT)throw new Error('Choose a regular file smaller than 64 KiB');return {file,hash:createHash('sha256').update(readBoundedFile(file,LIMIT)).digest('hex')};}
function installedCopilot():string|null {const names=process.platform==='win32'?['copilot.exe']:['copilot'];for(const directory of (process.env.PATH||'').split(path.delimiter)){if(!directory)continue;for(const name of names){const candidate=path.join(directory,name);try{accessSync(candidate,process.platform==='win32'?constants.F_OK:constants.X_OK);if(statSync(candidate).isFile())return realpathSync(candidate);}catch{}}}for(const candidate of [path.join(homedir(),'.local','share','gh','copilot','copilot'+(process.platform==='win32'?'.exe':'')),path.join(process.env.LOCALAPPDATA||homedir(),'GitHub CLI','copilot','copilot.exe')])if(existsSync(candidate)&&statSync(candidate).isFile())return realpathSync(candidate);return null;}
/** Dedicated main-process adapter. Arbitrary argv and process environments never cross IPC. */
export class CliWorkflowsService {
 private reviews=new Map<string,Plan>();private files=new Set<string>();private now:()=>number;private copilot:string|null;
 constructor(private catalog:Catalog,private engine:Engine,private workspace:string,private ghPath:string,private deps:CliWorkflowDependencies={}){this.workspace=realpathSync(workspace);this.now=deps.now||Date.now;this.copilot=deps.copilotPath===undefined?installedCopilot():deps.copilotPath;}
 private read(argv:string[]):string {if(this.deps.read)return this.deps.read(argv);const result=spawnSync(this.ghPath,argv,{cwd:this.workspace,encoding:'utf8',timeout:15000,maxBuffer:1024*1024,shell:false,windowsHide:true,env:{...process.env,GH_PROMPT_DISABLED:'1',GH_PAGER:'cat',PAGER:'cat',NO_COLOR:'1',GH_FORCE_TTY:''}});if(result.error||result.status!==0)throw new Error(redact(result.error?.message||result.stderr||'GitHub CLI could not read this list'));return redact(result.stdout);}
 private folder(value:unknown):string {const folder=realpathSync(text(value,'workspace folder',true));if(folder!==this.workspace&&!folder.startsWith(this.workspace+path.sep))throw new Error('Choose a folder inside the approved workspace');if(!statSync(folder).isDirectory())throw new Error('Choose a folder');return folder;}
 async handle(action:CliWorkflowAction,payload:CliWorkflowPayload={}):Promise<CliWorkflowResponse>{if(!payload||typeof payload!=='object'||Array.isArray(payload)||JSON.stringify(payload).length>128000)throw new Error('Invalid workflow request');if(action==='inventory')return {kind:'inventory',commands:structuredClone(this.catalog.commands),copilotInstalled:!!this.copilot,blockers:[{id:'preview prompter',reason:'The native CLI preview requires a terminal with a PTY. The desktop offers equivalent Material prompt previews, while native terminal interaction is outside the current desktop scope.'},{id:'codespace ssh:interactive',reason:'Interactive SSH needs a terminal/PTY; use the reviewed SSH configuration export or remote diagnostic profiles here.'},...(!this.copilot?[{id:'copilot',reason:'Copilot CLI is not installed on this machine. This route never downloads executable code implicitly. Install the official CLI, then refresh.'}]:[])]};
 if(action==='cancel'){this.engine.cancel(text(payload.operationId,'operation',true));return {kind:'cancelled'};}
 if(action==='import-file'){const chosen=await this.deps.chooseFile?.();if(!chosen)return {kind:'file',file:'',preview:''};const file=realpathSync(chosen);fingerprint(file);if(this.files.size>=32)this.files.delete(this.files.values().next().value!);this.files.add(file);return {kind:'file',file,preview:redact(readBoundedFile(file,LIMIT).toString('utf8'))};}
 if(action==='choices')return this.choices(payload);
 if(action==='review')return this.prepare(payload);
 if(action==='apply'){const reviewId=text(payload.reviewId,'review',true),plan=this.reviews.get(reviewId);this.reviews.delete(reviewId);if(payload.confirmed!==true)throw new Error('Confirm the exact reviewed operation');if(!plan||Date.parse(plan.review.expiresAt)<this.now())throw new Error('Review expired. Review this operation again.');for(const item of plan.fingerprints)if(fingerprint(item.file).hash!==item.hash)throw new Error('Reviewed file changed. Choose it and review again.');let temporary:string|undefined;let argv=[...plan.argv];if(plan.review.commandId==='alias import'){const file=plan.fingerprints[0];const bytes=readBoundedFile(file.file,LIMIT);if(createHash('sha256').update(bytes).digest('hex')!==file.hash)throw new Error('Reviewed file changed. Choose it and review again.');temporary=mkdtempSync(path.join(tmpdir(),'material-alias-import-'));const copy=path.join(temporary,'aliases.yml');writeFileSync(copy,bytes,{mode:0o600});argv=argv.map(value=>value===file.file?copy:value);}
 try{const operation=this.engine.executeAdapter(plan.review.commandId,argv,{executable:plan.executable,cwd:plan.cwd,timeoutMs:plan.timeoutMs});if(temporary){const folder=temporary;const unsubscribe=this.engine.subscribe(op=>{if(op.id===operation.id&&op.endedAt){unsubscribe();rmSync(folder,{recursive:true,force:true});}});}return {kind:'operation',operation};}catch(error){if(temporary)rmSync(temporary,{recursive:true,force:true});throw error;}}
 throw new Error('Unknown workflow action');}
 private choices(payload:CliWorkflowPayload):CliWorkflowResponse {const query=text(payload.query,'search query',false,200),page=payload.page??0;if(!Number.isInteger(page)||page<0||page>100)throw new Error('Invalid list page');let items:WorkflowChoice[]=[];let hasNext=false;
 if(payload.kind==='codespaces'){const rows=JSON.parse(this.read(['codespace','list','--json','name,displayName,repository,state','--limit=100']));if(!Array.isArray(rows))throw new Error('Invalid Codespaces response');items=rows.map(row=>({value:identifier(row.name,'codespace'),label:typeof row.displayName==='string'?row.displayName:row.name,detail:`${row.repository?.fullName||''} · ${row.state||'unknown'}`}));}
 else if(payload.kind==='extension-search'){const result=JSON.parse(this.read(['api',`search/repositories?q=${encodeURIComponent('topic:gh-extension '+query)}&per_page=20&page=${page+1}`]));if(!Array.isArray(result.items))throw new Error('Invalid extension search response');items=result.items.map((row:{full_name:string;description?:string})=>({value:row.full_name,label:row.full_name,detail:row.description||'No repository description'}));hasNext=(page+1)*20<Math.min(Number(result.total_count)||0,1000);return {kind:'choices',items,hasNext,notice:result.incomplete_results?'GitHub reports incomplete search results. Refine the query and retry.':undefined};}
 else if(payload.kind==='extensions'){items=this.read(['extension','list']).trim().split('\n').filter(Boolean).map(line=>{const fields=line.split('\t');const match=(fields[0]||'').match(/^gh\s+([\w.-]+)$/);if(!match)return null;return {value:match[1],label:match[1],detail:fields.slice(1).join(' · '),data:{repository:fields[1]||''}};}).filter((value):value is WorkflowChoice&{data:{repository:string}}=>value!==null);}
 else if(payload.kind==='aliases'){const lines=this.read(['alias','list']).split('\n');for(const line of lines){const match=line.match(/^([\w-]+):\s*(.*)$/);if(match)items.push({value:match[1],label:match[1],detail:match[2],data:{expansion:match[2]}});else if(/^\s/.test(line)&&items.length)items[items.length-1].detail+='\n'+line.trim();}}
 else throw new Error('Choose a supported list');items=items.filter(row=>`${row.label} ${row.detail}`.toLowerCase().includes(query.toLowerCase()));return {kind:'choices',items:items.slice(page*20,page*20+20),hasNext:items.length>(page+1)*20,...(payload.kind==='codespaces'?{notice:'CLI lists at most 100 Codespaces. Filter in the command workspace for larger accounts.'}:{})};}
 private prepare(payload:CliWorkflowPayload):CliWorkflowReview {const id=text(payload.commandId,'command',true);if(!workflowCommandIds.includes(id as typeof workflowCommandIds[number]))throw new Error('Unknown workflow command');const f=payload.fields||{};if(!f||typeof f!=='object'||Array.isArray(f))throw new Error('Use structured workflow fields');let argv=id.split(' '),executable=this.ghPath,cwd=this.workspace;const warnings:string[]=[],fingerprints:Plan['fingerprints']=[];let timeoutMs=300000;
 const accepted:Record<string,string[]>={
 'extension browse':['query'],'extension search':['query'],'extension list':[], 'extension create':['name','template','folder'],'extension exec':['name','arguments'],'extension install':['repository','pin','force','folder'],'extension upgrade':['name','all','dryRun','force'],'extension remove':['name'],
 'alias import':['file','clobber'],'alias set':['name','commandId','arguments'],'alias delete':['name','all'],'alias list':[],
 'codespace ssh':['codespace','mode','profile'],'codespace code':['codespace','insiders','web'],'codespace jupyter':['codespace'],'codespace cp':['codespace','direction','localPath','remotePath','recursive'],'codespace ports forward':['codespace','mappings'],'codespace ports visibility':['codespace','visibility'],'copilot':['mode','prompt'],'preview prompter':['promptType']};
 for(const key of Object.keys(f))if(!accepted[id].includes(key))throw new Error(`Unknown workflow field: ${key}`);
 for(const key of ['force','all','dryRun','clobber','insiders','web','recursive'])if(f[key]!==undefined&&typeof f[key]!=='boolean')throw new Error(`Boolean required: ${key}`);
 const named=(key:string,label=key)=>identifier(f[key],label);const external=()=>warnings.push('This operation runs or installs external programs. They can access your account, files, network and local configuration. Review the exact program and arguments.');
 if(id==='extension browse'||id==='extension search'){argv=['extension','search','--limit=30'];if(f.query)argv.push('--',text(f.query,'query'));}
 else if(id==='extension create'){const name=named('name','extension name');if(!/^gh-[a-z0-9][a-z0-9-]*$/.test(name))throw new Error('Extension names start with gh- and use lowercase letters, digits and hyphens');const template=text(f.template,'template')||'script';if(!['script','go','other'].includes(template))throw new Error('Choose script, go or other');if(f.folder)cwd=this.folder(f.folder);if(existsSync(path.join(cwd,name)))throw new Error('An extension folder with this name already exists');if(template!=='script')argv.push(`--precompiled=${template}`);argv.push('--',name);external();}
 else if(id==='extension exec'){const name=named('name','installed extension');const installed=this.read(['extension','list']).split('\n').some(line=>line.split('\t')[0]===`gh ${name}`);if(!installed)throw new Error('Select a currently installed extension');const values=f.arguments??[];if(!Array.isArray(values)||values.length>100)throw new Error('Add at most 100 separate argument values');argv.push('--',name,...values.map(value=>text(value,'argument',true)));external();warnings.push('Arguments are forwarded as separate values. No terminal input is available; interactive extensions may fail.');}
 else if(id==='extension install'){let repository=text(f.repository,'repository',true);if(repository==='.')cwd=this.folder(f.folder);else if(!/^[\w.-]+\/gh-[\w.-]+$/.test(repository))throw new Error('Choose an OWNER/gh-extension repository or a local folder');if(f.pin)argv.push(`--pin=${text(f.pin,'release tag or commit')}`);if(f.force)argv.push('--force');argv.push('--',repository);external();}
 else if(id==='extension upgrade'){if(f.all){if(f.name)throw new Error('Choose one extension or all extensions');argv.push('--all');}else argv.push('--',named('name'));if(f.dryRun)argv.splice(2,0,'--dry-run');if(f.force)argv.splice(2,0,'--force');external();}
 else if(id==='extension remove')argv.push('--',named('name'));
 else if(id==='alias import'){const file=realpathSync(text(f.file,'alias YAML file',true));if(!this.files.has(file))throw new Error('Choose the YAML file with the native import picker');fingerprints.push(fingerprint(file));if(f.clobber)argv.push('--clobber');argv.push('--',file);warnings.push('The entire reviewed YAML file is imported by GitHub CLI. Shell aliases can execute arbitrary programs when invoked. Existing aliases may be replaced only with Overwrite selected.');external();}
 else if(id==='alias set'){const name=named('name','alias name'),commandId=text(f.commandId,'built-in command',true);const command=this.catalog.commands.find(c=>c.id===commandId);if(!command||command.interactive||workflowCommandIds.includes(command.id as typeof workflowCommandIds[number])||command.group==='auth')throw new Error('Choose an ordinary built-in command');const values=f.arguments??[];if(!Array.isArray(values)||values.length>100)throw new Error('Use separate argument values');const quote=(value:string)=>"'"+value.replaceAll("'","'\\''")+"'";const expansion=[...command.path,...values.map(value=>text(value,'argument',true))].map(quote).join(' ');argv.push('--',name,expansion);warnings.push('Aliases are local configuration. This editor creates a regular gh alias; imported shell aliases remain visibly marked in the alias list.');}
 else if(id==='alias delete'){if(f.all){if(f.name)throw new Error('Choose one alias or all aliases');argv.push('--all');}else argv.push('--',named('name'));}
 else if(id.startsWith('codespace ')){const codespace=named('codespace');argv.push(`--codespace=${codespace}`);
 if(id==='codespace ssh'){const mode=text(f.mode,'SSH action')||'config';if(mode==='config')argv.push('--config');else if(mode==='diagnostic'){const profiles:Record<string,string[]>={system:['uname','-a'],directory:['pwd'],storage:['df','-h'],git:['git','status','--short'],processes:['ps','aux'],memory:['free','-h'],files:['ls','-la'],identity:['id']};const profile=text(f.profile,'diagnostic profile',true);if(!profiles[profile])throw new Error('Choose a supported diagnostic profile');argv.push('--','-T',...profiles[profile]);warnings.push('SSH may generate a key pair in your user SSH directory and uses your trusted SSH configuration. The remote diagnostic command is fixed by the selected profile.');}else throw new Error('Choose SSH configuration or a diagnostic profile');external();}
 if(id==='codespace code'){if(f.web)argv.push('--web');if(f.insiders)argv.push('--insiders');external();warnings.push(f.web?'Opens the Codespace web editor with your configured browser.':'Requires Visual Studio Code and its code launcher on PATH. The CLI reports a missing launcher.');}
 if(id==='codespace jupyter'){external();warnings.push('Starts a JupyterLab forwarding session and opens the configured browser. JupyterLab must be installed in the Codespace. Cancel stops the direct CLI process.');timeoutMs=3600000;}
 if(id==='codespace cp'){const direction=text(f.direction,'copy direction',true);if(!['upload','download'].includes(direction))throw new Error('Choose upload or download');const local=text(f.localPath,'local path',true),remote=text(f.remotePath,'remote path',true);if(!remote.startsWith('/')||/[\0\r\n]/.test(remote))throw new Error('Remote path starts with / and is copied literally');const destination=path.resolve(cwd,local);let ancestor=destination;while(!existsSync(ancestor))ancestor=path.dirname(ancestor);const root=realpathSync(ancestor);if(root!==this.workspace&&!root.startsWith(this.workspace+path.sep))throw new Error('Local copy path must stay inside the approved workspace');if(direction==='upload'&&!existsSync(destination))throw new Error('Choose an existing local source');if(f.recursive)argv.push('--recursive');argv.push('--',...(direction==='upload'?[destination,`remote:${remote}`]:[`remote:${remote}`,destination]));warnings.push('Copy can replace destination files. Remote expansion is disabled; paths are literal.');external();}
 if(id==='codespace ports forward'){const mappings=f.mappings;if(!Array.isArray(mappings)||!mappings.length||mappings.length>20)throw new Error('Add 1 to 20 port mappings');const values=mappings.map(item=>{if(!item||typeof item!=='object'||Object.keys(item).some(k=>!['remote','local'].includes(k)))throw new Error('Use remote and local port controls');return `${port(item.remote)}:${port(item.local)}`;});if(new Set(values.map(value=>value.split(':')[1])).size!==values.length)throw new Error('Each local port must be distinct');argv.push('--',...values);timeoutMs=3600000;warnings.push('Forwarding runs until cancelled or the one-hour session limit is reached. The selected local ports must be free.');}
 if(id==='codespace ports visibility'){const rows=f.visibility;if(!Array.isArray(rows)||!rows.length||rows.length>20)throw new Error('Add 1 to 20 port visibility rows');argv.push('--',...rows.map(row=>{if(!row||typeof row!=='object'||Object.keys(row).some(k=>!['port','visibility'].includes(k))||!['public','private','org'].includes(row.visibility))throw new Error('Select public, private or org visibility');if(row.visibility==='public')warnings.push('Public ports allow anyone with the forwarding URL to access the service.');return `${port(row.port)}:${row.visibility}`;}));}}
 else if(id==='copilot'){if(!this.copilot)throw new Error('Copilot CLI is not installed. Install the official CLI and refresh; no download occurs here.');executable=this.copilot;const mode=text(f.mode,'Copilot action')||'help';if(mode==='help')argv=['--help'];else if(mode==='version')argv=['--version'];else if(mode==='prompt'){const prompt=text(f.prompt,'prompt',true,16000);argv=['-p',prompt,'--deny-tool','*'];warnings.push('Noninteractive Copilot prompt denies all tools. Your Copilot account and network connection are required; local CLI versions can reject unsupported flags.');}else throw new Error('Choose help, version or a noninteractive prompt');external();}
 else if(id==='preview prompter')throw new Error('The native preview requires an interactive PTY and is outside the current desktop scope. Use the Material prompt preview in this panel.');
 const review:CliWorkflowReview={kind:'review',reviewId:randomUUID(),commandId:id,argv:argv.map(redact),executable:path.basename(executable),warnings,expiresAt:new Date(this.now()+TTL).toISOString(),description:this.catalog.commands.find(c=>c.id===id)?.description||id};for(const [key,value] of this.reviews)if(Date.parse(value.review.expiresAt)<this.now())this.reviews.delete(key);if(this.reviews.size>=32)this.reviews.delete(this.reviews.keys().next().value!);this.reviews.set(review.reviewId,{review,argv,executable,cwd,fingerprints,timeoutMs});return structuredClone(review);}
}
