import {mkdir,readFile,lstat,statfs} from 'node:fs/promises';import {join,basename,extname} from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {atomicJson} from './ollama-manager';import {ConverterDiscovery,sourceIdentifier,sourceQuery,type PrivateSourceEntry} from './converter-discovery';
import type {SourceReview,SourceScope,SourceAdmission} from '../shared/converter-discovery';import type {ConverterOptions} from '../shared/bundled-engines';import type {ConverterAdapter,FileGrant} from '../shared/local-tools';
interface PrivateReview extends SourceReview {destination:string;seal:string;at:number}
const scopeFrom=(value:unknown):SourceScope=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Choose a source selection scope');const scope=value as Record<string,unknown>;if(scope.kind==='all'&&Object.keys(scope).length===1)return {kind:'all'};if(scope.kind==='range'&&Object.keys(scope).length===3&&Number.isSafeInteger(scope.from)&&Number.isSafeInteger(scope.to)&&Number(scope.from)>=1&&Number(scope.to)>=Number(scope.from))return {kind:'range',from:Number(scope.from),to:Number(scope.to)};if(scope.kind==='selected'&&Object.keys(scope).length===2&&Array.isArray(scope.ids)&&scope.ids.length>0&&scope.ids.length<=250)return {kind:'selected',ids:[...new Set(scope.ids.map(sourceIdentifier))]};throw new Error('Use all matches, a positive ordinal range or 1 to 250 selected opaque source IDs');};
/** Stream reviewed selections to the durable queue, holding at most one granted source. */
export class ConverterSourceAdmission {
 private active?:{state:SourceAdmission;cancel:boolean};private reviewing=false;private admitting=false;private stopped=false;private cancellationEpoch=0;
 constructor(private directory:string,private discovery:ConverterDiscovery,private registry:()=>Promise<ConverterAdapter[]>,private inspect:(discovery:string,version:string,item:PrivateSourceEntry)=>Promise<FileGrant>,private pickOutput:()=>Promise<string|null>,private enqueue:(grant:FileGrant,adapter:ConverterAdapter,options:ConverterOptions,destination:string)=>Promise<void>){ }
 activeJobs(){return this.reviewing||this.admitting||!!this.active;}
 cancelReview(){this.cancellationEpoch++;return {cancelRequested:true};}
 cancelAll(){if(this.active)this.active.cancel=true;this.cancellationEpoch++;}
 dispose(){this.stopped=true;this.cancelAll();}
 async review(payload:Record<string,unknown>){if(this.reviewing||this.activeJobs())throw new Error('Another source review or queue admission is active');this.reviewing=true;const epoch=this.cancellationEpoch;try{
  const discovery=await this.discovery.complete(payload),scope=scopeFrom(payload.scope),query=sourceQuery(payload),adapter=(await this.registry()).find(item=>item.id===payload.adapter);if(scope.kind==='range'&&scope.to>discovery.indexed)throw new Error('Range exceeds this reviewed source index');
  if(!adapter?.enabled||['pdf-merge','pdf-inspect','zip-create','7z-create','7z-zip'].includes(adapter.id))throw new Error('Choose an enabled single-source adapter. Multi-source merge and archive operations use the finite selected-file workflow.');
  const options=(payload.options??{})as ConverterOptions;if(!options||typeof options!=='object'||Array.isArray(options)||JSON.stringify(options).length>16000||options.password||options.encryption&&options.encryption!=='none')throw new Error('Reviewed bulk queue options must be bounded and cannot include passwords or encryption');
  let count=0;const preview:string[]=[];for await(const {item} of this.discovery.matching({...query,id:discovery.id,version:discovery.version},scope,{cancel:()=>this.stopped||epoch!==this.cancellationEpoch})){count++;if(preview.length<8)preview.push(item.name);}
  if(!count)throw new Error('No source matches this exact selection and query');
  const destination=await this.pickOutput();if(this.stopped||epoch!==this.cancellationEpoch)throw new Error('Source review cancelled');if(!destination)return {cancelled:true};const info=await lstat(destination);if(!info.isDirectory()||info.isSymbolicLink())throw new Error('Choose a regular output directory');const free=await statfs(destination);if(free.bavail*free.bsize<128*1024*1024)throw new Error('Output directory requires at least 128 MiB free for bounded conversions');
  const id=randomUUID(),publicReview:SourceReview={id,discovery:discovery.id,version:discovery.version,count,adapter:adapter.id,options,destinationName:basename(destination),preview,scope,query,disclosures:['Each matching source is revalidated, inspected and admitted separately; incompatible or changed files have failed outcomes.','Outputs receive ordinal-based unique new names. Existing files are never overwritten.','The frozen query and complete discovery version bind this review. Cancelling admission preserves queued records already admitted; pause or cancel those through conversion history.','Only one source grant is materialized at a time; source bytes are not retained across queue records.']},seal=createHash('sha256').update(JSON.stringify(publicReview)).digest('hex');await mkdir(join(this.directory,'reviews'),{recursive:true,mode:0o700});await atomicJson(join(this.directory,'reviews',id+'.json'),{...publicReview,destination,seal,at:Date.now()});return publicReview;
 }finally{this.reviewing=false;}}
 async admit(payload:Record<string,unknown>){if(this.activeJobs())throw new Error('Another source review or admission is active');if(this.stopped)throw new Error('Source admission service is shutting down');if(payload.confirmed!==true)throw new Error('Review and confirm this exact source selection');this.admitting=true;try{const id=sourceIdentifier(payload.review),file=join(this.directory,'reviews',id+'.json');if((await lstat(file)).size>128000)throw new Error('Source review exceeds its byte bound');const review=JSON.parse(await readFile(file,'utf8'))as PrivateReview;const {destination:_destination,seal:_seal,at:_at,...publicReview}=review;if(review.id!==id||createHash('sha256').update(JSON.stringify(publicReview)).digest('hex')!==review.seal||Date.now()-review.at>10*60*1000)throw new Error('Source review expired or changed. Review the selection again');await this.discovery.complete({id:review.discovery,version:review.version});const adapter=(await this.registry()).find(item=>item.id===review.adapter);if(!adapter?.enabled)throw new Error('Reviewed adapter is no longer enabled');const state:SourceAdmission={id,status:'running',admitted:0,failed:0,skipped:0,total:review.count};await mkdir(join(this.directory,'admissions',id),{recursive:true,mode:0o700});const journal=join(this.directory,'admissions',id,'state.json');try{await lstat(journal);throw new Error('This source review has already been admitted; review again for a new batch');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}await atomicJson(journal,state);const live={state,cancel:false};this.active=live;void this.pump(live,review,adapter);return {...state};}finally{this.admitting=false;}}
 private async pump(live:{state:SourceAdmission;cancel:boolean},review:PrivateReview,adapter:ConverterAdapter){const folder=join(this.directory,'admissions',review.id);try{for await(const {item} of this.discovery.matching({...review.query,id:review.discovery,version:review.version},review.scope,{cancel:()=>live.cancel||this.stopped})){if(live.cancel||this.stopped){live.state.status='cancelled';break;}try{const grant=await this.inspect(review.discovery,review.version,item);if(!grant.compatible.includes(adapter.id))throw new Error('Inspected source type is incompatible with the reviewed adapter');const stem=basename(grant.name,extname(grant.name)).replace(/[\\/\x00-\x1f<>:"|?*]/g,'_').slice(0,100)||'source',destination=join(review.destination,item.ordinal+'-'+stem+'-converted.'+adapter.target);await this.enqueue(grant,adapter,review.options,destination);live.state.admitted++;await atomicJson(join(folder,String(item.ordinal)+'.json'),{source:item.name,id:item.id,status:'queued'});}catch(error){live.state.failed++;await atomicJson(join(folder,String(item.ordinal)+'.json'),{source:item.name,id:item.id,status:'failed',error:(error as NodeJS.ErrnoException).code?'Source is no longer available':error instanceof Error?error.message:'Source admission failed'});}await atomicJson(join(folder,'state.json'),live.state);await new Promise<void>(resolve=>setImmediate(resolve));}if(live.state.status==='running')live.state.status=live.cancel?'cancelled':'completed';}catch(error){live.state.status=live.cancel||this.stopped?'cancelled':'failed';live.state.error=(error as NodeJS.ErrnoException).code?'Source admission storage or source index became unavailable':error instanceof Error?error.message:'Admission failed';}finally{await atomicJson(join(folder,'state.json'),live.state).catch(()=>{});this.active=undefined;}}
 async status(payload:Record<string,unknown>){const id=sourceIdentifier(payload.id);if(this.active?.state.id===id)return {...this.active.state,status:'running' as const};const file=join(this.directory,'admissions',id,'state.json');if((await lstat(file)).size>16000)throw new Error('Admission journal exceeds its byte bound');const state=JSON.parse(await readFile(file,'utf8'))as SourceAdmission;if(state.status==='running'){state.status='failed';state.error='Application restarted during admission. Existing queue records remain recoverable; review the remaining selection again.';await atomicJson(file,state);}return state;}
 async cancel(payload:Record<string,unknown>){const id=sourceIdentifier(payload.id);if(this.active?.state.id!==id)throw new Error('Source admission is no longer active');this.active.cancel=true;return {cancelRequested:true};}
}
