import {mkdir,lstat,realpath,opendir,readFile,statfs} from 'node:fs/promises';import {join,basename,relative,resolve,sep} from 'node:path';import {randomUUID} from 'node:crypto';import type {Dir} from 'node:fs';
import {atomicJson} from './ollama-manager';import {catalogRegex} from './catalog-query';import {FILE_LIMIT} from './local-tools-codecs';
import type {SourceDiscovery,SourceEntry,SourcePage,SourceQuery,SourceScope} from '../shared/converter-discovery';
interface Frame {relative:string;seen:number;ino:number;dev:number;mtime:number}
interface Manifest extends SourceDiscovery {root:string;cursor:Frame[]}
export interface PrivateSourceEntry extends SourceEntry {relative:string;mtime:number;ino:number;dev:number}
export function sourceIdentifier(value:unknown){if(typeof value!=='string'||!/^[a-f0-9-]{36}$/.test(value))throw new Error('Invalid opaque discovery identifier');return value;}
export function sourceQuery(payload:Record<string,unknown>):SourceQuery {const query=payload.query??'',regex=payload.regex??false,pattern=payload.pattern??'',flags=payload.flags??'i';if(typeof query!=='string'||query.length>1000||typeof regex!=='boolean'||typeof pattern!=='string'||pattern.length>500||typeof flags!=='string'||flags.length>8)throw new Error('Invalid bounded source query');return {query,regex,pattern,flags};}
function publicDiscovery(manifest:Manifest):SourceDiscovery {const {root:_root,cursor:_cursor,...publicState}=manifest;return publicState;}
/** Recheck every directory segment and the actual resolved target; never follow a link outside the grant. */
export async function verifyFolderSource(root:string,item:PrivateSourceEntry){const parts=item.relative.split(/[\\/]/);if(!parts.length||parts.length>17||parts.some(p=>!p||p==='.'||p==='..')||item.relative.length>2048)throw new Error('Invalid relative source record');const rootDetails=await lstat(root);if(!rootDetails.isDirectory()||rootDetails.isSymbolicLink())throw new Error('Granted source directory is no longer a regular directory');let current=root;for(let i=0;i<parts.length;i++){current=join(current,parts[i]);const details=await lstat(current);if(details.isSymbolicLink()||i<parts.length-1&&!details.isDirectory()||i===parts.length-1&&(!details.isFile()||details.size!==item.bytes||details.mtimeMs!==item.mtime||details.ino!==item.ino||details.dev!==item.dev))throw new Error('Source changed since folder discovery. Choose the folder again.');}const resolved=await realpath(current),distance=relative(root,resolved);if(distance.startsWith('..'+sep)||distance==='..'||resolve(root,distance)!==resolved||!distance)throw new Error('Source escaped its granted directory');return resolved;}

/** Disk-backed ordinal index and finite-depth restart cursor; no whole-tree path array. */
export class ConverterDiscovery {
 private scans=new Map<string,{manifest:Manifest;stop:boolean;cancel:boolean}>();private stopped=false;private pageRequests=0;
 constructor(private directory:string,private pick:()=>Promise<string|null>,private excludedRoots:string[]=[]){ }
 private folder(id:unknown){return join(this.directory,sourceIdentifier(id));}
 private async manifest(id:unknown):Promise<Manifest>{const key=sourceIdentifier(id),live=this.scans.get(key);if(live)return live.manifest;const file=join(this.folder(key),'manifest.json');if((await lstat(file)).size>128000)throw new Error('Discovery cursor exceeds its byte limit');const manifest=JSON.parse(await readFile(file,'utf8'))as Manifest;if(manifest.id!==key||!Array.isArray(manifest.cursor)||manifest.cursor.length>16||!Number.isSafeInteger(manifest.indexed)||manifest.indexed<0)throw new Error('Invalid private discovery cursor');if(manifest.state==='scanning')manifest.state='paused';return manifest;}
 async start(){if(this.stopped)throw new Error('Discovery service is shutting down');if(this.scans.size>=1)throw new Error('Pause the active discovery before selecting another folder');const root=await this.pick();if(!root)return {cancelled:true};const details=await lstat(root);if(!details.isDirectory()||details.isSymbolicLink())throw new Error('Choose a regular directory, not a symbolic link');const canonical=await realpath(root),id=randomUUID();await mkdir(join(this.folder(id),'entries'),{recursive:true,mode:0o700});await mkdir(join(this.folder(id),'by-id'),{mode:0o700});const manifest:Manifest={id,version:randomUUID(),name:basename(canonical),root:canonical,state:'paused',indexed:0,skipped:0,cursor:[{relative:'',seen:0,ino:details.ino,dev:details.dev,mtime:details.mtimeMs}]};await atomicJson(join(this.folder(id),'manifest.json'),manifest);await atomicJson(join(this.directory,'last.json'),{id});return this.resume({id});}
 async latest(){try{const last=JSON.parse(await readFile(join(this.directory,'last.json'),'utf8'));return publicDiscovery(await this.manifest(last.id));}catch{return undefined;}}
 async status(payload:Record<string,unknown>){return publicDiscovery(await this.manifest(payload.id));}
 async resume(payload:Record<string,unknown>){const manifest=await this.manifest(payload.id);if(this.stopped)throw new Error('Discovery service is shutting down');if(manifest.state==='complete'||manifest.state==='cancelled'||manifest.state==='failed')return publicDiscovery(manifest);if(this.scans.has(manifest.id))return publicDiscovery(manifest);if(this.scans.size>=1)throw new Error('Only one folder discovery can run at a time');manifest.state='scanning';const state={manifest,stop:false,cancel:false};this.scans.set(manifest.id,state);void this.scan(state);return publicDiscovery(manifest);}
 async pause(payload:Record<string,unknown>,cancel=false){const manifest=await this.manifest(payload.id),state=this.scans.get(manifest.id);if(state){state.stop=true;state.cancel=cancel;}else if(manifest.state==='paused'){manifest.state=cancel?'cancelled':'paused';await atomicJson(join(this.folder(manifest.id),'manifest.json'),manifest);}return {stopRequested:!!state,discovery:publicDiscovery(manifest)};}
 activeJobs(){return this.scans.size>0;}
 cancelAll(){for(const state of this.scans.values())state.stop=true;}
 dispose(){this.stopped=true;this.cancelAll();}
 private async scan(state:{manifest:Manifest;stop:boolean;cancel:boolean}){const manifest=state.manifest,opened=new Map<Frame,Dir>();try{
  while(manifest.cursor.length&&!state.stop&&!this.stopped){const frame=manifest.cursor.at(-1)!,directory=join(manifest.root,frame.relative),details=await lstat(directory);if(!details.isDirectory()||details.isSymbolicLink()||details.ino!==frame.ino||details.dev!==frame.dev||details.mtimeMs!==frame.mtime)throw new Error('A source directory changed during discovery. Select it again to create a new reviewed version');let handle=opened.get(frame);if(!handle){handle=await opendir(directory);opened.set(frame,handle);for(let i=0;i<frame.seen;i++)if(!await handle.read())throw new Error('Directory cursor changed during restart');}
   const canonical=await realpath(directory),distance=relative(manifest.root,canonical);if(distance==='..'||distance.startsWith('..'+sep))throw new Error('Directory escaped its granted root');
   const entry=await handle.read();if(!entry){await handle.close();opened.delete(frame);manifest.cursor.pop();await atomicJson(join(this.folder(manifest.id),'manifest.json'),manifest);continue;}
   const childRelative=frame.relative?join(frame.relative,entry.name):entry.name,childPath=join(manifest.root,childRelative),info=await lstat(childPath);
   if(info.isSymbolicLink()||childRelative.length>2048||this.excludedRoots.some(root=>{const distance=relative(root,childPath);return distance===''||distance!=='..'&&!distance.startsWith('..'+sep)&&!distance.startsWith(sep);})){manifest.skipped++;frame.seen++;}
   else if(info.isDirectory()){frame.seen++;if(manifest.cursor.length>=16)manifest.skipped++;else manifest.cursor.push({relative:childRelative,seen:0,ino:info.ino,dev:info.dev,mtime:info.mtimeMs});}
   else if(!info.isFile()||info.size>FILE_LIMIT){manifest.skipped++;frame.seen++;}
   else{const id=randomUUID(),ordinal=manifest.indexed+1,item:PrivateSourceEntry={id,ordinal,name:childRelative.split(sep).join('/'),relative:childRelative,bytes:info.size,mtime:info.mtimeMs,ino:info.ino,dev:info.dev};await atomicJson(join(this.folder(manifest.id),'entries',String(ordinal)+'.json'),item);await atomicJson(join(this.folder(manifest.id),'by-id',id+'.json'),{ordinal});manifest.indexed=ordinal;frame.seen++;}
   await atomicJson(join(this.folder(manifest.id),'manifest.json'),manifest);
   if((manifest.indexed+manifest.skipped)%64===0){const space=await statfs(this.directory);if(space.bavail*space.bsize<64*1024*1024)throw new Error('Discovery storage has less than 64 MiB free. Clear unused private history before selecting the folder again.');await new Promise<void>(resolve=>setImmediate(resolve));}
  }manifest.state=state.cancel?'cancelled':manifest.cursor.length?'paused':'complete';
 }catch(error){manifest.state='failed';manifest.error=(error as NodeJS.ErrnoException).code?'Source enumeration failed because a directory or file became unavailable':error instanceof Error?error.message:'Source enumeration failed';}
 finally{for(const handle of opened.values())await handle.close().catch(()=>{});await atomicJson(join(this.folder(manifest.id),'manifest.json'),manifest).catch(()=>{});this.scans.delete(manifest.id);}}
 async entry(discovery:unknown,entryId:unknown,version:unknown){const manifest=await this.manifest(discovery);if(manifest.version!==version)throw new Error('Source discovery version changed; review again');const record=JSON.parse(await readFile(join(this.folder(discovery),'by-id',sourceIdentifier(entryId)+'.json'),'utf8')),row=await this.ordinal(manifest,record.ordinal);if(row.item.id!==entryId)throw new Error('Source index entry changed after an interrupted discovery');return row;}
 private async ordinal(manifest:Manifest,ordinal:number){if(!Number.isSafeInteger(ordinal)||ordinal<1||ordinal>manifest.indexed)throw new Error('Source ordinal is outside the discovery');const file=join(this.folder(manifest.id),'entries',String(ordinal)+'.json');if((await lstat(file)).size>16000)throw new Error('Source index record exceeds its bound');const item=JSON.parse(await readFile(file,'utf8'))as PrivateSourceEntry;if(item.ordinal!==ordinal||typeof item.relative!=='string'||typeof item.name!=='string'||item.name.length>2048||!Number.isSafeInteger(item.bytes)||item.bytes<0||item.bytes>FILE_LIMIT)throw new Error('Invalid source index record');sourceIdentifier(item.id);return {manifest,item};}
 async *matching(payload:Record<string,unknown>,scope:SourceScope={kind:'all'},control:{deadline?:number;cancel?:()=>boolean}={}):AsyncGenerator<{manifest:Manifest;item:PrivateSourceEntry}>{const manifest=await this.manifest(payload.id);if(payload.version!==manifest.version)throw new Error('Source discovery version changed; refresh the page');const query=sourceQuery(payload);if(query.regex)await catalogRegex([],query.pattern||query.query,query.flags);const ids=scope.kind==='selected'?new Set(scope.ids):undefined,excluded=scope.kind==='all'?new Set(scope.excluded??[]):undefined;let batch:Array<{manifest:Manifest;item:PrivateSourceEntry}>=[];const check=()=>{if(control.cancel?.())throw new Error('Source selection search cancelled');if(control.deadline&&Date.now()>control.deadline)throw new Error('Source page search exceeded its scan budget. Narrow the query or use reviewed streaming admission.');};
  const accept=async()=>{const texts=batch.map(row=>row.item.name),matches=query.regex?await catalogRegex(texts,query.pattern||query.query,query.flags):texts.map(text=>text.toLocaleLowerCase().includes(query.query.toLocaleLowerCase()));const selected=batch.filter((_,i)=>matches[i]);batch=[];return selected;};
  if(ids){for(const id of ids){check();const row=await this.entry(manifest.id,id,manifest.version);batch.push(row);if(batch.length===40)for(const selected of await accept())yield selected;}}
  else{const indexed=manifest.indexed,start=scope.kind==='range'?scope.from:1,end=scope.kind==='range'?Math.min(scope.to,indexed):indexed;for(let ordinal=start;ordinal<=end;ordinal++){check();const row=await this.ordinal(manifest,ordinal);if(excluded?.has(row.item.id))continue;batch.push(row);if(batch.length===40)for(const selected of await accept())yield selected;}}for(const selected of await accept())yield selected;
 }
 async page(payload:Record<string,unknown>):Promise<SourcePage>{if(this.pageRequests>=2)throw new Error('Two source page requests are active. Wait for the current search before retrying.');this.pageRequests++;try{
  const manifest=await this.manifest(payload.id),query=sourceQuery(payload),page=Number(payload.page??1);if(payload.version!==undefined&&payload.version!==manifest.version)throw new Error('Source discovery version changed; refresh the folder');if(!Number.isSafeInteger(page)||page<1||page>1000000)throw new Error('Invalid source page');let after=0;
  if(payload.cursor){const file=join(this.folder(manifest.id),'cursors',sourceIdentifier(payload.cursor)+'.json');if((await lstat(file)).size>16000)throw new Error('Source page cursor exceeds its byte limit');const cursor=JSON.parse(await readFile(file,'utf8'));if(cursor.version!==manifest.version||JSON.stringify(cursor.query)!==JSON.stringify(query)||cursor.page!==page||!Number.isSafeInteger(cursor.after)||cursor.after<0||cursor.after>manifest.indexed)throw new Error('Source page cursor does not match this exact query and version');after=cursor.after;}
  else if(!query.query&&!query.regex)after=(page-1)*40;
  const items:SourceEntry[]=[];let matched=0,hasNext=false,lastOrdinal=after;const deadline=Date.now()+15000;
  if(after<manifest.indexed)for await(const {item} of this.matching({...query,id:manifest.id,version:manifest.version},{kind:'range',from:after+1,to:manifest.indexed},{deadline})){
   if(Date.now()>deadline)throw new Error('Source page search exceeded its 15-second scan budget. Narrow the query or use the reviewed streaming selection.');matched++;
   if(!payload.cursor&&(query.query||query.regex)&&matched<=(page-1)*40)continue;
   if(items.length===40){hasNext=true;break;}items.push({id:item.id,ordinal:item.ordinal,name:item.name,bytes:item.bytes});lastOrdinal=item.ordinal;
  }
  let nextCursor:string|undefined;if(hasNext){nextCursor=randomUUID();await mkdir(join(this.folder(manifest.id),'cursors'),{recursive:true,mode:0o700});await atomicJson(join(this.folder(manifest.id),'cursors',nextCursor+'.json'),{version:manifest.version,query,after:lastOrdinal,page:page+1});}
  return {discovery:publicDiscovery(manifest),items,page,hasNext,matched,query,...nextCursor?{nextCursor}:{}};
 }finally{this.pageRequests--;}}
 async complete(payload:Record<string,unknown>){const manifest=await this.manifest(payload.id);if(manifest.version!==payload.version||manifest.state!=='complete')throw new Error('Wait for a completed unchanged discovery version before reviewing bulk admission');return publicDiscovery(manifest);}
}
