import {mkdir,readFile,lstat,statfs,opendir} from 'node:fs/promises';import {join,basename,extname} from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {catalogRegex} from './catalog-query';
import {atomicJson} from './ollama-manager';import {ConverterDiscovery,sourceIdentifier,sourceQuery,type PrivateSourceEntry} from './converter-discovery';
import type {SourceReview,SourceScope,SourceAdmission,SourceAdmissionOutcome,SourceAdmissionPage} from '../shared/converter-discovery';import type {ConverterOptions} from '../shared/bundled-engines';import type {ConverterAdapter,FileGrant} from '../shared/local-tools';
interface PrivateReview extends SourceReview {destination:string;seal:string;at:number}
interface AdmissionJournal {id:string;ordinal:number;source:string;status:'preparing'|'queued'|'failed';job?:string;error?:string}
interface ActiveAdmission {state:SourceAdmission;cancel:boolean;pause:boolean}
const scopeFrom=(value:unknown):SourceScope=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Choose a source selection scope');const scope=value as Record<string,unknown>;if(scope.kind==='all'&&Object.keys(scope).length===1)return {kind:'all'};if(scope.kind==='all'&&Object.keys(scope).length===2&&Array.isArray(scope.excluded)&&scope.excluded.length<=250)return {kind:'all',excluded:[...new Set(scope.excluded.map(sourceIdentifier))]};if(scope.kind==='range'&&Object.keys(scope).length===3&&Number.isSafeInteger(scope.from)&&Number.isSafeInteger(scope.to)&&Number(scope.from)>=1&&Number(scope.to)>=Number(scope.from))return {kind:'range',from:Number(scope.from),to:Number(scope.to)};if(scope.kind==='selected'&&Object.keys(scope).length===2&&Array.isArray(scope.ids)&&scope.ids.length>0&&scope.ids.length<=250)return {kind:'selected',ids:[...new Set(scope.ids.map(sourceIdentifier))]};throw new Error('Use all matches, a positive ordinal range or 1 to 250 selected opaque source IDs');};
/** Stream reviewed selections to the durable queue, holding at most one granted source. */
export class ConverterSourceAdmission {
 private active?:ActiveAdmission;private reviewing=false;private admitting=false;private stopped=false;private cancellationEpoch=0;private pageRequests=0;private creatingId?:string;
 constructor(private directory:string,private discovery:ConverterDiscovery,private registry:()=>Promise<ConverterAdapter[]>,private inspect:(discovery:string,version:string,item:PrivateSourceEntry)=>Promise<FileGrant>,private pickOutput:()=>Promise<string|null>,private enqueue:(grant:FileGrant,adapter:ConverterAdapter,options:ConverterOptions,destination:string,job:string)=>Promise<void>,private wasAdmitted:(job:string)=>Promise<boolean>){ }
 activeJobs(){return this.reviewing||this.admitting||!!this.active;}
 cancelReview(){this.cancellationEpoch++;return {cancelRequested:true};}
 cancelAll(){if(this.active)this.active.cancel=true;this.cancellationEpoch++;}
 dispose(){this.stopped=true;if(this.active)this.active.pause=true;this.cancellationEpoch++;}
 async review(payload:Record<string,unknown>){if(this.reviewing||this.activeJobs())throw new Error('Another source review or queue admission is active');this.reviewing=true;const epoch=this.cancellationEpoch;try{
  const discovery=await this.discovery.complete(payload),scope=scopeFrom(payload.scope),query=sourceQuery(payload),adapter=(await this.registry()).find(item=>item.id===payload.adapter);if(scope.kind==='range'&&scope.to>discovery.indexed)throw new Error('Range exceeds this reviewed source index');
  if(!adapter?.enabled||['pdf-merge','pdf-inspect','zip-create','7z-create','7z-zip'].includes(adapter.id))throw new Error('Choose an enabled single-source adapter. Multi-source merge and archive operations use the finite selected-file workflow.');
  const options=(payload.options??{})as ConverterOptions;if(!options||typeof options!=='object'||Array.isArray(options)||JSON.stringify(options).length>16000||options.password||options.encryption&&options.encryption!=='none')throw new Error('Reviewed bulk queue options must be bounded and cannot include passwords or encryption');
  let count=0;const preview:string[]=[];for await(const {item} of this.discovery.matching({...query,id:discovery.id,version:discovery.version},scope,{cancel:()=>this.stopped||epoch!==this.cancellationEpoch})){count++;if(preview.length<8)preview.push(item.name);}
  if(!count)throw new Error('No source matches this exact selection and query');
  const destination=await this.pickOutput();if(this.stopped||epoch!==this.cancellationEpoch)throw new Error('Source review cancelled');if(!destination)return {cancelled:true};const info=await lstat(destination);if(!info.isDirectory()||info.isSymbolicLink())throw new Error('Choose a regular output directory');const free=await statfs(destination);if(free.bavail*free.bsize<128*1024*1024)throw new Error('Output directory requires at least 128 MiB free for bounded conversions');
  const id=randomUUID(),publicReview:SourceReview={id,discovery:discovery.id,version:discovery.version,count,adapter:adapter.id,options,destinationName:basename(destination),preview,scope,query,disclosures:['Each matching source is revalidated, inspected and admitted separately; incompatible or changed files have failed outcomes.','Outputs receive ordinal-based unique new names. Existing files are never overwritten.','The frozen query and complete discovery version bind this review. Cancelling admission preserves queued records already admitted; pause or cancel those through conversion history.','Only one source grant is materialized at a time; source bytes are not retained across queue records.']},seal=createHash('sha256').update(JSON.stringify(publicReview)).digest('hex');await mkdir(join(this.directory,'reviews'),{recursive:true,mode:0o700});await atomicJson(join(this.directory,'reviews',id+'.json'),{...publicReview,destination,seal,at:Date.now()});return publicReview;
 }finally{this.reviewing=false;}}
 private async reviewed(id:string,expires:boolean){
  const file=join(this.directory,'reviews',id+'.json');if((await lstat(file)).size>128000)throw new Error('Source review exceeds its byte bound');
  const review=JSON.parse(await readFile(file,'utf8'))as PrivateReview,{destination:_destination,seal:_seal,at:_at,...publicReview}=review;
  if(review.id!==id||createHash('sha256').update(JSON.stringify(publicReview)).digest('hex')!==review.seal||expires&&Date.now()-review.at>10*60*1000)throw new Error('Source review expired or changed. Review the selection again');
  await this.discovery.complete({id:review.discovery,version:review.version});return review;
 }
 private async adapter(review:PrivateReview){const adapter=(await this.registry()).find(item=>item.id===review.adapter);if(!adapter?.enabled)throw new Error('Reviewed adapter is no longer enabled');return adapter;}
 async admit(payload:Record<string,unknown>){
  if(this.activeJobs())throw new Error('Another source review or admission is active');if(this.stopped)throw new Error('Source admission service is shutting down');if(payload.confirmed!==true)throw new Error('Review and confirm this exact source selection');this.admitting=true;
  try{const id=sourceIdentifier(payload.review);this.creatingId=id;const review=await this.reviewed(id,true),adapter=await this.adapter(review),state:SourceAdmission={id,status:'running',admitted:0,failed:0,skipped:0,total:review.count};
   await mkdir(join(this.directory,'admissions',id),{recursive:true,mode:0o700});const journal=join(this.directory,'admissions',id,'state.json');try{await lstat(journal);throw new Error('This source review has already been admitted; review again for a new batch');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
   await atomicJson(journal,state);await atomicJson(join(this.directory,'last-admission.json'),{id});const live:ActiveAdmission={state,cancel:false,pause:false};this.active=live;void this.pump(live,review,adapter);return {...state};
  }finally{this.admitting=false;this.creatingId=undefined;}
 }
 private async journal(id:string,ordinal:number):Promise<AdmissionJournal|undefined>{
  if(!Number.isSafeInteger(ordinal)||ordinal<1)throw new Error('Invalid admission source ordinal');const file=join(this.directory,'admissions',id,String(ordinal)+'.json');try{if((await lstat(file)).size>16000)throw new Error('Admission outcome exceeds its byte bound');const row=JSON.parse(await readFile(file,'utf8'))as AdmissionJournal;sourceIdentifier(row.id);if(row.ordinal!==undefined&&row.ordinal!==ordinal||!['preparing','queued','failed'].includes(row.status)||typeof row.source!=='string'||row.source.length>2048)throw new Error('Invalid admission outcome');if(row.job)sourceIdentifier(row.job);return {...row,ordinal};}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return;throw error;}
 }
 private async pump(live:ActiveAdmission,review:PrivateReview,adapter:ConverterAdapter){const folder=join(this.directory,'admissions',review.id);
  try{for await(const {item} of this.discovery.matching({...review.query,id:review.discovery,version:review.version},review.scope,{cancel:()=>live.cancel||live.pause||this.stopped})){
   if(live.cancel||live.pause||this.stopped)break;const previous=await this.journal(review.id,item.ordinal);if(previous&&previous.id!==item.id)throw new Error('Admission outcome no longer matches this source index');if(previous&&previous.status!=='preparing')continue;
   const job=previous?.job??randomUUID(),intent:AdmissionJournal={id:item.id,ordinal:item.ordinal,source:item.name,status:'preparing',job};await atomicJson(join(folder,String(item.ordinal)+'.json'),intent);
   try{if(!await this.wasAdmitted(job)){const grant=await this.inspect(review.discovery,review.version,item);if(!grant.compatible.includes(adapter.id))throw new Error('Inspected source type is incompatible with the reviewed adapter');const stem=basename(grant.name,extname(grant.name)).replace(/[\\/\x00-\x1f<>:"|?*]/g,'_').slice(0,100)||'source',destination=join(review.destination,item.ordinal+'-'+stem+'-converted.'+adapter.target);await this.enqueue(grant,adapter,review.options,destination,job);}
    await atomicJson(join(folder,String(item.ordinal)+'.json'),{...intent,status:'queued'});live.state.admitted++;
   }catch(error){live.state.failed++;await atomicJson(join(folder,String(item.ordinal)+'.json'),{...intent,status:'failed',error:(error as NodeJS.ErrnoException).code?'Source is no longer available':error instanceof Error?error.message:'Source admission failed'});}
   await atomicJson(join(folder,'state.json'),live.state);await new Promise<void>(resolve=>setImmediate(resolve));
  }live.state.status=live.cancel?'cancelled':live.pause||this.stopped?'paused':'completed';
  }catch(error){live.state.status=live.cancel?'cancelled':live.pause||this.stopped?'paused':'failed';live.state.error=live.state.status==='paused'?'Admission paused. Resume revalidates the remaining frozen source selection.':(error as NodeJS.ErrnoException).code?'Source admission storage or source index became unavailable':error instanceof Error?error.message:'Admission failed';}
  finally{await atomicJson(join(folder,'state.json'),live.state).catch(()=>{});this.active=undefined;}
 }
 async latest(){try{const file=join(this.directory,'last-admission.json');if((await lstat(file)).size>16000)throw new Error('Admission pointer exceeds its byte bound');return await this.status(JSON.parse(await readFile(file,'utf8')));}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return;throw error;}}
 async status(payload:Record<string,unknown>){
  const id=sourceIdentifier(payload.id);if(this.active?.state.id===id)return {...this.active.state,status:'running' as const};const file=join(this.directory,'admissions',id,'state.json');if((await lstat(file)).size>16000)throw new Error('Admission journal exceeds its byte bound');const state=JSON.parse(await readFile(file,'utf8'))as SourceAdmission;
  if(state.id!==id||!['running','paused','completed','cancelled','failed'].includes(state.status)||![state.admitted,state.failed,state.total].every(n=>Number.isSafeInteger(n)&&n>=0))throw new Error('Invalid admission state');
  if(state.status==='running'&&this.creatingId!==id){state.status='paused';state.error='Application restarted during admission. Resume revalidates remaining sources; previously queued jobs remain recoverable.';await atomicJson(file,state);}return state;
 }
 async pause(payload:Record<string,unknown>){const id=sourceIdentifier(payload.id);if(this.active?.state.id!==id)throw new Error('Source admission is no longer active');this.active.pause=true;return {pauseRequested:true};}
 async resume(payload:Record<string,unknown>){
  if(this.activeJobs()||this.stopped)throw new Error('Wait for active source work before resuming admission');this.admitting=true;const epoch=this.cancellationEpoch;
  try{const id=sourceIdentifier(payload.id),state=await this.status({id});if(state.status!=='paused')throw new Error('Only a paused source admission can resume');this.creatingId=id;const review=await this.reviewed(id,false),adapter=await this.adapter(review);state.admitted=0;state.failed=0;state.status='running';delete state.error;
   let visited=0;for await(const entry of await opendir(join(this.directory,'admissions',id))){if(this.stopped||epoch!==this.cancellationEpoch)throw new Error('Source admission recovery cancelled');if(!/^[1-9][0-9]*\.json$/.test(entry.name))continue;const row=await this.journal(id,Number(entry.name.slice(0,-5)));if(row?.status==='queued')state.admitted++;if(row?.status==='failed')state.failed++;if(++visited%64===0)await new Promise<void>(resolve=>setImmediate(resolve));}
   await atomicJson(join(this.directory,'admissions',id,'state.json'),state);const live:ActiveAdmission={state,cancel:false,pause:false};this.active=live;void this.pump(live,review,adapter);return {...state};
  }finally{this.admitting=false;this.creatingId=undefined;}
 }
 async page(payload:Record<string,unknown>):Promise<SourceAdmissionPage>{if(this.pageRequests>=2)throw new Error('Two admission outcome searches are active. Wait before retrying.');this.pageRequests++;try{return await this.pageRead(payload);}finally{this.pageRequests--;}}
 private async pageRead(payload:Record<string,unknown>):Promise<SourceAdmissionPage>{
  const id=sourceIdentifier(payload.id),page=Number(payload.page??1),query=sourceQuery(payload),status=String(payload.status??'all');if(!Number.isSafeInteger(page)||page<1||page>1000000)throw new Error('Invalid admission outcome page');if(!['all','pending','queued','failed'].includes(status))throw new Error('Unsupported admission outcome filter');await this.status({id});if(query.regex)await catalogRegex([],query.pattern||query.query,query.flags);
  const items:SourceAdmissionOutcome[]=[];let matched=0,hasNext=false;const deadline=Date.now()+15000;let batch:SourceAdmissionOutcome[]=[];
  const consume=async()=>{const texts=batch.map(row=>row.source+' '+(row.error??'')),matches=query.regex?await catalogRegex(texts,query.pattern||query.query,query.flags):texts.map(text=>text.toLocaleLowerCase().includes(query.query.toLocaleLowerCase()));for(let i=0;i<batch.length;i++){if(!matches[i])continue;if(matched++<(page-1)*40)continue;if(items.length===40){hasNext=true;break;}items.push(batch[i]);}batch=[];};
  for await(const entry of await opendir(join(this.directory,'admissions',id))){if(Date.now()>deadline)throw new Error('Admission outcome search exceeded its fifteen-second budget. Narrow the query.');if(!/^[1-9][0-9]*\.json$/.test(entry.name))continue;const row=await this.journal(id,Number(entry.name.slice(0,-5)));if(!row)continue;const outcome:SourceAdmissionOutcome={id:row.id,ordinal:row.ordinal,source:row.source,status:row.status==='preparing'?'pending':row.status,...row.error?{error:row.error}:{}};if(status!=='all'&&outcome.status!==status)continue;batch.push(outcome);if(batch.length===40){await consume();if(hasNext)break;}}
  if(!hasNext)await consume();return {items,page,hasNext};
 }
 async cancel(payload:Record<string,unknown>){const id=sourceIdentifier(payload.id);if(this.active?.state.id!==id)throw new Error('Source admission is no longer active');this.active.cancel=true;return {cancelRequested:true};}
}
