import {mkdir,opendir,readFile,unlink,access,lstat} from 'node:fs/promises';import {join} from 'node:path';import {atomicJson} from './ollama-manager';import type {ConverterOptions} from '../shared/bundled-engines';import type {ConverterResult} from '../shared/local-tools';
export interface QueueRecord{id:string;grants:string[];adapter:string;options:ConverterOptions;destination:string}
/** Unlimited total records on disk, bounded enumeration and at most two admitted jobs. */
export class ConverterQueue{
 private queued=0;private paused=true;private running=new Set<string>();private pumping=false;private stopped=false;private ready:Promise<void>;private timer:ReturnType<typeof setInterval>;
 constructor(private directory:string,private resultsDirectory:string,private active:()=>number,private start:(record:QueueRecord)=>Promise<void>){this.ready=mkdir(directory,{recursive:true,mode:0o700}).then(async()=>{try{const state=JSON.parse(await readFile(join(directory,'state.json'),'utf8'));this.paused=state.paused!==false;}catch{}this.paused=true;for await(const entry of await opendir(directory)){if(/^[a-f0-9-]{36}\.json$/.test(entry.name))this.queued++;if(this.queued%1024===0)await new Promise<void>(resolve=>setImmediate(resolve));}await atomicJson(join(directory,'state.json'),{paused:true,reason:'Queue requires explicit resume after application startup.'});});this.timer=setInterval(()=>void this.pump(),300);this.timer.unref();}
 async enqueue(record:QueueRecord,result:ConverterResult){await this.ready;if(record.options.password)throw new Error('Passwords cannot enter a durable queue; use Convert now for encrypted archives');await atomicJson(join(this.resultsDirectory,record.id+'.json'),result);await atomicJson(join(this.directory,record.id+'.json'),record);this.queued++;void this.pump();}
 async has(id:string){try{await access(join(this.directory,id+'.json'));return true;}catch{return false;}}
 async admitted(id:string){await this.ready;if(await this.has(id))return true;try{const file=join(this.resultsDirectory,id+'.json');if((await lstat(file)).size>256000)throw new Error('Queue result exceeds its byte bound');const result=JSON.parse(await readFile(file,'utf8'))as ConverterResult;return ['running','converted','failed','cancelled'].includes(result.status);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return false;throw error;}}
 async pause(){await this.ready;this.paused=true;await atomicJson(join(this.directory,'state.json'),{paused:true});return this.state();}
 async resume(){await this.ready;this.paused=false;await atomicJson(join(this.directory,'state.json'),{paused:false});void this.pump();return this.state();}
 async state(){await this.ready;return {paused:this.paused,queued:this.queued,running:this.running.size};}
 async cancel(id:string){await this.ready;if(this.running.has(id))return false;const result=JSON.parse(await readFile(join(this.resultsDirectory,id+'.json'),'utf8'))as ConverterResult;result.status='cancelled';await atomicJson(join(this.resultsDirectory,id+'.json'),result);await unlink(join(this.directory,id+'.json'));this.queued=Math.max(0,this.queued-1);return true;}
 async finished(id:string){this.running.delete(id);await unlink(join(this.directory,id+'.json')).catch(()=>{});void this.pump();}
 private async pump(){if(this.pumping||this.stopped)return;this.pumping=true;try{await this.ready;if(this.paused)return;for await(const entry of await opendir(this.directory)){if(this.paused||this.stopped||this.active()>=2)break;if(!/^[a-f0-9-]{36}\.json$/.test(entry.name))continue;const id=entry.name.slice(0,-5);if(this.running.has(id))continue;const result=JSON.parse(await readFile(join(this.resultsDirectory,entry.name),'utf8'))as ConverterResult;if(['converted','failed','cancelled'].includes(result.status)){await unlink(join(this.directory,entry.name));this.queued=Math.max(0,this.queued-1);continue;}const record=JSON.parse(await readFile(join(this.directory,entry.name),'utf8'))as QueueRecord;this.running.add(id);this.queued=Math.max(0,this.queued-1);try{await this.start(record);}catch(error){result.status='failed';result.error=error instanceof Error?error.message:'Queue admission failed';await atomicJson(join(this.resultsDirectory,entry.name),result);await this.finished(id);}}}catch{/* Corrupt record remains visible for inspection; no arbitrary path is executed. */}finally{this.pumping=false;}}
 dispose(){this.stopped=true;clearInterval(this.timer);this.paused=true;}
}
