import {createHash,randomUUID} from 'node:crypto';
import {constants} from 'node:fs';
import {open,lstat,link,unlink,realpath} from 'node:fs/promises';
import type {FileHandle} from 'node:fs/promises';
import path from 'node:path';
import {DOWNLOAD_PAGE_SIZE,validateDownloadSelection,type DownloadSelection,type DownloadJob,type DownloadPage,type DownloadRequest,type DownloadIssue} from '../shared/downloads';

/** Trusted resolver must re-read the exact provider record and reject unapproved hosts. */
export interface DownloadSource {selection:DownloadSelection;apiOrigin:string;endpoint:string;name:string;size?:number;sha256?:string}
export interface StoredDownload {version:1;job:DownloadJob;account:string;destinationPath:string;partialPath:string;sourceKey:string;etag?:string;range:boolean;identity?:{dev:string;ino:string};checkpointHash?:string;finalized?:{hash:string;verification:'sha256'|'length'}}
export interface DownloadDependencies {
 resolveSource(selection:DownloadSelection):Promise<DownloadSource>;
 accountFingerprint(hostname:string):Promise<string>;
 token(hostname:string,expectedAccount:string):Promise<string|undefined>;
 /** Returns an absolute native-picked file path. Cancellation returns null. */
 pickDestination(suggestedName:string):Promise<string|null>;
 /** Sensitive path metadata: use the existing native protected store, never ordinary history/export. */
 store:{durable?:boolean;read():Promise<unknown>;write(records:StoredDownload[]):Promise<void>};
 fetch?:typeof fetch;
 approveRedirect?:(url:URL,source:DownloadSource)=>boolean;
 /** Only an explicitly injected loopback HTTP fixture may enable this. */
 allowLoopbackFixture?:boolean;
}
class DownloadRequestError extends Error {}
class DownloadFailure extends Error {constructor(readonly issue:DownloadIssue){super(issue);}}
interface Internal extends StoredDownload {controller?:AbortController;task?:Promise<void>;stop?:'paused'|'cancelled';fresh?:boolean}
const active=new Set(['queued','downloading']);
const safeName=(name:string)=>path.basename(name).replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,180)||'download.bin';
const strongETag=(value:string|null)=>value&&/^"[^"\r\n]{1,512}"$/.test(value)?value:undefined;
const identity=(stat:{dev:number;ino:number})=>({dev:String(stat.dev),ino:String(stat.ino)});
const sameIdentity=(a:{dev:string;ino:string}|undefined,stat:{dev:number;ino:number})=>!!a&&a.dev===String(stat.dev)&&a.ino===String(stat.ino);
async function fileHash(file:FileHandle,bytes:number){const hash=createHash('sha256');if(bytes)for await(const chunk of file.createReadStream({start:0,end:bytes-1,autoClose:false}))hash.update(chunk);return hash;}
const sourceKey=(source:DownloadSource)=>JSON.stringify([source.selection,source.apiOrigin,source.endpoint,source.name,source.size??null,source.sha256??null]);
const validSize=(n:unknown):n is number=>typeof n==='number'&&Number.isSafeInteger(n)&&n>=0;
/** Real streaming queue. Success follows fsync, integrity verification and atomic no-overwrite publication. */
export class DownloadQueue {
 private jobs=new Map<string,Internal>();private listeners=new Set<(job:DownloadJob)=>void>();
 private mutations:Promise<unknown>=Promise.resolve();private saved:Promise<void>=Promise.resolve();private lastSave=0;private running=false;private closed=false;
 private ready:Promise<void>;private closing?:Promise<void>;
 constructor(private deps:DownloadDependencies){this.ready=this.restore();void this.ready.catch(()=>{});}
 get activeOperations():ReadonlySet<string>{return new Set([...this.jobs.values()].filter(record=>active.has(record.job.state)||record.task!==undefined).map(record=>record.job.id));}
 activeJobs():number{return this.activeOperations.size;}
 async pauseAll(){await this.stopAll('paused');}
 async cancelAll(){await this.stopAll('cancelled');}
 private async stopAll(state:'paused'|'cancelled'){await this.ready;const records=[...this.jobs.values()].filter(record=>active.has(record.job.state));for(const record of records){record.stop=state;record.controller?.abort();if(record.job.state==='queued'){record.job.state=state;this.publish(record);}}await Promise.all(records.map(record=>record.task));await this.persist();}
 subscribe(listener:(job:DownloadJob)=>void){this.listeners.add(listener);return()=>{this.listeners.delete(listener);};}
 private view(record:Internal):DownloadJob{return structuredClone(record.job);}
 private publish(record:Internal){record.job.updatedAt=new Date().toISOString();for(const listener of this.listeners){try{listener(this.view(record));}catch{/* A disconnected observer cannot stop a transfer. */}}}
 private snapshot():StoredDownload[]{return [...this.jobs.values()].map(record=>({version:1,job:this.view(record),account:record.account,destinationPath:record.destinationPath,partialPath:record.partialPath,sourceKey:record.sourceKey,etag:record.etag,range:record.range,identity:record.identity,checkpointHash:record.checkpointHash,finalized:record.finalized}));}
 private persist(completed?:DownloadJob){const records=this.snapshot();if(completed){const record=records.find(row=>row.job.id===completed.id);if(record)record.job=structuredClone(completed);}const next=this.saved.catch(()=>{}).then(()=>this.deps.store.write(records));this.saved=next;return next;}
 private async restore(){const rows=await this.deps.store.read();if(rows===undefined||rows===null)return;if(!Array.isArray(rows)||rows.length>200)throw new DownloadRequestError('Download recovery data is invalid.');for(const row of rows){try{
  const record=row as StoredDownload;const job=record.job;
  if(record.version!==1||!job||! /^[a-f0-9-]{36}$/.test(job.id)||!validSize(job.bytes)||!(job.total===null||validSize(job.total))||typeof record.account!=='string'||record.account.length>256||typeof record.sourceKey!=='string'||record.sourceKey.length>4096||typeof record.destinationPath!=='string'||!path.isAbsolute(record.destinationPath)||record.partialPath!==path.join(path.dirname(record.destinationPath),`.material-git-download-${job.id}.part`)||!['queued','downloading','paused','cancelled','failed','completed'].includes(job.state)||this.jobs.has(job.id))continue;
  if(record.identity&&(!/^\d+$/.test(record.identity.dev)||!/^\d+$/.test(record.identity.ino))||record.checkpointHash&&!/^[a-f0-9]{64}$/.test(record.checkpointHash)||record.finalized&&(!/^[a-f0-9]{64}$/.test(record.finalized.hash)||!['length','sha256'].includes(record.finalized.verification)))continue;
  const selection=validateDownloadSelection(job.selection);const internal:Internal={version:1,account:record.account,destinationPath:record.destinationPath,partialPath:record.partialPath,sourceKey:record.sourceKey,range:record.range===true,identity:record.identity,checkpointHash:record.checkpointHash,finalized:record.finalized,etag:strongETag(record.etag??null),job:{id:job.id,selection,name:safeName(job.name),destination:safeName(path.basename(record.destinationPath)),state:job.state,bytes:job.bytes,total:job.total,bytesPerSecond:0,etaSeconds:null,resumable:false,updatedAt:new Date().toISOString(),verification:job.verification==='sha256'?'sha256':job.verification==='length'?'length':undefined}};
  let recovered=false;
  if(internal.finalized){const final=await open(internal.destinationPath,constants.O_RDONLY|(constants.O_NOFOLLOW??0)).catch(()=>null);if(final){try{const stat=await final.stat();if(stat.isFile()&&sameIdentity(internal.identity,stat)&&stat.size===job.total&&(await fileHash(final,stat.size)).digest('hex')===internal.finalized.hash){internal.job.state='completed';internal.job.bytes=stat.size;internal.job.verification=internal.finalized.verification;recovered=true;}}finally{await final.close();}}}
  if(!recovered&&job.state!=='completed'){const partial=await open(internal.partialPath,constants.O_RDWR|(constants.O_NOFOLLOW??0)).catch(()=>null);let valid=false;if(partial){try{const stat=await partial.stat();if(stat.isFile()&&sameIdentity(internal.identity,stat)&&stat.size>=job.bytes&&internal.checkpointHash&&(await fileHash(partial,job.bytes)).digest('hex')===internal.checkpointHash){await partial.truncate(job.bytes);await partial.sync();valid=true;}}finally{await partial.close();}}if(valid){internal.job.resumable=!!internal.etag&&internal.range&&job.bytes>0&&job.bytes<(job.total??Infinity);}else{internal.job.bytes=0;internal.etag=undefined;internal.range=false;internal.job.issue='storage';}if(active.has(job.state)||internal.finalized){internal.job.state='paused';internal.job.issue='interrupted';}}
  if(recovered){const stat=await lstat(internal.partialPath).catch(()=>null);if(stat&&sameIdentity(internal.identity,stat))await unlink(internal.partialPath).catch(()=>{});}
  this.jobs.set(job.id,internal);
 }catch{/* Reject malformed recovery entries rather than trusting paths. */}}}
 private page(page=1):DownloadPage{if(!Number.isInteger(page)||page<1||page>10000)throw new DownloadRequestError('Invalid download page.');const rows=[...this.jobs.values()].reverse();return {items:rows.slice((page-1)*DOWNLOAD_PAGE_SIZE,page*DOWNLOAD_PAGE_SIZE).map(row=>this.view(row)),page,hasNext:page*DOWNLOAD_PAGE_SIZE<rows.length,total:rows.length,recovery:this.deps.store.durable===true?'durable':'session'};}
 async handle(request:DownloadRequest):Promise<DownloadPage>{try{if(request?.action==='list')return await this.dispatch(request);const operation=this.mutations.catch(()=>{}).then(()=>this.dispatch(request));this.mutations=operation;return await operation;}catch(error){if(error instanceof DownloadRequestError||error instanceof DownloadFailure)throw error;throw new DownloadRequestError('The native download service could not finish this action.');}}
 private async dispatch(request:DownloadRequest):Promise<DownloadPage>{await this.ready;if(this.closed)throw new DownloadRequestError('Downloads are closed.');if(!request||typeof request!=='object'||Array.isArray(request))throw new DownloadRequestError('Invalid download action.');
  const allowed=request.action==='list'?['action','page']:request.action==='enqueue'?['action','selection']:['action','id'];if(Object.keys(request).some(key=>!allowed.includes(key)))throw new DownloadRequestError('Invalid download action.');
  if(request.action==='list')return this.page(request.page);
  if(request.action==='enqueue'){if(this.jobs.size>=200)throw new DownloadRequestError('Remove completed downloads before adding more.');const selection=validateDownloadSelection(request.selection);const account=await this.deps.accountFingerprint(selection.hostname);if(!account||account.length>256)throw new DownloadFailure('authentication');const source=await this.resolve(selection);if(this.closed)throw new DownloadRequestError('Downloads are closed.');let destination=await this.deps.pickDestination(safeName(source.name));if(this.closed)throw new DownloadRequestError('Downloads are closed.');if(!destination)return this.page();if(!path.isAbsolute(destination)||destination.includes('\0'))throw new DownloadRequestError('Choose a native destination.');destination=path.join(await realpath(path.dirname(destination)),path.basename(destination));if(await lstat(destination).catch(()=>null))throw new DownloadRequestError('The destination already exists. Choose another filename.');
   if(await this.deps.accountFingerprint(selection.hostname)!==account)throw new DownloadFailure('authentication');if(this.closed)throw new DownloadRequestError('Downloads are closed.');const id=randomUUID();const record:Internal={version:1,job:{id,selection,name:safeName(source.name),destination:safeName(path.basename(destination)),state:'queued',bytes:0,total:source.size??null,bytesPerSecond:0,etaSeconds:null,resumable:false,updatedAt:new Date().toISOString()},account,destinationPath:destination,partialPath:path.join(path.dirname(destination),`.material-git-download-${id}.part`),sourceKey:sourceKey(source),range:false,fresh:true};this.jobs.set(id,record);try{await this.persist();}catch{this.jobs.delete(id);throw new DownloadRequestError('Download recovery storage is unavailable.');}this.publish(record);void this.pump();return this.page();}
  if(!['pause','cancel','resume','retry','remove'].includes(request.action)||!('id' in request)||typeof request.id!=='string')throw new DownloadRequestError('Invalid download action.');const record=this.jobs.get(request.id);if(!record)throw new DownloadRequestError('Download not found.');
  if(request.action==='pause'||request.action==='cancel'){if(record.job.state==='completed')throw new DownloadRequestError('This download is complete.');record.stop=request.action==='pause'?'paused':'cancelled';record.controller?.abort();if(record.task)await record.task;else{record.job.state=record.stop;this.publish(record);await this.persist();}return this.page();}
  if(request.action==='remove'){if(active.has(record.job.state))throw new DownloadRequestError('Stop the download before removing it.');await this.removePartial(record);this.jobs.delete(record.job.id);await this.persist();return this.page();}
  if(active.has(record.job.state)||record.job.state==='completed')throw new DownloadRequestError('This download cannot be restarted.');
  if(request.action==='resume'&&!record.job.resumable)throw new DownloadRequestError('Resume is unavailable. Retry starts a fresh transfer.');
  if(request.action==='retry'){const source=await this.resolve(record.job.selection);if(this.closed)throw new DownloadRequestError('Downloads are closed.');if(await this.deps.accountFingerprint(record.job.selection.hostname)!==record.account)throw new DownloadFailure('authentication');if(this.closed)throw new DownloadRequestError('Downloads are closed.');await this.removePartial(record);record.sourceKey=sourceKey(source);record.job.name=safeName(source.name);record.job.total=source.size??null;record.job.bytes=0;record.etag=undefined;record.identity=undefined;record.checkpointHash=undefined;record.finalized=undefined;record.range=false;record.fresh=true;}
  record.stop=undefined;record.job.state='queued';record.job.issue=undefined;record.job.bytesPerSecond=0;record.job.etaSeconds=null;await this.persist();this.publish(record);void this.pump();return this.page();
 }
 private async resolve(selection:DownloadSelection){const source=await this.deps.resolveSource(selection);if(JSON.stringify(validateDownloadSelection(source.selection))!==JSON.stringify(selection)||!source.name||source.name.length>512||source.size!==undefined&&!validSize(source.size)||source.sha256!==undefined&&!/^[a-f0-9]{64}$/i.test(source.sha256))throw new DownloadFailure('source-changed');const origin=new URL(source.apiOrigin);if(origin.origin!==source.apiOrigin||origin.username||origin.password||!this.safeProtocol(origin)||!source.endpoint.startsWith('/'))throw new DownloadFailure('source-changed');const expected=selection.kind==='release-asset'?`/repos/${selection.repository}/releases/assets/${selection.id}`:`/repos/${selection.repository}/actions/artifacts/${selection.id}/zip`;if(source.endpoint!==expected)throw new DownloadFailure('source-changed');return source;}
 private safeProtocol(url:URL){return url.protocol==='https:'||this.deps.allowLoopbackFixture===true&&url.protocol==='http:'&&['127.0.0.1','[::1]'].includes(url.hostname);}
 private redirectAllowed(url:URL,source:DownloadSource){if(!this.safeProtocol(url)||url.username||url.password)return false;if(url.origin===source.apiOrigin)return true;if(this.deps.approveRedirect)return this.deps.approveRedirect(url,source);return source.selection.hostname==='github.com'&&url.protocol==='https:'&&['release-assets.githubusercontent.com','objects.githubusercontent.com','github.com','productionresultssa0.blob.core.windows.net'].includes(url.hostname);}
 private async response(source:DownloadSource,record:Internal){let url=new URL(source.endpoint,source.apiOrigin);const headers:Record<string,string>={Accept:'application/octet-stream','Accept-Encoding':'identity'};const token=await this.deps.token(source.selection.hostname,record.account);if(await this.deps.accountFingerprint(source.selection.hostname)!==record.account)throw new DownloadFailure('authentication');if(token)headers.Authorization=`Bearer ${token}`;if(record.job.bytes>0){headers.Range=`bytes=${record.job.bytes}-`;headers['If-Range']=record.etag!;}for(let redirects=0;redirects<=5;redirects++){const response=await (this.deps.fetch??fetch)(url,{headers,redirect:'manual',signal:record.controller!.signal});if([301,302,303,307,308].includes(response.status)){await response.body?.cancel();const location=response.headers.get('location');if(!location||redirects===5)throw new DownloadFailure('transfer');const next=new URL(location,url);if(!this.redirectAllowed(next,source))throw new DownloadFailure('transfer');if(next.origin!==url.origin)delete headers.Authorization;url=next;continue;}return response;}throw new DownloadFailure('transfer');}
 private async pump(){if(this.running||this.closed)return;this.running=true;try{for(;;){const record=[...this.jobs.values()].find(row=>row.job.state==='queued');if(!record||this.closed)break;record.task=this.transfer(record);await record.task;record.task=undefined;}}finally{this.running=false;}}
 private async removePartial(record:Internal){const stat=await lstat(record.partialPath).catch(()=>null);if(stat&&(!stat.isFile()||!sameIdentity(record.identity,stat)))throw new DownloadFailure('storage');if(stat)await unlink(record.partialPath);}
 private async transfer(record:Internal){let file:FileHandle|undefined;let timeout:ReturnType<typeof setTimeout>|undefined;const touch=()=>{if(timeout)clearTimeout(timeout);timeout=setTimeout(()=>record.controller?.abort(),30000);};record.controller=new AbortController();touch();record.job.state='downloading';record.job.issue=undefined;this.publish(record);try{
  const source=await this.resolve(record.job.selection);if(await this.deps.accountFingerprint(record.job.selection.hostname)!==record.account)throw new DownloadFailure('authentication');if(sourceKey(source)!==record.sourceKey)throw new DownloadFailure('source-changed');if(await lstat(record.destinationPath).catch(()=>null))throw new DownloadFailure('destination-exists');
  const offset=record.job.bytes;if(offset&&!record.job.resumable)throw new DownloadFailure('source-changed');
  if(record.fresh){file=await open(record.partialPath,'wx+',0o600);record.fresh=false;record.identity=identity(await file.stat());record.checkpointHash=createHash('sha256').digest('hex');await file.sync();await this.persist();}else{file=await open(record.partialPath,constants.O_RDWR|(constants.O_NOFOLLOW??0));const stat=await file.stat();if(!stat.isFile()||!sameIdentity(record.identity,stat)||stat.size!==offset)throw new DownloadFailure('storage');}
  const hash=await fileHash(file,offset);if(offset&&hash.copy().digest('hex')!==record.checkpointHash)throw new DownloadFailure('storage');
  const response=await this.response(source,record);if([401,403].includes(response.status))throw new DownloadFailure('authentication');if(response.status!==200&&response.status!==206)throw new DownloadFailure('transfer');if(response.headers.get('content-encoding')&&response.headers.get('content-encoding')!=='identity')throw new DownloadFailure('integrity');
  const etag=strongETag(response.headers.get('etag'));const lengthHeader=response.headers.get('content-length');const length=lengthHeader!==null&&/^\d+$/.test(lengthHeader)&&validSize(Number(lengthHeader))?Number(lengthHeader):null;
  if(offset){const range=response.headers.get('content-range')?.match(/^bytes (\d+)-(\d+)\/(\d+)$/);if(response.status!==206||etag!==record.etag||!range||Number(range[1])!==offset||!validSize(Number(range[3]))||Number(range[2])!==Number(range[3])-1||length!==null&&length!==Number(range[3])-offset||record.job.total!==null&&record.job.total!==Number(range[3]))throw new DownloadFailure('source-changed');record.job.total=Number(range[3]);}else{if(response.status!==200)throw new DownloadFailure('integrity');record.job.total=length??source.size??null;if(source.size!==undefined&&record.job.total!==source.size)throw new DownloadFailure('integrity');}
  if(record.job.total===null||!response.body)throw new DownloadFailure('integrity');record.etag=etag;record.range=response.headers.get('accept-ranges')==='bytes'||response.status===206;record.job.resumable=!!etag&&record.range;
  const started=Date.now();let written=0;const reader=response.body.getReader();try{for(;;){if(record.controller.signal.aborted)throw new DownloadFailure('transfer');const chunk=await reader.read();if(chunk.done)break;touch();if(record.job.bytes+chunk.value.byteLength>record.job.total)throw new DownloadFailure('integrity');let position=0;while(position<chunk.value.byteLength){const result=await file.write(chunk.value,position,chunk.value.byteLength-position,record.job.bytes+position);if(!result.bytesWritten)throw new DownloadFailure('storage');position+=result.bytesWritten;}hash.update(chunk.value);record.job.bytes+=position;written+=position;record.job.bytesPerSecond=Math.round(written/Math.max(.001,(Date.now()-started)/1000));record.job.etaSeconds=record.job.bytesPerSecond?Math.ceil((record.job.total-record.job.bytes)/record.job.bytesPerSecond):null;this.publish(record);if(Date.now()-this.lastSave>250){this.lastSave=Date.now();await file.sync();record.checkpointHash=hash.copy().digest('hex');await this.persist();}}}finally{await reader.cancel().catch(()=>{});}
  if(record.job.bytes!==record.job.total)throw new DownloadFailure('integrity');await file.sync();
  const digest=(await fileHash(file,record.job.bytes)).digest('hex');if(source.sha256&&digest!==source.sha256.toLowerCase())throw new DownloadFailure('integrity');record.job.verification=source.sha256?'sha256':'length';record.checkpointHash=digest;record.finalized={hash:digest,verification:record.job.verification};await this.persist();
  if(record.controller.signal.aborted)throw new DownloadFailure('transfer');const partialStat=await lstat(record.partialPath);if(!sameIdentity(record.identity,partialStat)||!partialStat.isFile())throw new DownloadFailure('storage');
  try{await link(record.partialPath,record.destinationPath);}catch(error){if((error as NodeJS.ErrnoException).code==='EEXIST')throw new DownloadFailure('destination-exists');throw new DownloadFailure('storage');}const publishedStat=await lstat(record.destinationPath);if(!sameIdentity(record.identity,publishedStat)||!publishedStat.isFile()){await unlink(record.destinationPath);throw new DownloadFailure('storage');}
  await file.close();file=undefined;await unlink(record.partialPath);if(process.platform!=='win32'){const directory=await open(path.dirname(record.destinationPath),constants.O_RDONLY);try{await directory.sync();}finally{await directory.close();}}const completed:DownloadJob={...record.job,state:'completed',resumable:false,bytesPerSecond:0,etaSeconds:0};await this.persist(completed);record.job=completed;this.publish(record);
 }catch(error){record.job.state=record.stop??'failed';record.job.issue=record.stop?undefined:error instanceof DownloadFailure?error.issue:'transfer';record.job.bytesPerSecond=0;record.job.etaSeconds=null;record.job.resumable=!!record.etag&&record.range&&record.job.bytes>0&&record.job.bytes< (record.job.total??Infinity);if(file){try{await file.sync();record.checkpointHash=(await fileHash(file,record.job.bytes)).digest('hex');}catch{}await file.close().catch(()=>{});file=undefined;}if(record.finalized){const final=await open(record.destinationPath,constants.O_RDONLY|(constants.O_NOFOLLOW??0)).catch(()=>null);if(final){try{const stat=await final.stat();if(stat.isFile()&&sameIdentity(record.identity,stat)&&stat.size===record.job.total&&(await fileHash(final,stat.size)).digest('hex')===record.finalized.hash){record.job.state='completed';record.job.resumable=false;record.job.issue='storage';record.job.etaSeconds=0;}}finally{await final.close();}}}try{await this.persist();}catch{record.job.issue='storage';if(record.job.state!=='completed')record.job.state='failed';}this.publish(record);
 }finally{if(timeout)clearTimeout(timeout);record.controller?.abort();record.controller=undefined;if(file)await file.close().catch(()=>{});}}
 close():Promise<void>{if(this.closing)return this.closing;this.closed=true;const closing=this.shutdown();this.closing=closing;void closing.catch(()=>{if(this.closing===closing)this.closing=undefined;this.closed=false;});return closing;}
 private async shutdown(){
  try{await this.ready;}catch{if(this.jobs.size===0&&!this.running){await this.mutations.catch(()=>{});this.listeners.clear();return;}throw new DownloadRequestError('Download recovery could not be loaded.');}
  for(const record of this.jobs.values()){if(active.has(record.job.state)||record.task){record.stop='paused';record.controller?.abort();}}
  await this.mutations.catch(()=>{});
  for(const record of this.jobs.values()){if(active.has(record.job.state)||record.task){record.stop='paused';record.controller?.abort();}}
  await Promise.all([...this.jobs.values()].map(record=>record.task));
  for(const record of this.jobs.values())if(record.job.state==='queued'){record.job.state='paused';record.job.issue='interrupted';}
  try{await this.persist();}catch{throw new DownloadRequestError('Download recovery could not be saved. Check protected storage and try closing again.');}
  this.listeners.clear();
 }
}
