import {createHash} from 'node:crypto';
import {existsSync,lstatSync,realpathSync,readdirSync,readFileSync} from 'node:fs';
import path from 'node:path';
import type {GitRow} from '../shared/git';
/** Cache traversal stays inside native-approved metadata and binds every variant and journal byte. */
export function conflictReuseState(cache:string,journal:string,safePath:(value:string)=>string){
 const hash=createHash('sha256'),rows:GitRow[]=[];let bytes=0,count=0;const consume=(file:string)=>{const stat=lstatSync(file);if(stat.isSymbolicLink()||!stat.isFile()||stat.nlink!==1||realpathSync(file)!==file)throw new Error('Conflict reuse metadata must be an owned regular file without links');bytes+=stat.size;if(stat.size>67108864||bytes>134217728||++count>10000)throw new Error('Conflict reuse cache exceeds reviewed metadata limits');const content=readFileSync(file);hash.update(file).update(String(stat.mtimeMs)).update(content);return {content,mtime:stat.mtimeMs};};
 const cacheExists=existsSync(cache);hash.update(cacheExists?'cache':'missing-cache');if(cacheExists){const stat=lstatSync(cache);if(!stat.isDirectory()||stat.isSymbolicLink()||realpathSync(cache)!==cache)throw new Error('Conflict reuse cache directory changed');const entries=readdirSync(cache).sort();if(entries.length>2000)throw new Error('Conflict reuse cache exceeds the record limit');for(const id of entries){if(!/^[a-f0-9]{40}(?:[a-f0-9]{24})?$/.test(id))throw new Error('Unexpected conflict reuse cache entry');const directory=path.join(cache,id),stat=lstatSync(directory);if(!stat.isDirectory()||stat.isSymbolicLink()||realpathSync(directory)!==directory)throw new Error('Conflict reuse record directory changed');hash.update(id);const variants=new Map<string,{resolved:boolean;preimage:boolean;mtime:number}>();for(const file of readdirSync(directory).sort()){if(!/^(?:preimage|postimage|thisimage)(?:\.[0-9]{1,6})?$/.test(file))throw new Error('Unexpected conflict reuse record file');const {mtime}=consume(path.join(directory,file)),variant=file.split('.')[1]||'0',state=variants.get(variant)||{resolved:false,preimage:false,mtime:0};if(file.startsWith('preimage'))state.preimage=true;if(file.startsWith('postimage'))state.resolved=true;state.mtime=Math.max(state.mtime,mtime);variants.set(variant,state);}for(const [variant,state] of variants)rows.push({id:id+'.'+variant,label:id.slice(0,12)+' · '+variant,detail:state.resolved?'Recorded resolution':'Unresolved preimage',data:{resolved:String(state.resolved),preimage:String(state.preimage),modified:new Date(state.mtime).toISOString()}});}}
 const journalPaths:string[]=[];if(existsSync(journal)){const {content}=consume(journal);if(content.length>2097152)throw new Error('Conflict reuse journal exceeds the input limit');if(content.toString('utf8').includes('�'))throw new Error('Conflict reuse journal must contain valid UTF-8 paths');if(content.length&&content.at(-1)!==0)throw new Error('Conflict reuse journal is incomplete');for(const row of content.toString('utf8').split('\0').filter(Boolean)){const match=row.match(/^([a-f0-9]{40}(?:[a-f0-9]{24})?)(?:\.([0-9]{1,6}))?\t(.+)$/);if(!match)throw new Error('Conflict reuse journal is invalid');journalPaths.push(safePath(match[3]));}}else hash.update('missing-journal');return {fingerprint:hash.digest('hex'),cacheExists,rows,journalPaths};
}
