import {spawn, type ChildProcess} from 'node:child_process';
import {randomUUID,createHash} from 'node:crypto';
import type {GitResult} from '../shared/git';
export function redactGit(value:string):string {let output=value.replace(/(?:https?|ssh):\/\/[^\s/@]+:[^\s/@]+@/g,'https://[REDACTED]@').replace(/(?:gh[pousr]_|github_pat_)[A-Za-z0-9_]+/g,'[REDACTED]');for(const [key,secret] of Object.entries(process.env))if(/TOKEN|SECRET|PASSWORD/i.test(key)&&secret&&secret.length>3)output=output.split(secret).join('[REDACTED]');return output;}
export interface NativeGitResult extends GitResult {nativeHash:string;}
export class GitProcesses {
 private active=new Map<string,{child:ChildProcess;cancelled:boolean}>();
 constructor(private binary:string,private hooksDirectory:string){}
 async run(cwd:string,argv:string[],options:{input?:string;mutation?:boolean;trust?:boolean;id?:string;timeout?:number;allowFailure?:boolean;localFile?:boolean}={}):Promise<NativeGitResult>{const id=options.id||randomUUID();if(this.active.has(id))throw new Error('Operation is already running');const prefix=['--no-pager','-c','color.ui=false','-c','core.quotePath=false','-c','core.fsmonitor=false','-c','maintenance.auto=false','-c','gc.auto=0','-c','submodule.recurse=false','-c','push.recurseSubmodules=no'];if(!options.trust)prefix.push('-c',`core.hooksPath=${this.hooksDirectory}`,'-c','credential.helper=','-c','core.sshCommand=ssh -oBatchMode=yes','-c','protocol.allow=never','-c','protocol.https.allow=always','-c','protocol.ssh.allow=always','-c','protocol.git.allow=always');if(options.localFile)prefix.push('-c','protocol.file.allow=always');return new Promise((resolve,reject)=>{const environment={...process.env};for(const key of Object.keys(environment))if(/^(?:GIT_TRACE|GIT_CONFIG_KEY_|GIT_CONFIG_VALUE_|GIT_CONFIG_PARAMETERS|GIT_DIR$|GIT_WORK_TREE$|GIT_INDEX_FILE$|GIT_OBJECT_DIRECTORY$|GIT_ALTERNATE_OBJECT_DIRECTORIES$)/.test(key))delete environment[key];const child=spawn(this.binary,[...prefix,...argv],{cwd,shell:false,windowsHide:true,detached:process.platform!=='win32',env:{...environment,GIT_TERMINAL_PROMPT:'0',GIT_PAGER:'cat',PAGER:'cat',GIT_EDITOR:'true',GIT_SEQUENCE_EDITOR:'true',GIT_OPTIONAL_LOCKS:options.mutation?'1':'0',GIT_CONFIG_COUNT:'0'},stdio:['pipe','pipe','pipe']});const state={child,cancelled:false};this.active.set(id,state);let stdout='',stderr='',size=0,bounded=false;const append=(source:'out'|'err',chunk:Buffer)=>{size+=chunk.length;if(size>2097152){bounded=true;this.kill(child);return;}if(source==='out')stdout+=chunk.toString('utf8');else stderr+=chunk.toString('utf8');};child.stdout!.on('data',chunk=>append('out',chunk));child.stderr!.on('data',chunk=>append('err',chunk));const timer=setTimeout(()=>{state.cancelled=true;this.kill(child);},options.timeout||60000);child.on('error',error=>{clearTimeout(timer);this.active.delete(id);reject(new Error(redactGit(error.message)));});child.on('close',code=>{clearTimeout(timer);this.active.delete(id);const result:NativeGitResult={nativeHash:createHash('sha256').update(stdout).update(stderr).digest('hex'),kind:'result',ok:code===0&&!state.cancelled&&!bounded,exitCode:code,output:redactGit(stdout),error:redactGit(bounded?'Git output exceeded the 2 MiB limit. Narrow the selection.':stderr),cancelled:state.cancelled,partialEffects:!!options.mutation&&(state.cancelled||code!==0),operationId:id};if(!result.ok&&!options.allowFailure&&!options.mutation)reject(new Error(result.error||'Git could not complete this inspection'));else resolve(result);});child.stdin!.on('error',()=>{});child.stdin!.end(options.input);});}
 get activeCount(){return this.active.size;}
 cancelAll(){for(const id of this.active.keys())this.cancel(id);}
 dispose(){for(const id of this.active.keys())this.cancel(id);}
 cancel(id:string):boolean {const item=this.active.get(id);if(!item)return false;item.cancelled=true;this.kill(item.child);return true;}
 private kill(child:ChildProcess){if(!child.pid)return;if(process.platform==='win32'){spawn('taskkill',['/PID',String(child.pid),'/T','/F'],{shell:false,windowsHide:true,stdio:'ignore'});}else{try{process.kill(-child.pid,'SIGTERM');}catch{child.kill('SIGTERM');}const pid=child.pid;const timer=setTimeout(()=>{try{process.kill(-pid,'SIGKILL');}catch{}},1000);timer.unref();}}
}
