import {createHash} from 'node:crypto';import type {GitProviderTarget} from '../shared/git-provider';
function bounded(value:unknown,label:string,max=1024){if(typeof value!=='string'||!value||value.length>max||/[\0\r\n]/.test(value))throw new Error(`Invalid provider ${label}`);return value;}
export function canonicalProviderRepository(raw:string){try{let hostname:string,pathname:string;const scp=raw.match(/^[^@\s]+@([^:\s]+):([^\s?#]+)$/);if(scp){hostname=scp[1];pathname=scp[2];}else{const parsed=new URL(raw);if(!['https:','ssh:'].includes(parsed.protocol)||parsed.password||parsed.search||parsed.hash||parsed.protocol==='https:'&&parsed.username)return null;hostname=parsed.hostname;pathname=parsed.pathname;}const parts=pathname.replace(/^\//,'').replace(/\.git\/?$/i,'').split('/');if(parts.length!==2)return null;const [owner,name]=parts.map(part=>decodeURIComponent(part));if(!owner||!name||![owner,name].every(part=>/^[A-Za-z0-9_.-]+$/.test(part)))return null;return {hostname:hostname.toLowerCase(),owner:owner.toLowerCase(),name:name.toLowerCase()};}catch{return null;}}
export function validateProviderTarget(value:GitProviderTarget,id:string,now:number):GitProviderTarget {
 if(!value||typeof value!=='object'||value.id!==id||!['repository','gist','pull-request'].includes(value.kind))throw new Error('Provider source receipt is invalid');
 bounded(value.id,'source id');bounded(value.accountFingerprint,'account binding');bounded(value.providerId,'record id');bounded(value.name,'source name');
 const hostname=bounded(value.hostname,'hostname',255).toLowerCase();if(!/^[a-z0-9][a-z0-9.-]*$/.test(hostname))throw new Error('Provider source hostname is invalid');
 const expires=Date.parse(value.expiresAt);if(!Number.isFinite(expires)||expires<=now)throw new Error('Provider source receipt expired');
 const source=bounded(value.url,'clone URL',4096),url=new URL(source);if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash)throw new Error('Provider clone source must be an HTTPS URL without credentials');
 if(value.kind==='gist'){if(url.hostname.toLowerCase()!=='gist.'+hostname||url.pathname.split('/').filter(Boolean).at(-1)?.replace(/\.git$/i,'')!==value.providerId)throw new Error('Gist clone source does not match its approved provider');}
 else {const repository=value.repository;if(!repository)throw new Error('Provider repository identity is missing');bounded(repository.id,'repository id');bounded(repository.owner,'repository owner');bounded(repository.name,'repository name');const canonical=canonicalProviderRepository(source);if(!canonical||canonical.hostname!==hostname||canonical.owner!==repository.owner.toLowerCase()||canonical.name!==repository.name.toLowerCase())throw new Error('Clone URL does not match the provider repository identity');if(value.kind==='pull-request'){if(!Number.isSafeInteger(value.number)||value.number<1||value.number>2147483647||!/^[a-f0-9]{40,64}$/.test(value.headSha))throw new Error('Pull request number or head object is invalid');bounded(value.ref,'head reference');bounded(value.baseRef,'base reference');}}
 return structuredClone(value);
}
export function providerTargetFingerprint(target:GitProviderTarget){const sorted=(value:unknown):unknown=>Array.isArray(value)?value.map(sorted):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,sorted(item)])):value;return createHash('sha256').update(JSON.stringify(sorted(target))).digest('hex');}
export function matchesProviderRepository(url:string,target:Extract<GitProviderTarget,{kind:'repository'|'pull-request'}>){const repository=canonicalProviderRepository(url);return !!repository&&repository.hostname===target.hostname.toLowerCase()&&repository.owner===target.repository.owner.toLowerCase()&&repository.name===target.repository.name.toLowerCase();}
