import {existsSync,realpathSync,statSync,readFileSync} from 'node:fs';import path from 'node:path';
import type {AdvancedGitTask} from '../shared/git-advanced';import type {GitSnapshot} from '../shared/git';
export interface AdvancedGitContext {root:string;gitDir:string;commonDir:string;snapshot:GitSnapshot;trust:boolean;fields:Record<string,unknown>;read:(argv:string[],allowFailure?:boolean)=>Promise<{output:string;ok:boolean}>;safePath:(value:unknown,missing?:boolean)=>string;pickFolder?:()=>Promise<string|null>;target:(id:unknown)=>{root:string;gitDir:string;commonDir:string};imported:(id:unknown)=>{file:string;content:string};}
export interface AdvancedGitPlan {argv:string[];warnings:string[];input?:string;watch?:string[];destination?:string;}
const definitions:Record<AdvancedGitTask,string[]>={'notes-append':['revision','message'],'notes-copy':['source','destination'],'notes-merge':['reference','strategy'],'notes-prune':[],'notes-merge-commit':[],'notes-merge-abort':[],'stash-branch':['name','stash'],'branch-upstream':['name','upstream'],'branch-unset-upstream':['name'],'switch-detached':['revision'],'sparse-add':['directories'],'sparse-reapply':['sparseIndex'],'worktree-move':['targetId','name'],'worktree-repair':['targetId'],'submodule-absorb':['path'],'submodule-set-branch':['path','branch','default'],'submodule-set-url':['path','url'],'verify-commit':['revision','raw'],'verify-tag':['revision','raw'],'move-file':['path','destination'],'remove-file':['path','deleteFiles'],'restore-file':['path','revision','staged','working'],'index-properties':['path','property'],'bundle-create':['directory','name','revision','all'],'bundle-unbundle':['fileId'],'bundle-fetch':['fileId','source','destination'],archive:['directory','name','revision','format','prefix'],'clean-files':['paths','directories','ignored'],'reflog-delete':['reference','entry'],'remote-prune':['remote'],'repack':['mode'],'prune-objects':['days'],'commit-graph-write':['changedPaths'],'multi-pack-write':['bitmap']};
export function isAdvancedGitTask(task:string):task is AdvancedGitTask{return Object.hasOwn(definitions,task);}
function text(value:unknown,label:string,required=true,max=4096){if(value===undefined||value===''){if(required)throw new Error(`Choose ${label}`);return '';}if(typeof value!=='string'||value.length>max||/[\0\r\n]/.test(value))throw new Error(`Invalid ${label}`);return value;}
function revision(value:unknown,label='reference'){const result=text(value,label);if(result.startsWith('-')||!/^([A-Za-z0-9_][A-Za-z0-9_./-]*|HEAD(?:~[0-9]+|\^[123]?)?)$/.test(result)||result.includes('..')||result.includes('//')||result.endsWith('.lock'))throw new Error(`Invalid ${label}`);return result;}
function number(value:unknown,fallback:number,min:number,max:number){const result=value??fallback;if(typeof result!=='number'||!Number.isInteger(result)||result<min||result>max)throw new Error(`Choose a whole number from ${min} to ${max}`);return result;}
function url(value:unknown){const result=text(value,'remote URL');if(!/^(https:\/\/|ssh:\/\/|[\w.-]+@[\w.-]+:)/.test(result)||/^(?:https|ssh):\/\/[^/]*:[^/]*@/.test(result))throw new Error('Choose an HTTPS or SSH URL without credentials');return result;}
async function tracked(context:AdvancedGitContext,value:unknown){const filename=context.safePath(value,true);const result=await context.read(['ls-files','--error-unmatch','--',filename],true);if(!result.ok)throw new Error('Select a tracked file');return filename;}
/** Structured task plans, never generic command or shell input. */
export async function prepareAdvancedGit(task:AdvancedGitTask,context:AdvancedGitContext):Promise<AdvancedGitPlan>{const f=context.fields;for(const key of Object.keys(f))if(key!=='trust'&&!definitions[task].includes(key))throw new Error(`Unknown ${task} field: ${key}`);for(const key of ['default','raw','deleteFiles','staged','working','sparseIndex','all','directories','ignored','changedPaths','bitmap'])if(f[key]!==undefined&&key!=='directories'&&typeof f[key]!=='boolean')throw new Error(`Select a Boolean for ${key}`);let argv:string[]=[],input:string|undefined,watch:string[]|undefined,destination:string|undefined;const warnings:string[]=[];const rev=()=>revision(f.revision||'HEAD');
 if(task==='notes-append'){const message=f.message;if(typeof message!=='string'||!message||message.length>65536||message.includes('\0'))throw new Error('Write a note smaller than 64 KiB');argv=['notes','append','-m',message,'--',rev()];}
 else if(task==='notes-copy')argv=['notes','copy','--',revision(f.source,'source commit'),revision(f.destination,'destination commit')];
 else if(task==='notes-merge'){const strategy=f.strategy||'manual';if(!['manual','ours','theirs','union','cat_sort_uniq'].includes(String(strategy)))throw new Error('Choose a notes merge strategy');argv=['notes','merge',`--strategy=${strategy}`,'--',revision(f.reference,'notes reference')];warnings.push('Manual conflicts create a notes merge state. Resolve its note content before finishing.');}
 else if(task==='notes-prune'){argv=['notes','prune'];warnings.push('Removes notes for unreachable objects according to Git reachability.');}
 else if(task==='notes-merge-commit'||task==='notes-merge-abort'){if(!existsSync(path.join(context.gitDir,'NOTES_MERGE_REF')))throw new Error('No notes merge is in progress');argv=['notes','merge',task.endsWith('commit')?'--commit':'--abort'];}
 else if(task==='stash-branch'){const stash=text(f.stash,'stash');if(!/^stash@\{\d+\}$/.test(stash))throw new Error('Select an existing stash');argv=['stash','branch',revision(f.name,'new branch'),stash];warnings.push('Creates a branch from the stash base, applies its saved work and drops the stash after success.');}
 else if(task==='branch-upstream')argv=['branch',`--set-upstream-to=${revision(f.upstream,'upstream branch')}`,'--',revision(f.name,'local branch')];
 else if(task==='branch-unset-upstream')argv=['branch','--unset-upstream','--',revision(f.name,'local branch')];
 else if(task==='switch-detached'){argv=['switch','--detach','--',rev()];warnings.push('Detached commits need a new branch to retain a named reference.');}
 else if(task==='sparse-add'){if(!Array.isArray(f.directories)||!f.directories.length||f.directories.length>1000)throw new Error('Select sparse directory cones');input=f.directories.map(value=>context.safePath(value,true)).join('\n')+'\n';argv=['sparse-checkout','add','--stdin'];}
 else if(task==='sparse-reapply'){argv=['sparse-checkout','reapply',f.sparseIndex?'--sparse-index':'--no-sparse-index'];warnings.push('Reapplies sparse directory rules and changes the index representation only as selected.');}
 else if(task==='worktree-move'){const selected=context.target(f.targetId);const list=await context.read(['worktree','list','--porcelain']);if(!list.output.split('\n').includes('worktree '+selected.root)||selected.root===context.root||selected.gitDir===selected.commonDir)throw new Error('Select another linked working tree, not the primary repository');const parent=await context.pickFolder?.();if(!parent)throw new Error('Choose a destination parent with the native folder picker');const directory=realpathSync(parent);const name=text(f.name,'new folder name');if(!/^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(name))throw new Error('Use a simple folder name');destination=path.join(directory,name);if(existsSync(destination))throw new Error('Choose a new destination folder');argv=['worktree','move','--',selected.root,destination];warnings.push('Moves the selected registered linked working tree directory. Git refuses locked trees or trees with submodules. Existing grants to the old location expire.');}
 else if(task==='worktree-repair'){const selected=context.target(f.targetId);if(selected.commonDir!==context.commonDir)throw new Error('Select a working tree belonging to this repository');argv=['worktree','repair','--',selected.root];}
 else if(task==='submodule-absorb')argv=['submodule','absorbgitdirs','--',context.safePath(f.path,true)];
 else if(task==='submodule-set-branch')argv=['submodule','set-branch',...(f.default?['--default']:['--branch',revision(f.branch,'submodule branch')]),'--',context.safePath(f.path,true)];
 else if(task==='submodule-set-url')argv=['submodule','set-url','--',context.safePath(f.path,true),url(f.url)];
 else if(task==='verify-commit'||task==='verify-tag'){if(!context.trust)throw new Error('Signature verification runs your configured signing program. Explicitly trust repository programs first.');argv=[task,...(f.raw?['--raw']:[]),'--',rev()];warnings.push('Verification runs the configured signing program and reports its own trust result. It does not grant repository program trust.');}
 else if(task==='move-file'){const filename=await tracked(context,f.path);const target=context.safePath(f.destination,true);if(existsSync(path.join(context.root,target)))throw new Error('Choose a new destination path');argv=['mv','--',filename,target];watch=[filename];destination=path.join(context.root,target);}
 else if(task==='remove-file'){const filename=await tracked(context,f.path);argv=['rm',...(!f.deleteFiles?['--cached']:[]),'--',filename];watch=[filename];warnings.push(f.deleteFiles?'Permanently deletes this tracked working file and stages its removal. Git refuses uncommitted changes.':'Stops tracking the selected file and preserves its working contents.');}
 else if(task==='restore-file'){const filename=await tracked(context,f.path);if(!f.staged&&!f.working)throw new Error('Select index, working file or both');argv=['restore',`--source=${rev()}`,...(f.staged?['--staged']:[]),...(f.working?['--worktree']:[]),'--',filename];watch=[filename];warnings.push('Replaces the selected index and/or working file from the chosen revision. Existing changes in those selected locations are discarded.');}
 else if(task==='index-properties'){const filename=await tracked(context,f.path);const flags:Record<string,string>={'assume-unchanged':'--assume-unchanged','check-for-changes':'--no-assume-unchanged','skip-worktree':'--skip-worktree','include-worktree':'--no-skip-worktree','executable':'--chmod=+x','not-executable':'--chmod=-x'};const property=text(f.property,'index property');if(!flags[property])throw new Error('Choose a supported index property');argv=['update-index',flags[property],'--',filename];watch=[filename];warnings.push('Assume-unchanged and skip-worktree can hide local changes from ordinary status. Inspect index flags before changing files.');}
 else if(task==='bundle-create'||task==='archive'){const directory=f.directory==='.'?'.':context.safePath(f.directory,true);if(!existsSync(path.join(context.root,directory))||!statSync(path.join(context.root,directory)).isDirectory())throw new Error('Choose an existing approved output directory');const filename=text(f.name,'output filename');if(!/^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(filename))throw new Error('Use a simple output filename');destination=path.join(context.root,directory,filename);if(existsSync(destination))throw new Error('Output file already exists');if(task==='bundle-create'){argv=['bundle','create',destination,...(f.all?['--all']:[rev()])];warnings.push('The bundle contains selected Git objects and history. Review its contents before sharing.');}else{const format=f.format||'zip';if(!['zip','tar'].includes(String(format)))throw new Error('Choose ZIP or TAR');const prefix=text(f.prefix,'archive prefix',false);if(prefix&&(path.isAbsolute(prefix)||prefix.split('/').includes('..')))throw new Error('Archive prefix must be relative');argv=['archive',`--format=${format}`,`--output=${destination}`,...(prefix?[`--prefix=${prefix}`]:[]),'--',rev()];warnings.push('The archive exports tracked contents from the selected revision. Untracked files are excluded.');}}
 else if(task==='bundle-unbundle'||task==='bundle-fetch'){const file=context.imported(f.fileId);argv=task==='bundle-unbundle'?['bundle','unbundle','--',file.file]:['fetch','--',file.file,`${revision(f.source,'bundle source')}:${revision(f.destination,'local destination')}`];warnings.push('Imports reviewed bundle objects. Bundle fetch also updates the selected local reference. No network remote is contacted.');}
 else if(task==='clean-files'){if(!Array.isArray(f.paths)||!f.paths.length||f.paths.length>1000)throw new Error('Select untracked files');const filenames=f.paths.map(value=>context.safePath(value));if(f.directories!==undefined&&typeof f.directories!=='boolean')throw new Error('Select directory deletion explicitly');if(f.ignored)throw new Error('Ignored-file deletion needs a separate inventory and is not enabled here');for(const filename of filenames)if(!context.snapshot.files.find(file=>file.path===filename&&file.untracked))throw new Error('Choose currently untracked files only');argv=['clean','-f',...(f.directories?['-d']:[]),'--',...filenames];watch=filenames;warnings.push('Permanently deletes only the selected untracked paths. Git never removes nested repositories without additional force, which this task does not offer.');}
 else if(task==='reflog-delete'){const reference=revision(f.reference,'full reference');if(reference!=='HEAD'&&!reference.startsWith('refs/'))throw new Error('Choose HEAD or a full refs/ reference');argv=['reflog','delete','--',`${reference}@{${number(f.entry,0,0,1000000)}}`];warnings.push('Removes this exact reflog recovery entry. Commit references remain unchanged.');}
 else if(task==='remote-prune'){const remote=text(f.remote,'remote');if(!/^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(remote))throw new Error('Select a remote');argv=['remote','prune','--',remote];warnings.push('Queries the selected remote and removes local tracking references that no longer exist there.');}
 else if(task==='repack'){const mode=f.mode||'incremental';if(!['incremental','all','all-delete-old'].includes(String(mode)))throw new Error('Choose a packing mode');argv=['repack',...(mode==='incremental'?[]:mode==='all'?['-a']:['-a','-d'])];warnings.push('Repacking changes object storage. Delete old packs only when that explicit mode is selected.');}
 else if(task==='prune-objects'){argv=['prune',`--expire=${number(f.days,90,1,3650)}.days.ago`];warnings.push('Permanently removes unreachable loose objects older than the selected retention age. Lost commits may become unrecoverable.');}
 else if(task==='commit-graph-write')argv=['commit-graph','write','--reachable',...(f.changedPaths?['--changed-paths']:[])];
 else if(task==='multi-pack-write')argv=['multi-pack-index','write',...(f.bitmap?['--bitmap']:[])];
 return {argv,warnings,input,watch,destination};}
