import {createHash,randomUUID} from 'node:crypto';
import {existsSync,lstatSync,realpathSync,readFileSync,mkdtempSync,readdirSync,rmSync} from 'node:fs';
import path from 'node:path';
import {redactGit} from './git-process';
import type {GitResponse,GitResult} from '../shared/git';

export interface MailInput {file:string;hash:string;}
export interface MailGrant {bytes:Buffer;bindings:MailInput[];expires:number;amOptions:string[];identity:string;splitPolicy:string;}
interface Context {directory:string;now:()=>number;source:(id:string)=>MailInput|undefined;register:(grant:MailGrant)=>string;run:(root:string,argv:string[],input:Buffer)=>Promise<GitResult&{nativeHash?:string}>;}
interface Part {id:string;bytes:Buffer;source:MailInput;expires:number;number:number;splitPolicy:string;}
const LIMIT=2097152;
function digest(bytes:Buffer|string){return createHash('sha256').update(bytes).digest('hex');}
function exact(fields:Record<string,unknown>,keys:string[]){if(!fields||typeof fields!=='object'||Array.isArray(fields)||Object.keys(fields).some(key=>!keys.includes(key)))throw new Error('Use only typed patch-mail fields');}
function flag(fields:Record<string,unknown>,key:string,fallback=false){const value=fields[key]===undefined?fallback:fields[key];if(typeof value!=='boolean')throw new Error('Choose an explicit Boolean for '+key);return value;}
function text(bytes:Buffer){const value=bytes.toString('utf8');if(bytes.length>LIMIT||value.includes('\0')||!Buffer.from(value,'utf8').equals(bytes))throw new Error('Mail preview must be UTF-8 text within the 2 MiB limit');if(redactGit(value)!==value)throw new Error('Use a protected mail editor for messages containing recognized credentials');return value;}
function selected(source:MailInput){if(!existsSync(source.file)||realpathSync(source.file)!==source.file||!lstatSync(source.file).isFile()||lstatSync(source.file).size>LIMIT)throw new Error('Native mail input path or size changed');const bytes=readFileSync(source.file);if(digest(bytes)!==source.hash)throw new Error('Native mail input changed. Choose it again');if(redactGit(bytes.toString('utf8'))!==bytes.toString('utf8'))throw new Error('Use a protected mail editor for messages containing recognized credentials');return bytes;}
function nativeSuccess(result:GitResult&{nativeHash?:string}){if(!result.ok)throw new Error(result.error||'Native patch-mail inspection stopped');if(result.nativeHash&&createHash('sha256').update(result.output).update(result.error).digest('hex')!==result.nativeHash)throw new Error('Use a protected mail editor for decoded messages containing recognized credentials');}

/** Mail parsing writes owned temporary outputs only; mutations need a separate native review. */
export class GitMailTools {
 private parts=new Map<string,Part>();
 constructor(private context:Context){}
 clear(){this.parts.clear();}
 async split(root:string,fields:Record<string,unknown>):Promise<GitResponse>{
  exact(fields,['fileId','bare','keepCR','mboxrd']);if(typeof fields.fileId!=='string')throw new Error('Choose a mailbox with the native picker');const source=this.context.source(fields.fileId);if(!source)throw new Error('Native mailbox grant expired');const bytes=selected(source);if((bytes.toString('latin1').match(/^From /gm)||[]).length>500)throw new Error('Mailbox exceeds the 500-message split limit');const directory=mkdtempSync(path.join(this.context.directory,'mail-split-'));
  try{
   const result=await this.context.run(root,['mailsplit',...(flag(fields,'bare',true)?['-b']:[]),...(flag(fields,'keepCR')?['--keep-cr']:[]),...(flag(fields,'mboxrd')?['--mboxrd']:[]),'-d4',`-o${directory}`,'--'],bytes);nativeSuccess(result);selected(source);const names=readdirSync(directory).sort();if(!names.length||names.length>500||names.some(name=>!/^\d{4}$/.test(name))||Number(result.output.trim())!==names.length)throw new Error('Native mailbox split returned an invalid message set');for(const [id,part] of this.parts)if(part.expires<this.context.now())this.parts.delete(id);if(this.parts.size+names.length>2000)throw new Error('Clear or reopen the workspace before splitting more mail');const expires=this.context.now()+300000;let total=0;
   const messages=names.map((name,index)=>{const file=path.join(directory,name),stat=lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||realpathSync(file)!==file||stat.size>LIMIT||(total+=stat.size)>LIMIT*2)throw new Error('Separated messages exceed the native input limit');return {id:randomUUID(),bytes:readFileSync(file),size:stat.size,index};});
   if([...this.parts.values()].reduce((size,part)=>size+part.bytes.length,0)+total>33554432)throw new Error('Separated mail storage exceeds the 32 MiB session limit');for(const message of messages)this.parts.set(message.id,{id:message.id,bytes:message.bytes,source,expires,number:message.index+1,splitPolicy:`Single email: ${flag(fields,'bare',true)}; CRLF: ${flag(fields,'keepCR')?'preserved':'normalized'}; mailbox From escaping: ${flag(fields,'mboxrd')?'decoded':'unchanged'}`});return {kind:'mailbox',messages:messages.map(message=>({id:message.id,label:'Message '+(message.index+1),detail:message.size+' bytes'})),expiresAt:new Date(expires).toISOString()};
  }finally{rmSync(directory,{recursive:true,force:true});}
 }
 async preview(root:string,fields:Record<string,unknown>):Promise<GitResponse>{
  exact(fields,['partId','keepSubject','keepNonPatch','messageId','scissors','quotedCR']);const part=typeof fields.partId==='string'?this.parts.get(fields.partId):undefined;if(!part||part.expires<this.context.now())throw new Error('Separated mail message expired. Split the native source again');selected(part.source);const keepSubject=flag(fields,'keepSubject'),keepNonPatch=flag(fields,'keepNonPatch'),messageId=flag(fields,'messageId'),scissors=flag(fields,'scissors'),quotedCR=fields.quotedCR===undefined?'warn':fields.quotedCR;if(typeof quotedCR!=='string'||!['warn','strip','nowarn'].includes(quotedCR))throw new Error('Choose a supported quoted line-ending policy');if(keepSubject&&keepNonPatch)throw new Error('Choose subject preservation or non-patch-prefix preservation');const directory=mkdtempSync(path.join(this.context.directory,'mail-info-')),message=path.join(directory,'message.txt'),patch=path.join(directory,'patch.txt');
  try{
   const options=[...(keepSubject?['-k']:[]),...(keepNonPatch?['-b']:[]),...(messageId?['--message-id']:[]),scissors?'--scissors':'--no-scissors',`--quoted-cr=${quotedCR}`],result=await this.context.run(root,['mailinfo','--encoding=UTF-8',...options,'--',message,patch],part.bytes);nativeSuccess(result);selected(part.source);for(const file of [message,patch]){const stat=lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||realpathSync(file)!==file||stat.size>LIMIT)throw new Error('Mail extraction output exceeds its native text limit');}const content=text(readFileSync(message)),patchText=text(readFileSync(patch)),metadata:Record<string,string>={};for(const line of result.output.split('\n').filter(Boolean)){const match=line.match(/^(Author|Email|Subject|Date): (.*)$/);if(!match)throw new Error('Native mail extraction returned unexpected metadata');metadata[match[1].toLowerCase()]=match[2];}if(!metadata.author||!metadata.email||!metadata.subject)throw new Error('Selected mail has no complete author, email and subject');if(Buffer.byteLength(content+patchText+result.output,'utf8')>LIMIT)throw new Error('Combined mail preview exceeds the 2 MiB output limit');
   const amOptions=['--utf8',...(keepSubject?['--keep']:[]),...(keepNonPatch?['--keep-non-patch']:[]),...(messageId?['--message-id']:[]),scissors?'--scissors':'--no-scissors',`--quoted-cr=${quotedCR}`],fileId=patchText.trim()?this.context.register({bytes:part.bytes,bindings:[part.source],expires:part.expires,amOptions,identity:`Message ${part.number} from ${path.basename(part.source.file)}: ${metadata.subject} · ${metadata.author} <${metadata.email}> · SHA-256 ${digest(part.bytes)}`,splitPolicy:part.splitPolicy}):'';return {kind:'mail-preview',fileId,author:metadata.author,email:metadata.email,subject:metadata.subject,date:metadata.date||'',message:content,patch:patchText,warning:result.error,expiresAt:new Date(part.expires).toISOString()};
  }finally{rmSync(directory,{recursive:true,force:true});}
 }
}
