export interface TrailerEntry {key:string;value:string;}
export function trailerDraft(fields:Record<string,unknown>){
 if(!fields||typeof fields!=='object'||Array.isArray(fields)||Object.keys(fields).some(key=>!['message','mode','entries','placement','duplicates','missing','trimEmpty','noDivider','trust'].includes(key)))throw new Error('Choose structured message metadata fields');
 if(typeof fields.message!=='string'||fields.message.length>65536||fields.message.includes('\0'))throw new Error('Enter a message smaller than 64 KiB');
 const mode=fields.mode??'edit';if(!['edit','parse'].includes(String(mode)))throw new Error('Choose message preview or existing metadata parsing');for(const key of ['trimEmpty','noDivider','trust'])if(fields[key]!==undefined&&typeof fields[key]!=='boolean')throw new Error('Choose Boolean message metadata options');
 const argv=['interpret-trailers','--no-in-place',...(fields.noDivider===false?[]:['--no-divider'])];
 if(mode==='parse'){if(fields.entries!==undefined&&(!Array.isArray(fields.entries)||fields.entries.length))throw new Error('Parsing does not add message metadata');argv.push('--parse');}
 else{const placement=fields.placement??'end',duplicates=fields.duplicates??'addIfDifferentNeighbor',missing=fields.missing??'add';if(!['after','before','end','start'].includes(String(placement))||!['addIfDifferent','addIfDifferentNeighbor','add','replace','doNothing'].includes(String(duplicates))||!['doNothing','add'].includes(String(missing)))throw new Error('Choose defined message metadata policies');argv.push(`--where=${placement}`,`--if-exists=${duplicates}`,`--if-missing=${missing}`);if(fields.trimEmpty)argv.push('--trim-empty');const entries=fields.entries??[];if(!Array.isArray(entries)||entries.length>50)throw new Error('Choose at most fifty metadata rows');for(const entry of entries){if(!entry||typeof entry!=='object'||Object.keys(entry).some(key=>!['key','value'].includes(key))||typeof entry.key!=='string'||!/^[A-Za-z0-9][A-Za-z0-9-]{0,79}$/.test(entry.key)||typeof entry.value!=='string'||entry.value.length>2048||/[\0\r\n]/.test(entry.value))throw new Error('Each metadata row needs a bounded ASCII key and single-line value');argv.push('--trailer',entry.key+': '+entry.value);}}
 argv.push('--');return {argv,input:fields.message,parse:mode==='parse'};
}
export function pullRequestDraft(fields:Record<string,unknown>,reference:(value:unknown,label?:string)=>string){
 if(!fields||typeof fields!=='object'||Array.isArray(fields)||Object.keys(fields).some(key=>!['start','end','remote','sourceId','remoteRef','patch','trust'].includes(key)))throw new Error('Choose a repository and structured commit range');for(const key of ['patch','trust'])if(fields[key]!==undefined&&typeof fields[key]!=='boolean')throw new Error('Choose Boolean pull draft options');
 if(!!fields.remote===!!fields.sourceId)throw new Error('Choose exactly one configured remote or approved local source repository');
 return {start:reference(fields.start,'upstream starting commit'),end:reference(fields.end||'HEAD','local ending commit'),remoteRef:fields.remoteRef?reference(fields.remoteRef,'advertised ending reference'):undefined,patch:fields.patch===true,trust:fields.trust===true};
}
export function draftRemoteUrl(value:string){const scp=/^[A-Za-z0-9_.-]+@[A-Za-z0-9.-]+:[^\s?#]+$/.test(value);if(scp)return value;let parsed:URL;try{parsed=new URL(value);}catch{throw new Error('Choose an HTTPS or SSH remote without credentials');}if(!['https:','ssh:'].includes(parsed.protocol)||parsed.password||parsed.protocol==='https:'&&parsed.username||parsed.search||parsed.hash)throw new Error('Choose an HTTPS or SSH remote without embedded credentials or query data');return value;}
