import type {GitRow} from '../shared/git';
interface Context {page:number;revision:string;path?:string;fields:Record<string,unknown>;safePath:(value:unknown,missing?:boolean)=>string;}
function number(value:unknown,fallback:number,min:number,max:number){const result=value??fallback;if(typeof result!=='number'||!Number.isInteger(result)||result<min||result>max)throw new Error(`Choose a whole number from ${min} to ${max}`);return result;}
function text(value:unknown,label:string){if(value===undefined||value==='')return '';if(typeof value!=='string'||value.length>1000||/[\0\r\n]/.test(value))throw new Error(`Choose a valid ${label}`);return value;}
export function gitInspectorArguments(kind:string,context:Context):string[]{const f=context.fields,allowed:Record<string,string[]>={blame:['start','count','ignoreWhitespace','moved','copied'],reflog:['grep','caseInsensitive'],search:['grep','grepRegex','caseInsensitive','source','context']};if(!allowed[kind])throw new Error('Choose a supported detailed inspector');for(const key of Object.keys(f))if(!allowed[kind].includes(key))throw new Error(`Unknown ${kind} field: ${key}`);for(const key of ['ignoreWhitespace','moved','copied','grepRegex','caseInsensitive'])if(f[key]!==undefined&&typeof f[key]!=='boolean')throw new Error(`Choose a Boolean for ${key}`);
 if(kind==='blame'){const start=number(f.start,1,1,10000000),count=number(f.count,200,1,200);return ['blame','--no-textconv','--line-porcelain',...(f.ignoreWhitespace?['-w']:[]),...(f.moved?['-M']:[]),...(f.copied?['-C']:[]),'-L',`${start},+${count+1}`,context.revision,'--',context.safePath(context.path,true)];}
 if(kind==='reflog'){const grep=text(f.grep,'recovery message');return ['reflog','show','-z','--format=%H%x00%gd%x00%gn%x00%gs','--max-count=101',`--skip=${context.page*100}`,'--fixed-strings',...(grep?[`--grep-reflog=${grep}`]:[]),...(f.caseInsensitive?['--regexp-ignore-case']:[]),context.revision,'--'];}
 const grep=text(f.grep,'content search');if(!grep)throw new Error('Write a tracked content search');const source=f.source||'working';if(!['working','index','revision'].includes(String(source)))throw new Error('Choose working files, index or revision');return ['grep','--no-textconv','--line-number','--column','-I',f.grepRegex?'--perl-regexp':'--fixed-strings',...(f.caseInsensitive?['--ignore-case']:[]),`--context=${number(f.context,0,0,20)}`,...(source==='index'?['--cached']:[]),'-e',grep,...(source==='revision'?[context.revision]:[]),'--',...(context.path?[context.safePath(context.path,true)]:[])];}
export function parseGitBlame(output:string):GitRow[]{const rows:GitRow[]=[];let data:Record<string,string>={};for(const line of output.split('\n')){const header=line.match(/^([a-f0-9]{40,64}) (\d+) (\d+)(?: \d+)?$/);if(header){data={hash:header[1],original:header[2],line:header[3]};continue;}if(line.startsWith('\t')){if(!data.hash)throw new Error('Invalid native attribution framing');rows.push({id:data.hash+':'+data.line,label:line.slice(1),detail:`Line ${data.line} · ${data.author||'Unknown'} · ${(data.hash||'').slice(0,12)}`,data:{...data}});continue;}const separator=line.indexOf(' ');if(separator>0)data[line.slice(0,separator)]=line.slice(separator+1);}return rows;}
export function parseGitReflog(output:string):GitRow[]{const fields=output.split('\0');if(fields.at(-1)==='')fields.pop();if(fields.length%4)throw new Error('Invalid native reflog framing');const rows:GitRow[]=[];for(let index=0;index<fields.length;index+=4){const [hash,selector,actor,subject]=fields.slice(index,index+4);if(!/^[a-f0-9]{40,64}$/.test(hash))throw new Error('Invalid recovery object ID');rows.push({id:selector,label:subject,detail:`${selector} · ${actor} · ${hash.slice(0,12)}`,data:{hash,selector,actor}});}return rows;}
