import {createHash} from 'node:crypto';import {existsSync,lstatSync,realpathSync,readdirSync,readFileSync} from 'node:fs';import path from 'node:path';
export const MAX_PACK_INPUT=134217728;
export function packBytes(file:string,hash:string){const stat=lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||realpathSync(file)!==file||stat.size>MAX_PACK_INPUT)throw new Error('Choose an unchanged regular pack input smaller than 128 MiB');const bytes=readFileSync(file);if(createHash('sha256').update(bytes).digest('hex')!==hash)throw new Error('Imported pack input changed. Choose it again.');return bytes;}
export function validatePackHeader(bytes:Buffer){if(bytes.length<32||bytes.subarray(0,4).toString('ascii')!=='PACK'||![2,3].includes(bytes.readUInt32BE(4)))throw new Error('Choose a supported Git pack file');const objects=bytes.readUInt32BE(8);if(objects>1000000)throw new Error('Pack object count exceeds the inspected input limit');return {version:bytes.readUInt32BE(4),objects};}
export function packChecksum(bytes:Buffer,format:string){validatePackHeader(bytes);if(!['sha1','sha256'].includes(format))throw new Error('Unsupported repository object format');const length=format==='sha1'?20:32;if(bytes.length<12+length)throw new Error('Pack file is incomplete');const expected=bytes.subarray(bytes.length-length).toString('hex'),actual=createHash(format).update(bytes.subarray(0,bytes.length-length)).digest('hex');if(expected!==actual)throw new Error('Pack checksum does not match its contents');return expected;}
export function packStore(commonDir:string){const objects=path.join(commonDir,'objects'),directory=path.join(objects,'pack');if(!existsSync(objects)||realpathSync(objects)!==objects||!lstatSync(objects).isDirectory())throw new Error('Repository object storage is outside the approved metadata');const hash=createHash('sha256').update(objects);if(!existsSync(directory))return {directory,fingerprint:hash.update('missing-pack-directory').digest('hex')};if(realpathSync(directory)!==directory||!lstatSync(directory).isDirectory())throw new Error('Repository pack directory changed');const names=readdirSync(directory).sort();if(names.length>10000)throw new Error('Repository pack metadata exceeds the reviewed input limit');for(const name of names){const file=path.join(directory,name),stat=lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||realpathSync(file)!==file)throw new Error('Repository pack files must be regular files without links');hash.update(name).update(String(stat.size)).update(String(stat.mtimeMs)).update(String(stat.ctimeMs)).update(String(stat.ino));}return {directory,fingerprint:hash.digest('hex')};}
export function packDestinations(directory:string,id:string){return ['pack','idx','keep','rev','bitmap','promisor','mtimes'].map(extension=>path.join(directory,`pack-${id}.${extension}`));}
export function parsePackIndex(output:string){return output.split('\n').filter(Boolean).map(line=>{const match=line.match(/^(\d+) ([a-f0-9]{40}(?:[a-f0-9]{24})?)(?: \(([a-f0-9]+)\))?$/);if(!match)throw new Error('Git returned an unexpected pack index entry');return {id:match[2],label:match[2].slice(0,12),detail:'Offset '+match[1]+(match[3]?' · CRC '+match[3]:''),data:{object:match[2],offset:match[1],crc:match[3]||''}};});}
export function validatePackIndex(bytes:Buffer,format?:string){
 if(bytes.length<1024)throw new Error('Choose a complete Git pack index');const modern=bytes.subarray(0,4).equals(Buffer.from([255,116,79,99])),base=modern?8:0;if(modern&&bytes.readUInt32BE(4)!==2||bytes.length<base+1024)throw new Error('Unsupported pack index version');let total=0;for(let i=0;i<256;i++){const count=bytes.readUInt32BE(base+i*4);if(count<total||count>1000000)throw new Error('Pack index fanout is invalid or exceeds the object limit');total=count;}if(!format)return {objects:total,version:modern?2:1};if(!['sha1','sha256'].includes(format))throw new Error('Unsupported repository object format');const length=format==='sha1'?20:32;let expected=base+1024+total*(length+(modern?8:4))+2*length;if(modern){const offsetTable=base+1024+total*(length+4);if(bytes.length<expected)throw new Error('Pack index object table is incomplete');let large=0;const indices:number[]=[];for(let i=0;i<total;i++){const offset=bytes.readUInt32BE(offsetTable+i*4);if(offset&0x80000000){large++;indices.push(offset&0x7fffffff);}}if(indices.some(index=>index>=large))throw new Error('Pack index large-offset table is invalid');expected+=large*8;}if(bytes.length!==expected)throw new Error('Pack index length or repository object format does not match');if(createHash(format).update(bytes.subarray(0,bytes.length-length)).digest('hex')!==bytes.subarray(bytes.length-length).toString('hex'))throw new Error('Pack index checksum does not match its contents');return {objects:total,version:modern?2:1};
}
