import {mkdtempSync,readFileSync,writeFileSync,statSync,lstatSync,realpathSync,existsSync,rmSync} from 'node:fs';
import path from 'node:path';import {createHash,randomUUID} from 'node:crypto';import {redactGit} from './git-process';import type {GitResult,GitResponse} from '../shared/git';
interface FileGrant {file:string;hash:string;}
export interface GitMergeSave {previewId:string;file:string;content:string;bindings:FileGrant[];}
interface Preview {id:string;text:string;conflicts:number;expires:number;bindings:FileGrant[];}
interface Context {temporaryDirectory:string;now:()=>number;source:(id:string)=>FileGrant|undefined;run:(root:string,argv:string[])=>Promise<GitResult&{nativeHash?:string}>;}
function hash(content:Buffer|string){return createHash('sha256').update(content).digest('hex');}
function text(content:Buffer){const decoded=content.toString('utf8');if(decoded.includes('\0')||!Buffer.from(decoded,'utf8').equals(content))throw new Error('Choose UTF-8 text files without binary bytes');if(redactGit(decoded)!==decoded)throw new Error('Use a protected editor for files containing recognized credentials');return decoded;}
function exact(fields:Record<string,unknown>,allowed:string[]){if(!fields||typeof fields!=='object'||Array.isArray(fields))throw new Error('Use structured file merge fields');for(const key of Object.keys(fields))if(!allowed.includes(key))throw new Error(`Unknown file merge field: ${key}`);}
function choice(value:unknown,fallback:string,allowed:string[]){const selected=value??fallback;if(typeof selected!=='string'||!allowed.includes(selected))throw new Error('Choose a supported merge presentation');return selected;}
/** Native-picked input grants are copied into owned files; originals are never merge targets. */
export class GitFileMerges {
 private previews=new Map<string,Preview>();constructor(private context:Context){}
 private source(id:unknown){if(typeof id!=='string')throw new Error('Choose all three inputs with the native file picker');const grant=this.context.source(id);if(!grant)throw new Error('Selected file grant expired');if(!existsSync(grant.file)||realpathSync(grant.file)!==grant.file||!lstatSync(grant.file).isFile()||statSync(grant.file).size>2097152)throw new Error('Selected input path or size changed');const bytes=readFileSync(grant.file);if(hash(bytes)!==grant.hash)throw new Error('Selected input changed. Pick the file again');return {grant,content:text(bytes)};}
 async preview(root:string,fields:Record<string,unknown>):Promise<GitResponse>{exact(fields,['currentId','baseId','incomingId','style','favor','algorithm','markerSize']);const style=choice(fields.style,'merge',['merge','diff3','zdiff3']),favor=choice(fields.favor,'normal',['normal','ours','theirs','union']),algorithm=choice(fields.algorithm,'histogram',['myers','minimal','patience','histogram']);const markerSize=fields.markerSize??7;if(typeof markerSize!=='number'||!Number.isInteger(markerSize)||markerSize<3||markerSize>64)throw new Error('Choose a marker size from 3 to 64');const sources=[this.source(fields.currentId),this.source(fields.baseId),this.source(fields.incomingId)],directory=mkdtempSync(path.join(this.context.temporaryDirectory,'merge-files-'));try{const files=sources.map((source,index)=>{const file=path.join(directory,String(index)+'.txt');writeFileSync(file,source.content,{flag:'wx',mode:0o600});return file;});const result=await this.context.run(root,['merge-file','--stdout',...(style==='merge'?[]:[`--${style}`]),...(favor==='normal'?[]:[`--${favor}`]),`--diff-algorithm=${algorithm}`,`--marker-size=${markerSize}`,'-L','Current','-L','Base','-L','Incoming','--',...files]);if(result.cancelled)throw new Error('File merge preview cancelled');if(result.exitCode===null||result.exitCode<0||result.exitCode>127||result.error)throw new Error(result.error||'Git could not preview this file merge');if(result.nativeHash&&hash(result.output)!==result.nativeHash)throw new Error('Use a protected editor for merged results containing recognized credentials');if(Buffer.byteLength(result.output,'utf8')>2097152)throw new Error('Merged result exceeds the safe preview limit');const id=randomUUID(),expires=this.context.now()+300000;for(const [key,preview] of this.previews)if(preview.expires<this.context.now())this.previews.delete(key);if(this.previews.size>=16)this.previews.delete(this.previews.keys().next().value!);this.previews.set(id,{id,text:result.output,conflicts:result.exitCode,expires,bindings:sources.map(source=>source.grant)});return {kind:'merge-preview',previewId:id,text:result.output,conflicts:result.exitCode,expiresAt:new Date(expires).toISOString()};}finally{rmSync(directory,{recursive:true,force:true});}}
 async prepareSave(fields:Record<string,unknown>,pickFolder:(()=>Promise<string|null>)|undefined,forbidden:string[]):Promise<GitMergeSave>{exact(fields,['previewId','name','content','allowConflicts','trust']);const preview=typeof fields.previewId==='string'?this.previews.get(fields.previewId):undefined;if(!preview||preview.expires<this.context.now())throw new Error('File merge preview expired. Preview the selected files again');const name=fields.name;if(typeof name!=='string'||!name||Buffer.byteLength(name,'utf8')>255||name.startsWith('-')||name==='.'||name==='..'||/[\0\r\n\\/]/.test(name))throw new Error('Choose a fresh output filename');const content=fields.content??preview.text;if(typeof content!=='string'||Buffer.byteLength(content,'utf8')>2097152||content.includes('\0'))throw new Error('Merged result must be text smaller than 2 MiB');text(Buffer.from(content,'utf8'));if(fields.allowConflicts!==undefined&&typeof fields.allowConflicts!=='boolean')throw new Error('Choose unresolved-result saving explicitly');if(/^(?:<{3,64} |={3,64}$|>{3,64} |\|{3,64} )/m.test(content)&&fields.allowConflicts!==true)throw new Error('Resolve conflict markers or explicitly allow saving an unresolved result');const selected=await pickFolder?.();if(!selected)throw new Error('Choose the output directory with the native folder picker');const parent=realpathSync(selected);if(!statSync(parent).isDirectory()||/[\\/]\.git(?:[\\/]|$)/i.test(parent)||forbidden.some(root=>parent===root||parent.startsWith(root+path.sep)))throw new Error('Choose an output folder outside Git metadata');const file=path.join(parent,name);if(existsSync(file))throw new Error('Output already exists. Choose a new name; existing files are never overwritten');return {previewId:preview.id,file,content,bindings:preview.bindings};}
 save(plan:GitMergeSave){const preview=this.previews.get(plan.previewId);if(!preview||preview.expires<this.context.now())throw new Error('File merge preview expired or was already saved');if(realpathSync(path.dirname(plan.file))!==path.dirname(plan.file))throw new Error('Output directory changed');for(const binding of plan.bindings){if(!existsSync(binding.file)||realpathSync(binding.file)!==binding.file||!lstatSync(binding.file).isFile()||hash(readFileSync(binding.file))!==binding.hash)throw new Error('Selected merge input changed. Preview again');}writeFileSync(plan.file,plan.content,{flag:'wx',mode:0o600});this.previews.delete(plan.previewId);return path.basename(plan.file);}
}
