import type {AdvancedGitContext,AdvancedGitPlan} from './git-advanced';
export const objectTasks={'object-store':['fileId'],'index-tree':[],'create-commit-object':['tree','parents','message'],'create-tag-object':['object','name','tagger','email','message'],'load-index-tree':['mode','trees'],'checkout-index-file':['path','overwrite'],'index-entry':['path','object','mode']} as const;
export type GitObjectTask=keyof typeof objectTasks;
function line(value:unknown,label:string){if(typeof value!=='string'||!value||value.length>1000||/[\0\r\n]/.test(value)||value.startsWith('-'))throw new Error(`Choose a valid ${label}`);return value;}
function reference(value:unknown,label:string){const result=line(value,label);if(!/^[A-Za-z0-9_][A-Za-z0-9_./~^-]*$/.test(result)||result.includes('..')||result.includes('//'))throw new Error(`Choose a valid ${label}`);return result;}
function message(value:unknown){if(typeof value!=='string'||!value||value.length>65536||value.includes('\0'))throw new Error('Write an object message smaller than 64 KiB');return value.endsWith('\n')?value:value+'\n';}
async function object(context:AdvancedGitContext,value:unknown,type?:'tree'|'commit'|'blob'){const ref=reference(value,'object or reference');const resolved=await context.read(['rev-parse','--verify',`${ref}^{${type||'object'}}`]);const hash=resolved.output.trim();if(!/^[a-f0-9]{40,64}$/.test(hash))throw new Error('Git did not resolve a valid object ID');if(type==='blob'){const actual=await context.read(['cat-file','-t',hash]);if(actual.output.trim()!=='blob')throw new Error('Choose a stored blob object');}return hash;}
/** Dedicated object and index workflows. No shell grammar or raw index records cross IPC. */
export async function prepareGitObject(task:GitObjectTask,context:AdvancedGitContext):Promise<AdvancedGitPlan>{const f=context.fields;const warnings:string[]=[];let argv:string[]=[],input:string|undefined,watch:string[]|undefined;
 if(task==='object-store'){const source=context.imported(f.fileId);argv=['hash-object','-w','--no-filters','--',source.file];warnings.push('Stores the exact native-picked bytes as a blob. No clean filter runs. The returned object ID is not attached to a branch or index entry.');}
 else if(task==='index-tree'){argv=['write-tree'];warnings.push('Stores a tree from the reviewed index. Unresolved index entries prevent tree creation. Working files and references stay as they are.');}
 else if(task==='create-commit-object'){const tree=await object(context,f.tree,'tree');if(!Array.isArray(f.parents)||f.parents.length>8)throw new Error('Select up to eight parent commits, or an empty list for a root commit');const parents=await Promise.all(f.parents.map(value=>object(context,value,'commit')));if(new Set(parents).size!==parents.length)throw new Error('Choose distinct parent commits');argv=['commit-tree','--no-gpg-sign',tree,...parents.flatMap(parent=>['-p',parent]),'-F','-'];input=message(f.message);warnings.push('Creates an unsigned commit object from the chosen tree and parents, using configured author and committer identity. It does not move HEAD or a branch. Retain the returned object ID before pruning.');}
 else if(task==='create-tag-object'){const hash=await object(context,f.object);const type=(await context.read(['cat-file','-t',hash])).output.trim();if(!['blob','tree','commit','tag'].includes(type))throw new Error('Choose a taggable object');const name=reference(f.name,'tag name');await context.read(['check-ref-format',`refs/tags/${name}`]);const tagger=line(f.tagger,'tagger name'),email=line(f.email,'tagger email');if(/[<>]/.test(tagger)||!/^([^<>\s@]+)@([^<>\s@]+)$/.test(email))throw new Error('Use a tagger name without angle brackets and a valid email');input=`object ${hash}\ntype ${type}\ntag ${name}\ntagger ${tagger} <${email}> ${Math.floor(Date.now()/1000)} +0000\n\n${message(f.message)}`;argv=['mktag'];warnings.push('Creates an unsigned annotated tag object. A separate reviewed reference update is required to publish it as refs/tags/name.');}
 else if(task==='load-index-tree'){const mode=f.mode||'replace';if(!['replace','merge','empty'].includes(String(mode)))throw new Error('Choose replace, merge or empty index mode');if(!Array.isArray(f.trees)||f.trees.length>3)throw new Error('Choose up to three tree references');const values=f.trees as unknown[];if(mode==='empty'){if(values.length)throw new Error('Empty index mode does not accept trees');argv=['read-tree','--empty'];}else{if(mode==='replace'&&values.length!==1||mode==='merge'&&(values.length<2||values.length>3))throw new Error('Replace needs one tree; merge needs two or three trees');const trees=await Promise.all(values.map(value=>object(context,value,'tree')));argv=['read-tree',...(mode==='merge'?['-m']:[]),...trees];}warnings.push('Replaces or merges only the index. Existing staged changes may be lost and merge mode may produce unresolved stages. Working files are preserved because working-tree update is disabled.');}
 else if(task==='checkout-index-file'){if(f.overwrite!==undefined&&typeof f.overwrite!=='boolean')throw new Error('Choose overwrite explicitly');const filename=context.safePath(f.path,true);const tracked=await context.read(['ls-files','--error-unmatch','--',filename],true);if(!tracked.ok)throw new Error('Choose an indexed file');argv=['checkout-index',...(f.overwrite?['--force']:[]),'--',filename];watch=[filename];warnings.push(f.overwrite?'Overwrites this working file from its staged contents. Existing unstaged changes are permanently discarded.':'Writes this staged file only if its working destination does not already exist. Unresolved index stages are refused.');}
 else if(task==='index-entry'){const filename=context.safePath(f.path,true),mode=String(f.mode||'100644');if(!['100644','100755'].includes(mode))throw new Error('Choose a regular file index mode');const hash=await object(context,f.object,'blob');argv=['update-index','--add','--cacheinfo',mode,hash,filename];watch=[filename];warnings.push('Records this stored blob at the selected index path without running filters or changing the working file. The next commit will contain these indexed bytes.');}
 return {argv,input,watch,warnings};}
