import {AsyncLocalStorage} from 'node:async_hooks';
import {randomUUID} from 'node:crypto';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {Engine} from './engine';
import type {Operation} from '../shared/types';
import {githubDomains,githubMutationActions,type GitHubAction,type GitHubPayload,type GitHubResponse,type GitHubItem} from '../shared/github';
const mutationSchemas:Record<string,string[]>={
 'repositories.create':['name','description','visibility','readme','owner'],'repositories.edit':['description','homepage','visibility','name','archived','defaultBranch'],'repositories.delete':[],'repositories.fork':['owner','name','defaultBranchOnly'],
 'issues.create':['title','body','labels','assignees','milestone'],'issues.edit':['title','body','labels','assignees','milestone'],'issues.comment':['body'],'issues.close':['reason'],'issues.reopen':[],
 'pulls.create':['title','head','base','body','draft'],'pulls.edit':['title','body','base'],'pulls.comment':['body'],'pulls.close':[],'pulls.reopen':[],'pulls.merge':['method','deleteBranch'],'pulls.review':['event','body'],'pulls.request-review':['reviewers','teamReviewers'],
 'actions.cancel':[],'actions.rerun':['failedOnly'],'actions.rerun-failed':[],'actions.delete':[],'actions.dispatch':['ref','inputs'],'actions.enable-workflow':[],'actions.disable-workflow':[],'actions.download-artifacts':['directory','names'],
 'releases.create':['tag','title','target','notes','draft','prerelease'],'releases.edit':['title','notes','draft','prerelease'],'releases.delete':[],'releases.upload':['files'],'releases.download-assets':['directory','names'],
 'projects.create':['title','owner'],'projects.edit':['title','description','readme','public','closed'],'projects.delete':[],'projects.add-item':['url'],
 'discussions.create':['title','category','body'],'discussions.comment':['body'],'discussions.close':['reason'],'discussions.reopen':[],
 'gists.create':['description','filename','content','visibility'],'gists.edit':['description','filename','content'],'gists.delete':[],
 'codespaces.create':['repository','branch','displayName'],'codespaces.start':[],'codespaces.stop':[],'codespaces.delete':[],
 'security.dismiss':['type','reason','comment'],'organizations.invite':['login','role'],'organizations.remove-member':['login']};

const SIZE=20;
const readActions=new Set<string>(githubDomains.flatMap(domain=>[`${domain}.list`,`${domain}.detail`]).concat(['repositories.owners','discussions.categories']));
function text(value:unknown,label:string,required=false,max=4096):string {if(value===undefined||value===''){if(required)throw new Error(`Choose ${label}`);return '';}if(typeof value!=='string'||value.length>max||value.includes('\0'))throw new Error(`Invalid ${label}`);return value;}
function identifier(value:unknown,label:string):string {const result=text(value,label,true,100);if(!/^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(result))throw new Error(`Invalid ${label}`);return result;}
function repository(value:unknown):string {const result=text(value,'repository',true,200);if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(result))throw new Error('Choose an OWNER/repository');return result;}
function numericId(value:unknown):string {const result=String(value??'');if(!/^[1-9][0-9]{0,15}$/.test(result))throw new Error('Choose a positive entity number');return result;}
function nodeId(value:unknown):string {const result=text(value,'entity ID',true,200);if(!/^[A-Za-z0-9_=-]+$/.test(result))throw new Error('Invalid entity ID');return result;}
function redacted(value:unknown,depth=0):unknown {if(depth>30)return '[Depth limit]';if(typeof value==='string')return value.replace(/(?:gh[pousr]_|github_pat_)[A-Za-z0-9_]+/g,'[REDACTED]');if(Array.isArray(value))return value.slice(0,1000).map(item=>redacted(item,depth+1));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,/^(?:token|password|secret|authorization|cookie|set-cookie|access_token|refresh_token)$/i.test(key)?'[REDACTED]':redacted(item,depth+1)]));return value;}
function item(row:Record<string,unknown>):GitHubItem {const result=redacted(row) as Record<string,unknown>;return {...result,id:String(row.id??row.number??row.name??row.login??''),title:String(row.title??row.full_name??row.name??row.login??row.displayName??row.display_name??row.number??'Untitled'),subtitle:String(row.description??row.state??row.status??row.conclusion??row.visibility??''),url:typeof(row.html_url??row.url)==='string'?String(row.html_url??row.url):undefined,state:typeof row.state==='string'?row.state:undefined,...(typeof row.number==='number'?{number:row.number}:{}),...(typeof row.full_name==='string'?{repository:row.full_name}:{} )};}
export interface GitHubDependencies {authorize?:(action:GitHubAction,payload:GitHubPayload)=>Promise<void>;completed?:(action:GitHubAction,payload:GitHubPayload)=>Promise<void>;resolveHost?:(hostname?:string)=>string;cli?:(argv:string[])=>Promise<Operation>;request?:(method:string,endpoint:string,body?:Record<string,unknown>)=>Promise<{data:unknown;hasNext:boolean}>}
/** Fixed domain actions, provider-backed entities and validated main-process argument construction. */
export class GitHubService {
 private context=new AsyncLocalStorage<string>();
 private reviews=new Map<string,{action:GitHubAction;payload:GitHubPayload;account:string;expiresAt:number;hostname:string}>();
 private engine:Engine;private activeOperations=new Set<string>();private cursors=new Map<string,Map<number,string|null>>();
 constructor(private binary:string,private cwd:string,engine?:Engine,private deps:GitHubDependencies={}){this.engine=new Engine({version:'2.102.0',generatedAt:'',source:'domain service',commands:[]},cwd,binary);this.engine.subscribe(operation=>{if(operation.status==='running')this.activeOperations.add(operation.id);else this.activeOperations.delete(operation.id);});}
 cancelAll():void{for(const id of this.activeOperations)this.engine.cancel(id);}
 close():void{this.cancelAll();}
 private async request(method:string,endpoint:string,body?:Record<string,unknown>):Promise<{data:unknown;hasNext:boolean}>{if(this.deps.request)return this.deps.request(method,endpoint,body);let temporary:string|undefined;const argv=['api',`--hostname=${this.context.getStore()||'github.com'}`,'--include',`--method=${method}`];if(body){const json=JSON.stringify(body);if(json.length>65536)throw new Error('Request body exceeds 64 KiB');temporary=await mkdtemp(path.join(tmpdir(),'material-github-'));const file=path.join(temporary,'request.json');await writeFile(file,json,{mode:0o600});argv.push(`--input=${file}`);}argv.push('--',endpoint);try{const operation=this.engine.executeAdapter(`github:${method}:${endpoint.split('?')[0]}`,argv);const finished=await new Promise<ReturnType<Engine['operation']>>((resolve)=>{const unsubscribe=this.engine.subscribe(value=>{if(value.id===operation.id&&value.endedAt){unsubscribe();resolve(value);}});const current=this.engine.operation(operation.id);if(current.endedAt){unsubscribe();resolve(current);}});if(finished.status!=='succeeded')throw new Error(finished.stderr||`GitHub request ${finished.status}`);if(finished.truncated)throw new Error('GitHub response exceeds the bounded result limit. Use a narrower task or search.');const boundary=finished.stdout.search(/\r?\n\r?\n/);const headers=boundary<0?'':finished.stdout.slice(0,boundary);const bodyText=boundary<0?finished.stdout:finished.stdout.slice(boundary).replace(/^\r?\n\r?\n/,'');const data=bodyText.trim()?JSON.parse(bodyText):{};return {data:redacted(data),hasNext:/^link:.*rel="next"/im.test(headers)};}finally{if(temporary)await rm(temporary,{recursive:true,force:true});}}
 private params(base:string,payload:GitHubPayload,extra:Record<string,string>={}):string {const page=payload.page??0;const query=new URLSearchParams({per_page:String(SIZE),page:String(page+1),...extra});return `${base}?${query}`;}
 private response(data:unknown,hasNext=false,page=0,collection?:string):GitHubResponse {const object=data&&typeof data==='object'&&!Array.isArray(data)?data as Record<string,unknown>:undefined;const rows=Array.isArray(data)?data:collection&&Array.isArray(object?.[collection])?object![collection] as unknown[]:[];return {items:rows.filter((row):row is Record<string,unknown>=>!!row&&typeof row==='object'&&!Array.isArray(row)).map(item),hasNext,page,...(typeof object?.total_count==='number'?{total:object.total_count}:{}),...(object?{detail:redacted(object) as Record<string,unknown>}:{} )};}
 async handle(action:GitHubAction,payload:GitHubPayload={}):Promise<GitHubResponse>{if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('Invalid task request');const hostname=this.deps.resolveHost?this.deps.resolveHost(payload.hostname):payload.hostname||'github.com';if(!/^[a-zA-Z0-9.-]+$/.test(hostname)||!this.deps.resolveHost&&hostname!=='github.com')throw new Error('Choose an approved GitHub hostname');return this.context.run(hostname,async()=>{await this.deps.authorize?.(action,payload);return this.dispatch(action,payload);});}
 private async dispatch(action:GitHubAction,payload:GitHubPayload={}):Promise<GitHubResponse>{if(!payload||typeof payload!=='object'||Array.isArray(payload)||JSON.stringify(payload).length>128000)throw new Error('Invalid GitHub task request');for(const key of Object.keys(payload))if(!['repository','page','query','state','id','tab','values','confirmed','action','reviewId','entity','hostname'].includes(key))throw new Error(`Unknown task field: ${key}`);if(action==='choices')return this.choices(payload);if(action==='review')return this.review(payload.action!,payload);if(action==='apply'){const reviewId=text(payload.reviewId,'review',true),plan=this.reviews.get(reviewId);this.reviews.delete(reviewId);if(payload.confirmed!==true)throw new Error('Confirm the exact reviewed task');if(!plan||Date.now()>plan.expiresAt)throw new Error('Task review expired. Review again.');for(const key of Object.keys(payload))if(!['reviewId','confirmed'].includes(key))throw new Error('Apply cannot replace reviewed task values');return this.context.run(plan.hostname,async()=>{const account=await this.account();if(account!==plan.account)throw new Error('The active account changed. Review this task again.');await this.deps.authorize?.(plan.action,plan.payload);const result=await this.mutate(plan.action,plan.payload);await this.deps.completed?.(plan.action,plan.payload);return result;});}if(!readActions.has(action)&&!githubMutationActions.includes(action as typeof githubMutationActions[number]))throw new Error('Unknown GitHub task');const page=payload.page??0;if(!Number.isInteger(page)||page<0||page>100)throw new Error('Invalid page');if(githubMutationActions.includes(action as typeof githubMutationActions[number])){return this.review(action,payload);}const [domain,kind]=action.split('.');const tab=text(payload.tab,'detail tab')||'overview';const query=text(payload.query,'search query',false,300);const state=text(payload.state,'state')||(domain==='actions'?'all':'open');const states=domain==='actions'?['all','completed','action_required','cancelled','failure','neutral','skipped','stale','success','timed_out','in_progress','queued','requested','waiting','pending']:domain==='pulls'?['open','closed','all','merged']:['open','closed','all'];if(!states.includes(state))throw new Error(`Choose a supported ${domain} state`);let endpoint='',collection:string|undefined;
 if(action==='repositories.owners'){const [viewer,organizations]=await Promise.all([this.request('GET','user'),this.request('GET',this.params('user/orgs',payload))]);const rows=[viewer.data,...(Array.isArray(organizations.data)?organizations.data:[])];return this.response(rows,organizations.hasNext,page);}
 if(domain==='projects'||domain==='discussions')return this.graphRead(action,payload);
 if(kind==='list'){
 if(domain==='repositories')endpoint=query?this.params('search/repositories',payload,{q:query}):this.params('user/repos',payload,{sort:'updated',affiliation:'owner,collaborator,organization_member'});
 if(domain==='issues'){const repo=repository(payload.repository);endpoint=query?this.params('search/issues',payload,{q:`repo:${repo} is:issue ${state==='all'?'':`is:${state}`} ${query}`}):this.params(`repos/${repo}/issues`,payload,{state,sort:'updated'});}
 if(domain==='pulls'){const repo=repository(payload.repository);endpoint=query||state==='merged'?this.params('search/issues',payload,{q:`repo:${repo} is:pr ${state==='all'?'':`is:${state}`} ${query}`}):this.params(`repos/${repo}/pulls`,payload,{state,sort:'updated'});}
 if(domain==='actions'&&tab==='workflows'){endpoint=this.params(`repos/${repository(payload.repository)}/actions/workflows`,payload);collection='workflows';}
 if(domain==='actions'&&tab!=='workflows'){endpoint=this.params(`repos/${repository(payload.repository)}/actions/runs`,payload,{...(query?{branch:query}:{}),...(state==='all'?{}:{status:state})});collection='workflow_runs';}
 if(domain==='releases')endpoint=this.params(`repos/${repository(payload.repository)}/releases`,payload);
 if(domain==='gists')endpoint=this.params('gists',payload);
 if(domain==='organizations')endpoint=this.params('user/orgs',payload);
 if(domain==='codespaces'){endpoint=this.params('user/codespaces',payload);collection='codespaces';}
 if(domain==='search'){const source=['repositories','issues','code','commits','users','topics'].includes(tab)?tab:'repositories';if(!query)throw new Error('Enter a search query');endpoint=this.params(`search/${source}`,payload,{q:query});collection='items';}
 if(domain==='security'){const source=['dependabot','code-scanning','secret-scanning'].includes(tab)?tab:'dependabot';endpoint=this.params(`repos/${repository(payload.repository)}/${source}/alerts`,payload,state==='all'?{}:{state:source==='dependabot'?state==='closed'?'dismissed,fixed,auto_dismissed':'open':source==='code-scanning'?state==='closed'?'closed':'open':state==='closed'?'resolved':'open'});}
 if(endpoint.startsWith('search/'))collection='items';
 }else{
 const repo=payload.repository?repository(payload.repository):'';
 if(domain==='repositories'){if(!repo)throw new Error('Choose a repository');const suffix:Record<string,string>={overview:'',branches:'/branches',collaborators:'/collaborators',teams:'/teams'};if(!(tab in suffix))throw new Error('This repository tab has no registered provider adapter');endpoint=tab==='overview'?`repos/${repo}`:this.params(`repos/${repo}${suffix[tab]}`,payload);}
 if(domain==='issues'||domain==='pulls'){if(!repo)throw new Error('Choose a repository');const id=numericId(payload.id);const suffix:Record<string,string>={overview:'',comments:'comments',labels:'labels',assignees:'assignees',files:'files',checks:'checks',reviews:'reviews',commits:'commits'};if(!(tab in suffix)||domain==='issues'&&['files','checks','reviews','commits'].includes(tab))throw new Error('This entity tab has no registered provider adapter');if(['labels','assignees'].includes(tab)){const result=await this.request('GET',`repos/${repo}/issues/${id}`);const data=result.data as Record<string,unknown>;return this.response(data[tab],false,page);}if(tab==='checks'){const pull=await this.request('GET',`repos/${repo}/pulls/${id}`);const sha=(pull.data as {head?:{sha?:string}}).head?.sha;if(!sha||! /^[a-f0-9]{40,64}$/.test(sha))throw new Error('Pull request head SHA unavailable');endpoint=this.params(`repos/${repo}/commits/${sha}/check-runs`,payload);collection='check_runs';}else{const segment=domain==='issues'||tab==='comments'?'issues':'pulls';endpoint=tab==='overview'?`repos/${repo}/${segment}/${id}`:this.params(`repos/${repo}/${segment}/${id}/${suffix[tab]}`,payload);}}
 if(domain==='actions'){if(!repo)throw new Error('Choose a repository');if(tab==='workflows'){if(payload.id!==undefined)endpoint=`repos/${repo}/actions/workflows/${identifier(String(payload.id),'workflow')}`;else{endpoint=this.params(`repos/${repo}/actions/workflows`,payload);collection='workflows';}}else{const id=numericId(payload.id);if(tab==='overview')endpoint=`repos/${repo}/actions/runs/${id}`;else if(tab==='jobs'||tab==='artifacts'){endpoint=this.params(`repos/${repo}/actions/runs/${id}/${tab}`,payload);collection=tab;}else if(tab==='logs'){const result=await this.cli(['run','view',`--repo=${this.context.getStore()||'github.com'}/${repo}`,'--log','--',id]);return {items:[],hasNext:false,page,detail:{text:result.stdout,body:result.stdout,truncated:!!result.truncated},...(result.truncated?{notice:'The log display reached its 1 MiB output bound. Select a job in the native run viewer for a narrower log.'}:{})};}else throw new Error('This Actions tab has no registered provider adapter');}}
 if(domain==='releases'){if(!repo)throw new Error('Choose a repository');const id=numericId(payload.id);if(tab==='overview')endpoint=`repos/${repo}/releases/${id}`;else if(tab==='assets')endpoint=this.params(`repos/${repo}/releases/${id}/assets`,payload);else throw new Error('This release tab has no registered provider adapter');}
 if(domain==='gists'){const id=identifier(String(payload.id??''),'gist ID');if(tab==='overview')endpoint=`gists/${id}`;else if(tab==='comments'||tab==='commits')endpoint=this.params(`gists/${id}/${tab}`,payload);else throw new Error('This gist tab has no registered provider adapter');}
 if(domain==='organizations'){const id=identifier(String(payload.id??''),'organization');if(tab==='overview')endpoint=`orgs/${id}`;else if(['members','teams','repositories'].includes(tab))endpoint=this.params(`orgs/${id}/${tab==='repositories'?'repos':tab}`,payload);else throw new Error('This organization tab has no registered provider adapter');}
 if(domain==='codespaces'){const id=identifier(String(payload.id??''),'Codespace name');if(tab==='overview')endpoint=`user/codespaces/${id}`;else if(tab==='ports'){const result=await this.cli(['codespace','ports',`--codespace=${id}`,'--json=browseUrl,label,sourcePort,visibility']);const rows=JSON.parse(result.stdout);if(!Array.isArray(rows))throw new Error('Codespace ports returned invalid data');return this.response(rows.map(row=>({...row,id:row.sourcePort,title:row.label||String(row.sourcePort),url:row.browseUrl})),false,page);}else throw new Error('This Codespace tab has no registered provider adapter');}
 if(domain==='security'){if(!repo)throw new Error('Choose a repository');const source=['dependabot','code-scanning','secret-scanning'].includes(String(payload.values?.type||''))?String(payload.values?.type):'dependabot';const id=numericId(payload.id);if(tab==='overview')endpoint=`repos/${repo}/${source}/alerts/${id}`;else if(tab==='locations'&&source==='secret-scanning')endpoint=this.params(`repos/${repo}/secret-scanning/alerts/${id}/locations`,payload);else if(tab==='locations'&&source==='code-scanning')endpoint=this.params(`repos/${repo}/code-scanning/alerts/${id}/instances`,payload);else throw new Error('This security tab has no registered provider adapter');}
 if(domain==='search')throw new Error('Open a search result in its matching repository, issue, pull request or account task');
 }
 if(!endpoint)throw new Error('Task adapter is unavailable');const result=await this.request('GET',endpoint);const response=this.response(result.data,result.hasNext,page,collection);if(kind==='list'){if(['issues','pulls'].includes(domain))response.items=response.items.map(row=>({...row,id:String(row.number||row.id)}));if(domain==='codespaces')response.items=response.items.map(row=>({...row,id:String(row.name||row.id)}));if(domain==='organizations')response.items=response.items.map(row=>({...row,id:String(row.login||row.id)}));}if(domain==='issues'&&kind==='list'&&!query){response.items=response.items.filter(row=>!row.pull_request);if(!response.items.length&&response.hasNext)response.notice='This provider page contains only pull requests. Next follows the real remaining issue pages.';}return response;}
 private async cli(argv:string[]):Promise<Operation>{if(this.deps.cli){const result=await this.deps.cli(argv);if(result.status!=='succeeded')throw new Error(result.stderr||`GitHub task ${result.status}`);return result;}const operation=this.engine.executeAdapter('github:task',argv,{hostname:this.context.getStore()||'github.com'});const result=await new Promise<Operation>(resolve=>{const unsubscribe=this.engine.subscribe(op=>{if(op.id===operation.id&&op.endedAt){unsubscribe();resolve(op);}});const current=this.engine.operation(operation.id);if(current.endedAt){unsubscribe();resolve(current);}});if(result.status!=='succeeded')throw new Error(result.stderr||`GitHub task ${result.status}`);return result;}
 private async account():Promise<string>{const record=(await this.request('GET','user')).data as {id?:number;login?:string};if(!Number.isSafeInteger(record.id))throw new Error('Sign in again; the active account could not be verified');return String(record.id);}
 private async review(action:GitHubAction,payload:GitHubPayload):Promise<GitHubResponse>{if(!githubMutationActions.includes(action as typeof githubMutationActions[number]))throw new Error('Choose a registered mutation task');await this.deps.authorize?.(action,payload);const values=payload.values||{};if(!values||typeof values!=='object'||Array.isArray(values))throw new Error('Use structured task values');const allowed=mutationSchemas[action];if(!allowed)throw new Error('Task has no review schema');for(const key of Object.keys(values))if(!allowed.includes(key))throw new Error(`Unknown ${action} value: ${key}`);for(const [key,value] of Object.entries(values)){if(value===null||value===undefined)throw new Error(`Choose ${key}`);if(typeof value==='string'&&(value.length>50000||value.includes('\0')))throw new Error(`Invalid ${key}`);if(['draft','prerelease','deleteBranch','defaultBranchOnly','failedOnly','archived','public','closed'].includes(key)&&typeof value!=='boolean')throw new Error(`Boolean required: ${key}`);if(['labels','assignees','reviewers','teamReviewers','files','names'].includes(key)&&(!Array.isArray(value)||value.length>100||value.some(item=>typeof item!=='string'||item.includes('\0'))))throw new Error(`Choose a bounded list for ${key}`);}
 const required:Record<string,string[]>={'repositories.create':['name'],'issues.create':['title'],'issues.comment':['body'],'pulls.create':['title','head','base'],'pulls.comment':['body'],'releases.create':['tag'],'projects.create':['title'],'projects.add-item':['url'],'discussions.create':['title','category','body'],'discussions.comment':['body'],'gists.create':['filename','content'],'organizations.invite':['login'],'organizations.remove-member':['login'],'actions.dispatch':['ref'],'actions.download-artifacts':['directory'],'releases.download-assets':['directory']};for(const key of required[action]||[])text(values[key],key,true,key==='content'?50000:16000);if(action==='codespaces.create')repository(values.repository||payload.repository);
 const account=await this.account(),reviewId=randomUUID(),expiresAt=Date.now()+300000;const stored=structuredClone(payload);delete stored.action;delete stored.confirmed;delete stored.reviewId;for(const [id,plan] of this.reviews)if(plan.expiresAt<Date.now())this.reviews.delete(id);if(this.reviews.size>=100)this.reviews.delete(this.reviews.keys().next().value!);this.reviews.set(reviewId,{action,payload:stored,account,expiresAt,hostname:this.context.getStore()||'github.com'});return {items:[],hasNext:false,page:0,review:{reviewId,action,repository:payload.repository,id:payload.id,values:redacted(values) as Record<string,unknown>,expiresAt:new Date(expiresAt).toISOString(),warnings:['This task changes GitHub resources for the verified active account. Review the exact target and values.',...(/(?:delete|remove-member)$/.test(action)?['Deleting this provider resource removes its data.']:[])]}};}
 private async choices(payload:GitHubPayload):Promise<GitHubResponse>{const entity=payload.entity,repo=payload.repository?repository(payload.repository):'';const page=payload.page??0;if(!Number.isInteger(page)||page<0||page>100)throw new Error('Invalid picker page');if(entity==='projects')return this.graphRead('projects.list',payload);if(entity==='discussion-categories')return this.graphRead('discussions.categories',payload);const sources:Record<string,{endpoint:string;collection?:string;value:string}>={labels:{endpoint:`repos/${repo}/labels`,value:'name'},assignees:{endpoint:`repos/${repo}/assignees`,value:'login'},collaborators:{endpoint:`repos/${repo}/collaborators`,value:'login'},reviewers:{endpoint:`repos/${repo}/collaborators`,value:'login'},milestones:{endpoint:`repos/${repo}/milestones`,value:'number'},branches:{endpoint:`repos/${repo}/branches`,value:'name'},tags:{endpoint:`repos/${repo}/tags`,value:'name'},workflows:{endpoint:`repos/${repo}/actions/workflows`,collection:'workflows',value:'id'}};if(!entity||!sources[entity])throw new Error('Choose a registered entity picker');if(!repo)throw new Error('Choose a repository for this picker');const source=sources[entity],result=await this.request('GET',this.params(source.endpoint,payload,entity==='milestones'?{state:'open'}:{}));const response=this.response(result.data,result.hasNext,page,source.collection);response.items=response.items.map(row=>({...row,value:String(row[source.value]),label:String(row.name??row.title??row.login??row.number),title:String(row.name??row.title??row.login??row.number)}));if(payload.query){const query=text(payload.query,'picker query',false,300).toLowerCase();response.items=response.items.filter(row=>`${row.title} ${row.subtitle||''}`.toLowerCase().includes(query));response.notice='Search filters this provider page. Next continues the provider list without inventing choices.';}return response;}
 private async graph(query:string):Promise<Record<string,unknown>>{const result=await this.request('POST','graphql',{query});const object=result.data as {data?:Record<string,unknown>;errors?:{message?:string}[]};if(object.errors?.length)throw new Error(object.errors.map(error=>error.message||'GraphQL request failed').join('; '));if(!object.data)throw new Error('GitHub returned no GraphQL data');return object.data;}
 private async owner(payload:GitHubPayload):Promise<{login:string;id:string;type:'user'|'organization'}>{let login=payload.values?.owner?identifier(payload.values.owner,'owner'):payload.repository?repository(payload.repository).split('/')[0]:'';if(!login){const viewer=(await this.request('GET','user')).data as {login?:string};login=identifier(viewer.login,'active account');}const record=(await this.request('GET',`users/${login}`)).data as {node_id?:string;type?:string};return {login,id:nodeId(record.node_id),type:record.type==='Organization'?'organization':'user'};}
 private cursor(key:string,page:number):string {if(page===0)return '';const value=this.cursors.get(key)?.get(page);if(!value)throw new Error('Open the previous provider page before requesting this page');return `,after:${JSON.stringify(value)}`;}
 private remember(key:string,page:number,pageInfo:{hasNextPage?:boolean;endCursor?:string}):boolean {if(this.cursors.size>100)this.cursors.delete(this.cursors.keys().next().value!);const pages=page===0?new Map<number,string|null>([[0,null]]):this.cursors.get(key)||new Map();if(pageInfo.hasNextPage&&pageInfo.endCursor)pages.set(page+1,pageInfo.endCursor);this.cursors.set(key,pages);return !!pageInfo.hasNextPage;}
 private async graphRead(action:string,payload:GitHubPayload):Promise<GitHubResponse>{const page=payload.page??0,tab=payload.tab||'overview';if(action.startsWith('projects.')){if(action==='projects.list'){const owner=await this.owner(payload),key=`projects:${owner.login}`,after=this.cursor(key,page);const data=await this.graph(`query { ${owner.type}(login:${JSON.stringify(owner.login)}) { projectsV2(first:${SIZE}${after}) { nodes { id number title shortDescription url closed public updatedAt } pageInfo { hasNextPage endCursor } } } }`);const container=data[owner.type] as {projectsV2?:{nodes:Record<string,unknown>[];pageInfo:{hasNextPage:boolean;endCursor:string}}};if(!container?.projectsV2)throw new Error('Owner project collection unavailable');const connection=container.projectsV2;const response=this.response(connection.nodes,this.remember(key,page,connection.pageInfo),page);if(payload.query){const query=payload.query.toLowerCase();response.items=response.items.filter(row=>`${row.title} ${row.shortDescription||''}`.toLowerCase().includes(query));response.notice='Search filters this provider page. Continue through remaining pages for more projects.';}return response;}
 const id=nodeId(String(payload.id??'')),key=`project:${this.context.getStore()}:${id}:${tab}`,after=this.cursor(key,page);let selection='id number title shortDescription readme url closed public';if(tab==='items')selection+=` items(first:${SIZE}${after}) { nodes { id type content { ... on Issue { number title body url state } ... on PullRequest { number title body url state } ... on DraftIssue { title body } } } pageInfo { hasNextPage endCursor } }`;else if(tab==='fields')selection+=` fields(first:${SIZE}${after}) { nodes { ... on ProjectV2Field { id name dataType } ... on ProjectV2SingleSelectField { id name options { id name } } ... on ProjectV2IterationField { id name configuration { iterations { id title startDate duration } } } } pageInfo { hasNextPage endCursor } }`;else if(tab!=='overview')throw new Error('Choose project Overview, Items or Fields');const data=await this.graph(`query { node(id:${JSON.stringify(id)}) { ... on ProjectV2 { ${selection} } } }`);const project=data.node as Record<string,unknown>;if(!project)throw new Error('Project unavailable');const connection=project[tab] as {nodes?:Record<string,unknown>[];pageInfo?:{hasNextPage:boolean;endCursor:string}}|undefined;return {...this.response(connection?.nodes||[],connection?.pageInfo?this.remember(key,page,connection.pageInfo):false,page),detail:redacted(project) as Record<string,unknown>};}
 const repo=repository(payload.repository),[owner,name]=repo.split('/');if(action==='discussions.categories'){const key=`categories:${this.context.getStore()}:${repo}`,after=this.cursor(key,page);const data=await this.graph(`query { repository(owner:${JSON.stringify(owner)},name:${JSON.stringify(name)}) { discussionCategories(first:${SIZE}${after}) { nodes { id name description isAnswerable } pageInfo { hasNextPage endCursor } } } }`);const connection=(data.repository as {discussionCategories:{nodes:Record<string,unknown>[];pageInfo:{hasNextPage:boolean;endCursor:string}}})?.discussionCategories;if(!connection)throw new Error('Discussion categories unavailable');return this.response(connection.nodes,this.remember(key,page,connection.pageInfo),page);}
 if(action==='discussions.list'){const key=`discussions:${this.context.getStore()}:${repo}`,after=this.cursor(key,page);const data=await this.graph(`query { repository(owner:${JSON.stringify(owner)},name:${JSON.stringify(name)}) { discussions(first:${SIZE}${after},orderBy:{field:UPDATED_AT,direction:DESC}) { nodes { id number title body url closed updatedAt category { id name } author { login } } pageInfo { hasNextPage endCursor } } } }`);const connection=(data.repository as {discussions:{nodes:Record<string,unknown>[];pageInfo:{hasNextPage:boolean;endCursor:string}}})?.discussions;if(!connection)throw new Error('Discussions unavailable');const response=this.response(connection.nodes,this.remember(key,page,connection.pageInfo),page);response.items=response.items.map(row=>({...row,id:String(row.number||row.id)}));if(payload.query){response.items=response.items.filter(row=>row.title.toLowerCase().includes(payload.query!.toLowerCase()));response.notice='Search filters the current discussion page. Next continues provider pagination.';}return response;}
 const number=numericId(payload.id),key=`discussion:${this.context.getStore()}:${repo}:${number}:${tab}`,after=this.cursor(key,page);let fields='id number title body url closed category { id name } author { login }';if(tab==='comments')fields+=` comments(first:${SIZE}${after}) { nodes { id body createdAt author { login } } pageInfo { hasNextPage endCursor } }`;else if(tab==='answers')fields+=' answer { id body createdAt author { login } }';else if(tab!=='overview')throw new Error('Choose discussion Overview, Comments or Answers');const data=await this.graph(`query { repository(owner:${JSON.stringify(owner)},name:${JSON.stringify(name)}) { discussion(number:${number}) { ${fields} } } }`);const discussion=(data.repository as {discussion?:Record<string,unknown>})?.discussion;if(!discussion)throw new Error('Discussion unavailable');const connection=discussion.comments as {nodes?:Record<string,unknown>[];pageInfo?:{hasNextPage:boolean;endCursor:string}}|undefined;return {...this.response(tab==='answers'&&discussion.answer?[discussion.answer]:connection?.nodes||[],connection?.pageInfo?this.remember(key,page,connection.pageInfo):false,page),detail:redacted(discussion) as Record<string,unknown>};}
 private async mutate(action:string,payload:GitHubPayload):Promise<GitHubResponse>{const values=payload.values||{};if(!values||typeof values!=='object'||Array.isArray(values))throw new Error('Use structured task values'); const allowed=mutationSchemas[action];if(!allowed)throw new Error('Mutation task has no registered adapter');for(const key of Object.keys(values))if(!allowed.includes(key))throw new Error(`Unknown ${action} value: ${key}`);
 for(const key of ['readme','draft','prerelease','deleteBranch','defaultBranchOnly','failedOnly','archived','public','closed'])if(values[key]!==undefined&&!(key==='readme'&&action.startsWith('projects.'))&&typeof values[key]!=='boolean')throw new Error(`Boolean required: ${key}`);
 const string=(key:string,required=false,max=16000)=>text(values[key],key,required,max);const choice=(key:string,choices:string[],fallback:string)=>{const value=string(key)||fallback;if(!choices.includes(value))throw new Error(`Choose ${key}: ${choices.join(', ')}`);return value;};
 const list=(key:string):string[]|undefined=>{if(values[key]===undefined)return;const rows=values[key];if(!Array.isArray(rows)||rows.length>100)throw new Error(`Choose at most 100 ${key}`);return rows.map(value=>text(value,key,true,200));};
 let endpoint='',method='POST',body:Record<string,unknown>|undefined={};const domain=action.split('.')[0],verb=action.split('.')[1];const repo=['repositories','issues','pulls','actions','releases','security'].includes(domain)&&!(domain==='repositories'&&verb==='create')?repository(payload.repository):'';
 if(domain==='projects'||domain==='discussions')return this.graphMutation(action,payload);
 if(domain==='repositories'){
 if(verb==='create'){const name=identifier(values.name,'repository name'),visibility=choice('visibility',['public','private','internal'],'private');body={name,description:string('description'),private:visibility!=='public',auto_init:values.readme===true};if(visibility==='internal')body.visibility='internal';if(values.owner){const owner=identifier(values.owner,'owner'),viewer=(await this.request('GET','user')).data as {login?:string};if(owner.toLowerCase()===viewer.login?.toLowerCase())endpoint='user/repos';else{const target=(await this.request('GET',`users/${owner}`)).data as {type?:string};if(target.type!=='Organization')throw new Error('A personal repository can be created only for the active account');endpoint=`orgs/${owner}/repos`;}}else endpoint='user/repos';}
 if(verb==='edit'){endpoint=`repos/${repo}`;method='PATCH';body={};for(const key of ['description','name'])if(values[key]!==undefined)body[key]=string(key);if(values.homepage!==undefined){const homepage=string('homepage');if(homepage){const url=new URL(homepage);if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw new Error('Homepage uses HTTP or HTTPS without credentials');}body.homepage=homepage;}if(values.visibility!==undefined)body.private=choice('visibility',['public','private'],'private')==='private';if(values.archived!==undefined)body.archived=values.archived;if(values.defaultBranch!==undefined)body.default_branch=string('defaultBranch',true);}
 if(verb==='delete'){endpoint=`repos/${repo}`;method='DELETE';body=undefined;}
 if(verb==='fork'){endpoint=`repos/${repo}/forks`;body={};if(values.owner)body.organization=identifier(values.owner,'organization owner');if(values.name)body.name=identifier(values.name,'repository name');if(values.defaultBranchOnly!==undefined)body.default_branch_only=values.defaultBranchOnly;}}
 if(domain==='issues'||domain==='pulls'){const id=verb==='create'?'':numericId(payload.id);const base=`repos/${repo}/${domain==='issues'?'issues':'pulls'}`;endpoint=verb==='create'?base:`${base}/${id}`;
 if(verb==='create'||verb==='edit'){if(verb==='edit')method='PATCH';body={};for(const key of ['title','body','base','head'])if(values[key]!==undefined)body[key]=string(key,false,key==='title'?240:16000);if(verb==='create'){body.title=string('title',true,240);if(domain==='pulls'){body.head=string('head',true,200);body.base=string('base',true,200);body.draft=values.draft===true;}}if(domain==='issues'){if(values.labels!==undefined)body.labels=list('labels');if(values.assignees!==undefined)body.assignees=list('assignees');if(values.milestone!==undefined)body.milestone=Number(numericId(values.milestone));}}
 if(verb==='comment'){endpoint=`repos/${repo}/issues/${id}/comments`;body={body:string('body',true)};}
 if(verb==='close'||verb==='reopen'){method='PATCH';body={state:verb==='close'?'closed':'open'};if(domain==='issues'&&verb==='close')body.state_reason=choice('reason',['completed','not_planned'],'completed');}
 if(verb==='merge'){method='PUT';endpoint+= '/merge';body={merge_method:choice('method',['squash','merge','rebase'],'squash')};}
 if(verb==='request-review'){endpoint+='/requested_reviewers';body={reviewers:list('reviewers')||[],team_reviewers:list('teamReviewers')||[]};}
 if(verb==='review'){endpoint+= '/reviews';body={event:choice('event',['COMMENT','APPROVE','REQUEST_CHANGES'],'COMMENT'),body:string('body')};if(body.event==='REQUEST_CHANGES'&&!body.body)throw new Error('Explain the requested changes in the review body');}}
 if(domain==='actions'){if(verb==='download-artifacts')return this.download(payload,'artifacts');if(['dispatch','enable-workflow','disable-workflow'].includes(verb)){const workflow=identifier(String(payload.id??''),'workflow');endpoint=`repos/${repo}/actions/workflows/${workflow}`;if(verb==='dispatch'){endpoint+='/dispatches';const ref=string('ref',true,200),inputs=values.inputs||{};if(!inputs||typeof inputs!=='object'||Array.isArray(inputs)||Object.keys(inputs).length>100)throw new Error('Use a bounded workflow input map');for(const [key,value] of Object.entries(inputs)){if(!/^[A-Za-z0-9_-]+$/.test(key)||typeof value!=='string'||value.length>4096||value.includes('\0'))throw new Error('Workflow inputs have named string values');}body={ref,inputs};}else{endpoint+=verb==='enable-workflow'?'/enable':'/disable';method='PUT';body=undefined;}}else{const id=numericId(payload.id);endpoint=`repos/${repo}/actions/runs/${id}`;if(verb==='delete'){method='DELETE';body=undefined;}else endpoint+=verb==='cancel'?'/cancel':verb==='rerun-failed'||values.failedOnly?'/rerun-failed-jobs':'/rerun';}}
 if(domain==='releases'){if(verb==='upload')return this.upload(payload);if(verb==='download-assets')return this.download(payload,'assets');endpoint=`repos/${repo}/releases${verb==='create'?'':`/${numericId(payload.id)}`}`;if(verb==='delete'){method='DELETE';body=undefined;}else{if(verb==='edit')method='PATCH';body={};if(verb==='create'){body.tag_name=string('tag',true,200);if(values.target)body.target_commitish=string('target',false,200);}if(values.title!==undefined)body.name=string('title');if(values.notes!==undefined)body.body=string('notes');if(values.draft!==undefined)body.draft=values.draft;if(values.prerelease!==undefined)body.prerelease=values.prerelease;}}
 if(domain==='gists'){endpoint=verb==='create'?'gists':`gists/${identifier(String(payload.id??''),'gist ID')}`;if(verb==='delete'){method='DELETE';body=undefined;}else{if(verb==='edit')method='PATCH';body={};if(values.description!==undefined)body.description=string('description');if(verb==='create')body.public=choice('visibility',['secret','public'],'secret')==='public';if(verb==='create'||values.content!==undefined){const filename=string('filename',true,200);if(/[\r\n\/\\]/.test(filename)||filename==='.'||filename==='..')throw new Error('Choose a filename without a path');body.files={[filename]:{content:string('content',true,50000)}};}}}
 if(domain==='codespaces'){if(verb==='create'){const source=repository(values.repository||payload.repository),record=(await this.request('GET',`repos/${source}`)).data as {id?:number};if(!Number.isSafeInteger(record.id))throw new Error('Repository ID unavailable');endpoint='user/codespaces';body={repository_id:record.id};if(values.branch)body.ref=string('branch',false,200);if(values.displayName)body.display_name=string('displayName',false,100);}else{endpoint=`user/codespaces/${identifier(String(payload.id??''),'Codespace name')}`;if(verb==='delete'){method='DELETE';body=undefined;}else endpoint+=`/${verb}`;}}
 if(domain==='security'){const type=choice('type',['dependabot','code-scanning','secret-scanning'],'dependabot');endpoint=`repos/${repo}/${type}/alerts/${numericId(payload.id)}`;method='PATCH';const reason=choice('reason',type==='dependabot'?['fix_started','inaccurate','no_bandwidth','not_used','tolerable_risk']:type==='code-scanning'?['false positive',"won't fix",'used in tests']:['false_positive','wont_fix','revoked','used_in_tests','pattern_edited','pattern_deleted'],type==='dependabot'?'tolerable_risk':type==='code-scanning'?'false positive':'false_positive');body=type==='secret-scanning'?{state:'resolved',resolution:reason,resolution_comment:string('comment')}:{state:'dismissed',dismissed_reason:reason,dismissed_comment:string('comment')};}
 if(domain==='organizations'){const organization=identifier(String(payload.id??''),'organization'),login=identifier(values.login,'member login');if(verb==='remove-member'){endpoint=`orgs/${organization}/members/${login}`;method='DELETE';body=undefined;}else{const user=(await this.request('GET',`users/${login}`)).data as {id?:number};if(!Number.isSafeInteger(user.id))throw new Error('Member ID unavailable');endpoint=`orgs/${organization}/invitations`;body={invitee_id:user.id,role:choice('role',['direct_member','admin','billing_manager'],'direct_member')};}}
 if(!endpoint)throw new Error('Mutation adapter unavailable');const result=await this.request(method,endpoint,body);const response=this.response(result.data,false,0);response.notice='GitHub accepted the task. Refresh the list to read the resulting state.';
 if(action==='pulls.merge'&&!(result.data as {merged?:boolean}).merged)throw new Error((result.data as {message?:string}).message||'GitHub did not merge the pull request');
 if(action==='pulls.merge'&&values.deleteBranch){const merged=result.data as {merged?:boolean;message?:string};if(!merged.merged)throw new Error(merged.message||'GitHub did not merge the pull request');const pull=(await this.request('GET',`repos/${repo}/pulls/${numericId(payload.id)}`)).data as {head?:{ref?:string;repo?:{full_name?:string}}};if(!pull.head?.ref||pull.head.repo?.full_name!==repo){response.notice='Pull request merged. Source branch was not deleted because it belongs to another repository or its identity is unavailable.';}else{try{await this.request('DELETE',`repos/${repo}/git/refs/heads/${encodeURIComponent(pull.head.ref)}`);response.notice='Pull request merged and its source branch deleted.';}catch(error){response.notice=`Pull request merged, but source branch deletion failed: ${error instanceof Error?error.message:'unknown error'}`;}}}return response;}
 private async graphMutation(action:string,payload:GitHubPayload):Promise<GitHubResponse>{const values=payload.values||{},quote=JSON.stringify;const inputText=(key:string,required=false,max=16000)=>text(values[key],key,required,max);let query='';
 if(action==='projects.create'){const owner=await this.owner(payload);query=`mutation { createProjectV2(input:{ownerId:${quote(owner.id)},title:${quote(inputText('title',true,240))}}) { projectV2 { id number title url } } }`;}
 if(action==='projects.edit'){const id=nodeId(String(payload.id??''));const fields=[`projectId:${quote(id)}`];if(values.title!==undefined)fields.push(`title:${quote(inputText('title',true,240))}`);if(values.description!==undefined)fields.push(`shortDescription:${quote(inputText('description',false,1024))}`);if(values.readme!==undefined)fields.push(`readme:${quote(inputText('readme'))}`);for(const key of ['public','closed'])if(values[key]!==undefined){if(typeof values[key]!=='boolean')throw new Error(`Boolean required: ${key}`);fields.push(`${key}:${values[key]}`);}query=`mutation { updateProjectV2(input:{${fields.join(',')}}) { projectV2 { id number title url } } }`;}
 if(action==='projects.delete')query=`mutation { deleteProjectV2(input:{projectId:${quote(nodeId(String(payload.id??'')))}}) { clientMutationId } }`;
 if(action==='projects.add-item'){const id=nodeId(String(payload.id??'')),url=inputText('url',true,1000),parsed=new URL(url);if(parsed.hostname!==(this.context.getStore()||'github.com')||parsed.protocol!=='https:'||parsed.username||parsed.password)throw new Error('Choose a GitHub issue or pull-request URL');const match=parsed.pathname.match(/^\/([\w.-]+)\/([\w.-]+)\/(issues|pull)\/([1-9][0-9]*)$/);if(!match)throw new Error('Choose a GitHub issue or pull-request URL');const record=(await this.request('GET',`repos/${match[1]}/${match[2]}/${match[3]==='pull'?'pulls':'issues'}/${match[4]}`)).data as {node_id?:string};query=`mutation { addProjectV2ItemById(input:{projectId:${quote(id)},contentId:${quote(nodeId(record.node_id))}}) { item { id } } }`;}
 if(action.startsWith('discussions.')){const repo=repository(payload.repository),[owner,name]=repo.split('/');let id='';if(action!=='discussions.create'){const result=await this.graph(`query { repository(owner:${quote(owner)},name:${quote(name)}) { discussion(number:${numericId(payload.id)}) { id } } }`);id=nodeId((result.repository as {discussion?:{id?:string}})?.discussion?.id);}
 if(action==='discussions.create'){const record=(await this.request('GET',`repos/${repo}`)).data as {node_id?:string};query=`mutation { createDiscussion(input:{repositoryId:${quote(nodeId(record.node_id))},categoryId:${quote(nodeId(values.category))},title:${quote(inputText('title',true,240))},body:${quote(inputText('body',true))}}) { discussion { id number title body url } } }`;}
 if(action==='discussions.comment')query=`mutation { addDiscussionComment(input:{discussionId:${quote(id)},body:${quote(inputText('body',true))}}) { comment { id body url } } }`;
 if(action==='discussions.close'){const reason=inputText('reason')||'RESOLVED';if(!['RESOLVED','OUTDATED','DUPLICATE'].includes(reason))throw new Error('Choose RESOLVED, OUTDATED or DUPLICATE');query=`mutation { closeDiscussion(input:{discussionId:${quote(id)},reason:${reason}}) { discussion { id closed } } }`;}
 if(action==='discussions.reopen')query=`mutation { reopenDiscussion(input:{discussionId:${quote(id)}}) { discussion { id closed } } }`;}
 if(!query)throw new Error('GraphQL task has no registered mutation');const data=await this.graph(query);return {...this.response(data),notice:'GitHub accepted the task. Refresh to read the updated provider state.'};}
 private async download(payload:GitHubPayload,kind:'assets'|'artifacts'):Promise<GitHubResponse>{const {realpath,stat}=await import('node:fs/promises');const root=await realpath(this.cwd),directory=await realpath(text(payload.values?.directory,'download folder',true));if(directory!==root&&!directory.startsWith(root+path.sep)||!(await stat(directory)).isDirectory())throw new Error('Choose a download folder inside the approved workspace');const names=payload.values?.names;if(names!==undefined&&(!Array.isArray(names)||names.length>100||names.some(value=>typeof value!=='string'||value.length>200||/[\0\r\n]/.test(value))))throw new Error('Choose at most 100 asset or artifact names');const repo=repository(payload.repository),hostRepo=`${this.context.getStore()||'github.com'}/${repo}`,id=numericId(payload.id);let argv:string[];
 if(kind==='artifacts'){argv=['run','download',`--repo=${hostRepo}`,`--dir=${directory}`,...(Array.isArray(names)?names.map(name=>`--name=${name}`):[]),'--',id];}else{const release=(await this.request('GET',`repos/${repo}/releases/${id}`)).data as {tag_name?:string};argv=['release','download',`--repo=${hostRepo}`,`--dir=${directory}`,'--skip-existing',...(Array.isArray(names)?names.map(name=>`--pattern=${name}`):[]),'--',text(release.tag_name,'release tag',true,200)];}await this.cli(argv);return {items:[],hasNext:false,page:0,notice:`GitHub CLI downloaded the selected ${kind}. Existing release files are skipped; inspect the chosen local folder.`};}
 private async upload(payload:GitHubPayload):Promise<GitHubResponse>{const {realpath,stat}=await import('node:fs/promises');const repo=repository(payload.repository),id=numericId(payload.id);const release=(await this.request('GET',`repos/${repo}/releases/${id}`)).data as {tag_name?:string};const tag=text(release.tag_name,'release tag',true,200);const files=payload.values?.files;if(!Array.isArray(files)||!files.length||files.length>20)throw new Error('Choose 1 to 20 release asset files');const root=await realpath(this.cwd);const paths=await Promise.all(files.map(async value=>{const file=await realpath(text(value,'release asset file',true,4096));if(!file.startsWith(root+path.sep))throw new Error('Release assets must be selected inside the approved workspace');const status=await stat(file);if(!status.isFile()||status.size>256*1024*1024)throw new Error('Choose regular assets of at most 256 MiB');return file;}));const operation=this.engine.executeAdapter('github:releases.upload',['release','upload',`--repo=${this.context.getStore()||'github.com'}/${repo}`,'--',tag,...paths]);const finished=await new Promise<ReturnType<Engine['operation']>>(resolve=>{const unsubscribe=this.engine.subscribe(op=>{if(op.id===operation.id&&op.endedAt){unsubscribe();resolve(op);}});const current=this.engine.operation(operation.id);if(current.endedAt){unsubscribe();resolve(current);}});if(finished.status!=='succeeded')throw new Error(finished.stderr||`Asset upload ${finished.status}`);return {items:[],hasNext:false,page:0,notice:'GitHub CLI uploaded the selected assets. Refresh the release Assets tab to read the provider result.'};}
}
