import {constants} from 'node:fs';import {lstat,open,readFile,mkdir,realpath} from 'node:fs/promises';import {basename,join} from 'node:path';import {createHash,randomUUID} from 'node:crypto';import {execFile} from 'node:child_process';
import {atomicJson} from './ollama-manager';import type {HarnessRuntimeReview,HarnessRuntimeRegistration} from '../shared/ollama-harness';
interface Identity {size:number;mtime:number;ino:number;dev:number;sha256:string;format:'ELF'|'PE'}
interface PrivateReview extends HarnessRuntimeReview {path:string;identity:Identity;created:number}
interface PrivateRegistration extends HarnessRuntimeRegistration {path:string;identity:Identity}
const identifier=(value:unknown)=>{if(typeof value!=='string'||!/^[a-f0-9-]{36}$/.test(value))throw Error('Invalid runtime review identifier');return value;};
/** Selection hashes bytes without execution. The owner must approve those exact bytes before probing. */
export class OllamaRuntime {
 private pending?:PrivateReview;private registering=false;
 constructor(private directory:string,private picker?:()=>Promise<string|null>){}
 activeJobs(){return this.registering;}
 private async identity(path:string):Promise<Identity>{
  const entry=await lstat(path);if(!entry.isFile()||entry.isSymbolicLink()||entry.size<4||entry.size>256*1024*1024)throw Error('Choose a regular native executable of at most 256 MiB. Links and scripts cannot register.');if(process.platform!=='win32'&&(entry.mode&0o111)===0)throw Error('The selected native file is not executable. Choose an installed runtime.');
  const file=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0)),hash=createHash('sha256'),chunk=Buffer.alloc(65536);let bytes=0,format:Identity['format']|undefined;
  try{const before=await file.stat();if(before.ino!==entry.ino||before.dev!==entry.dev||before.size!==entry.size)throw Error('Runtime changed during selection');while(true){const part=await file.read(chunk,0,chunk.length,null);if(!part.bytesRead)break;bytes+=part.bytesRead;if(bytes>256*1024*1024)throw Error('Runtime exceeds its byte limit');if(!format){if(chunk[0]===0x7f&&chunk.subarray(1,4).toString()==='ELF')format='ELF';else if(chunk[0]===0x4d&&chunk[1]===0x5a)format='PE';else throw Error('Only native ELF or PE executables can register. Shell and script files are refused.');if(format!==(process.platform==='win32'?'PE':'ELF'))throw Error('Runtime executable does not match this platform');}if(bytes===part.bytesRead){if(format==='ELF'&&(part.bytesRead<64||chunk[4]!==2||chunk[5]!==1||chunk.readUInt16LE(18)!==(process.arch==='arm64'?183:62)))throw Error('Choose a compatible native 64-bit runtime');if(format==='PE'){if(part.bytesRead<64)throw Error('Invalid native PE header');const offset=chunk.readUInt32LE(60);if(offset>1024*1024||offset+6>entry.size)throw Error('Invalid native PE header offset');const signature=Buffer.alloc(6);const header=await file.read(signature,0,6,offset);if(header.bytesRead!==6||signature.subarray(0,4).toString()!=='PE\0\0'||signature.readUInt16LE(4)!==(process.arch==='arm64'?0xaa64:0x8664))throw Error('Choose a compatible native 64-bit PE runtime');}}hash.update(chunk.subarray(0,part.bytesRead));}
   const after=await file.stat();if(bytes!==entry.size||after.size!==before.size||after.mtimeMs!==before.mtimeMs||after.ino!==before.ino||after.dev!==before.dev)throw Error('Runtime changed while hashing. Select it again.');return {size:bytes,mtime:after.mtimeMs,ino:after.ino,dev:after.dev,sha256:hash.digest('hex'),format:format!};
  }finally{await file.close();}
 }
 private same(first:Identity,second:Identity){return JSON.stringify(first)===JSON.stringify(second);}
 async pick(){if(!this.picker)throw Error('Native runtime selection is unavailable in this build');if(this.registering)throw Error('Wait for runtime verification to finish');const selected=await this.picker();if(!selected)return {cancelled:true};const original=await lstat(selected);if(original.isSymbolicLink())throw Error('Choose the native runtime itself, not a symbolic link');const path=await realpath(selected),identity=await this.identity(path),review:HarnessRuntimeReview={id:randomUUID(),name:basename(path).replace(/[\x00-\x1f]/g,'').slice(0,200),bytes:identity.size,sha256:identity.sha256,format:identity.format,provenance:'Execution trust required',disclosures:['Path and version output do not establish an official publisher. This build has no vendor-signature or known-release-digest attestation for the selected file.','Approval permits execution of these exact bytes with fixed --version and serve arguments. A native executable can access your account resources; approve only a runtime whose origin you have verified.','No execution occurs before confirmation. Any byte or file-identity change invalidates this approval. The native path remains private.']};this.pending={...review,path,identity,created:Date.now()};return review;}
 async register(payload:Record<string,unknown>){if(payload.confirmed!==true)throw Error('Review the exact digest and explicitly approve native execution');const id=identifier(payload.review),review=this.pending;if(this.registering)throw Error('Runtime verification is already active');if(!review||review.id!==id||Date.now()-review.created>120000)throw Error('Runtime review expired. Select the runtime again');this.registering=true;
  try{const identity=await this.identity(review.path);if(!this.same(identity,review.identity))throw Error('Runtime bytes or identity changed after review. Select and approve it again.');const version=await new Promise<string>((resolve,reject)=>{execFile(review.path,['--version'],{shell:false,windowsHide:true,timeout:5000,maxBuffer:16384,cwd:this.directory,env:{PATH:process.env.PATH??'',HOME:process.env.HOME??'',USERPROFILE:process.env.USERPROFILE??'',LOCALAPPDATA:process.env.LOCALAPPDATA??'',SYSTEMROOT:process.env.SYSTEMROOT??'',OLLAMA_HOST:'127.0.0.1:11434'}},(error,stdout)=>{if(error)return reject(Error('Approved runtime version probe failed or exceeded its five-second/output budget. No service was launched.'));const match=/\bollama version(?: is|:)?\s+v?(\d+\.\d+\.\d+(?:[.-][A-Za-z0-9]+)*)\b/i.exec(stdout);if(!match)return reject(Error('The approved executable did not identify a compatible Ollama version. It was not registered.'));resolve(match[1]);});});if(!this.same(await this.identity(review.path),identity))throw Error('Runtime changed during verification. Select it again.');const registration:HarnessRuntimeRegistration={name:review.name,bytes:identity.size,sha256:identity.sha256,version,approvedAt:new Date().toISOString(),provenance:'User-reviewed exact bytes'};await mkdir(this.directory,{recursive:true,mode:0o700});await atomicJson(join(this.directory,'registered-runtime.json'),{...registration,path:review.path,identity});this.pending=undefined;return registration;
  }finally{this.registering=false;}
 }
 async registered():Promise<PrivateRegistration|undefined>{try{const file=join(this.directory,'registered-runtime.json');if((await lstat(file)).size>16000)throw Error('Runtime registration exceeds its byte limit');const registration=JSON.parse(await readFile(file,'utf8'))as PrivateRegistration;if(typeof registration.path!=='string'||registration.provenance!=='User-reviewed exact bytes'||!this.same(await this.identity(registration.path),registration.identity)||registration.sha256!==registration.identity.sha256)throw Error('Registered runtime bytes or identity changed. Select and approve the runtime again.');return registration;}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return;throw error;}}
 async status(){const runtime=await this.registered();if(!runtime)return {pickerAvailable:!!this.picker};const {path:_path,identity:_identity,...publicRuntime}=runtime;return {pickerAvailable:!!this.picker,runtime:publicRuntime};}
}
