import {OllamaRuntime} from './ollama-runtime';
import {harnessProfiles} from '../shared/ollama-harness';
import {OllamaGeneration} from './ollama-generation';
import { catalogRegex } from './catalog-query';
import {saveChatImages,readChatImage,deleteChatImages,validateChatAttachment,type PreparedChatImage} from './chat-attachments';
import {randomUUID,createHash} from 'node:crypto';
import {mkdir,readFile,writeFile,rename,readdir,stat,statfs,access,unlink} from 'node:fs/promises';
import {join,basename} from 'node:path';
import {totalmem,freemem,cpus,arch,homedir,platform} from 'node:os';
import {spawn,execFile,type ChildProcess} from 'node:child_process';
import type {CatalogStatus,CatalogVariant,HardwareEvidence,FitEvidence,PullItem,ChatSession,ChatRun,HarnessState,ChatMessage,ModelCapabilities} from '../shared/local-tools';
const ENDPOINT='http://127.0.0.1:11434';
const modelPattern=/^[A-Za-z0-9][A-Za-z0-9_.\/-]*(?::[A-Za-z0-9_.-]+)?$/;
export function validateModel(value:unknown):string{if(typeof value!=='string'||value.length>200||!modelPattern.test(value)||value.includes('..'))throw new Error('Choose a valid exact model tag');return value;}
function identifier(value:unknown):string{if(typeof value!=='string'||! /^[a-f0-9-]{36}$/.test(value))throw new Error('Invalid local record identifier');return value;}
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Expected a structured request');return value as Record<string,unknown>;}
export function redactExport(text:string):string{return text.replace(/(?:gh[pousr]_[A-Za-z0-9_]+|github_pat_[A-Za-z0-9_]+|sk-[A-Za-z0-9_-]{12,})/g,'[REDACTED]').replace(/\b(?:password|api[_-]?key|access[_-]?token|secret)\s*[:=]\s*[^\s,;]+/gi,'[REDACTED]').replace(/(?:[A-Za-z]:\\(?:[^\s<>"']+)|\/(?:home|Users|workspace|tmp|var|etc)\/[^\s<>"']+)/g,'[LOCAL PATH]');}
export async function atomicJson(path:string,data:unknown){const temporary=path+'.'+randomUUID()+'.tmp';try{await writeFile(temporary,JSON.stringify(data),{mode:0o600,flag:'wx'});await rename(temporary,path);}finally{await unlink(temporary).catch(()=>{});}}
async function limitedText(response:Response,limit:number,signal?:AbortSignal):Promise<string>{const reader=response.body?.getReader();if(!reader)throw new Error('Empty response body');const decoder=new TextDecoder('utf-8',{fatal:true});let text='',bytes=0;try{while(true){if(signal?.aborted)throw new Error('Operation cancelled');const part=await reader.read();if(part.done)break;bytes+=part.value.length;if(bytes>limit)throw new Error('Response exceeded safety bound');text+=decoder.decode(part.value,{stream:true});}return text+decoder.decode();}finally{await reader.cancel().catch(()=>{});}}
export async function localApi(action:'health'|'models'|'running'|'show'|'copy'|'delete',payload:Record<string,unknown>={},fetcher:typeof fetch=fetch):Promise<unknown>{const routes={health:['GET','version'],models:['GET','tags'],running:['GET','ps'],show:['POST','show'],copy:['POST','copy'],delete:['DELETE','delete']}as const;if(!Object.hasOwn(routes,action))throw new Error('Unknown local API operation');const[method,path]=routes[action];const allowed=action==='copy'?['source','destination']:action==='delete'?['model','confirmed']:action==='show'?['model']:[];for(const key of Object.keys(payload))if(!allowed.includes(key))throw new Error('Unsupported local API field');const body:Record<string,unknown>={};if(action==='show'||action==='delete')body.model=validateModel(payload.model);if(action==='copy'){body.source=validateModel(payload.source);body.destination=validateModel(payload.destination);if(body.source===body.destination)throw new Error('Choose a new destination name');const tags=object(await localApi('models',{},fetcher)).models;if(!Array.isArray(tags))throw new Error('Invalid installed-model inventory');if(tags.some(m=>object(m).name===body.destination||object(m).name===body.destination+':latest'))throw new Error('Destination model already exists');}if(action==='delete'&&payload.confirmed!==true)throw new Error('Deletion requires confirmation');try{const response=await fetcher(ENDPOINT+'/api/'+path,{method,redirect:'error',signal:AbortSignal.timeout(8000),headers:{'Content-Type':'application/json'},...(method==='GET'?{}:{body:JSON.stringify(body)})});if(!response.ok)throw new Error(`Local Ollama returned HTTP ${response.status}`);const text=(action==='copy'||action==='delete')&&!response.body?'':await limitedText(response,4*1024*1024);const result=text?JSON.parse(text):{};return action==='health'?{available:true,...object(result)}:result;}catch(error){if(action==='health')return {available:false,error:'Ollama is not reachable at 127.0.0.1:11434. Start the installed local service, then retry.'};throw error;}}
/** Parse official public catalog HTML only; links never authorize arbitrary destinations. */
export function parseCatalogPage(html:string,family?:string):{names:string[];variants:CatalogVariant[];next:string[]}{
 const names=new Set<string>(),variants=new Map<string,CatalogVariant>(),next=new Set<string>();
 for(const match of html.matchAll(/<a\b[^>]*href="([^"]+)"[^>]*>/g)){const href=match[1].replace(/&amp;/g,'&');if(/^(?:\/library)(?:\/[A-Za-z0-9_.-]+\/tags)?\?[^#]*\bpage=\d+/.test(href))next.add(href);if(!family){const m=/^\/library\/([A-Za-z0-9_.-]+)$/.exec(href);if(m)names.add(m[1]);}else{const m=/^\/library\/([A-Za-z0-9_.-]+):([A-Za-z0-9_.-]+)$/.exec(href);if(m&&m[1]===family&&!variants.has(m[1]+':'+m[2])){const end=html.indexOf('</a>',match.index!);const block=html.slice(match.index!,end<0?match.index!+2500:end).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ');const size=/\b([\d.]+)\s*(KB|MB|GB|TB)\b/i.exec(block),context=/\b([\d.]+)([KM]?)\s+context window/i.exec(block),digest=/\b[a-f0-9]{12,64}\b/.exec(block);variants.set(m[1]+':'+m[2],{tag:m[1]+':'+m[2],family,source:'https://ollama.com'+href,capabilities:/text.*image|image.*text/i.test(block)?['text','vision']:/embedding/i.test(block)?['embedding']:/text input/i.test(block)?['text']:[],...(size?{bytes:Math.ceil(Number(size[1])*({KB:1000,MB:1e6,GB:1e9,TB:1e12}[size[2].toUpperCase()]!))}:{}),...(context?{context:Number(context[1])*({K:1000,M:1e6,'':1}[context[2]]!)}:{}),...(digest?{digest:digest[0]}:{})});}}}
 return {names:[...names],variants:[...variants.values()],next:[...next]};
}
export function hardwareFit(model:Pick<CatalogVariant,'bytes'|'context'|'parameterCount'|'quantization'|'kvBytesPerToken'>,hardware:HardwareEvidence,context=4096):FitEvidence{const evidence=[`RAM: ${hardware.ram} bytes; currently free: ${hardware.freeRam} bytes`,`CPU: ${hardware.cpu}; ${hardware.cpuCores} logical cores; ${hardware.architecture}`,`GPU: ${hardware.gpu.reason}`,`Model bytes: ${model.bytes??'unknown'}; declared context: ${model.context??'unknown'}; selected context: ${context}`,`Parameters: ${model.parameterCount??'unknown'}; quantization: ${model.quantization??'unknown'}; KV cache bytes/token: ${model.kvBytesPerToken??'unknown'}`];let verdict:FitEvidence['verdict']='Unknown';if(hardware.diskFree!==undefined)evidence.push(`Free detected Ollama model volume: ${hardware.diskFree} bytes. An externally configured service may use another volume.`);else evidence.push('Detected Ollama model destination free disk is unknown.');if(model.bytes!==undefined&&model.bytes>hardware.ram*.9){verdict='Unlikely';evidence.push('Model blob alone exceeds 90% of total RAM, before runtime/context overhead.');}else if(model.bytes!==undefined&&hardware.gpu.status==='verified'&&hardware.gpu.vram!==undefined&&model.context!==undefined&&model.parameterCount!==undefined&&model.quantization!==undefined&&model.kvBytesPerToken!==undefined&&hardware.diskFree!==undefined){const overhead=Math.max(2*1024**3,model.bytes*.35)+model.kvBytesPerToken*context;evidence.push(`Conservative overhead estimate ${Math.ceil(overhead)} bytes, not an exact KV-cache measurement.`);if(hardware.diskFree<model.bytes*1.2)verdict='Unlikely';else if(context>model.context||model.bytes+overhead>hardware.freeRam)verdict='Runs with limits';else if(hardware.gpu.vram>=model.bytes+overhead&&hardware.gpu.backend)verdict='Runs well';else verdict='Runs with limits';}else evidence.push('Exact parameter/quantization memory needs, GPU backend/VRAM or storage evidence is incomplete; execution fit remains unknown.');return {verdict,at:new Date().toISOString(),evidence};}
interface ManagerOptions {directory:string;fetcher?:typeof fetch;pickHarnessExecutable?:()=>Promise<string|null>}
export class OllamaManager{
 private runtime:OllamaRuntime;private generation:OllamaGeneration;readonly directory:string;private fetcher:typeof fetch;private catalog:CatalogStatus={state:'empty',complete:false,pages:0,families:0,variants:0};private inventory:CatalogVariant[]=[];private localInventory:Record<string,unknown>[]=[];private localAt?:string;private refreshing?:AbortController;private jobs=new Map<string,AbortController>();private runners=new Map<string,ChatRun>();private pullActive=false;private chatAdmission=false;private activePullItems?:PullItem[];private pending=new Map<string,HarnessState>();private children=new Map<string,ChildProcess>();private ready:Promise<void>;
 constructor(options:ManagerOptions){this.directory=options.directory;this.fetcher=options.fetcher??fetch;this.ready=this.initialize();this.runtime=new OllamaRuntime(this.directory,options.pickHarnessExecutable);this.generation=new OllamaGeneration(join(this.directory,'generations'),model=>this.modelCapabilities({model}),(body,signal,callback)=>this.stream('/api/generate',body,signal,callback));}
 private async initialize(){await mkdir(this.directory,{recursive:true,mode:0o700});await mkdir(join(this.directory,'sessions'),{recursive:true,mode:0o700});try{const cache=join(this.directory,'catalog.json');if((await stat(cache)).size>64*1024*1024)throw new Error('Catalog cache exceeds 64 MiB');const c=JSON.parse(await readFile(cache,'utf8'));if(Array.isArray(c.inventory)&&c.inventory.length<=500000&&c.status?.complete){this.inventory=c.inventory.map((entry:unknown)=>{const v=object(entry);validateModel(v.tag);if(typeof v.family!=='string'||v.family.length>200||typeof v.source!=='string'||v.source.length>500||!Array.isArray(v.capabilities)||v.capabilities.length>20||v.capabilities.some((cap:unknown)=>typeof cap!=='string'||cap.length>100))throw new Error('Invalid cached catalog metadata');if(v.bytes!==undefined&&(typeof v.bytes!=='number'||!Number.isSafeInteger(v.bytes)||v.bytes<0))throw new Error('Invalid cached model bytes');return v as unknown as CatalogVariant;});this.catalog={...c.status,state:'ready'};}}catch{}try{const cache=join(this.directory,'local-models.json');if((await stat(cache)).size>4*1024*1024)throw new Error('Local model cache exceeds its bound');const data=object(JSON.parse(await readFile(cache,'utf8')));if(!Array.isArray(data.models)||data.models.length>10000||typeof data.at!=='string')throw new Error('Invalid local model cache');this.localInventory=data.models.map((entry:unknown)=>{const model=object(entry);validateModel(model.name??model.model);return model;});this.localAt=data.at;}catch{}try{const items=await this.pullItems();for(const item of items)if(item.status==='pulling'){item.status='queued';item.message='Interrupted pull. Retry resumes from Ollama content-addressed blobs.';}await this.savePulls(items);}catch{}}
 async modelCapabilities(payload:Record<string,unknown>):Promise<ModelCapabilities>{await this.ready;const model=validateModel(payload.model),tags=object(await localApi('models',{},this.fetcher));if(!Array.isArray(tags.models)||tags.models.length>10000)throw new Error('Invalid installed-model inventory');const installed=tags.models.map(object).find(item=>(item.name??item.model)===model);if(!installed)throw new Error('Model is not installed. Select an installed model or explicitly pull it in Model Store.');const metadata=object(await localApi('show',{model},this.fetcher));if(!Array.isArray(metadata.capabilities)||metadata.capabilities.length>20||metadata.capabilities.some(value=>typeof value!=='string'||value.length>100))throw new Error('Installed model capability metadata is unavailable. Refresh service and inspect another installed model.');const info=metadata.model_info&&typeof metadata.model_info==='object'?object(metadata.model_info):{},context=Object.entries(info).find(([key,value])=>key.endsWith('.context_length')&&Number.isSafeInteger(value)&&Number(value)>0)?.[1];return {model,at:new Date().toISOString(),source:ENDPOINT+'/api/show',capabilities:metadata.capabilities as string[],...(typeof installed.digest==='string'?{digest:installed.digest.slice(0,128)}:{}),...(typeof context==='number'?{context}:{})};}
 async copyModel(payload:Record<string,unknown>){await this.ready;if(payload.confirmed!==true)throw new Error('Review and confirm the local model copy');const source=validateModel(payload.source),destination=validateModel(payload.destination);if(!destination.includes(':'))throw new Error('Choose an explicit destination variant, such as the suggested :latest tag');await this.modelCapabilities({model:source});await localApi('copy',{source,destination},this.fetcher);const tags=object(await localApi('models',{},this.fetcher));if(!Array.isArray(tags.models)||!tags.models.some(item=>object(item).name===destination))throw new Error('Copy returned without the exact destination appearing in installed models. Refresh service to reconcile the outcome.');return {copied:true,source,destination,notice:'Local model tag copied without a pull. Existing destination tags are refused.'};}
 async startGeneration(payload:Record<string,unknown>){await this.ready;if(this.chatAdmission||[...this.runners.values()].some(run=>run.status==='running'))throw new Error('Stop the active chat response before starting generation');return this.generation.start(payload);}
 async generationStatus(payload:Record<string,unknown>){await this.ready;return this.generation.status(payload);}
 async generationHistory(payload:Record<string,unknown>){await this.ready;return this.generation.history(payload);}
 async cancelGeneration(payload:Record<string,unknown>){return this.generation.cancel(payload);}
 async hardware():Promise<HardwareEvidence>{await this.ready;let diskFree:number|undefined;const destination=process.env.OLLAMA_MODELS||join(homedir(),'.ollama','models');try{const s=await statfs(destination);diskFree=s.bavail*s.bsize;}catch{}const gpu:HardwareEvidence['gpu']={status:'unknown',reason:'GPU capacity and driver/backend are not verified. No supported device telemetry was detected.'};const paths=platform()==='win32'?[join(process.env.SYSTEMROOT??'C:\\Windows','System32','nvidia-smi.exe')]:['/usr/bin/nvidia-smi','/usr/local/bin/nvidia-smi'];for(const path of paths){try{await access(path);const output=await new Promise<string>((resolve,reject)=>execFile(path,['--query-gpu=name,memory.total,driver_version','--format=csv,noheader,nounits'],{timeout:3000,maxBuffer:8192,windowsHide:true},(error,stdout)=>error?reject(error):resolve(stdout)));const values=output.trim().split('\n')[0].split(',').map(v=>v.trim());const memory=Number(values[1]);if(values.length===3&&memory>0&&Number.isFinite(memory)){gpu.name=values[0].slice(0,160);gpu.vram=Math.floor(memory*1024**2);gpu.reason='NVIDIA telemetry detected capacity and driver '+values[2].slice(0,50)+'. Ollama GPU backend compatibility remains unverified.';}break;}catch{}}return {at:new Date().toISOString(),ram:totalmem(),freeRam:freemem(),cpu:cpus()[0]?.model??'Unknown',cpuCores:cpus().length,architecture:arch(),diskFree,gpu};}
 async status(){await this.ready;return this.catalog;}
 async catalogPage(payload:Record<string,unknown>){
  await this.ready;const page=Number(payload.page??1),size=Number(payload.size??40);
  if(!Number.isInteger(page)||page<1||page>500000||!Number.isInteger(size)||size<1||size>100)throw new Error('Invalid catalog page');
  if(payload.regex!==undefined&&typeof payload.regex!=='boolean')throw new Error('Invalid regex mode');const query=String(payload.query??'');if(query.length>500)throw new Error('Catalog query exceeds 500 characters');
  for(const key of ['family','capability','state','variant','quantization','fit','sort'])if(payload[key]!==undefined&&(typeof payload[key]!=='string'||String(payload[key]).length>200))throw new Error('Invalid catalog filter');
  if(payload.state&&!['installed','running','not-installed'].includes(String(payload.state)))throw new Error('Unsupported catalog local-state filter');
  if(payload.fit&&!['Runs well','Runs with limits','Unlikely','Unknown'].includes(String(payload.fit)))throw new Error('Unsupported hardware-fit filter');
  if(payload.sort&&!['name','size','size-desc','context'].includes(String(payload.sort)))throw new Error('Unsupported catalog sort');
  const maxBytes=payload.maxBytes===undefined?undefined:Number(payload.maxBytes);if(maxBytes!==undefined&&(!Number.isSafeInteger(maxBytes)||maxBytes<1||maxBytes>10**15))throw new Error('Invalid model-size filter');
  const hardware=await this.hardware();let localState:'available'|'unavailable'='available';
  const responses=await Promise.allSettled([localApi('models',{},this.fetcher),localApi('running',{},this.fetcher)]);
  const inventory=new Map(this.inventory.map(v=>[v.tag,{...v,installed:false,running:false}]));
  for(let i=0;i<responses.length;i++){
   const response=responses[i];let models:unknown;
   if(response.status==='rejected'){localState='unavailable';if(i!==0)continue;models=this.localInventory;}else models=object(response.value).models;
   if(!Array.isArray(models)||models.length>10000)throw new Error('Invalid bounded local model inventory');
   if(i===0&&response.status==='fulfilled'){for(const model of models)validateModel(object(model).name??object(model).model);this.localInventory=models;this.localAt=new Date().toISOString();await atomicJson(join(this.directory,'local-models.json'),{at:this.localAt,models});}
   for(const raw of models){const model=object(raw),tag=validateModel(model.name??model.model),details=model.details?object(model.details):{};
    const existing=inventory.get(tag),variant:CatalogVariant&{installed:boolean;running:boolean}=existing??{tag,family:tag.split(':')[0],source:'Local Ollama tags API',capabilities:[],localOnly:true,installed:false,running:false};
    if(i===0)variant.installed=true;else{variant.running=true;variant.installed=true;}
    if(typeof model.size==='number'&&Number.isSafeInteger(model.size)&&model.size>=0)variant.bytes=model.size;
    if(typeof details.quantization_level==='string'&&details.quantization_level.length<=100)variant.quantization=details.quantization_level;
    inventory.set(tag,variant);
   }
  }
  const all=[...inventory.values()];
  let rows=all.filter(v=>(!payload.family||v.family===payload.family)&&(!payload.capability||v.capabilities.includes(String(payload.capability)))&&(!payload.state||localState==='available'&&(payload.state==='running'?v.running:payload.state==='installed'?v.installed:!v.installed))&&(!payload.variant||v.tag.split(':').slice(1).join(':')===payload.variant)&&(!payload.quantization||(payload.quantization==='unknown'?!v.quantization:v.quantization===payload.quantization))&&(maxBytes===undefined||v.bytes!==undefined&&v.bytes<=maxBytes));
  const fitCache=new Map<string,FitEvidence>();const fit=(v:CatalogVariant)=>{let result=fitCache.get(v.tag);if(!result){result=hardwareFit(v,hardware);fitCache.set(v.tag,result);}return result;};
  if(payload.fit)rows=rows.filter(v=>fit(v).verdict===payload.fit);
  const searchValues=rows.map(v=>[v.tag,v.quantization??'Unknown',...v.capabilities].join(' '));
  if(payload.regex===true){const matches=await catalogRegex(searchValues,payload.pattern??query,payload.flags??'i');rows=rows.filter((_,i)=>matches[i]);}
  else if(query){const lower=query.toLowerCase();rows=rows.filter((_,i)=>searchValues[i].toLowerCase().includes(lower));}
  if(payload.sort==='size'||payload.sort==='size-desc')rows.sort((a,b)=>a.bytes===undefined?b.bytes===undefined?a.tag.localeCompare(b.tag):1:b.bytes===undefined?-1:(payload.sort==='size-desc'?b.bytes-a.bytes:a.bytes-b.bytes)||a.tag.localeCompare(b.tag));
  else if(payload.sort==='context')rows.sort((a,b)=>(b.context??-1)-(a.context??-1)||a.tag.localeCompare(b.tag));else rows.sort((a,b)=>a.tag.localeCompare(b.tag));
  return {status:this.catalog,localState,localAt:this.localAt,total:rows.length,page,hasNext:page*size<rows.length,families:[...new Set(all.map(v=>v.family))].sort(),variants:[...new Set(all.map(v=>v.tag.split(':').slice(1).join(':')).filter(Boolean))].sort(),quantizations:[...new Set(all.map(v=>v.quantization).filter((v):v is string=>!!v))].sort(),items:rows.slice((page-1)*size,page*size).map(v=>({...v,fit:fit(v)}))};
 }
 async refreshCatalog(){await this.ready;if(this.refreshing)return this.catalog;this.refreshing=new AbortController();this.catalog={...this.catalog,state:'refreshing',error:undefined};void this.crawl(this.refreshing).finally(()=>{this.refreshing=undefined;});return this.catalog;}
 private async crawl(controller:AbortController){const hashes:string[]=[],seen=new Set<string>(),familyNames=new Set<string>(),variants=new Map<string,CatalogVariant>();let pages=0;const page=async(path:string,family?:string)=>{if(! /^\/library(?:\/[A-Za-z0-9_.-]+\/tags)?(?:\?[^#]*)?$/.test(path))throw new Error('Official catalog returned an unsupported page link');if(seen.has(path))return null;if(seen.size>=10000)throw new Error('Catalog exceeded 10,000 page safety bound');seen.add(path);const response=await this.fetcher('https://ollama.com'+path,{redirect:'error',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)])});if(!response.ok)throw new Error(`Official catalog returned HTTP ${response.status}`);const text=await limitedText(response,8*1024*1024,controller.signal);hashes.push(createHash('sha256').update(text).digest('hex'));pages++;const parsed=parseCatalogPage(text,family);if(family&&!parsed.variants.length)throw new Error(`Official tag page has no recognized variants for ${family}; catalog is incomplete`);if(!family&&!parsed.names.length)throw new Error('Official library markup has no recognized models; catalog is incomplete');this.catalog={...this.catalog,pages,families:familyNames.size,variants:variants.size};return parsed;};try{const library=['/library'];while(library.length){const parsed=await page(library.shift()!);if(!parsed)continue;parsed.names.forEach(n=>familyNames.add(n));for(const p of parsed.next)if(!seen.has(p))library.push(p);}for(const family of familyNames){const tagPages=[`/library/${family}/tags`];while(tagPages.length){const parsed=await page(tagPages.shift()!,family);if(!parsed)continue;for(const item of parsed.variants){if(variants.size>=500000&&!variants.has(item.tag))throw new Error('Catalog exceeds 500,000 variants');variants.set(item.tag,item);}for(const p of parsed.next)if(!seen.has(p))tagPages.push(p);}}
 const now=new Date().toISOString();const status:CatalogStatus={state:'ready',complete:true,at:now,lastSuccess:now,pages,families:familyNames.size,variants:variants.size,revision:createHash('sha256').update(hashes.join('\n')).digest('hex')};const inventory=[...variants.values()];await atomicJson(join(this.directory,'catalog.json'),{status,inventory});this.inventory=inventory;this.catalog=status;
 }catch(error){this.catalog={...this.catalog,state:this.inventory.length?'offline':'failed',complete:this.inventory.length>0,error:error instanceof Error?error.message:'Catalog refresh failed'};}}
 private async pullItems():Promise<PullItem[]>{try{const data=JSON.parse(await readFile(join(this.directory,'pulls.json'),'utf8'));if(!Array.isArray(data)||data.length>1000)throw new Error('Invalid pull journal');return data;}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return [];throw e;}}
 private savePulls(items:PullItem[]){return atomicJson(join(this.directory,'pulls.json'),items);}
 async pullReview(payload:Record<string,unknown>){await this.ready;const tags=payload.tags;if(!Array.isArray(tags)||!tags.length||tags.length>100)throw new Error('Choose between 1 and 100 exact tags per batch');const hardware=await this.hardware();const items=[...new Set(tags.map(validateModel))].map(tag=>{const metadata=this.inventory.find(v=>v.tag===tag);return {tag,bytes:metadata?.bytes,additionalDisk:metadata?.bytes===undefined?undefined:Math.ceil(metadata.bytes*1.2),fit:hardwareFit(metadata??{},hardware)};});return {items,hardware,totalKnownBytes:items.reduce((n,i)=>n+(i.bytes??0),0),unknownSizes:items.filter(i=>i.bytes===undefined).length,disclosure:'Ollama downloads registry blobs over the network. Sizes are reported catalog estimates. The detected model-volume free space is conservative evidence; an externally configured Ollama service may use another destination.'};}
 async startPulls(payload:Record<string,unknown>){await this.ready;if(payload.confirmed!==true)throw new Error('Review and confirm the model download batch');if(this.pullActive)throw new Error('A pull batch is already running');const review=await this.pullReview(payload),items=await this.pullItems();if(items.length+review.items.length>1000)throw new Error('Pull history safety bound reached');const parallel=Number(payload.parallel??1);if(!Number.isInteger(parallel)||parallel<1||parallel>3)throw new Error('Parallel pulls must be between 1 and 3');const added=review.items.map(i=>({id:randomUUID(),tag:i.tag,status:'queued' as const}));items.push(...added);await this.savePulls(items);this.pullActive=true;void this.processPulls(items,added.map(i=>i.id),parallel).finally(()=>{this.pullActive=false;});return added;}
 private async processPulls(items:PullItem[],ids:string[],parallel:number){this.activePullItems=items;let save=Promise.resolve();const persist=()=>{const snapshot=JSON.parse(JSON.stringify(items));save=save.then(()=>this.savePulls(snapshot));return save;};let installed=new Set<string>();try{const data=object(await localApi('models',{},this.fetcher));if(!Array.isArray(data.models))throw new Error('Invalid installed models');installed=new Set(data.models.map(m=>validateModel(object(m).name)));}catch{}let position=0;await Promise.all(Array.from({length:parallel},async()=>{while(position<ids.length){const id=ids[position++],item=items.find(i=>i.id===id)!;if(item.status==='cancelled')continue;if(installed.has(item.tag)){item.status='skipped';item.message='Exact tag already installed.';await persist();continue;}const controller=new AbortController();this.jobs.set(id,controller);item.status='pulling';item.error=undefined;await persist();try{await this.stream('/api/pull',{model:item.tag,stream:true},controller.signal,async record=>{if(record.error)throw new Error(String(record.error).slice(0,500));item.message=String(record.status??'Pulling').slice(0,200);if(typeof record.total==='number'&&Number.isSafeInteger(record.total)&&record.total>=0)item.total=record.total;if(typeof record.completed==='number'&&Number.isSafeInteger(record.completed)&&record.completed>=0)item.completed=record.completed;if(typeof record.digest==='string')item.digest=record.digest.slice(0,100);await persist();});if(item.message!=='success')throw new Error('Pull stream ended without success; retry to reconcile');const current=object(await localApi('models',{},this.fetcher));if(!Array.isArray(current.models)||!current.models.some(m=>object(m).name===item.tag))throw new Error('Pull reported success but the exact installed tag was not found');item.status='pulled';}catch(e){item.status=controller.signal.aborted?'cancelled':'failed';item.error=redactExport(e instanceof Error?e.message:'Pull failed');}finally{this.jobs.delete(id);await persist();}}}));await persist();this.activePullItems=undefined;}
 private async stream(path:'/api/pull'|'/api/chat'|'/api/generate',body:unknown,signal:AbortSignal,onRecord:(record:Record<string,unknown>)=>Promise<void>):Promise<void>{if(signal.aborted)throw new Error('Local operation cancelled');const response=await this.fetcher(ENDPOINT+path,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.any([signal,AbortSignal.timeout(path==='/api/pull'?4*60*60*1000:10*60*1000)])});if(!response.ok)throw new Error(`Local Ollama returned HTTP ${response.status}`);const reader=response.body?.getReader();if(!reader)throw new Error('Missing local Ollama stream');const decoder=new TextDecoder('utf-8',{fatal:true});let pending='',total=0;try{while(true){const part=await reader.read();if(part.done)break;total+=part.value.length;if(total>8*1024*1024)throw new Error('Local stream exceeded 8 MiB limit');pending+=decoder.decode(part.value,{stream:true});if(pending.length>512000)throw new Error('Local stream line exceeded safety limit');let split:number;while((split=pending.indexOf('\n'))>=0){const line=pending.slice(0,split);pending=pending.slice(split+1);if(line.trim())await onRecord(object(JSON.parse(line)));}}pending+=decoder.decode();if(pending.trim())await onRecord(object(JSON.parse(pending)));}finally{await reader.cancel().catch(()=>{});}}
 async pullStatus(){await this.ready;return {active:this.pullActive,items:await this.pullItems()};}
 async cancelPull(payload:Record<string,unknown>){await this.ready;const items=this.activePullItems??await this.pullItems(),id=identifier(payload.id),item=items.find(i=>i.id===id);if(!item)throw new Error('Pull not found');if(this.jobs.has(id)){this.jobs.get(id)!.abort();return {cancelRequested:true};}if(item.status==='queued'){item.status='cancelled';await this.savePulls(items);}return item;}
 async retryPull(payload:Record<string,unknown>){await this.ready;if(this.pullActive)throw new Error('Wait for active pulls before retry');const id=identifier(payload.id),items=await this.pullItems(),item=items.find(i=>i.id===id);if(!item||!['failed','cancelled','queued'].includes(item.status))throw new Error('Choose an interrupted or failed pull');item.status='queued';item.error=undefined;await this.savePulls(items);this.pullActive=true;void this.processPulls(items,[id],1).finally(()=>{this.pullActive=false;});return item;}
 private attachmentDirectory(){return join(this.directory,'attachments');}
 private sessionPath(id:unknown){return join(this.directory,'sessions',identifier(id)+'.json');}
 async sessions(){await this.ready;const files=await readdir(join(this.directory,'sessions'));const result:Array<{id:string;name:string;model:string;at:string;count:number}>=[];for(const file of files.slice(0,500)){if(!/^[a-f0-9-]{36}\.json$/.test(file))continue;try{const s=await this.session(file.slice(0,-5));result.push({id:s.id,name:s.name,model:s.model,at:s.at,count:s.messages.length});}catch{}}return result.sort((a,b)=>b.at.localeCompare(a.at));}
 async session(id:unknown):Promise<ChatSession>{await this.ready;const file=this.sessionPath(id);if((await stat(file)).size>1024*1024)throw new Error('Chat session exceeds resource limit');const s=JSON.parse(await readFile(file,'utf8'));if(!Array.isArray(s.messages)||s.messages.length>128||typeof s.system!=='string'||s.system.length>16000)throw new Error('Invalid local chat session');for(const message of s.messages){if(!message||!['system','user','assistant'].includes(message.role)||typeof message.content!=='string'||message.content.length>128000||message.attachments!==undefined&&(!Array.isArray(message.attachments)||message.attachments.length>4))throw new Error('Invalid saved chat message');for(const attachment of message.attachments??[])validateChatAttachment(attachment);}if(s.messages.reduce((n:number,m:ChatMessage)=>n+(m.attachments?.length??0),0)>16)throw new Error('Saved chat image count exceeds its resource bound');return s;}
 async createSession(payload:Record<string,unknown>){await this.ready;const model=validateModel(payload.model);const s:ChatSession={id:randomUUID(),name:String(payload.name??'New conversation').trim().slice(0,100)||'New conversation',model,at:new Date().toISOString(),system:'',messages:[]};if((await this.sessions()).length>=500)throw new Error('Saved chat session limit reached');await atomicJson(this.sessionPath(s.id),s);return s;}
 async renameSession(payload:Record<string,unknown>){await this.ready;const s=await this.session(payload.id);if([...this.runners.values()].some(r=>r.session===s.id&&r.status==='running'))throw new Error('Stop the response before renaming its session');const name=String(payload.name??'').trim();if(!name||name.length>100)throw new Error('Use a session name of 1 to 100 characters');s.name=name;await atomicJson(this.sessionPath(s.id),s);return s;}
 async deleteSession(payload:Record<string,unknown>){await this.ready;if(payload.confirmed!==true)throw new Error('Confirm deleting this saved conversation');const id=identifier(payload.id);if([...this.runners.values()].some(r=>r.session===id&&r.status==='running'))throw new Error('Stop the response before deleting its session');const session=await this.session(id);await unlink(this.sessionPath(id));await deleteChatImages(this.attachmentDirectory(),session.messages.flatMap(m=>m.attachments??[]));return {deleted:true};}
 async exportSession(payload:Record<string,unknown>){await this.ready;const s=await this.session(payload.id);return {id:s.id,name:redactExport(s.name),model:s.model,at:s.at,system:redactExport(s.system),messages:s.messages.map(m=>({...m,content:redactExport(m.content),...(m.attachments?{attachments:m.attachments.map(a=>({name:redactExport(a.name),mime:a.mime,bytes:a.bytes,notice:'Image content is not included in this text export.'}))}:{})})),notice:'Known credential patterns and local filesystem paths are redacted. Review freeform content before sharing.'};}
 async startChat(payload:Record<string,unknown>,images:PreparedChatImage[]=[]){
  await this.ready;if(this.generation.activeJobs()||this.chatAdmission||[...this.runners.values()].some(r=>r.status==='running'))throw new Error('Only one local chat response can run at a time');
  this.chatAdmission=true;const admission=randomUUID(),controller=new AbortController();this.jobs.set(admission,controller);try{return await this.startChatAdmitted(payload,images,controller);}finally{this.jobs.delete(admission);this.chatAdmission=false;}
 }
 private async startChatAdmitted(payload:Record<string,unknown>,images:PreparedChatImage[],controller:AbortController){
  const s=await this.session(payload.session),prompt=String(payload.prompt??''),system=String(payload.system??s.system);
  if(!prompt.trim()||prompt.length>16000||system.length>16000)throw new Error('Prompt/system must be nonempty and at most 16,000 characters each');
  const temperature=Number(payload.temperature??.7),tokens=Number(payload.tokens??1024),context=Number(payload.context??4096);
  if(!Number.isFinite(temperature)||temperature<0||temperature>2||!Number.isInteger(tokens)||tokens<1||tokens>8192||!Number.isInteger(context)||context<512||context>32768)throw new Error('Chat parameters are outside supported bounds');
  const regenerate=payload.regenerate===true;
  if(!regenerate&&s.messages.length>=126)throw new Error('Session reached 128-message resource limit; create another conversation');
  if(regenerate&&s.messages.at(-1)?.role!=='assistant')throw new Error('No assistant response to regenerate');
  const previousUser=regenerate?[...s.messages].reverse().find(m=>m.role==='user'):undefined,existingImages=previousUser?.attachments??[];
  if(images.length&&regenerate)throw new Error('Regenerate reuses the original images; send a new message to change them');
  if(images.length||s.messages.some(m=>m.attachments?.length)){
   const metadata=object(await localApi('show',{model:s.model},this.fetcher));
   if(!Array.isArray(metadata.capabilities)||!metadata.capabilities.includes('vision'))throw new Error('The installed model did not report vision support; choose a verified vision model before sending images');
  }
  if(s.messages.reduce((n,m)=>n+(m.attachments?.length??0),0)+images.length>16)throw new Error('Conversation reached its 16-image storage bound; create another conversation');
  if(controller.signal.aborted)throw new Error('Chat preparation cancelled');
  const added=images.length?await saveChatImages(this.attachmentDirectory(),images):[],attachments=added.length?added:existingImages;
  try{
   if(regenerate){s.messages.pop();if(s.messages.at(-1)?.role==='user')s.messages.pop();}
   s.system=system;s.messages.push({role:'user',content:prompt,...(attachments.length?{attachments}:{})});s.at=new Date().toISOString();
   if(JSON.stringify(s).length>512000)throw new Error('Chat history exceeds 512,000 characters');
   if(s.messages.slice(-40).reduce((n,m)=>n+(m.attachments??[]).reduce((bytes,a)=>bytes+a.bytes,0),0)>8*1024*1024)throw new Error('Active chat context exceeds 8 MiB of images; create another conversation');
   await atomicJson(this.sessionPath(s.id),s);
  }catch(error){await deleteChatImages(this.attachmentDirectory(),added);throw error;}
  const run:ChatRun={id:randomUUID(),session:s.id,status:'running',content:''};this.runners.set(run.id,run);
  this.jobs.set(run.id,controller);
  void(async()=>{
   let done=false,lastSaved=0;let terminal:ChatRun['status']='succeeded';const assistant:ChatMessage={role:'assistant',content:''};let recorded=false;
   const checkpoint=async()=>{if(!run.content)return;if(!recorded){s.messages.push(assistant);recorded=true;}assistant.content=run.content;s.at=new Date().toISOString();await atomicJson(this.sessionPath(s.id),s);lastSaved=Date.now();};
   try{
    const history=await Promise.all(s.messages.slice(-40).map(async message=>({role:message.role,content:message.content,...(message.attachments?.length?{images:await Promise.all(message.attachments.map(a=>readChatImage(this.attachmentDirectory(),a)))}:{})})));
    const messages=[...(s.system?[{role:'system',content:s.system}]:[]),...history];
    await this.stream('/api/chat',{model:s.model,messages,stream:true,options:{temperature,num_predict:tokens,num_ctx:context}},controller.signal,async record=>{
     if(record.error)throw new Error(String(record.error).slice(0,500));const content=object(record.message??{}).content;
     if(typeof content==='string'){if(run.content.length+content.length>128000)throw new Error('Response exceeded 128,000-character bound');run.content+=content;if(Date.now()-lastSaved>=750)await checkpoint();}
     if(record.done===true){done=true;if(typeof record.eval_count==='number')run.tokens=record.eval_count;}
    });
    if(!done)throw new Error('Local response stream ended before completion');
   }catch(error){terminal=controller.signal.aborted?'cancelled':'failed';run.error=redactExport(error instanceof Error?error.message:'Chat failed');}
   finally{
    try{await checkpoint();}catch{terminal='failed';run.error='Response received, but local session persistence failed.';}
    run.status=terminal;this.jobs.delete(run.id);
    while(this.runners.size>50){const first=this.runners.keys().next().value;if(first)this.runners.delete(first);else break;}
   }
  })();return {...run};
 }
 async chatStatus(payload:Record<string,unknown>){await this.ready;const run=this.runners.get(identifier(payload.id));if(!run)throw new Error('Response not found, possibly interrupted by app restart. Saved history remains available.');return {...run};}
 async cancelChat(payload:Record<string,unknown>){const id=identifier(payload.id);this.jobs.get(id)?.abort();return {cancelRequested:true};}
 async harnessProfiles(){await this.ready;return {profiles:harnessProfiles,...await this.runtime.status()};}
 async pickHarnessRuntime(){await this.ready;return this.runtime.pick();}
 async registerHarnessRuntime(payload:Record<string,unknown>){await this.ready;return this.runtime.register(payload);}
 async preflight(payload:Record<string,unknown>={}){await this.ready;const id=randomUUID(),profile=harnessProfiles.find(item=>item.id===(payload.profile??'ollama-conservative'));if(!profile)throw Error('Choose a shipped local service profile');const runtime=await this.runtime.registered(),health=object(await localApi('health',{},this.fetcher)),hardware=await this.hardware(),blockers:string[]=[];
  if(!runtime)blockers.push('Select a native Ollama runtime and review its exact digest before approving execution.');if(health.available===true)blockers.push('Local Ollama is already running. Restore the app-owned service or stop the external service before starting a stopped-service profile.');if(this.children.size)blockers.push('An app-owned service process remains active. Restore that launch before starting another profile.');
  const review:HarnessState={id,state:'review',profile:profile.id,executable:runtime?.name??'Not registered',runtimeDigest:runtime?.sha256,runtimeVersion:runtime?.version,arguments:['serve'],environmentKeys:['PATH','HOME','USERPROFILE','LOCALAPPDATA','SYSTEMROOT','OLLAMA_HOST',...Object.keys(profile.environment)],environment:{OLLAMA_HOST:'127.0.0.1:11434',...profile.environment},workingDirectory:'Private app-owned runtime folder',requiredPorts:[11434],fit:hardwareFit({},hardware,Number(profile.environment.OLLAMA_CONTEXT_LENGTH??4096)),blockers,message:profile.reason+' This profile starts only an explicitly trusted stopped runtime; it does not load or download models. Model-specific memory fit is unknown until an installed model is inspected in the model workspace.'};
  for(const[key,state]of this.pending)if(!this.children.has(key)&&state.state!=='starting')this.pending.delete(key);this.pending.set(id,review);await atomicJson(join(this.directory,'harness-review.json'),{...review,executablePath:runtime?.path??'',identity:runtime?.identity??null,created:Date.now()});return review;
 }
 async launchHarness(payload:Record<string,unknown>){await this.ready;if(payload.confirmed!==true)throw new Error('Review and confirm this harness launch');const id=identifier(payload.id),review=this.pending.get(id);if(!review||review.blockers.length)throw new Error('Run a successful preflight first');const data=JSON.parse(await readFile(join(this.directory,'harness-review.json'),'utf8'));if(data.id!==id||Date.now()-data.created>120000)throw new Error('Harness review expired; run preflight again');const runtime=await this.runtime.registered();if(!runtime||runtime.path!==data.executablePath||runtime.sha256!==review.runtimeDigest||JSON.stringify(runtime.identity)!==JSON.stringify(data.identity))throw new Error('Detected executable changed after preflight; review it again');if(object(await localApi('health',{},this.fetcher)).available===true)throw new Error('Another local service started after preflight; launch cancelled');const snapshot=randomUUID();await atomicJson(join(this.directory,'harness-snapshot.json'),{id:snapshot,profile:review.profile,arguments:review.arguments,environmentKeys:review.environmentKeys,previousState:'stopped',at:new Date().toISOString()});review.snapshot=snapshot;review.state='starting';const child=spawn(data.executablePath,['serve'],{shell:false,cwd:this.directory,windowsHide:true,stdio:'ignore',env:{PATH:process.env.PATH??'',HOME:homedir(),USERPROFILE:homedir(),LOCALAPPDATA:process.env.LOCALAPPDATA??'',SYSTEMROOT:process.env.SYSTEMROOT??'',OLLAMA_HOST:'127.0.0.1:11434',...review.environment}});this.children.set(id,child);child.once('error',()=>{review.state='failed';review.message='Native service start failed. The snapshot is retained; restore verifies owned process closure.';});child.once('exit',()=>{if(review.state==='ready'){review.state='exited';review.message='Owned local service exited.';}});child.once('close',()=>this.children.delete(id));void(async()=>{for(let n=0;n<20;n++){await new Promise(r=>setTimeout(r,500));if(review.state==='failed'||child.exitCode!==null)break;const health=object(await localApi('health',{},this.fetcher));if(health.available===true&&this.children.has(id)){review.state='ready';review.message='Owned process started and local API readiness verified.';return;}}try{await this.stopHarness(id);review.state='failed';review.message='Readiness failed or timed out. Owned process closure verified; the prior stopped-service state is restored.';}catch{review.state='failed';review.message='Readiness failed and owned process closure could not be verified. Restore again before another launch.';}})();return review;}
 async harnessStatus(payload:Record<string,unknown>){await this.ready;const state=this.pending.get(identifier(payload.id));if(!state)throw new Error('Harness review is no longer available; run preflight again');return {...state};}
 private async stopHarness(id:string){const child=this.children.get(id);if(!child)return;await new Promise<void>((resolve,reject)=>{let settled=false;const done=(error?:Error)=>{if(settled)return;settled=true;clearTimeout(kill);clearTimeout(deadline);error?reject(error):resolve();};const kill=setTimeout(()=>child.kill('SIGKILL'),3000),deadline=setTimeout(()=>done(Error('Owned service closure was not verified within five seconds')),5000);child.once('close',()=>done());if(child.exitCode===null&&child.signalCode===null)child.kill('SIGTERM');});}
 async restoreHarness(payload:Record<string,unknown>){await this.ready;const id=identifier(payload.id),state=this.pending.get(id);if(!state||!state.snapshot)throw new Error('No owned harness snapshot is available');await this.stopHarness(id);state.state='restored';state.message='Owned service closure verified. The prior stopped-service state is restored; no external process or user configuration was changed.';return {...state};}
 activeJobs(){return this.children.size>0||this.runtime.activeJobs()||this.generation.activeJobs()||this.jobs.size>0||this.chatAdmission||this.pullActive||!!this.refreshing||[...this.pending.values()].some(s=>s.state==='starting');}
 cancelAll(){for(const id of this.children.keys())void this.stopHarness(id).catch(()=>{});this.generation.cancelAll();this.refreshing?.abort();for(const controller of this.jobs.values())controller.abort();if(this.activePullItems)for(const item of this.activePullItems)if(item.status==='queued')item.status='cancelled';}
 dispose(){this.cancelAll();for(const child of this.children.values())child.kill();}
}
