import {createLocalRecovery} from './local-recovery.js';
import {createElementLocks} from './element-locks.js';
import {UnlockLadder} from './unlock-ladder.js';
import {createHmac,randomBytes,scryptSync,timingSafeEqual,randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';import {watch,type FSWatcher}from'node:fs';import path from'node:path';
import {parseOtpAuth,otpAuthUri,validateTotpParameters,type TotpParameters,type SecurityStatus,type AuthenticatorSummary,type LockTarget}from'../shared/security.js';
export interface SecretVault{isEncryptionAvailable():boolean;encryptString(value:string):Buffer;decryptString(value:Buffer):string;getSelectedStorageBackend?():string}
export function vaultAvailable(vault:SecretVault):boolean{try{return vault.isEncryptionAvailable()&&vault.getSelectedStorageBackend?.()!=='basic_text';}catch{return false;}}
function base32(secret:string):Buffer{let bits=0,value=0;const bytes:number[]=[];for(const char of secret.toUpperCase().replace(/=+$/,'')){const n='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(char);if(n<0)throw new Error('Invalid base32');value=(value<<5)|n;bits+=5;if(bits>=8){bits-=8;bytes.push((value>>>bits)&255);}}if(!bytes.length||((value&((1<<bits)-1))!==0))throw new Error('Invalid base32 padding');return Buffer.from(bytes);}
export function totp(parameters:TotpParameters,timeMilliseconds=Date.now()):string{const p=validateTotpParameters(parameters);if(!Number.isFinite(timeMilliseconds)||timeMilliseconds<0)throw new Error('Invalid system time');const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(timeMilliseconds/1000/p.period)));const hash=createHmac(p.algorithm.toLowerCase(),base32(p.secret)).update(counter).digest(),offset=hash[hash.length-1]&15,value=(hash.readUInt32BE(offset)&0x7fffffff)%10**p.digits;return String(value).padStart(p.digits,'0');}
export function verifyTotp(parameters:TotpParameters,code:string,timeMilliseconds=Date.now(),window=1):boolean{if(!new RegExp(`^\\d{${parameters.digits}}$`).test(code)||!Number.isInteger(window)||window<0||window>2)return false;for(let n=-window;n<=window;n++){const time=timeMilliseconds+n*parameters.period*1000;if(time<0)continue;if(timingSafeEqual(Buffer.from(totp(parameters,time)),Buffer.from(code)))return true;}return false;}
export function encodeBase32(bytes:Uint8Array):string{let bits=0,value=0,result='';for(const byte of bytes){value=(value<<8)|byte;bits+=8;while(bits>=5){bits-=5;result+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'[(value>>>bits)&31];}}if(bits)result+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'[(value<<(5-bits))&31];return result;}
export function hashCredential(password:string):string{if(typeof password!=='string'||password.length<4||password.length>256)throw new Error('Use a credential between 4 and 256 characters');const salt=randomBytes(16);return `scrypt-v1:${salt.toString('hex')}:${scryptSync(password,salt,32).toString('hex')}`;}
export function verifyCredential(password:string,hash:string):boolean{if(typeof password!=='string'||password.length>256||!/^scrypt-v1:[0-9a-f]{32}:[0-9a-f]{64}$/.test(hash))return false;const[,salt,digest]=hash.split(':');return timingSafeEqual(scryptSync(password,Buffer.from(salt,'hex'),32),Buffer.from(digest,'hex'));}
export class AttemptBudget{private failures=0;private until=0;check(now=Date.now()){if(now<this.until)throw new Error('Too many attempts; wait before trying again');if(this.until){this.failures=0;this.until=0;}}result(valid:boolean,now=Date.now()){if(valid){this.failures=0;this.until=0;}else if(++this.failures>=5)this.until=now+30000;return valid;}}
interface RecordData{schemaVersion:1;schoolMode:SecurityStatus['schoolMode'];credential?:string;locks:Record<string,string>}
interface EntryData extends AuthenticatorSummary{encrypted:string}
export function createSecurityService(options:{directory:string;authenticatorDirectory:string;vault:SecretVault;now?:()=>number;openRecoveryDirectory?:(directory:string)=>Promise<void>;recordMutation?:(action:string,metadata:unknown)=>Promise<void>}){
 const {directory,authenticatorDirectory,vault}=options,file=path.join(directory,'shared-ui-state.json'),entryFile=path.join(authenticatorDirectory,'authenticator.json'),listeners=new Set<(status:SecurityStatus)=>void>(),nativeTargets=new Set<string>(),ladderSkips:number[]=[],budget=new UnlockLadder(options.now,ladderSkips);let watcher:FSWatcher|null=null;let error:string|undefined;let lastMode:SecurityStatus['schoolMode']={displayName:'Presentation mode',active:true,revision:0,updatedAt:null};let serial:Promise<unknown>=Promise.resolve();
 const locks=createElementLocks({directory:authenticatorDirectory,encrypt,decrypt,hash:hashCredential,verify:verifyCredential,verifyOtp:(value,code)=>verifyTotp(validateTotpParameters(value),code,(options.now??Date.now)()),validateOtp:validateTotpParameters,now:options.now,ladderSkips,recordMutation:options.recordMutation});
 const recovery=createLocalRecovery(authenticatorDirectory,options.openRecoveryDirectory);
 const initial=():RecordData=>({schemaVersion:1,schoolMode:{displayName:'School mode',active:false,revision:0,updatedAt:null},locks:Object.create(null)});
 function encrypt(value:string){if(!vaultAvailable(vault))throw new Error('Operating-system encrypted storage is unavailable; no secret was saved');return vault.encryptString(value).toString('base64');}
 function decrypt(value:string){if(!vaultAvailable(vault))throw new Error('Operating-system encrypted storage is unavailable');return vault.decryptString(Buffer.from(value,'base64'));}
 async function read():Promise<RecordData>{try{const raw=await readFile(file,'utf8');if(raw.length>131072)throw new Error();const data=JSON.parse(raw)as RecordData;if(data.schemaVersion!==1||!data.schoolMode||typeof data.schoolMode.active!=='boolean'||typeof data.schoolMode.displayName!=='string'||!data.schoolMode.displayName.trim()||data.schoolMode.displayName.length>80||/[\u0000-\u001f]/.test(data.schoolMode.displayName)||Object.keys(data.schoolMode).some(k=>!['displayName','active','revision','updatedAt'].includes(k))||(data.schoolMode.updatedAt!==null&&(typeof data.schoolMode.updatedAt!=='string'||!Number.isFinite(Date.parse(data.schoolMode.updatedAt))))||!Number.isSafeInteger(data.schoolMode.revision)||data.schoolMode.revision<0||!data.locks||typeof data.locks!=='object'||Array.isArray(data.locks)||Object.keys(data.locks).length>100||Object.keys(data).some(k=>!['schemaVersion','schoolMode','credential','locks'].includes(k))||(data.credential!==undefined&&(typeof data.credential!=='string'||data.credential.length>4096))||Object.entries(data.locks).some(([id,value])=>!validId(id)||typeof value!=='string'||value.length>4096))throw new Error();lastMode={...data.schoolMode};return data;}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return initial();throw new Error('Shared mode record is unavailable or invalid');}}
 async function write(data:unknown,destination=file){const folder=path.dirname(destination);await mkdir(folder,{recursive:true,mode:0o700});const temporary=destination+'.'+randomUUID()+'.tmp';await writeFile(temporary,JSON.stringify(data),{mode:0o600});await rename(temporary,destination);}
 async function status():Promise<SecurityStatus>{try{const data=await read();return {available:true,vaultAvailable:vaultAvailable(vault),watching:Boolean(watcher),recoveryDirectory:directory,lockRecoveryDirectory:authenticatorDirectory,schoolMode:data.schoolMode,credentialSet:Boolean(data.credential),...(error?{error}:{})};}catch(e){return {available:false,vaultAvailable:vaultAvailable(vault),watching:Boolean(watcher),recoveryDirectory:directory,lockRecoveryDirectory:authenticatorDirectory,schoolMode:{...lastMode,active:true},credentialSet:false,error:(e as Error).message};}}
 async function emit(){const value=await status();for(const listener of listeners)listener(value);}
 async function start(){await mkdir(directory,{recursive:true,mode:0o700});try{watcher=watch(directory,()=>{void emit();});watcher.on('error',()=>{error='Shared state watch unavailable; live mode changes cannot be guaranteed';void emit();});}catch{error='Shared state watch unavailable; live mode changes cannot be guaranteed';}return status();}
 function validId(id:unknown):id is string{return typeof id==='string'&&/^[a-zA-Z0-9._-]{1,128}$/.test(id)&&!['__proto__','constructor','prototype'].includes(id);}
 function credential(data:RecordData,password:unknown){budget.check();const valid=typeof password==='string'&&Boolean(data.credential)&&verifyCredential(password,decrypt(data.credential!));if(!budget.result(valid))throw new Error('Credential did not match');}
 async function entries():Promise<EntryData[]>{try{const raw=await readFile(entryFile,'utf8');if(raw.length>262144)throw new Error();const data=JSON.parse(raw);if(data.schemaVersion!==1||!Array.isArray(data.entries)||data.entries.length>100)throw new Error();const ids=new Set<string>();for(const entry of data.entries){if(!validId(entry.id)||ids.has(entry.id)||typeof entry.encrypted!=='string'||entry.encrypted.length>8192)throw new Error();ids.add(entry.id);if(Object.keys(entry).some(k=>!['id','issuer','account','algorithm','digits','period','encrypted'].includes(k)))throw new Error();const p=validateTotpParameters(JSON.parse(decrypt(entry.encrypted)));if(entry.issuer!==p.issuer||entry.account!==p.account||entry.period!==p.period||entry.digits!==p.digits||entry.algorithm!==p.algorithm)throw new Error();}return data.entries;}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return [];throw new Error('Authenticator storage is unavailable or invalid');}}
 const summary=({encrypted:_,...metadata}:EntryData):AuthenticatorSummary=>metadata;
 async function handle(action:string,payload:Record<string,unknown>={}){
  if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('Invalid local security request');
  const allowed=['targets','id','pin','password','code','uri','policy','duration','parameters','disclosed','currentAnswers','currentPassword','displayName','active','issuer','account','algorithm','digits','period','confirmed','nonce','answer','cell','category','description','severity'];
  if(Object.keys(payload).length>24||Object.keys(payload).some(k=>!allowed.includes(k))||Object.values(payload).some(v=>typeof v==='string'&&v.length>8192))throw new Error('Invalid local security parameter');
  if(action==='status')return status();
  if(action==='lockRegister'){if(!Array.isArray(payload.targets)||payload.targets.length>1000)throw new Error('Invalid lock targets');if((payload.targets as LockTarget[]).some(target=>target.ancestors!==undefined))throw new Error('Renderer targets cannot assign native lock ancestors');locks.registerTargets((payload.targets as LockTarget[]).filter(target=>!nativeTargets.has(target.id)));return{registered:true};}
  if(payload.id==='shared-mode'){if(action==='ladderChallenge')return budget.generate((await status()).schoolMode.active);if(action==='ladderAnswer')return budget.answer(payload.nonce,payload.answer);if(action==='ladderHit')return budget.hit(payload.nonce,payload.cell);if(action==='lockVerify'){credential(await read(),payload.password);return{verified:true};}if(action==='lockSet')throw new Error('Use the shared mode credential control');}
  if(['lockList','lockSet','lockVerify','lockAgain','lockRemove','ladderChallenge','ladderAnswer','ladderHit'].includes(action))return locks.handle(action,payload,(await status()).schoolMode.active);
  if(action==='modeLadderChallenge')return budget.generate((await status()).schoolMode.active);
  if(action==='modeLadderAnswer')return budget.answer(payload.nonce,payload.answer);
  if(action==='attemptStatus')return budget.status();
  if(['recoveryList','recoveryCreate','recoveryAdvance','recoveryRemove','recoveryOpen'].includes(action))return recovery.handle(action,payload);
if(action==='pairingGenerate'){if(!vaultAvailable(vault))throw new Error('Operating-system encrypted storage is unavailable');const parameters=validateTotpParameters({secret:encodeBase32(randomBytes(20)),issuer:payload.issuer??'Material Git',account:payload.account,algorithm:payload.algorithm??'SHA1',digits:payload.digits??6,period:payload.period??30});return {parameters,uri:otpAuthUri(parameters)};}const data=await read();
  if(action==='verifyCredential'){credential(data,payload.password);return {verified:true};}
  if(action==='setCredential'){if(data.credential)credential(data,payload.currentPassword);data.credential=encrypt(hashCredential(payload.password as string));}
  else if(action==='rename'){credential(data,payload.password);if(typeof payload.displayName!=='string'||!payload.displayName.trim()||payload.displayName.length>80||/[\u0000-\u001f]/.test(payload.displayName))throw new Error('Invalid mode name');data.schoolMode.displayName=payload.displayName.trim();}
  else if(action==='setMode'){if(typeof payload.active!=='boolean')throw new Error('Invalid mode state');credential(data,payload.password);data.schoolMode.active=payload.active;}
  else if(action==='authenticatorList')return {entries:(await entries()).map(summary)};
  else if(action==='authenticatorEnroll'){const p=typeof payload.uri==='string'?parseOtpAuth(payload.uri):validateTotpParameters(payload.parameters);budget.check();if(!budget.result(typeof payload.code==='string'&&verifyTotp(p,payload.code)))throw new Error('Current code did not match; registration was not completed');const all=await entries();if(all.length>=100)throw new Error('Authenticator entry limit reached');const{id:_,...parameters}=p as TotpParameters&{id?:string};const entry:EntryData={id:randomUUID(),issuer:p.issuer,account:p.account,algorithm:p.algorithm,digits:p.digits,period:p.period,encrypted:encrypt(JSON.stringify(parameters))};all.push(entry);await options.recordMutation?.('authenticatorEnrolled',{id:entry.id,issuer:p.issuer,account:p.account,secretsOmitted:true});await write({schemaVersion:1,entries:all},entryFile);return summary(entry);}
  else if(action==='authenticatorCodes'){const all=await entries(),now=Date.now();return {clockSource:'system',clockVerified:false,entries:all.map(entry=>{const p=validateTotpParameters(JSON.parse(decrypt(entry.encrypted)));return {...summary(entry),code:totp(p,now),nextCode:totp(p,now+p.period*1000),remaining:p.period-Math.floor(now/1000)%p.period};})};}
  else if(action==='authenticatorRemove'){if(!validId(payload.id)||payload.confirmed!==true)throw new Error('Confirm the selected authenticator removal');const all=await entries();if(!all.some(e=>e.id===payload.id))throw new Error('Authenticator entry is unavailable');await options.recordMutation?.('authenticatorRemoved',{id:payload.id,secretsOmitted:true});await write({schemaVersion:1,entries:all.filter(e=>e.id!==payload.id)},entryFile);return {removed:true};}
  else throw new Error('Unsupported local security action');
  await options.recordMutation?.(action,{schoolMode:data.schoolMode,secretsOmitted:true});data.schoolMode.revision++;data.schoolMode.updatedAt=new Date().toISOString();await write(data);await emit();return status();
 }
 return {start,status,registerTargets(targets:LockTarget[]){locks.registerTargets(targets);for(const target of targets)nativeTargets.add(target.id);},assertUnlocked:locks.assertUnlocked,consumeSurfaceUnlock:locks.consumeSurfaceUnlock,handle(action:string,payload?:Record<string,unknown>){const operation=serial.then(()=>handle(action,payload));serial=operation.catch(()=>{});return operation;},subscribe(listener:(status:SecurityStatus)=>void){listeners.add(listener);return()=>listeners.delete(listener);},close(){watcher?.close();watcher=null;listeners.clear();}};
}
