import {mkdirSync,writeFileSync,renameSync,existsSync} from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {validateAppearance} from '../shared/appearance';
import {randomUUID} from 'node:crypto';
import {readBoundedFile} from './bounded-file';
import {safeText,validateEnvelope,validateNotification,validateWorkspace,workspaceDefaults,type WorkspaceState,type WorkspaceAction,type WorkspaceResponse,type WorkspaceRevision,type WorkspaceNotification,type WorkspaceEnvelope,sanitizeRecord,type ManagedRecordRevision} from '../shared/workspace';
/** Isolated app-owned Git history; no user repository is opened or modified. */
export class WorkspaceStore {
 private managed:ManagedRecordRevision[]=[];private restorer?: (kind:string,id:string,snapshot:unknown)=>unknown;private state:WorkspaceState;private notices:WorkspaceNotification[];private revisions:WorkspaceRevision[];private warning='';private root:string;
 constructor(directory:string,restorer?: (kind:string,id:string,snapshot:unknown)=>unknown){this.restorer=restorer;this.root=path.join(directory,'workspace-records');mkdirSync(this.root,{recursive:true,mode:0o700});this.state=this.read('workspace',validateWorkspace,structuredClone(workspaceDefaults));this.notices=this.read('notifications',v=>(validateEnvelope({schema:'material-git-records',version:1,encoding:'UTF-8',kind:'notifications',records:v}).records as WorkspaceNotification[]),[]);this.revisions=this.read('revisions',v=>(validateEnvelope({schema:'material-git-records',version:1,encoding:'UTF-8',kind:'revisions',records:v}).records as WorkspaceRevision[]),[]);this.managed=this.read('managed-revisions',v=>{if(!Array.isArray(v)||v.length>500)throw Error('Invalid managed history.');return v.map(row=>{if(!row||typeof row!=='object')throw Error('Invalid managed revision.');return {id:safeText(row.id,100),at:safeText(row.at,40),kind:safeText(row.kind,100),recordId:safeText(row.recordId,160),action:safeText(row.action,160),label:safeText(row.label,100),snapshot:sanitizeRecord(row.snapshot)};});},[]);try{if(!existsSync(path.join(this.root,'.git')))this.git('init','--quiet');}catch{this.warning='Local Git history is unavailable. Validated snapshots still remain on this device.';}}
 private read<T>(name:string,validate:(v:unknown)=>T,fallback:T):T{try{if(!existsSync(path.join(this.root,name+'.json')))return fallback;return validate(JSON.parse(readBoundedFile(path.join(this.root,name+'.json'),2097152).toString('utf8')));}catch{this.warning='A saved workspace record could not be read. Original files were retained; defaults are in use.';return fallback;}}
 private write(name:string,value:unknown){const file=path.join(this.root,name+'.json'),tmp=file+'.tmp';writeFileSync(tmp,JSON.stringify(value,null,2),{mode:0o600});renameSync(tmp,file);}
 private git(...args:string[]){return execFileSync('git',['-c',`core.hooksPath=${path.join(this.root,'.disabled-hooks')}`,'-C',this.root,...args],{encoding:'utf8',timeout:5000,stdio:['ignore','pipe','pipe'],env:{...process.env,GIT_CONFIG_GLOBAL:path.join(this.root,'.no-global-config'),GIT_CONFIG_NOSYSTEM:'1'}});}
 private record(action:string){const revision:WorkspaceRevision={id:randomUUID(),at:new Date().toISOString(),action,label:'',state:structuredClone(this.state)};this.revisions=[...this.revisions,revision].slice(-500);this.write('revisions',this.revisions);try{this.git('add','--','workspace.json','revisions.json');this.git('-c','user.name=Material Git','-c','user.email=local@invalid','commit','--quiet','--no-gpg-sign','-m',action);}catch{this.warning='Local Git revision write failed. The requested change and its validated snapshot were saved.';}}
 private status():WorkspaceResponse{return {state:structuredClone(this.state),notifications:structuredClone(this.notices),revisions:structuredClone(this.revisions),managedRevisions:structuredClone(this.managed),...(this.warning?{warning:this.warning}:{})};}
 setRestorer(restorer:(kind:string,id:string,snapshot:unknown)=>unknown){this.restorer=restorer;}
 recordExternal(kind:string,id:string,action:string,snapshot:unknown):void{try{const record:ManagedRecordRevision={id:randomUUID(),at:new Date().toISOString(),kind:safeText(kind,100),recordId:safeText(id,160),action:safeText(action,160),label:'',snapshot:sanitizeRecord(snapshot)};if(this.managed.at(-1)?.kind===kind&&this.managed.at(-1)?.recordId===id&&JSON.stringify(this.managed.at(-1)?.snapshot)===JSON.stringify(record.snapshot)&&action!=='Record restored')return;this.managed=[...this.managed,record].slice(-500);this.write('managed-revisions',this.managed);try{this.git('add','--','managed-revisions.json');this.git('-c','user.name=Material Git','-c','user.email=local@invalid','commit','--quiet','--no-gpg-sign','-m',action);}catch{this.warning='Managed record Git history is unavailable; validated snapshots are retained.';}}catch{this.warning='A managed history snapshot could not be recorded; the requested action is unaffected.';}}
 dispatch(action:'record-restore',payload?:unknown):Promise<WorkspaceResponse>;
 dispatch(action:Exclude<WorkspaceAction,'record-restore'>,payload?:unknown):WorkspaceResponse;
 dispatch(action:WorkspaceAction,payload?:unknown):WorkspaceResponse|Promise<WorkspaceResponse>;
 dispatch(action:WorkspaceAction,payload?:unknown):WorkspaceResponse|Promise<WorkspaceResponse>{
 const p=(payload&&typeof payload==='object'&&!Array.isArray(payload)?payload:{}) as Record<string,unknown>;
 if(action==='status')return this.status();
 if(action==='record-revisions')return {managedRevisions:structuredClone(this.managed)};
 if(action==='record-label'){if(Object.keys(p).some(key=>!['id','label'].includes(key)))throw Error('Unsupported managed label fields.');const id=safeText(p.id,100),label=safeText(p.label,100);if(!this.managed.some(record=>record.id===id))throw Error('Managed revision not found.');const next=this.managed.map(record=>record.id===id?{...record,label}:record);this.write('managed-revisions',next);this.managed=next;return this.status();}
 if(action==='record-prune'){if(Object.keys(p).some(key=>!['keep','confirmed'].includes(key))||p.confirmed!==true||!Number.isInteger(p.keep)||Number(p.keep)<1||Number(p.keep)>500)throw Error('Review managed retention before pruning; keep 1 to 500 revisions.');const next=this.managed.slice(-Number(p.keep));this.write('managed-revisions',next);this.managed=next;return this.status();}
 if(action==='record-appearance'){if(Object.keys(p).some(key=>!['schemaVersion','targetId','record','changedAt'].includes(key))||p.schemaVersion!==1||typeof p.targetId!=='string'||!/^[a-zA-Z0-9._-]{1,128}$/.test(p.targetId)||['__proto__','constructor','prototype'].includes(p.targetId)||typeof p.changedAt!=='string'||!Number.isFinite(Date.parse(p.changedAt)))throw Error('Invalid appearance history event.');const record=validateAppearance(p.record);this.recordExternal('appearance',p.targetId,'Appearance changed',record);return {managedRevisions:structuredClone(this.managed),...(this.warning?{warning:this.warning}:{})};}
 if(action==='record-diff'){const before=this.managed.find(r=>r.id===p.before),after=this.managed.find(r=>r.id===p.after);if(!before||!after||before.kind!==after.kind||before.recordId!==after.recordId)throw Error('Choose two revisions of the same record.');return {diff:{before:before.snapshot,after:after.snapshot}};}
 if(action==='record-restore'){const revision=this.managed.find(r=>r.id===p.id);if(!revision||p.confirmed!==true)throw Error('Review the managed record revision before restoring.');if(!this.restorer)throw Error('This record has no supported restore handler.');const restored=this.restorer(revision.kind,revision.recordId,structuredClone(revision.snapshot));return Promise.resolve(restored).then(snapshot=>{this.recordExternal(revision.kind,revision.recordId,'Record restored',snapshot);return {managedRevisions:structuredClone(this.managed)};});}
 if(action==='discard'){const ids=p.ids;if(!Array.isArray(ids)||ids.length>100)throw Error('Invalid discarded tab selection.');this.recordExternal('draft-discard','task-tabs','Command inputs discarded',{tabs:ids.map(id=>safeText(id,160)),state:this.state});return this.status();}
 if(action==='save'){const state=validateWorkspace(payload);if(JSON.stringify(state)!==JSON.stringify(this.state)){this.state=state;this.write('workspace',state);this.record('Workspace updated');}return this.status();}
 if(action==='notify'){const notice=validateNotification({id:randomUUID(),at:new Date().toISOString(),kind:p.kind,title:p.title,read:false,dismissed:false,...(p.operationId?{operationId:p.operationId}:{}),...(p.facts===undefined?{}:{facts:p.facts}),...(p.category===undefined?{}:{category:p.category}),...(p.route===undefined?{}:{route:p.route})});const next=[...this.notices,notice].slice(-500);while(Buffer.byteLength(JSON.stringify(next))>1800000&&next.length>1)next.shift();this.write('notifications',next);this.notices=next;return this.status();}
 if(action==='notifications'){if(!Array.isArray(p.ids)||p.ids.length>500||p.ids.some(id=>typeof id!=='string'))throw Error('Invalid notification selection.');if(!['read','unread','dismiss','restore'].includes(String(p.action)))throw Error('Invalid notification action.');this.notices=this.notices.map(n=>!(p.ids as string[]).includes(n.id)?n:{...n,...(p.action==='read'||p.action==='unread'?{read:p.action==='read'}:{dismissed:p.action==='dismiss'})});this.write('notifications',this.notices);return this.status();}
 if(action==='label'){const id=safeText(p.id,100),label=safeText(p.label,100);if(!this.revisions.some(r=>r.id===id))throw Error('Revision not found.');this.revisions=this.revisions.map(r=>r.id===id?{...r,label}:r);this.write('revisions',this.revisions);return this.status();}
 if(action==='restore'){const revision=this.revisions.find(r=>r.id===p.id);if(!revision)throw Error('Revision not found.');this.state=structuredClone(revision.state);this.write('workspace',this.state);this.record(`Workspace restored from ${revision.id}`);return this.status();}
 if(action==='prune'){if(p.confirmed!==true||!Number.isInteger(p.keep)||Number(p.keep)<1||Number(p.keep)>500)throw Error('Review retention before pruning; keep 1 to 500 revisions.');this.revisions=this.revisions.slice(-Number(p.keep));this.write('revisions',this.revisions);this.record('Workspace revision retention changed');return this.status();}
 if(action==='export'){const kind=p.kind as WorkspaceEnvelope['kind'];if(!['workspace','notifications','revisions'].includes(kind))throw Error('Invalid export kind.');if(p.ids!==undefined&&(!Array.isArray(p.ids)||p.ids.some(id=>typeof id!=='string')))throw Error('Invalid export selection.');const selected=(rows:{id:string}[])=>p.ids===undefined?rows:rows.filter(r=>(p.ids as string[]).includes(r.id));const records=kind==='workspace'?this.state:kind==='notifications'?selected(this.notices):selected(this.revisions);return {export:validateEnvelope({schema:'material-git-records',version:1,encoding:'UTF-8',kind,records})};}
 if(action==='import-preview'||action==='import-apply'){const envelope=validateEnvelope(action==='import-apply'?p.envelope:payload);if(envelope.kind==='revisions')throw Error('Revision imports are read-only. Restore a reviewed workspace export instead.');const preview={kind:envelope.kind,count:envelope.kind==='workspace'?(envelope.records as WorkspaceState).tabs.length:(envelope.records as WorkspaceNotification[]).length,...(envelope.kind==='workspace'?{state:envelope.records as WorkspaceState}:{notifications:envelope.records as WorkspaceNotification[]})};if(action==='import-preview')return {preview};if(p.confirmed!==true)throw Error('Review the import before applying it.');if(envelope.kind==='workspace'){this.state=envelope.records as WorkspaceState;this.write('workspace',this.state);this.record('Workspace imported');}else{this.notices=envelope.records as WorkspaceNotification[];this.write('notifications',this.notices);}return this.status();}
 throw Error('Unsupported workspace action.');
 }
}
