import {LitElement, html, css, nothing} from './material';
import {unsafeHTML} from 'lit/directives/unsafe-html.js';
import {marked} from 'marked';
import DOMPurify from 'dompurify';
import './components';
import type {Search} from './components';
import type {ApiJson} from '../shared/github-api';
import {initialValue, schemaType, validateValue, redactPreview, resolveSchema, alternativeSchema, jsonValueType, emptyTypedValue, type FormSchema} from './api-form';

export {resolveSchema} from './api-form';
export type ApiLanguage = 'en'|'yue'|'both';
export function apiCopy(en: string, yue: string, language: ApiLanguage = 'en') {
  return language === 'yue' ? yue : language === 'both' ? `${en} · ${yue}` : en;
}
/** Provider text only: bounded Markdown, an allowlist sanitizer, and main-process link handling. */
export class ApiMarkdown extends LitElement {
  static properties={content:{type:String},label:{type:String},language:{type:String},markup:{state:true},fallback:{state:true},limited:{state:true},linkError:{state:true}};
  content='';label='Provider description';language:ApiLanguage='en';private markup='';private fallback='';private limited=false;private linkError='';
  static styles=css`:host{display:block;min-width:0;font-size:inherit;line-height:1.55;color:inherit}.prose{overflow-wrap:anywhere}.prose>:first-child{margin-top:0}.prose>:last-child{margin-bottom:0}p,ul,ol,blockquote,pre,table{margin:.5em 0}h1,h2,h3,h4,h5,h6{font-size:1.05em;line-height:1.4;margin:.75em 0 .35em;font-weight:600}ul,ol{padding-inline-start:1.6em}blockquote{padding-inline-start:12px;border-inline-start:3px solid var(--md-sys-color-outline-variant);color:var(--md-sys-color-on-surface-variant)}pre,code{font: .92em/1.5 ui-monospace,monospace;background:var(--md-sys-color-surface-container-high);border-radius:6px}code{padding:1px 4px}pre{padding:10px;white-space:pre-wrap;overflow-wrap:anywhere}pre code{padding:0}a{color:var(--md-sys-color-primary);text-decoration:underline;text-underline-offset:3px;cursor:pointer}a:focus-visible{outline:2px solid var(--md-sys-color-primary);outline-offset:3px;border-radius:2px}table{display:block;max-width:100%;overflow:auto;scrollbar-color:var(--md-sys-color-outline) var(--md-sys-color-surface-container);border-collapse:collapse}th,td{text-align:start;padding:6px;border:1px solid var(--md-sys-color-outline-variant)}hr{border:0;border-top:1px solid var(--md-sys-color-outline-variant)}.fallback{white-space:pre-wrap;overflow-wrap:anywhere}.notice{font-size:.75rem;color:var(--md-sys-color-on-surface-variant)}.error{color:var(--md-sys-color-error);font-size:.75rem}`;
  protected willUpdate(changed:Map<string,unknown>){
    if(!changed.has('content'))return;
    const source=String(this.content||'').slice(0,32768);this.limited=this.content.length>32768;this.linkError='';this.fallback='';
    try{
      const fragment=DOMPurify.sanitize(marked.parse(source,{async:false,gfm:true}),{ALLOWED_TAGS:['p','br','h1','h2','h3','h4','h5','h6','ul','ol','li','blockquote','pre','code','strong','em','del','hr','table','thead','tbody','tr','th','td','sub','sup','a'],ALLOWED_ATTR:['href','title'],ALLOW_DATA_ATTR:false,ALLOW_ARIA_ATTR:false,RETURN_DOM_FRAGMENT:true});
      if(fragment.querySelectorAll('*').length>2048){this.markup='';this.fallback=fragment.textContent||source;this.limited=true;return;}
      for(const anchor of fragment.querySelectorAll('a')){
        try{const href=anchor.getAttribute('href')||'';const url=new URL(href);if(url.protocol!=='https:'||url.username||url.password||href.length>2048)throw new Error('Unsupported link');anchor.setAttribute('href',url.href);anchor.setAttribute('title',anchor.getAttribute('title')||url.href);}
        catch{anchor.replaceWith(...anchor.childNodes);}
      }
      const container=document.createElement('div');container.append(fragment);this.markup=container.innerHTML;
    }catch{this.markup='';this.fallback=source;}
  }
  private link(event:Event){const anchor=event.composedPath().find(node=>node instanceof HTMLAnchorElement) as HTMLAnchorElement|undefined;if(!anchor)return;event.preventDefault();if(event.type==='contextmenu'||(event instanceof MouseEvent&&event.button>1))return;const url=anchor.getAttribute('href');if(!url)return;this.linkError='';void window.material.openExternal(url).catch(()=>this.linkError=apiCopy('The link could not be opened. Try again.','未能開啟連結，請再試。',this.language));}
  render(){return html`<div class="prose" role="region" aria-label=${this.label} @click=${this.link} @auxclick=${this.link} @contextmenu=${this.link}>${this.fallback?html`<div class="fallback">${this.fallback}</div>`:unsafeHTML(this.markup)}</div>${this.limited?html`<div class="notice">${apiCopy('Description display limit reached.','已到說明顯示限制。',this.language)}</div>`:nothing}${this.linkError?html`<div class="error" role="status">${this.linkError}</div>`:nothing}`;}
}
customElements.define('mg-api-markdown',ApiMarkdown);
/** Registered M3 composition: official controls, typed property forms and tokenized disclosure. */
export class ApiSchemaField extends LitElement {
  static properties = {schema:{attribute:false}, references:{attribute:false}, value:{attribute:false}, label:{type:String}, required:{type:Boolean}, language:{type:String}, expanded:{state:true}, variant:{state:true}, enumItems:{state:true}, propertyName:{state:true}, touched:{state:true},depth:{type:Number},referenceLoader:{attribute:false},loading:{state:true},loadError:{state:true}};
  schema: FormSchema = {}; references: Record<string, FormSchema> = {}; value: unknown;
  label = 'Value'; required = false; language: ApiLanguage = 'en'; expanded = false; variant = 0;
  enumItems?: unknown[]; propertyName = ''; touched = false; depth=0; referenceLoader?: (name:string)=>Promise<FormSchema>; private loading=false; private loadError=''; private loaded?:FormSchema; private loadGeneration=0;
  protected willUpdate(changed:Map<string,unknown>){if(changed.has('schema')||changed.has('value')){const schema=resolveSchema(this.schema,this.references),alternatives=schema.oneOf||schema.anyOf;if(alternatives&&this.value!==undefined){const matches=alternatives.map((option,index)=>validateValue(option,this.value,false,this.label,this.references).length?undefined:index).filter(index=>index!==undefined);if(matches.length===1)this.variant=matches[0]!;}}}
  protected updated(changed:Map<string,unknown>){if(changed.has('schema')){this.loaded=undefined;this.loadError='';this.loadGeneration++;}if(this.schema.$ref&&!this.references[this.schema.$ref]&&!this.loaded&&this.referenceLoader&&!this.loading&&!this.loadError&&(this.required||this.value!==undefined)&&this.depth<16)void this.loadReference();}
  private async loadReference(){const generation=++this.loadGeneration;this.loading=true;try{const schema=await this.referenceLoader!(this.schema.$ref!);if(generation===this.loadGeneration){this.loaded={...schema,...Object.fromEntries(Object.entries(this.schema).filter(([key])=>key!=='$ref'))};if(this.value!==undefined&&schemaType(schema)==='object'&&(!this.value||typeof this.value!=='object'||Array.isArray(this.value)))this.change({});}}catch(error){if(generation===this.loadGeneration)this.loadError=String(error);}finally{if(generation===this.loadGeneration)this.loading=false;}}
  static styles = css`
    :host{display:block;min-width:0} .field{display:grid;gap:8px;padding:12px;border:1px solid var(--md-sys-color-outline-variant);border-radius:var(--md-sys-shape-corner-medium,12px);background:var(--md-sys-color-surface-container-low)}
    .head,.row,.chips{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.head{justify-content:space-between}.label{font-weight:600;overflow-wrap:anywhere}.hint{font-size:.75rem;line-height:1.5;color:var(--md-sys-color-on-surface-variant);overflow-wrap:anywhere}.nested{display:grid;gap:10px;padding-inline-start:12px;border-inline-start:2px solid var(--md-sys-color-outline-variant)}
    md-outlined-text-field,md-filled-select,mg-search{width:100%;min-width:0}md-outlined-text-field{--md-outlined-text-field-container-shape:12px}.row md-outlined-text-field{flex:1}.error{color:var(--md-sys-color-error);font-size:.75rem}.type{font-size:.7rem;color:var(--md-sys-color-primary)}md-text-button{--md-text-button-container-height:32px}.optional{font-size:.75rem;display:flex;align-items:center;gap:8px}.chips md-input-chip{max-width:100%} :focus-visible{outline:2px solid var(--md-sys-color-primary);outline-offset:3px}
  `;
  private copy(en:string,yue:string) {return apiCopy(en,yue,this.language);}
  private change(value: unknown) {this.touched = true; this.dispatchEvent(new CustomEvent('value-change',{detail:{value},bubbles:true,composed:true}));}
  private child(schema: FormSchema, value: unknown, label: string, required: boolean, update:(value:unknown)=>void) {
    return html`<mg-api-field .schema=${schema} .references=${this.references} .value=${value} .label=${label} .required=${required} .language=${this.language} .depth=${this.depth+1} .referenceLoader=${this.referenceLoader} @value-change=${(event:CustomEvent)=>{event.stopPropagation();update(event.detail.value);}}></mg-api-field>`;
  }
  render() {
    let schema = resolveSchema(this.loaded||this.schema,this.references);
    const alternatives = schema.oneOf || schema.anyOf;
    if (alternatives) schema = resolveSchema(alternativeSchema(schema,alternatives[this.variant]),this.references);
    const declaredType=schemaType(schema),type=declaredType==='json'?jsonValueType(this.value):declaredType, present = this.value !== undefined;
    const object = this.value && typeof this.value === 'object' && !Array.isArray(this.value) ? this.value as Record<string,unknown> : {};
    const list = Array.isArray(this.value) ? this.value : [];
    const errors = this.touched ? validateValue(schema,this.value,this.required,this.label,this.references).filter(error=>!this.referenceLoader||!error.includes('unavailable schema reference')) : [];
    const updateProperty = (key:string,value:unknown) => {const next={...object}; if(value===undefined)delete next[key];else next[key]=value;this.change(next);};
    return html`<div class="field"><div class="head"><span class="label">${this.label}${this.required ? this.copy(' · required',' · 必填') : ''}</span><span class="type">${type}${schema.format ? ` · ${schema.format}` : ''}</span></div>
      ${schema.description ? html`<mg-api-markdown class="hint" .content=${schema.description} .label=${`${this.label}: ${this.copy('description','說明')}`} .language=${this.language}></mg-api-markdown>` : nothing}
      ${schema.default !== undefined ? html`<div class="hint">${this.copy('Schema default','結構預設值')}: ${JSON.stringify(redactPreview(schema.default,this.label))}</div>` : nothing}
      ${schema.example !== undefined && !schema.writeOnly ? html`<div class="hint">${this.copy('Example','例子')}: ${JSON.stringify(redactPreview(schema.example,this.label))}</div>` : nothing}
      ${!this.required ? html`<label class="optional"><md-switch aria-label=${`${this.label}: ${this.copy('include in request','加入要求')}`} .selected=${present} @change=${(e:Event)=>{const enabled=(e.target as unknown as {selected:boolean}).selected;this.change(enabled?(initialValue(schema,this.references) ?? (type==='boolean'?false:type==='object'?{}:type==='array'?[]:'')):undefined);}}></md-switch>${this.copy('Include in request','加入要求')}</label>` : nothing}
      ${alternatives ? html`<md-filled-select label=${this.copy('Value shape','值嘅結構')} .value=${String(this.variant)} @change=${(e:Event)=>{this.variant=Number((e.target as HTMLSelectElement).value);if(!alternatives[this.variant].required||alternatives[this.variant].type)this.change(initialValue(alternativeSchema(this.schema,alternatives[this.variant]),this.references)??emptyTypedValue(schemaType(alternatives[this.variant])));else this.requestUpdate();}}>${alternatives.map((option,index)=>html`<md-select-option value=${String(index)} ?selected=${index===this.variant}><div slot="headline">${option.title || `${this.copy('Option','選項')} ${index+1}: ${schemaType(option)}`}</div></md-select-option>`)}</md-filled-select>` : nothing}
      ${this.depth>=16&&(type==='object'||type==='array'||schema.$ref)?html`<div class="hint">${this.copy('The guided input depth limit is 16. Remove this nested value or edit a shallower object.','引導輸入深度限制係 16，請移除呢個巢狀值或編輯較淺物件。')}</div>`:schema.$ref&&this.loading?html`<md-linear-progress indeterminate aria-label=${this.copy('Loading input type','載入輸入類型')}></md-linear-progress>`:schema.$ref ? html`<div class="error">${this.copy('This reference is unavailable; this value cannot be edited safely.','無法取得呢個參照，未能安全編輯呢個值。')} ${schema.$ref} ${this.loadError}</div>` : !present && !this.required ? nothing : html`${declaredType==='json'?html`<md-filled-select label=${this.copy('JSON value type','JSON 值類型')} .value=${type} @change=${(e:Event)=>this.change(emptyTypedValue((e.target as HTMLSelectElement).value))}>${['string','number','boolean','object','array','null'].map(value=>html`<md-select-option value=${value} ?selected=${value===type}><div slot="headline">${this.copy({string:'Text',number:'Number',boolean:'Boolean',object:'Object',array:'List',null:'Null'}[value]!,{string:'文字',number:'數字',boolean:'布林值',object:'物件',array:'清單',null:'空值'}[value]!)}</div></md-select-option>`)}</md-filled-select>`:nothing}${type==='null'?html`<div class="hint">null</div>`:schema.enum ? html`
        <mg-search label=${`${this.label}: ${this.copy('filter choices','篩選選項')}`} search-id=${`api-enum-${this.label}`} @search-change=${async(e:Event)=>{const search=e.target as Search;const matches=await search.matchValues(schema.enum!.map(item=>String(item)));this.enumItems=schema.enum!.filter((_,index)=>matches[index]);}}></mg-search>
        <md-filled-select label=${this.label} .value=${String(schema.enum.findIndex(item=>JSON.stringify(item)===JSON.stringify(this.value)))} @change=${(e:Event)=>this.change(schema.enum![Number((e.target as HTMLSelectElement).value)])}><md-select-option value="-1" ?selected=${!schema.enum.some(item=>JSON.stringify(item)===JSON.stringify(this.value))}><div slot="headline">${this.copy('Choose a value','選擇值')}</div></md-select-option>${schema.enum.map((item,index)=>!this.enumItems || this.enumItems.includes(item) || item===this.value ? html`<md-select-option value=${String(index)} ?selected=${JSON.stringify(item)===JSON.stringify(this.value)}><div slot="headline">${String(item)}</div></md-select-option>`:nothing)}</md-filled-select>${schema.enumDescriptions?.[String(this.value)]?html`<mg-api-markdown .content=${schema.enumDescriptions[String(this.value)]} .label=${`${this.label}: ${this.copy('selected choice description','所選項目說明')}`} .language=${this.language}></mg-api-markdown>`:nothing}`
      : type === 'boolean' ? html`<div class="row"><md-switch aria-label=${this.label} .selected=${this.value===true} @change=${(e:Event)=>this.change((e.target as unknown as {selected:boolean}).selected)}></md-switch><span>${this.value===true ? this.copy('On','開') : this.copy('Off','關')}</span></div>`
      : type === 'object' ? html`<md-text-button aria-expanded=${String(this.expanded)} @click=${()=>this.expanded=!this.expanded}>${this.expanded ? this.copy('Collapse properties','收起屬性') : this.copy('Edit properties','編輯屬性')} (${Object.keys(schema.properties || {}).length})</md-text-button>${this.expanded ? html`<div class="nested">${Object.entries(schema.properties||{}).filter(([,child])=>!child.readOnly).map(([key,child])=>this.child(child,object[key],key,!!schema.required?.includes(key),value=>updateProperty(key,value)))}
        ${schema.additionalProperties!==false ? html`${Object.keys(object).filter(key=>!Object.hasOwn(schema.properties||{},key)).map(key=>html`<div class="row">${this.child(typeof schema.additionalProperties==='object'?schema.additionalProperties:{},object[key],key,false,value=>updateProperty(key,value))}<md-text-button aria-label=${`${this.copy('Remove','移除')} ${key}`} @click=${()=>updateProperty(key,undefined)}>${this.copy('Remove','移除')}</md-text-button></div>`)}<div class="row"><md-outlined-text-field label=${this.copy('New property name','新屬性名稱')} .value=${this.propertyName} @input=${(e:Event)=>this.propertyName=(e.target as HTMLInputElement).value}></md-outlined-text-field><md-outlined-button ?disabled=${!this.propertyName.trim()||Object.hasOwn(object,this.propertyName.trim())||['__proto__','constructor','prototype'].includes(this.propertyName.trim())} title=${this.copy('Enter a unique property name','輸入唯一嘅屬性名稱')} @click=${()=>{updateProperty(this.propertyName.trim(),initialValue(typeof schema.additionalProperties==='object'?schema.additionalProperties:{})??'');this.propertyName='';}}>${this.copy('Add property','新增屬性')}</md-outlined-button></div>`:nothing}</div>`:nothing}`
      : type === 'array' ? html`<div class="chips">${list.map((item,index)=>html`<md-input-chip label=${`${index+1}: ${typeof item==='object'?this.copy('Structured item','結構項目'):String(redactPreview(item,this.label))}`} aria-label=${`${this.copy('Remove','移除')} ${this.label} ${this.copy('item','項目')} ${index+1}`} remove-only @remove=${()=>this.change(list.filter((_,i)=>i!==index))}></md-input-chip>`)}</div><md-text-button aria-expanded=${String(this.expanded)} @click=${()=>this.expanded=!this.expanded}>${this.expanded?this.copy('Collapse items','收起項目'):this.copy('Edit items','編輯項目')}</md-text-button>${this.expanded?html`<div class="nested">${list.map((item,index)=>this.child(schema.items||{},item,`${this.label} ${index+1}`,true,value=>{const next=[...list];next[index]=value;this.change(next);} ))}</div>`:nothing}<md-outlined-button ?disabled=${schema.maxItems!==undefined&&list.length>=schema.maxItems} title=${schema.maxItems!==undefined?`Maximum ${schema.maxItems} items`:this.copy('Add a typed item','新增指定類型項目')} @click=${()=>{const child=schema.items||{};this.change([...list,initialValue(child,this.references)??(schemaType(child)==='object'?{}:schemaType(child)==='boolean'?false:'')]);this.expanded=true;}}>${this.copy('Add item','新增項目')}</md-outlined-button>`
      : html`<div class="row">${type==='number'||type==='integer'?html`<md-outlined-button aria-label=${`${this.label}: ${this.copy('decrease','減少')}`}  title=${this.copy('Decrease by one','減一')} @click=${()=>this.change((typeof this.value==='number'?this.value:0)-1)}>−</md-outlined-button>`:nothing}<md-outlined-text-field .type=${schema.writeOnly?'password':type==='number'||type==='integer'?'number':/^(body|description|bio|comment|content|message)$/i.test(this.label)?'textarea':'text'} .value=${this.value===undefined?'':String(this.value??'')} .label=${this.label} .min=${schema.minimum===undefined?'':String(schema.minimum)} .max=${schema.maximum===undefined?'':String(schema.maximum)} .step=${type==='integer'?'1':'any'} .supportingText=${[schema.minimum!==undefined?`Min ${schema.minimum}`:'',schema.maximum!==undefined?`Max ${schema.maximum}`:'',schema.pattern?`${this.copy('Pattern','格式')}: ${schema.pattern}`:''].filter(Boolean).join(' · ')} @input=${(e:Event)=>{const raw=(e.target as HTMLInputElement).value;this.change(type==='number'||type==='integer'?raw===''?undefined:Number(raw):raw);}}></md-outlined-text-field>${type==='number'||type==='integer'?html`<md-outlined-button aria-label=${`${this.label}: ${this.copy('increase','增加')}`}  title=${this.copy('Increase by one','加一')} @click=${()=>this.change((typeof this.value==='number'?this.value:0)+1)}>+</md-outlined-button>`:nothing}</div>`}`}
      ${(schema.nullable||(Array.isArray(schema.type)&&schema.type.includes('null')))&&present?html`<label class="optional"><md-switch aria-label=${`${this.label}: null`} .selected=${this.value===null} @change=${(e:Event)=>this.change((e.target as unknown as {selected:boolean}).selected?null:initialValue(schema,this.references))}></md-switch>${this.copy('Explicit null','明確空值')}</label>`:nothing}
      ${errors.map(error=>html`<div class="error" role="status">${error}</div>`)}</div>`;
  }
}
customElements.define('mg-api-field',ApiSchemaField);

/** Bounded structured result tree; records are tables inside the registered composition. */
export class ApiRecords extends LitElement {
  static properties={value:{attribute:false},label:{type:String},language:{type:String},page:{state:true},expanded:{state:true}};
  value: unknown; label='Result'; language:ApiLanguage='en'; page=1; expanded=false;
  static styles=css`:host{display:block;min-width:0}.tree{display:grid;gap:8px}table{border-collapse:collapse;width:100%;font-size:.75rem}th,td{text-align:start;padding:8px;border-bottom:1px solid var(--md-sys-color-outline-variant);vertical-align:top;overflow-wrap:anywhere;max-width:280px}th{color:var(--md-sys-color-on-surface-variant);font-weight:500}.table{overflow:auto;scrollbar-color:var(--md-sys-color-outline) var(--md-sys-color-surface-container)}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.scalar{white-space:pre-wrap;overflow-wrap:anywhere;font-size:.8125rem;line-height:1.5}.child{border-inline-start:2px solid var(--md-sys-color-outline-variant);padding-inline-start:10px}md-text-button{--md-text-button-container-height:32px}`;
  protected willUpdate(changed:Map<string,unknown>){if(changed.has('value'))this.page=1;}
  private child(value:unknown,label:string){return html`<mg-api-records .value=${value} .label=${label} .language=${this.language}></mg-api-records>`;}
  render(){
    const value=redactPreview(this.value,this.label),copy=(en:string,yue:string)=>apiCopy(en,yue,this.language);
    if(!value||typeof value!=='object')return html`<div class="scalar">${value===undefined?copy('No value','未有值'):value===null?'null':String(value)}</div>`;
    const entries=Array.isArray(value)?value.map((item,index)=>[String(index+1),item] as const):Object.entries(value);
    const pages=Math.max(1,Math.ceil(entries.length/20)),shown=entries.slice((this.page-1)*20,this.page*20);
    const records=Array.isArray(value)&&value.length>0&&value.every(item=>item&&typeof item==='object'&&!Array.isArray(item));
    const columns=records?[...new Set(value.flatMap(item=>Object.keys(item as object)))].slice(0,8):[];
    return html`<div class="tree"><div class="row"><md-text-button aria-expanded=${String(this.expanded)} @click=${()=>this.expanded=!this.expanded}>${this.expanded?copy('Collapse','收起'):copy('Expand','展開')} ${this.label} (${entries.length})</md-text-button></div>${this.expanded?html`${records?html`<div class="table"><table aria-label=${this.label}><thead><tr>${columns.map(key=>html`<th scope="col">${key}</th>`)}</tr></thead><tbody>${shown.map(([,item])=>html`<tr>${columns.map(key=>html`<td>${this.child((item as Record<string,unknown>)[key],key)}</td>`)}</tr>`)}</tbody></table>${Object.keys(value[0] as object).length>columns.length?html`<div class="scalar">${copy('Additional properties are available in each full record below.','額外屬性可以喺下面每個完整記錄查看。')}</div>`:nothing}</div>`:nothing}${shown.map(([key,item])=>html`<div class="child"><div class="scalar">${key}</div>${this.child(item,key)}</div>`)}${pages>1?html`<div class="row"><md-outlined-button ?disabled=${this.page===1} title=${this.page===1?copy('First page','第一頁'):copy('Previous result page','上一頁結果')} @click=${()=>this.page--}>${copy('Previous','上一頁')}</md-outlined-button><span>${this.page}/${pages}</span><md-outlined-button ?disabled=${this.page>=pages} title=${this.page>=pages?copy('Last page','最後一頁'):copy('Next result page','下一頁結果')} @click=${()=>this.page++}>${copy('Next','下一頁')}</md-outlined-button></div>`:nothing}`:nothing}</div>`;
  }
}
customElements.define('mg-api-records',ApiRecords);
