import {LitElement,html,css,nothing} from 'lit';
import '@material/web/slider/slider.js';import '@material/web/select/outlined-select.js';import '@material/web/select/select-option.js';import '@material/web/textfield/outlined-text-field.js';import '@material/web/button/filled-button.js';import '@material/web/button/text-button.js';import './components.js';
import {appearanceFields,validateAppearance,appearanceCss,hslToHex,hexToHsl,type AppearanceValues,type AppearanceState,type AppearanceRecord} from '../shared/appearance.js';
const storageKey='material-git.element-appearance.v1';
export class MaterialAppearance extends LitElement{
 static properties={target:{attribute:false},targetId:{type:String},state:{state:true},record:{state:true},visibleFields:{state:true},status:{state:true}};
 target:HTMLElement|null=null;targetId='';state:AppearanceState='default';record:AppearanceRecord={};visibleFields=Object.keys(appearanceFields);status='';private undoRecords:AppearanceRecord[]=[];
 static styles=css`:host{display:block}md-slider{flex:1;min-width:160px}md-outlined-select,md-outlined-text-field{width:100%}.field{display:flex;align-items:center;gap:16px;flex-wrap:wrap}mg-layout{padding:16px}`;
 protected updated(changes:Map<PropertyKey,unknown>){if(changes.has('target')||changes.has('targetId')){this.undoRecords=[];if(this.target&&this.targetId){try{this.record=this.read()[this.validId()]??{};this.apply();}catch{this.status='A valid stable element identifier is required.';}}}}
 private validId(){if(!/^[a-zA-Z0-9._-]{1,128}$/.test(this.targetId))throw new Error('A stable element identifier is required');return this.targetId;}
 private read():Record<string,AppearanceRecord>{try{const raw=localStorage.getItem(storageKey);if(!raw)return {};if(raw.length>131072)throw new Error();const data=JSON.parse(raw);if(!data||typeof data!=='object'||Array.isArray(data)||Object.keys(data).length>100)throw new Error();const result:Record<string,AppearanceRecord>=Object.create(null);for(const[id,record]of Object.entries(data)){if(!/^[a-zA-Z0-9._-]{1,128}$/.test(id)||['__proto__','constructor','prototype'].includes(id))throw new Error();result[id]=validateAppearance(record);}return result;}catch{this.status='Saved appearance unavailable; original appearance restored.';return {};}}
 private save(){const all=this.read(),id=this.validId();all[id]=this.record;if(Object.keys(all).length>100)throw new Error('At most 100 elements can be customized');const serialized=JSON.stringify(all);if(serialized.length>131072)throw new Error('Appearance storage limit reached');localStorage.setItem(storageKey,serialized);}
 private apply(){if(!this.target||!this.targetId)return;const id=this.validId();this.target.dataset.mgAppearance=id;const styleId='mg-appearance-'+id;let sheet=document.getElementById(styleId)as HTMLStyleElement|null;if(!sheet){sheet=document.createElement('style');sheet.id=styleId;document.head.append(sheet);}const suffixes:Record<AppearanceState,string>={default:'',hover:':hover',focus:':focus-within',pressed:':active',disabled:':is([disabled],[aria-disabled="true"])'};sheet.textContent=Object.entries(this.record).map(([state,values])=>`[data-mg-appearance="${id}"]${suffixes[state as AppearanceState]}{${appearanceCss(values!)}}`).join('\n');}
 private edit(values:AppearanceValues){try{this.undoRecords.push(structuredClone(this.record));if(this.undoRecords.length>30)this.undoRecords.shift();this.record=validateAppearance({...this.record,[this.state]:{...this.record[this.state],...values}});this.save();this.apply();this.status='Appearance saved locally.';}catch(e){this.status=e instanceof Error?e.message:'Appearance update failed';}}
 private undo(){const prior=this.undoRecords.pop();if(prior){this.record=prior;this.save();this.apply();this.status='Previous appearance restored.';}}
 private reset(){this.undoRecords.push(structuredClone(this.record));this.record={};this.save();this.apply();this.status='Original appearance restored.';}
 render(){if(!this.target||!this.targetId)return html`<mg-layout column><mg-text>Select an element through its appearance context action.</mg-text></mg-layout>`;const values=this.record[this.state]??{},h=values.hue??270,s=values.saturation??50,l=values.lightness??50,hex=hslToHex(h,s,l),rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));return html`<mg-layout column aria-label="Element appearance editor"><mg-text kind="title">Element appearance: ${this.targetId}</mg-text><mg-search label="Search appearance properties" @search-change=${async(e:CustomEvent)=>{const keys=Object.keys(appearanceFields);const results=await(e.target as HTMLElement&{matchValues(values:string[]):Promise<boolean[]>}).matchValues(keys);this.visibleFields=keys.filter((_,i)=>results[i]);}}></mg-search><md-outlined-select label="Interaction state" .value=${this.state} @change=${(e:Event)=>{this.state=(e.target as HTMLSelectElement).value as AppearanceState;}}>${['default','hover','focus','pressed','disabled'].map(state=>html`<md-select-option value=${state}><div slot="headline">${state}</div></md-select-option>`)}</md-outlined-select>${Object.entries(appearanceFields).map(([key,[min,max]])=>this.visibleFields.includes(key)?html`<mg-layout class="field"><mg-text id=${key}>${key}: ${values[key as keyof AppearanceValues]??'Original'}</mg-text><md-slider aria-labelledby=${key} min=${min} max=${max} step=${key==='alpha'?.01:key==='lineHeight'?.05:1} .value=${values[key as keyof AppearanceValues]??(key==='alpha'?1:min)} @input=${(e:Event)=>this.edit({[key]:Number((e.target as HTMLInputElement).value)})}></md-slider></mg-layout>`:nothing)}<md-outlined-text-field label="Hexadecimal colour" .value=${hex} @change=${(e:Event)=>{try{this.edit(hexToHsl((e.target as HTMLInputElement).value));}catch(error){this.status=(error as Error).message;}}}></md-outlined-text-field><mg-text>RGB ${rgb.join(', ')} · HSL ${h.toFixed(1)}°, ${s.toFixed(1)}%, ${l.toFixed(1)}% · Alpha ${values.alpha??1}</mg-text><md-text-button ?disabled=${!this.undoRecords.length} @click=${()=>this.undo()}>Undo</md-text-button><md-text-button @click=${()=>this.reset()}>Reset element appearance</md-text-button><md-filled-button @click=${async()=>{try{const saved=await window.material.exportData({schemaVersion:1,targetId:this.validId(),appearance:this.record},'json');this.status=saved?'Appearance exported.':'Export cancelled.';}catch{this.status='Appearance export failed.';}}}>Export element appearance</md-filled-button><mg-text role="status">${this.status}</mg-text></mg-layout>`;}
}
customElements.define('mg-appearance',MaterialAppearance);

/** Restore validated styles after the app renders stable data-design-id hosts. */
export function restoreAppearance(root:ParentNode=document):void{
 try{const raw=localStorage.getItem(storageKey);if(!raw||raw.length>131072)return;const all=JSON.parse(raw);if(!all||typeof all!=='object'||Array.isArray(all)||Object.keys(all).length>100)return;
 for(const target of root.querySelectorAll<HTMLElement>('[data-design-id]')){const id=target.dataset.designId;if(!id||!/^[a-zA-Z0-9._-]{1,128}$/.test(id)||!Object.hasOwn(all,id))continue;const record=validateAppearance(all[id]);target.dataset.mgAppearance=id;const styleId='mg-appearance-'+id;let sheet=document.getElementById(styleId)as HTMLStyleElement|null;if(!sheet){sheet=document.createElement('style');sheet.id=styleId;document.head.append(sheet);}const suffixes:Record<AppearanceState,string>={default:'',hover:':hover',focus:':focus-within',pressed:':active',disabled:':is([disabled],[aria-disabled="true"])'};sheet.textContent=Object.entries(record).map(([state,values])=>`[data-mg-appearance="${id}"]${suffixes[state as AppearanceState]}{${appearanceCss(values!)}}`).join('\n');}}catch{/* Invalid caches leave shipped styling untouched. */}
}
