import{rainbowSpeed,setRainbowSpeed}from'./appearance-rainbow.js';import{rainbowDuration}from'../shared/appearance-rainbow.js';
import{LitElement,html,css,nothing}from'lit';
import{defaults}from'../shared/preferences.js';import type{AppSettings}from'../shared/types.js';import{localizePair}from'./localization.js';
import{colourSpaces,colourChannels,channelsColour,colourHex,parseColourHex,inSrgb,colourContrast,type Colour,type ColourSpace}from'../shared/appearance-colour.js';
export class AppearanceColour extends LitElement{
 static properties={animationSupported:{type:Boolean},mode:{type:String},speed:{state:true},value:{attribute:false},background:{attribute:false},settings:{attribute:false},space:{state:true},pending:{state:true},error:{state:true},name:{state:true}};
 animationSupported=true;mode='solid';speed=3;private speedChanged=()=>{this.speed=rainbowSpeed();};
 value:Colour={r:.4,g:.3,b:.7,a:1};background:Colour={r:1,g:1,b:1,a:1};settings:AppSettings={...defaults};space:ColourSpace='rgb';pending:Colour|null=null;error='';name='';
 static styles=css`:host{display:block;min-width:0}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.channels{display:grid;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:8px}md-outlined-select,md-outlined-text-field{width:100%;min-width:0}.field{width:100%;height:120px;touch-action:none;border:1px solid var(--md-sys-color-outline);border-radius:8px;position:relative;cursor:crosshair}.point{position:absolute;width:12px;height:12px;border:2px solid white;box-shadow:0 0 0 1px black;border-radius:50%;transform:translate(-50%,-50%);pointer-events:none}.sample{height:32px;border:1px solid var(--md-sys-color-outline);border-radius:4px}.hint{font-size:12px;line-height:1.5}md-slider{width:100%}`;
 private names=new Map<string,string[]>();
 connectedCallback(){super.connectedCallback();this.speed=rainbowSpeed();window.addEventListener('appearance-rainbow-change',this.speedChanged);const canvas=document.createElement('canvas');canvas.width=canvas.height=1;const ctx=canvas.getContext('2d')!;for(const name of 'aliceblue antiquewhite aqua aquamarine azure beige bisque black blanchedalmond blue blueviolet brown burlywood cadetblue chartreuse chocolate coral cornflowerblue cornsilk crimson cyan darkblue darkcyan darkgoldenrod darkgray darkgreen darkgrey darkkhaki darkmagenta darkolivegreen darkorange darkorchid darkred darksalmon darkseagreen darkslateblue darkslategray darkslategrey darkturquoise darkviolet deeppink deepskyblue dimgray dimgrey dodgerblue firebrick floralwhite forestgreen fuchsia gainsboro ghostwhite gold goldenrod gray green greenyellow grey honeydew hotpink indianred indigo ivory khaki lavender lavenderblush lawngreen lemonchiffon lightblue lightcoral lightcyan lightgoldenrodyellow lightgray lightgreen lightgrey lightpink lightsalmon lightseagreen lightskyblue lightslategray lightslategrey lightsteelblue lightyellow lime limegreen linen magenta maroon mediumaquamarine mediumblue mediumorchid mediumpurple mediumseagreen mediumslateblue mediumspringgreen mediumturquoise mediumvioletred midnightblue mintcream mistyrose moccasin navajowhite navy oldlace olive olivedrab orange orangered orchid palegoldenrod palegreen paleturquoise palevioletred papayawhip peachpuff peru pink plum powderblue purple rebeccapurple red rosybrown royalblue saddlebrown salmon sandybrown seagreen seashell sienna silver skyblue slateblue slategray slategrey snow springgreen steelblue tan teal thistle tomato turquoise violet wheat white whitesmoke yellow yellowgreen'.split(' ')){ctx.fillStyle=name;ctx.fillRect(0,0,1,1);const c=ctx.getImageData(0,0,1,1).data,key=colourHex({r:c[0]/255,g:c[1]/255,b:c[2]/255,a:1});this.names.set(key,[...(this.names.get(key)??[]),name]);}}
 disconnectedCallback(){super.disconnectedCallback();window.removeEventListener('appearance-rainbow-change',this.speedChanged);}
 private copy(en:string,yue:string){return localizePair(en,yue,this.settings);}
 private accept(c:Colour){this.error='';if(!inSrgb(c)){this.pending=c;return;}this.pending=null;const bounded={r:Math.max(0,Math.min(1,c.r)),g:Math.max(0,Math.min(1,c.g)),b:Math.max(0,Math.min(1,c.b)),a:c.a};this.dispatchEvent(new CustomEvent('colour-change',{detail:bounded,bubbles:true,composed:true}));}
 private coordinate(e:PointerEvent){const el=e.currentTarget as HTMLElement;if(e.type==='pointermove'&&!el.hasPointerCapture(e.pointerId))return;if(e.type==='pointerdown')el.setPointerCapture(e.pointerId);const rect=el.getBoundingClientRect(),h=colourChannels('hsv',this.value)[0];this.accept(channelsColour('hsv',[h,Math.max(0,Math.min(100,(e.clientX-rect.left)/rect.width*100)),Math.max(0,Math.min(100,100-(e.clientY-rect.top)/rect.height*100))],this.value.a));}
 render(){const channels=colourChannels(this.space,this.value).map((v,i)=>Math.max(colourSpaces[this.space].ranges[i][0],Math.min(colourSpaces[this.space].ranges[i][1],v))),hsv=colourChannels('hsv',this.value),hex=colourHex(this.value,true);return html`
 <div class="row"><md-filter-chip label=${this.copy('Solid color','固定顏色')} .selected=${this.mode==='solid'} @click=${()=>this.dispatchEvent(new CustomEvent('colour-mode-change',{detail:'solid',bubbles:true,composed:true}))}></md-filter-chip><md-filter-chip label=${this.copy('Animated rainbow','流動彩虹')} ?disabled=${!this.animationSupported} .selected=${this.mode==='rainbow'} @click=${()=>this.dispatchEvent(new CustomEvent('colour-mode-change',{detail:'rainbow',bubbles:true,composed:true}))}></md-filter-chip></div>${!this.animationSupported?html`<p class="hint">${this.copy('This exported image paint is static. Animated color remains available on the containing UI layer.','匯出圖片填色係靜態，所屬介面圖層仍可使用流動顏色。')}</p>`:nothing}
 ${this.mode==='rainbow'?html`<md-slider aria-label=${this.copy('Global rainbow speed','全域彩虹速度')} min="1" max="5" step="1" .value=${this.speed} @change=${(e:Event)=>setRainbowSpeed(Number((e.target as HTMLInputElement).value))}></md-slider><div class="hint">${this.copy('One speed for every rainbow surface. Reduced motion holds hue 270.','所有彩虹表面共用速度，減少動態時固定喺色相 270。')} ${this.speed}/5 · ${rainbowDuration(this.speed)} s</div>`:nothing}
 <div class="field" role="group" aria-label=${this.copy('Saturation and brightness. Numeric controls follow.','飽和度同亮度，下方有數值控制。')} style=${`background:linear-gradient(to top,black,transparent),linear-gradient(to right,white,hsl(${hsv[0]} 100% 50%))`} @pointerdown=${this.coordinate} @pointermove=${this.coordinate}><span class="point" style=${`left:${hsv[1]}%;top:${100-hsv[2]}%`}></span></div>
 <md-slider aria-label=${this.copy('Hue','色相')} min="0" max="360" step="0.1" .value=${hsv[0]} @change=${(e:Event)=>this.accept(channelsColour('hsv',[Number((e.target as HTMLInputElement).value),hsv[1],hsv[2]],this.value.a))}></md-slider>
 <div class="channels">${[1,2].map((i)=>html`<md-outlined-text-field label=${this.copy(i===1?'Saturation %':'Brightness %',i===1?'飽和度 %':'亮度 %')} type="number" min="0" max="100" .value=${hsv[i].toFixed(2)} @change=${(e:Event)=>{try{const next=[...hsv];next[i]=Number((e.target as HTMLInputElement).value);this.accept(channelsColour('hsv',next,this.value.a));}catch{this.error=this.copy('Use a value from 0 to 100.','請輸入 0 至 100。');}}}></md-outlined-text-field>`)}</div>
 <md-outlined-select label=${this.copy('Color space','色彩空間')} .value=${this.space} @change=${(e:Event)=>this.space=(e.target as HTMLSelectElement).value as ColourSpace}>${Object.entries(colourSpaces).map(([id,s])=>html`<md-select-option value=${id}><span slot="headline">${s.label}</span></md-select-option>`)}</md-outlined-select>
 <div class="channels">${channels.map((v,i)=>html`<md-outlined-text-field label=${colourSpaces[this.space].channels[i]} type="number" .value=${String(Number(v.toFixed(4)))} @change=${(e:Event)=>{try{const next=[...channels];next[i]=Number((e.target as HTMLInputElement).value);this.accept(channelsColour(this.space,next,this.value.a));}catch{this.error=this.copy('Channel is outside this color space’s range.','數值超出呢個色彩空間範圍。');}}}></md-outlined-text-field>`)}</div>
 <md-outlined-text-field label="HEX / HEX8" .value=${hex} @change=${(e:Event)=>{try{this.accept(parseColourHex((e.target as HTMLInputElement).value));}catch{this.error=this.copy('Enter six or eight hexadecimal digits after #.','請喺 # 後輸入六或八位十六進制數字。');}}}></md-outlined-text-field>
 <md-slider aria-label=${this.copy('Alpha','透明度')} min="0" max="1" step="0.01" .value=${this.value.a} @change=${(e:Event)=>this.accept({...this.value,a:Number((e.target as HTMLInputElement).value)})}></md-slider>
 <md-outlined-text-field label=${this.copy('CSS named color','CSS 命名顏色')} .value=${this.name} @change=${(e:Event)=>{this.name=(e.target as HTMLInputElement).value.trim();if(!/^[a-z]{1,30}$/i.test(this.name)||!CSS.supports('color',this.name)||['inherit','initial','unset','currentcolor','revert'].includes(this.name.toLowerCase())){this.error=this.copy('Enter a supported CSS color name.','請輸入支援嘅 CSS 顏色名稱。');return;}const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d')!;canvas.width=canvas.height=1;ctx.fillStyle=this.name;ctx.fillRect(0,0,1,1);const c=ctx.getImageData(0,0,1,1).data;this.accept({r:c[0]/255,g:c[1]/255,b:c[2]/255,a:this.name.toLowerCase()==='transparent'?0:this.value.a});}}></md-outlined-text-field>
 <div class="sample" style=${`background:${this.mode==='rainbow'?'hsl(var(--mg-rainbow-hue,270) 100% 50%)':hex}`}></div><div class="hint">${this.copy('Matching CSS names','對應 CSS 名稱')}: ${(this.value.a===1?this.names.get(colourHex(this.value)):this.value.a===0?['transparent']:undefined)?.join(', ')||this.copy('No exact named color','無完全相符嘅命名顏色')}</div><div class="hint">sRGB · ${this.copy(this.mode==='rainbow'?'Underlying solid-color contrast':'Composited contrast',this.mode==='rainbow'?'底層固定色對比度':'合成對比度')}: ${colourContrast(this.value,this.background).toFixed(2)}:1. ${this.mode==='rainbow'?this.copy('Animated contrast varies through the cycle.','流動彩虹嘅對比度會隨色相改變。'):nothing} ${this.space==='cmyk'?this.copy('CMYK is a mathematical conversion without a printer ICC profile.','CMYK 係數學轉換，無打印機 ICC 色彩描述檔。'):nothing}</div>
 <md-text-button @click=${()=>void navigator.clipboard.writeText(`${colourSpaces[this.space].label}: ${channels.map(v=>Number(v.toFixed(4))).join(', ')}; alpha ${this.value.a}; ${hex}`)}>${this.copy('Copy translated color','複製轉換後顏色')}</md-text-button>
 ${this.pending?html`<div role="alert">${this.copy('Outside sRGB. Clipping changes the color; the current style has not changed.','超出 sRGB。裁切色域會改變顏色，目前樣式未改動。')}<md-filled-button @click=${()=>{const c=this.pending!;this.pending=null;this.accept(parseColourHex(colourHex(c,true)));}}>${this.copy('Apply clipped sRGB','套用裁切後 sRGB')}</md-filled-button><md-text-button @click=${()=>this.pending=null}>${this.copy('Cancel','取消')}</md-text-button></div>`:nothing}<div role="status">${this.error}</div>`;}
}
customElements.define('mg-appearance-colour',AppearanceColour);
