import{LitElement,html,css,nothing}from'lit';import './material.js';
import{defaults}from'../shared/preferences.js';import type{AppSettings}from'../shared/types.js';import{localizePair}from'./localization.js';import{pngDimensions,validateRasterRecipe,type RasterRecipe}from'../shared/appearance-raster.js';
import type{AppearanceStyle}from'../shared/appearance.js';
export function rasterBytes(source:string):Uint8Array{if(source.length>49152||!/^data:image\/png;base64,[A-Za-z0-9+/]+=*$/.test(source))throw Error('Use a bounded converted local PNG');const bytes=Uint8Array.from(atob(source.slice(source.indexOf(',')+1)),c=>c.charCodeAt(0));pngDimensions(bytes);return bytes;}
export async function renderRaster(source:string,recipe:RasterRecipe):Promise<string>{const bytes=rasterBytes(source),size=pngDimensions(bytes),r=validateRasterRecipe(recipe,size),bitmap=await createImageBitmap(new Blob([bytes as BlobPart],{type:'image/png'}));try{if(bitmap.width!==size.width||bitmap.height!==size.height)throw Error('Decoded PNG dimensions differ from the header');const canvas=document.createElement('canvas'),quarter=r.rotation===90||r.rotation===270;canvas.width=quarter?r.height:r.width;canvas.height=quarter?r.width:r.height;const ctx=canvas.getContext('2d')!;ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(r.rotation*Math.PI/180);ctx.scale(r.flipX?-1:1,r.flipY?-1:1);ctx.drawImage(bitmap,r.x,r.y,r.width,r.height,-r.width/2,-r.height/2,r.width,r.height);const result=canvas.toDataURL('image/png');if(result.length>49152)throw Error('Rendered fill exceeds the 48 KiB data URL limit');rasterBytes(result);return result;}finally{bitmap.close();}}
export class AppearanceRaster extends LitElement{
 static properties={values:{attribute:false},settings:{attribute:false},disabled:{type:Boolean},recipe:{state:true},preview:{state:true},status:{state:true},busy:{state:true}};
 values:AppearanceStyle={};settings:AppSettings={...defaults};disabled=false;recipe:RasterRecipe={x:0,y:0,width:1,height:1,rotation:0,flipX:false,flipY:false};preview='';status='';busy=false;private source='';private loaded='';private generation=0;
 static styles=css`:host{display:block;min-width:0}.fields{display:grid;grid-template-columns:repeat(2,minmax(100px,1fr));gap:8px}.preview{display:flex;gap:12px;flex-wrap:wrap}.preview figure{margin:0;min-width:0}.preview img{max-width:160px;max-height:160px;object-fit:contain;background:repeating-conic-gradient(#ddd 0% 25%,white 0% 50%) 0 0/16px 16px;border:1px solid var(--md-sys-color-outline)}md-outlined-text-field,md-outlined-select{width:100%}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.hint{font-size:12px;line-height:1.5}`;
 private copy(en:string,yue:string){return localizePair(en,yue,this.settings);}
 protected updated(changes:Map<PropertyKey,unknown>){if(changes.has('values')){const source=this.values.imageSource||this.values.image||'';const signature=source+'|'+[this.values.imageCropX,this.values.imageCropY,this.values.imageCropWidth,this.values.imageCropHeight,this.values.imageRotation,this.values.imageFlip].join(',');if(signature!==this.loaded){this.loaded=signature;this.generation++;this.source='';this.preview='';this.busy=false;if(source)try{const size=pngDimensions(rasterBytes(source));this.source=source;this.recipe={x:this.values.imageCropX??0,y:this.values.imageCropY??0,width:this.values.imageCropWidth??size.width,height:this.values.imageCropHeight??size.height,rotation:Number(this.values.imageRotation??0)as RasterRecipe['rotation'],flipX:this.values.imageFlip==='horizontal'||this.values.imageFlip==='both',flipY:this.values.imageFlip==='vertical'||this.values.imageFlip==='both'};void this.refresh();}catch{this.status=this.copy('This fill cannot be safely decoded within the PNG limits. The original remains unchanged.','呢個填色無法喺 PNG 限制內安全解碼，原圖保持不變。');}}}}
 disconnectedCallback(){super.disconnectedCallback();this.generation++;}
 private async refresh(){const generation=++this.generation;this.busy=true;this.status='';try{const preview=await renderRaster(this.source,this.recipe);if(generation===this.generation)this.preview=preview;}catch{if(generation===this.generation){this.preview='';this.status=this.copy('Invalid crop, unsupported PNG or output limit exceeded. Adjust the values; the active fill has not changed.','裁剪無效、PNG 不受支援或輸出超出限制。請調整數值，目前填色未改動。');}}finally{if(generation===this.generation)this.busy=false;}}
 private patch(value:Partial<RasterRecipe>){this.recipe={...this.recipe,...value};void this.refresh();}
 private apply(){if(!this.preview||this.busy||this.disabled)return;const r=this.recipe;this.dispatchEvent(new CustomEvent('raster-apply',{detail:{image:this.preview,imageSource:this.source,imageCropX:r.x,imageCropY:r.y,imageCropWidth:r.width,imageCropHeight:r.height,imageRotation:String(r.rotation),imageFlip:r.flipX&&r.flipY?'both':r.flipX?'horizontal':r.flipY?'vertical':'none'},bubbles:true,composed:true}));}
 render(){if(!this.values.image)return nothing;return html`<section aria-label=${this.copy('Image crop and transform','圖片裁剪同變換')}><h3>${this.copy('Image crop and transform','圖片裁剪同變換')}</h3><p class="hint">${this.copy('Local PNG only, at most 512 × 512 pixels. Crop uses source pixels. Apply retains the original for later edits. This is a layer fill, not a change to the source file.','只支援本機 PNG，最多 512 × 512 像素。裁剪使用原圖像素，套用會保留原圖供日後修改。只改圖層填色，唔改來源檔案。')}</p><div class="preview"><figure><figcaption>${this.copy('Original','原圖')}</figcaption><img src=${this.source} alt=${this.copy('Original local layer fill','原本本機圖層填色')}></figure>${this.preview?html`<figure><figcaption>${this.copy('Preview','預覽')}</figcaption><img src=${this.preview} alt=${this.copy('Transformed fill preview','變換後填色預覽')}></figure>`:nothing}</div><div class="fields">${(['x','y','width','height']as const).map(key=>html`<md-outlined-text-field data-appearance-field=${{x:'imageCropX',y:'imageCropY',width:'imageCropWidth',height:'imageCropHeight'}[key]} ?disabled=${this.disabled} label=${this.copy({x:'Crop X',y:'Crop Y',width:'Crop width',height:'Crop height'}[key],{x:'裁剪 X',y:'裁剪 Y',width:'裁剪闊度',height:'裁剪高度'}[key])} type="number" min=${key==='x'||key==='y'?0:1} max="512" .value=${String(this.recipe[key])} @change=${(e:Event)=>this.patch({[key]:Number((e.target as HTMLInputElement).value)})}></md-outlined-text-field>`)}</div><md-outlined-select data-appearance-field="imageRotation" ?disabled=${this.disabled} label=${this.copy('Rotation','旋轉')} .value=${String(this.recipe.rotation)} @change=${(e:Event)=>this.patch({rotation:Number((e.target as HTMLSelectElement).value)as RasterRecipe['rotation']})}>${[0,90,180,270].map(n=>html`<md-select-option value=${String(n)}><span slot="headline">${n}°</span></md-select-option>`)}</md-outlined-select><div class="row">${(['flipX','flipY']as const).map(key=>html`<md-filter-chip data-appearance-field=${key==='flipX'?'imageFlip':'imageFlipY'} ?disabled=${this.disabled} label=${this.copy(key==='flipX'?'Flip horizontally':'Flip vertically',key==='flipX'?'水平翻轉':'垂直翻轉')} .selected=${this.recipe[key]} @click=${()=>this.patch({[key]:!this.recipe[key]})}></md-filter-chip>`)}<md-text-button ?disabled=${this.disabled||this.busy} @click=${()=>{try{const size=pngDimensions(rasterBytes(this.source));this.recipe={x:0,y:0,width:size.width,height:size.height,rotation:0,flipX:false,flipY:false};void this.refresh();}catch{}}}>${this.copy('Reset preview','重設預覽')}</md-text-button><md-filled-button ?disabled=${this.disabled||this.busy||!this.preview} @click=${this.apply}>${this.copy('Apply image transform','套用圖片變換')}</md-filled-button></div><div role="status">${this.busy?this.copy('Rendering local preview…','正在繪製本機預覽…'):this.status}</div></section>`;}
}
customElements.define('mg-appearance-raster',AppearanceRaster);
