import {LitElement,html,css,nothing} from './material';
import './components';
import './cli-workflows';
import {defaults} from '../shared/preferences';
import type {AppSettings} from '../shared/types';
import type {CliWorkflowInventory} from '../shared/cli-workflows';
import {localizePair} from './localization';
/** Productive model tasks retain the reviewed native executable and never run suggested commands. */
export class MaterialCopilotWorkspace extends LitElement {
 static properties={settings:{attribute:false},hostname:{type:String},schoolMode:{type:Boolean},inventory:{state:true},loading:{state:true},mode:{state:true},busy:{state:true},dirty:{state:true},notice:{state:true}};
 settings:AppSettings={...defaults};hostname='github.com';schoolMode=false;inventory?:CliWorkflowInventory;loading=false;mode='explain';busy=false;dirty=false;notice='';private generation=0;
 static styles=css`:host{display:block;min-width:0}[hidden]{display:none!important}mg-layout{--gap:12px}mg-layout::part(container){gap:12px}mg-text{overflow-wrap:anywhere}md-tabs{width:100%}.notice{color:var(--md-sys-color-error)}`;
 private copy(en:string,yue:string){return localizePair(en,yue,this.schoolMode?{...this.settings,language:'en'}:this.settings);}
 connectedCallback(){super.connectedCallback();void this.refresh();}
 protected updated(changed:Map<PropertyKey,unknown>){if(changed.has('hostname'))void this.refresh();}
 private workState(){this.dispatchEvent(new CustomEvent('copilot-work-state',{detail:{busy:this.busy||this.loading,dirty:this.dirty},bubbles:true,composed:true}));}
 private async refresh(){const generation=++this.generation;this.loading=true;this.workState();try{const response=await window.material.cliWorkflows('inventory',{hostname:this.hostname});if(generation===this.generation&&response.kind==='inventory')this.inventory=response;}catch(error){if(generation===this.generation)this.notice=error instanceof Error?error.message:'Copilot availability could not be read.';}finally{if(generation===this.generation){this.loading=false;this.workState();}}}
 private changeTask(mode:string){if(this.busy||this.loading||this.dirty){this.notice=this.copy('Finish the request or discard its edited inputs before changing tasks.','切換工作前，請完成要求或放棄已編輯輸入。');return;}this.mode=mode;this.notice='';}
 public discardDrafts(){(this.renderRoot.querySelector('mg-cli-workflows') as HTMLElement&{discardDraft():void}|null)?.discardDraft();this.dirty=false;this.notice='';this.workState();}
 private async discard(){if(this.busy)return;try{await window.material.workspace('discard',{ids:['tools:copilot']});if(this.busy)return;this.discardDrafts();}catch{this.notice=this.copy('The discard record could not be saved. Your edited inputs remain open.','無法儲存放棄記錄，已編輯輸入會保持開啟。');}}
 private childState(event:CustomEvent<{busy:boolean;dirty:boolean}>){event.stopPropagation();this.busy=event.detail.busy;this.dirty=event.detail.dirty;this.workState();}
 private get effectiveTask(){return ['explain','suggest'].includes(this.mode)&&!this.inventory?.copilotCapabilities?.prompt?'help':this.mode;}
 render(){return html`<mg-layout column><mg-layout spread><mg-text kind="title">${this.copy('Copilot command assistance','Copilot 指令協助')}</mg-text><md-outlined-button ?disabled=${this.busy||this.loading} @click=${()=>this.refresh()}>${this.copy('Refresh availability','重新整理可用狀態')}</md-outlined-button></mg-layout><mg-text kind="muted">${this.copy('Explain command text or ask for a suggested command. Answers are never executed. The installed Copilot CLI uses its own sign-in, entitlement and provider configuration.','解釋指令文字或要求建議指令，答案唔會被執行。已安裝嘅 Copilot CLI 使用自己嘅登入、使用資格同提供者設定。')}</mg-text><md-tabs .activeTabIndex=${this.mode==='explain'?0:this.mode==='suggest'?1:2} @change=${(event:Event)=>this.changeTask(['explain','suggest','help'][(event.target as HTMLElement&{activeTabIndex:number}).activeTabIndex]||'help')}><md-primary-tab>${this.copy('Explain command','解釋指令')}</md-primary-tab><md-primary-tab>${this.copy('Suggest command','建議指令')}</md-primary-tab><md-primary-tab>${this.copy('Setup and version','設定同版本')}</md-primary-tab></md-tabs>${this.loading?html`<md-linear-progress indeterminate aria-label=${this.copy('Reading installed availability','讀取已安裝程式狀態')}></md-linear-progress>`:nothing}<mg-text role="status">${this.inventory?.copilotCapabilities?.message}</mg-text>${this.inventory&&!this.inventory.copilotInstalled?html`<mg-text>${this.copy('Install the official Copilot CLI yourself, then refresh. This app does not download or install it automatically.','請自行安裝官方 Copilot CLI，再重新整理。呢個應用程式唔會自動下載或安裝。')}</mg-text><md-outlined-button @click=${()=>window.material.openExternal('https://github.com/github/copilot-cli')}>${this.copy('Official installation instructions','官方安裝指引')}</md-outlined-button>`:nothing}${this.effectiveTask==='help'||this.effectiveTask==='version'?html`<mg-layout><md-outlined-button ?disabled=${this.busy||this.dirty} @click=${()=>this.changeTask('help')}>${this.copy('Read capabilities','讀取功能')}</md-outlined-button><md-outlined-button ?disabled=${this.busy||this.dirty} @click=${()=>this.changeTask('version')}>${this.copy('Read installed version','讀取已安裝版本')}</md-outlined-button></mg-layout><mg-text kind="muted">${this.copy('Review the installed program before reading its help or version. Noninteractive model tasks require the actual help to advertise prompt and tool-denial flags.','讀取說明或版本前，請檢查已安裝程式。非互動模型工作需要實際說明列出提示同工具拒絕選項。')}</mg-text>`:nothing}${this.notice?html`<mg-text class="notice" role="alert">${this.notice}</mg-text>`:nothing}${this.dirty?html`<md-text-button ?disabled=${this.busy} @click=${()=>this.discard()}>${this.copy('Discard edited inputs','放棄已編輯輸入')}</md-text-button>`:nothing}<mg-cli-workflows .commandId=${'copilot'} .contextual=${true} .copilotTask=${this.effectiveTask} .hostname=${this.hostname} .settings=${this.settings} .schoolMode=${this.schoolMode} @cli-workflows-work-state=${this.childState} @cli-workflows-complete=${(event:CustomEvent)=>{event.stopPropagation();void this.refresh();}}></mg-cli-workflows></mg-layout>`;}
}
customElements.define('mg-copilot-workspace',MaterialCopilotWorkspace);
