import {LitElement,html,css,nothing} from './material';
import './components';
import './scroll-surface';
import {ui} from './github-workspace-model';
import type {AppSettings} from '../shared/types';
import type {DownloadClient,DownloadJob,DownloadPage,DownloadRequest,DownloadSelection,DownloadIssue,DownloadState} from '../shared/downloads';

const states:Record<DownloadState,[string,string]>={queued:['Queued','等候下載'],downloading:['Downloading','下載中'],paused:['Paused','已暫停'],cancelled:['Cancelled','已取消'],failed:['Failed','下載失敗'],completed:['Complete','下載完成']};
const issues:Record<DownloadIssue,[string,string]>={authentication:['Sign in to the original account and try again.','請登入原本嘅帳戶，然後再試。'],'source-changed':['The source or its ETag changed. Retry starts a verified fresh transfer.','來源或者 ETag 已更改。再試會重新下載並核對。'],'destination-exists':['The destination already exists. Choose another destination for a new download.','目的地已經有檔案。請重新下載並揀另一個目的地。'],transfer:['The transfer stopped. Resume if available, or retry.','傳輸已中斷。可以繼續嘅話請繼續，或者再試。'],integrity:['The received data did not match its expected size or checksum. Retry.','收到嘅資料同預期大小或者檢查碼唔一致。請再試。'],storage:['Recovery storage or destination access failed. Check access and try again.','復原記錄或者目的地無法存取。請檢查存取權限，再試。'],interrupted:['The app stopped during this transfer. Resume if available, or retry.','應用程式喺下載期間停止。可以繼續嘅話請繼續，或者再試。']};
/** Backend-bound download workspace with independent start/progress surfaces. */
export class Downloads extends LitElement {
 static properties={client:{attribute:false},settings:{attribute:false},selection:{attribute:false},sourceName:{type:String},page:{state:true},busy:{state:true},message:{state:true},focused:{state:true},completion:{state:true}};
 client?:DownloadClient;settings?:AppSettings;selection?:DownloadSelection;sourceName='';
 page:DownloadPage={items:[],page:1,hasNext:false,total:0,recovery:'session'};busy=false;message='';focused?:DownloadJob;completion?:DownloadJob;
 private unsubscribe?:()=>void;private generation=0;private connectedClient?:DownloadClient;
 static styles=css`:host{display:block;min-width:0;height:100%}mg-layout{min-width:0}mg-text{overflow-wrap:anywhere}mg-scroll.jobs{height:min(52vh,560px);min-height:160px}md-linear-progress{width:100%}md-dialog{--md-dialog-container-max-width:min(680px,calc(100vw - 24px))}mg-scroll.progress{height:min(44vh,360px)}mg-layout.actions{padding-top:8px}mg-surface.job{margin-bottom:12px}mg-text[role=alert]{color:var(--md-sys-color-error)}md-outlined-button,md-filled-button,md-text-button{min-height:48px}:focus-visible{outline:2px solid var(--md-sys-color-primary);outline-offset:3px}@media(prefers-reduced-motion:reduce){*{transition:none}}`;
 private copy(en:string,yue:string){return ui(this.settings,en,yue);}
 protected updated(changed:Map<string,unknown>){if(changed.has('busy'))this.dispatchEvent(new CustomEvent('download-work-state',{detail:{id:'downloads',busy:this.busy,dirty:false},bubbles:true,composed:true}));if(changed.has('client')&&this.connectedClient!==this.client){this.unsubscribe?.();this.connectedClient=this.client;if(this.client)this.unsubscribe=this.client.subscribe(job=>{this.page={...this.page,items:this.page.items.map(row=>row.id===job.id?job:row)};if(this.focused?.id===job.id)this.focused=job;if(job.state==='completed'){this.completion=job;this.dispatchEvent(new CustomEvent('download-complete',{detail:{job},bubbles:true,composed:true}));}});void this.load();}}
 disconnectedCallback(){super.disconnectedCallback();this.generation++;this.unsubscribe?.();this.connectedClient=undefined;}
 connectedCallback(){super.connectedCallback();if(this.hasUpdated){this.requestUpdate('client');}}
 async load(page=this.page.page){if(!this.client)return;const generation=++this.generation;try{const result=await this.client.handle({action:'list',page});if(generation===this.generation)this.page=result;}catch{if(generation===this.generation)this.message=this.copy('Could not load downloads. Try again.','無法載入下載。請再試。');}}
 private async run(request:DownloadRequest){if(!this.client||this.busy)return;this.busy=true;this.message='';try{const previous=new Set(this.page.items.map(job=>job.id));const result=await this.client.handle(request);this.page=result;if(this.focused)this.focused=result.items.find(job=>job.id===this.focused?.id)??this.focused;if(request.action==='enqueue'){const job=result.items.find(job=>!previous.has(job.id));if(job)this.focused=job;this.selection=undefined;this.dispatchEvent(new CustomEvent('download-start-dismissed',{bubbles:true,composed:true}));}}catch{this.message=this.copy('The download action could not finish. Refresh the queue and check the recovery message.','下載操作未能完成。請重新整理下載列，查看復原訊息。');}finally{this.busy=false;}}
 private closeStart(){this.selection=undefined;this.dispatchEvent(new CustomEvent('download-start-dismissed',{bubbles:true,composed:true}));}
 private controls(job:DownloadJob){const stopped=['failed','paused','cancelled'].includes(job.state);return html`<mg-layout class="actions">
 ${job.state==='downloading'||job.state==='queued'?html`<md-outlined-button ?disabled=${this.busy} @click=${()=>this.run({action:'pause',id:job.id})}>${this.copy('Pause','暫停')}</md-outlined-button><md-text-button ?disabled=${this.busy} @click=${()=>this.run({action:'cancel',id:job.id})}>${this.copy('Cancel transfer','取消下載')}</md-text-button>`:nothing}
 ${stopped&&job.resumable?html`<md-filled-button ?disabled=${this.busy} @click=${()=>this.run({action:'resume',id:job.id})}>${this.copy('Resume','繼續下載')}</md-filled-button>`:nothing}
 ${stopped?html`<md-outlined-button ?disabled=${this.busy} @click=${()=>this.run({action:'retry',id:job.id})}>${this.copy('Retry from start','重新下載')}</md-outlined-button>`:nothing}
 ${job.issue==='authentication'?html`<md-filled-tonal-button @click=${()=>this.dispatchEvent(new CustomEvent('github-navigate',{detail:{domain:'accounts'},bubbles:true,composed:true}))}>${this.copy('Sign in','登入')}</md-filled-tonal-button>`:nothing}
 ${job.issue==='source-changed'||job.issue==='destination-exists'?html`<md-text-button @click=${()=>{this.sourceName=job.name;this.selection=job.selection;this.focused=undefined;}}>${this.copy('Choose new destination','揀新目的地')}</md-text-button>`:nothing}
 ${!['downloading','queued'].includes(job.state)?html`<md-text-button ?disabled=${this.busy} @click=${()=>this.run({action:'remove',id:job.id})}>${this.copy('Remove queue entry and partial file','移除下載記錄同未完成檔案')}</md-text-button>`:nothing}</mg-layout>`;}
 private facts(job:DownloadJob){return html`<mg-layout column><mg-text kind="title">${job.name}</mg-text><mg-text>${this.copy(...states[job.state])}</mg-text><mg-text kind="muted">${job.selection.hostname} · ${job.selection.repository} · ${job.selection.id}</mg-text><mg-text>${this.copy('Destination file','目的地檔案')}: ${job.destination}</mg-text><mg-text>${job.bytes.toLocaleString()} / ${job.total===null?this.copy('Unknown bytes','位元組數未知'):job.total.toLocaleString()} ${this.copy('bytes','位元組')}</mg-text>${job.state==='downloading'?html`<md-linear-progress .indeterminate=${job.total===null} .value=${job.total?job.bytes/job.total:0} aria-label=${this.copy(`Download progress for ${job.name}`,`${job.name} 嘅下載進度`)}></md-linear-progress><mg-text>${job.bytesPerSecond.toLocaleString()} ${this.copy('bytes/s','位元組／秒')} · ${this.copy('ETA','預計剩餘時間')}: ${job.etaSeconds===null?this.copy('Unknown','未知'):`${job.etaSeconds} ${this.copy('seconds','秒')}`}</mg-text>`:nothing}
 ${job.verification&&job.state==='completed'?html`<mg-text>${this.copy(job.verification==='sha256'?'SHA-256 verified':'Exact byte length verified',job.verification==='sha256'?'SHA-256 已核對':'確實位元組大小已核對')}</mg-text>`:nothing}
 ${job.issue?html`<mg-text role="alert">${this.copy(...issues[job.issue])}</mg-text>`:nothing}${this.controls(job)}</mg-layout>`;}
 render(){return html`<mg-surface plain><mg-layout column><mg-layout spread><mg-text kind="title">${this.copy('Downloads','下載')}</mg-text><md-outlined-button ?disabled=${this.busy||!this.client} @click=${()=>this.load()}>${this.copy('Refresh','重新整理')}</md-outlined-button></mg-layout>
 <mg-text kind="muted">${this.copy('Select a release asset or workflow artifact to start. Downloads continue while you use other workspaces.','揀選版本資產或者工作流程成品開始下載。使用其他工作區時，下載會繼續。')}</mg-text>
 ${this.client&&this.page.recovery==='session'?html`<mg-text role="status">${this.copy('Recovery is available only during this session because protected storage is unavailable.','受保護儲存未能使用，復原只適用於今次使用期間。')}</mg-text>`:nothing}
 ${!this.client?html`<mg-text role="status">${this.copy('Native download service is unavailable.','原生下載服務未能使用。')}</mg-text>`:nothing}
 ${this.message?html`<mg-text role="alert">${this.message}</mg-text><md-text-button @click=${()=>this.load()}>${this.copy('Reload queue','重新載入下載列')}</md-text-button>`:nothing}
 <mg-scroll class="jobs" label=${this.copy('Download queue','下載列')}>${this.page.items.map(job=>html`<mg-surface class="job"><mg-layout column>${this.facts(job)}<md-text-button @click=${()=>this.focused=job}>${this.copy('Open download progress','開啟下載進度')}</md-text-button></mg-layout></mg-surface>`)}${!this.page.items.length?html`<mg-text>${this.copy('No downloads on this page.','呢一頁未有下載。')}</mg-text>`:nothing}</mg-scroll>
 <mg-layout spread><md-text-button ?disabled=${this.page.page<=1||this.busy} @click=${()=>this.load(this.page.page-1)}>${this.copy('Previous','上一頁')}</md-text-button><mg-text>${this.copy('Page','頁')} ${this.page.page} · ${this.page.total} ${this.copy('downloads','個下載')}</mg-text><md-text-button ?disabled=${!this.page.hasNext||this.busy} @click=${()=>this.load(this.page.page+1)}>${this.copy('Next','下一頁')}</md-text-button></mg-layout>
 ${this.completion?html`<mg-surface role="status" aria-live="polite"><mg-layout spread><mg-text>${this.copy('Download complete','下載完成')}: ${this.completion.name}</mg-text><md-text-button @click=${()=>this.completion=undefined}>${this.copy('Dismiss','關閉')}</md-text-button></mg-layout></mg-surface>`:nothing}</mg-layout></mg-surface>
 ${this.selection?html`<md-dialog open aria-label=${this.copy('Start download','開始下載')} @cancel=${()=>this.closeStart()}><mg-text slot="headline">${this.copy('Start download','開始下載')}</mg-text><mg-layout slot="content" column>${this.message?html`<mg-text role="alert">${this.message}</mg-text><md-text-button @click=${()=>{this.closeStart();this.dispatchEvent(new CustomEvent('github-navigate',{detail:{domain:'accounts'},bubbles:true,composed:true}));}}>${this.copy('Sign in','登入')}</md-text-button>`:nothing}<mg-text>${this.sourceName||this.copy('Selected GitHub file','已揀選嘅 GitHub 檔案')}</mg-text><mg-text>${this.selection.hostname} · ${this.selection.repository} · ${this.selection.id}</mg-text><mg-text>${this.copy('Start opens the native save picker, then queues this exact provider file. Cancelling leaves the queue unchanged.','開始後會開啟原生儲存檔案選擇器，再將呢個檔案加入下載列。取消唔會更改下載列。')}</mg-text></mg-layout><mg-layout slot="actions"><md-text-button ?disabled=${this.busy} @click=${()=>this.closeStart()}>${this.copy('Cancel','取消')}</md-text-button><md-filled-button ?disabled=${this.busy||!this.client} @click=${()=>this.selection&&this.run({action:'enqueue',selection:this.selection})}>${this.copy('Start and choose destination','開始並揀目的地')}</md-filled-button></mg-layout></md-dialog>`:nothing}
 ${this.focused?html`<md-dialog open aria-label=${this.copy('Downloading','下載中')} @cancel=${()=>this.focused=undefined}><mg-text slot="headline">${this.copy('Download progress','下載進度')}</mg-text><mg-scroll class="progress" slot="content" label=${this.copy('Transfer details','傳輸詳情')}>${this.facts(this.focused)}</mg-scroll><md-text-button slot="actions" @click=${()=>this.focused=undefined}>${this.copy(this.focused.state==='downloading'||this.focused.state==='queued'?'Keep downloading and close':'Close progress',this.focused.state==='downloading'||this.focused.state==='queued'?'繼續下載並關閉':'關閉進度')}</md-text-button></md-dialog>`:nothing}`;}
}
if(!customElements.get('mg-downloads'))customElements.define('mg-downloads',Downloads);
