import {LitElement,html,css,nothing} from './material';
import './components';
import {exportFormats,serializeExport,type ExportFormat} from '../shared/exports';
import type {AppSettings} from '../shared/types';
/** Format choices derive from the actual datum; disclosures appear before the native save action. */
export class ExportMenu extends LitElement{
 static properties={data:{attribute:false},settings:{attribute:false},scope:{type:String},disabled:{type:Boolean},format:{state:true},busy:{state:true},error:{state:true},notice:{state:true}};
 data:unknown=null;settings?:AppSettings;scope='Displayed data';disabled=false;format:ExportFormat='json';busy=false;error='';notice='';
 static styles=css`:host{display:block;min-width:0}mg-layout{gap:12px}.format-choices{display:flex;flex-wrap:wrap;gap:8px;min-width:0}mg-text{overflow-wrap:anywhere}`;
 private text(en:string,yue:string){return this.settings?.language==='yue'?yue:this.settings?.language==='both'?en+' · '+yue:en;}
 private async save(){if(this.disabled||this.busy)return;this.busy=true;this.error='';this.notice='';try{serializeExport(this.data,this.format);const bridge=window.material as typeof window.material&{exportData:(data:unknown,format:ExportFormat)=>Promise<boolean>};const saved=await bridge.exportData(this.data,this.format);this.notice=saved?this.text('Export saved.','已儲存匯出檔案。'):this.text('Save was cancelled.','已取消儲存。');}catch(e){this.error=e instanceof Error?e.message:'Export failed';}finally{this.busy=false;}}
 render(){const formats=exportFormats(this.data);if(formats.length&&!formats.includes(this.format))this.format=formats[0];let disclosures:string[]=[];try{if(formats.length)disclosures=serializeExport(this.data,this.format).disclosures;}catch(e){return html`<mg-text role="alert">${e instanceof Error?e.message:'Unsupported export data'}</mg-text>`;}return html`<mg-layout column aria-label=${this.text('Export this data','匯出呢啲資料')}><mg-text>${this.scope}</mg-text><mg-layout class="format-choices" role="group" aria-label=${this.text('Export format','匯出格式')}>${formats.map(format=>html`<md-filter-chip label=${format.toUpperCase()} .selected=${this.format===format} ?disabled=${this.busy||this.disabled} @click=${()=>{this.format=format;this.notice='';}}></md-filter-chip>`)}</mg-layout>${disclosures.map(d=>html`<mg-text>${d}</mg-text>`)}${!formats.length?html`<mg-text>${this.text('This datum contains unsupported non-JSON values. Select structured records or plain text for export.','呢啲資料包含未支援嘅非 JSON 值。請選擇結構化記錄或純文字匯出。')}</mg-text>`:nothing}<md-outlined-button ?disabled=${!formats.length||this.busy||this.disabled} @click=${()=>this.save()}>${this.text('Choose destination and export','選擇位置同匯出')}</md-outlined-button>${this.error?html`<mg-text role="alert">${this.error}</mg-text>`:nothing}<mg-text role="status">${this.notice}</mg-text></mg-layout>`;}
}
customElements.define('mg-export-menu',ExportMenu);
