import {LitElement,html,css} from './material';
import './components';
export interface GitTreeEntry {name:string;mode:string;object:string;}
/** Structured tree entries. Object IDs and filenames are data, never index or command syntax. */
export class GitTreeEditor extends LitElement {
 static properties={entries:{attribute:false},disabled:{type:Boolean},language:{}};
 entries:GitTreeEntry[]=[];disabled=false;language='en';
 static styles=css`:host{display:block}.entries{display:grid;gap:12px}.entry{display:grid;grid-template-columns:minmax(120px,1fr) minmax(140px,.7fr) minmax(200px,1.6fr) auto;gap:8px;align-items:center}md-outlined-text-field,md-outlined-select{width:100%;min-width:0}.actions{display:flex;gap:8px;margin-top:10px}@media(max-width:900px){.entry{grid-template-columns:1fr}}`;
 private label(value:string){const yue:Record<string,string>={'Entry name':'項目名稱','Stored object or reference':'已儲存物件或者參照','Entry type':'項目類型','Remove entry':'移除項目','Add tree entry':'加入樹狀項目','File':'檔案','Executable file':'可執行檔案','Symbolic link contents':'符號連結內容','Subdirectory tree':'子目錄樹狀物件','Submodule commit':'子模組提交','No entries, creates an empty tree.':'冇項目，會建立空樹狀物件。'};return this.language==='yue'?(yue[value]||value):this.language==='both'&&yue[value]?value+' · '+yue[value]:value;}
 private change(entries:GitTreeEntry[]){this.dispatchEvent(new CustomEvent('tree-change',{detail:{entries},bubbles:true,composed:true}));}
 private updateEntry(index:number,key:keyof GitTreeEntry,value:string){this.change(this.entries.map((entry,current)=>current===index?{...entry,[key]:value}:entry));}
 render(){const modes=[['100644','File'],['100755','Executable file'],['120000','Symbolic link contents'],['040000','Subdirectory tree'],['160000','Submodule commit']];return html`<div class="entries">${this.entries.map((entry,index)=>html`<div class="entry"><md-outlined-text-field label=${this.label('Entry name')} .value=${entry.name} ?disabled=${this.disabled} @input=${(event:Event)=>this.updateEntry(index,'name',(event.target as HTMLInputElement).value)}></md-outlined-text-field><md-outlined-select label=${this.label('Entry type')} .value=${entry.mode} ?disabled=${this.disabled} @change=${(event:Event)=>this.updateEntry(index,'mode',(event.target as HTMLSelectElement).value)}>${modes.map(([mode,label])=>html`<md-select-option value=${mode} ?selected=${entry.mode===mode}><div slot="headline">${this.label(label)}</div></md-select-option>`)}</md-outlined-select><md-outlined-text-field label=${this.label('Stored object or reference')} .value=${entry.object} ?disabled=${this.disabled} @input=${(event:Event)=>this.updateEntry(index,'object',(event.target as HTMLInputElement).value)}></md-outlined-text-field><md-text-button ?disabled=${this.disabled} @click=${()=>this.change(this.entries.filter((_,current)=>current!==index))}>${this.label('Remove entry')}</md-text-button></div>`)}</div>${!this.entries.length?html`<mg-text kind="muted">${this.label('No entries, creates an empty tree.')}</mg-text>`:null}<div class="actions"><md-outlined-button ?disabled=${this.disabled} @click=${()=>this.change([...this.entries,{name:'',mode:'100644',object:''}])}>${this.label('Add tree entry')}</md-outlined-button></div>`;}
}
customElements.define('mg-git-tree-editor',GitTreeEditor);
