import {LitElement,html,css,nothing} from './material';import './components';import type {GitResponse,GitRow} from '../shared/git';
const translated:Record<string,string>={'Advertised references':'遠端提供嘅參照','Scope':'範圍','All references':'所有參照','Branches':'分支','Tags':'標籤','Reference-name prefix':'參照名稱開頭','Inspect remote references':'檢查遠端參照','Previous':'上一頁','Next':'下一頁','Fetch selected branch':'擷取所選分支','No matching advertised references.':'冇符合嘅遠端參照。','This reads the selected remote using the current repository-program trust setting. It does not fetch objects or change references.':'呢個操作會按目前儲存庫程式信任設定讀取所選遠端，唔會擷取物件或者更改參照。'};
export class GitRemoteRefs extends LitElement {
 static properties={remote:{},language:{},bridge:{attribute:false},disabled:{type:Boolean},scope:{state:true},prefix:{state:true},rows:{state:true},busy:{state:true},error:{state:true},loaded:{state:true},page:{state:true},hasNext:{state:true}};
 remote='';language='en';bridge?:(fields:Record<string,unknown>,page:number)=>Promise<GitResponse>;disabled=false;scope='all';prefix='';rows:GitRow[]=[];busy=false;error='';loaded=false;page=0;hasNext=false;
 static styles=css`:host{display:block;min-width:0;color:var(--md-sys-color-on-surface,#18201b)}.fields,.records{display:grid;gap:12px}.fields{grid-template-columns:repeat(2,minmax(0,1fr))}.actions,.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.record{min-width:0;flex:1;overflow-wrap:anywhere}.hint{color:var(--md-sys-color-on-surface-variant,#40534b)}.error{color:var(--md-sys-color-error,#ba1a1a)}.records{max-height:420px;overflow:auto;scrollbar-width:thin;scrollbar-color:var(--md-sys-color-primary,#006b55) transparent}.records::-webkit-scrollbar{width:8px}.records::-webkit-scrollbar-thumb{background:var(--md-sys-color-primary,#006b55);border-radius:8px}@media(max-width:680px){.fields{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*{transition:none!important;animation:none!important}}`;
 private label(text:string){return this.language==='yue'?translated[text]||text:this.language==='both'&&translated[text]?text+' · '+translated[text]:text;}
 protected updated(changed:Map<string,unknown>){if(changed.has('remote')){this.rows=[];this.loaded=false;this.page=0;this.error='';}}
 private async inspect(page=0){if(this.disabled||this.busy||!this.bridge)return;this.busy=true;this.error='';const remote=this.remote;try{const response=await this.bridge({remote,scope:this.scope,prefix:this.prefix},page);if(remote!==this.remote)return;if(response.kind!=='rows')throw new Error('Remote did not return reference records');this.rows=response.rows;this.hasNext=response.hasNext;this.page=page;this.loaded=true;}catch(error){this.error=error instanceof Error?error.message:String(error);}finally{this.busy=false;}}
 render(){return html`<mg-surface><mg-layout><mg-text kind="title">${this.label('Advertised references')}: ${this.remote}</mg-text><mg-text kind="muted">${this.label('This reads the selected remote using the current repository-program trust setting. It does not fetch objects or change references.')}</mg-text><div class="fields"><md-outlined-select label=${this.label('Scope')} .value=${this.scope} ?disabled=${this.busy||this.disabled} @change=${(event:Event)=>{this.scope=(event.target as HTMLSelectElement).value;this.loaded=false;}}>${[['all','All references'],['branches','Branches'],['tags','Tags']].map(([value,label])=>html`<md-select-option value=${value}><div slot="headline">${this.label(label)}</div></md-select-option>`)}</md-outlined-select><md-outlined-text-field label=${this.label('Reference-name prefix')} .value=${this.prefix} ?disabled=${this.busy||this.disabled} @input=${(event:Event)=>{this.prefix=(event.target as HTMLInputElement).value;this.loaded=false;}}></md-outlined-text-field></div><div class="actions"><md-filled-button ?disabled=${this.busy||this.disabled} @click=${()=>this.inspect()}>${this.label('Inspect remote references')}</md-filled-button></div>${this.error?html`<mg-text class="error" role="alert">${this.error}</mg-text>`:nothing}${this.busy?html`<md-linear-progress indeterminate></md-linear-progress>`:nothing}<div class="records">${this.loaded&&!this.rows.length?html`<mg-text>${this.label('No matching advertised references.')}</mg-text>`:nothing}${this.rows.map(row=>html`<div class="row"><div class="record"><mg-text>${row.label}</mg-text><mg-text kind="code">${row.detail}</mg-text>${row.data?.symbolic?html`<mg-text kind="muted">${row.data.symbolic}</mg-text>`:nothing}</div>${row.id.startsWith('refs/heads/')?html`<md-outlined-button ?disabled=${this.busy||this.disabled} @click=${()=>this.dispatchEvent(new CustomEvent('remote-fetch',{detail:{remote:this.remote,reference:row.id},bubbles:true,composed:true}))}>${this.label('Fetch selected branch')}</md-outlined-button>`:nothing}</div>`)}</div>${this.loaded?html`<div class="actions"><md-outlined-button ?disabled=${this.busy||this.disabled||!this.page} @click=${()=>this.inspect(this.page-1)}>${this.label('Previous')}</md-outlined-button><md-outlined-button ?disabled=${this.busy||this.disabled||!this.hasNext} @click=${()=>this.inspect(this.page+1)}>${this.label('Next')}</md-outlined-button></div>`:nothing}</mg-layout></mg-surface>`;}
}
customElements.define('mg-git-remote-refs',GitRemoteRefs);
