/** Application-owned Git editor copy. Repository data and native diagnostics remain literal. */
export const gitEditorYue:Record<string,string>={
'Check out selected pull request':'檢出所選合併請求','Choose a clean local repository with a matching remote during review. Its exact provider head is fetched and verified before switching to a fresh branch. Existing changes and ignored-file collisions are preserved.':'檢查時揀乾淨而遠端吻合嘅本機儲存庫。程式會擷取並核對來源提交，先切換到新分支，保留現有變更同衝突嘅忽略檔案。','New local branch name':'新本機分支名稱','Leave empty to use pr followed by the selected pull request number.':'留空就用 pr 加所選合併請求編號。',
 'Save merged result as a new file':'將合併結果另存新檔','Choose a native output folder during review. Existing files are never overwritten and the three original inputs stay unchanged.':'檢查操作時用原生選擇器揀輸出目錄，唔會覆寫現有檔案，三個原本輸入亦會保留。','New output filename':'新輸出檔名','Merged result':'合併結果','Allow saving unresolved conflict markers':'容許儲存未解決衝突標記',
"Create tree from object entries":"從物件項目建立樹狀物件","Create tree from entries":"從項目建立樹狀物件","Tree entries":"樹狀項目","Preview branch integration":"預覽分支整合","Preview integration":"預覽整合","Current-side commit or reference":"目前一方提交或者參照","Incoming commit or reference":"傳入提交或者參照","Optional explicit merge base":"明確合併基礎（可選）","Allow unrelated histories":"容許無關歷史",
"Skip untestable regression candidates":"略過無法測試嘅回歸候選版本","Untestable commits, one per line":"無法測試嘅提交，每行一個","Replay imported regression journal":"重播已匯入回歸記錄","Good classification term":"正常版本分類詞","Bad classification term":"出錯版本分類詞","Follow first parents only":"只跟隨第一父提交","Preserve working files while selecting candidates":"選擇候選版本時保留工作檔案","Optional regression file paths, one per line":"回歸檔案路徑（可選），每行一個","Regression journal":"回歸記錄","Regression terms":"回歸分類詞","Import regression journal":"匯入回歸記錄","Replay regression journal":"重播回歸記錄","Skip candidate":"略過候選版本","Search tracked content":"搜尋已追蹤內容",
"Store imported file object":"儲存匯入檔案物件","Store exact native-picked bytes as a Git blob without running filters. This does not stage the file.":"將原生選擇器揀嘅原始內容儲存成 Git 檔案物件，唔會執行過濾器或者暫存檔案。","Create tree from index":"從暫存區建立樹狀物件","Create detached commit object":"建立獨立提交物件","Create detached tag object":"建立獨立標籤物件","Load trees into index":"將樹狀物件載入暫存區","Restore staged file to working directory":"將已暫存檔案還原到工作目錄","Stage stored blob at a file path":"將檔案物件暫存到路徑","Tree object or reference":"樹狀物件或者參照","Parent commits, one per line":"父提交，每行一個","Target object or reference":"目標物件或者參照","Tagger name":"標籤建立者姓名","Tagger email":"標籤建立者電郵","Index loading mode":"暫存區載入模式","Tree references, one per line":"樹狀參照，每行一個","Indexed file":"已暫存檔案","Overwrite existing working file":"覆寫現有工作檔案","Relative index path":"相對暫存區路徑","Stored blob object ID":"已儲存檔案物件識別碼","Regular file mode":"一般檔案模式","Import object bytes":"匯入物件內容","Store imported blob":"儲存匯入檔案物件","Create index tree":"建立暫存區樹狀物件","Create detached commit":"建立獨立提交","Create detached tag":"建立獨立標籤","Load index from tree":"從樹狀物件載入暫存區","Stage stored blob":"暫存已儲存檔案物件","Restore staged contents":"還原已暫存內容","History filters":"歷史篩選","Author contains":"作者包含","Since (UTC date)":"開始日期（UTC）","Until (UTC date)":"結束日期（UTC）","Ordering":"排序","Merge commits":"合併提交","Selected reference":"所選參照","Apply history filters":"套用歷史篩選",
'Create repository':'新增儲存庫','Clone repository':'複製儲存庫','Choose a native parent directory and create a new repository folder.':'用原生選擇器揀上層目錄，再建立新儲存庫。','Choose a native parent directory and clone an HTTPS or SSH remote into a new folder.':'用原生選擇器揀上層目錄，再將 HTTPS 或 SSH 遠端複製到新目錄。','New repository folder':'新儲存庫目錄','Initial branch':'初始分支','Optional remote branch':'遠端分支（可選）','Optional shallow history depth':'淺層歷史深度（可選）','Fetch file contents on demand':'需要時先擷取檔案內容','Fetch a single branch':'只擷取一個分支',
'Commit staged changes':'提交已暫存變更','Create a commit from the index. Unstaged files remain in the working tree.':'用暫存區內容建立提交。未暫存檔案會留喺工作目錄。','Commit message':'提交訊息','Amend latest commit':'修改最近一次提交','Sign commit using configured signing tool':'用設定好嘅工具簽署提交','Override author (Name <email>)':'指定作者（姓名 <電郵>）',
'Create branch':'新增分支','Name a branch and select its starting commit.':'輸入分支名稱，再選擇起點提交。','New branch name':'新分支名稱','Starting commit or reference':'起點提交或參照','Switch to the new branch':'切換到新分支','Rename branch':'重新命名分支','Rename the selected local branch.':'重新命名所選本機分支。','Branch':'分支','Merge branch':'合併分支','Integrate the selected branch into the current branch.':'將所選分支整合到目前分支。','Commit or reference':'提交或參照','Merge strategy':'合併方式','Rebase branch':'重整分支','Replay current commits onto the selected reference. This rewrites commit identities.':'將目前提交重新套用到所選參照。提交識別碼會改變。','Apply commit':'套用提交','Copy the selected commit changes onto the current branch.':'將所選提交嘅變更複製到目前分支。','Revert commit':'還原提交','Create a commit that reverses the selected commit.':'建立新提交，撤銷所選提交嘅變更。',
'Fetch remote changes':'擷取遠端變更','Update remote tracking references without changing local files.':'更新遠端追蹤參照，保留本機檔案。','Remote':'遠端','Optional source:destination refspec':'來源:目的地參照規格（可選）','Prune deleted remote tracking references':'清理已刪除嘅遠端追蹤參照','Fetch tags':'擷取標籤','Pull into current branch':'拉取到目前分支','Fetch and integrate a selected remote branch.':'擷取並整合所選遠端分支。','Remote branch':'遠端分支','Integration mode':'整合方式','Publish selected reference':'發佈所選參照','Push a single explicit source and destination. No force option is used.':'推送一組明確嘅來源同目的地，唔會強制推送。','Local source':'本機來源','Remote destination':'遠端目的地','Set upstream tracking':'設定上游追蹤','Add remote':'新增遠端','Connect this repository to an HTTPS or SSH remote.':'將儲存庫連接到 HTTPS 或 SSH 遠端。','Remote name':'遠端名稱','HTTPS or SSH URL':'HTTPS 或 SSH 網址','Change remote URL':'更改遠端網址','Change the selected remote connection.':'更改所選遠端連接。','Rename remote':'重新命名遠端','Rename a configured remote and its tracking references.':'重新命名遠端同佢嘅追蹤參照。','New remote name':'新遠端名稱',
'Create tag':'新增標籤','Mark a selected commit with a lightweight or annotated tag.':'為所選提交加入輕量標籤或者註解標籤。','Tag name':'標籤名稱','Annotation message':'註解訊息','Sign using configured signing tool':'用設定好嘅簽署工具簽署','Save work in a stash':'將工作儲存到暫存','Save tracked changes and restore their current base.':'儲存已追蹤變更，再還原到目前基礎版本。','Stash message':'暫存訊息','Include untracked files':'包括未追蹤檔案',
'Add working tree':'新增工作目錄','A native folder picker chooses its parent. Existing files are preserved.':'用原生目錄選擇器揀上層目錄，保留現有檔案。','New folder name':'新目錄名稱','Create this branch':'建立呢個分支','Lock working tree':'鎖定工作目錄','Prevent automatic pruning or removal while the working tree is unavailable.':'工作目錄暫時無法使用時，防止自動清理或者移除。','Lock reason':'鎖定原因','Add submodule':'新增子模組','Clone a nested repository and record its location.':'複製巢狀儲存庫並記錄位置。','Relative submodule directory':'相對子模組目錄','Update submodule':'更新子模組','Check out the recorded nested repository revision.':'檢出已記錄嘅巢狀儲存庫版本。','Submodule path':'子模組路徑','Initialize if needed':'需要時初始化','Include nested submodules':'包括巢狀子模組',
'Find regression':'尋找回歸問題','Begin a binary search between a known good and bad commit. Check each candidate manually.':'喺已知正常同出錯提交之間開始二分搜尋，逐個候選版本手動檢查。','Known good commit':'已知正常提交','Known bad commit':'已知出錯提交','Choose sparse directories':'選擇稀疏目錄','Keep only selected tracked directory cones in this working tree.':'喺工作目錄只保留所選嘅已追蹤目錄範圍。','Directories, one per line':'目錄，每行一個','Deepen shallow history':'加深淺層歷史','Fetch more ancestors from a selected remote.':'從所選遠端擷取更多祖先提交。','Additional history depth':'額外歷史深度',
'Apply imported patch':'套用已匯入修補檔','Apply the reviewed patch bytes to working files or the index.':'將已檢查修補檔內容套用到工作檔案或者暫存區。','Apply to index only':'只套用到暫存區','Reverse the patch':'反向套用修補檔','Import mailbox commits':'匯入郵件格式提交','Create commits from the imported mailbox patch. Conflicts enter the recovery workflow.':'用已匯入郵件修補檔建立提交，衝突會進入復原流程。','Export commit patches':'匯出提交修補檔','Write email patches to a relative directory inside the working tree.':'將郵件修補檔寫入工作目錄內嘅相對目錄。','Commit count':'提交數量','Output directory':'輸出目錄',
'Set Git configuration':'設定 Git 選項','Edit any configuration key with explicit scope. Executable settings remain visibly marked.':'用明確範圍編輯設定鍵。可執行程式嘅設定會有清楚標記。','Section.key':'區段.設定鍵','Value':'值','Scope':'範圍','Remove Git configuration':'移除 Git 設定','Remove the selected key only in the chosen scope.':'只喺所選範圍移除設定鍵。','Run repository maintenance':'執行儲存庫維護','Use Git retention settings to maintain repository objects.':'按 Git 保留設定維護儲存庫物件。','Maintenance task':'維護工作','Expire old recovery entries':'清理舊復原記錄','Remove reflog entries older than a selected retention interval.':'移除早過所選保留期嘅參照日誌記錄。','Retention in days':'保留日數',
'Add commit note':'加入提交註記','Attach a note without replacing the commit.':'附加註記並保留原有提交。','Note':'註記','Remove commit note':'移除提交註記','Remove the selected commit note.':'移除所選提交註記。','Create object replacement':'新增物件替代','Redirect local object traversal through an alternate object.':'本機物件遍歷改用替代物件。','Replacement object':'替代物件','Remove object replacement':'移除物件替代','Restore normal traversal for a replaced object.':'還原被替代物件嘅正常遍歷。','Update reference with expected value':'按預期值更新參照','Atomically update a full reference only when its old object matches.':'舊物件符合預期先會原子更新完整參照。','Full refs/ reference':'完整 refs/ 參照','New object ID':'新物件識別碼','Expected old object ID':'預期舊物件識別碼','Reset current branch':'重設目前分支','Move HEAD to a selected commit using an explicit index and working tree mode.':'用明確暫存區同工作目錄模式，將 HEAD 移到所選提交。','Reset mode':'重設模式'
};
