import {svg} from 'lit';
import {LitElement,html,css,nothing} from './material';import type {GitRow} from '../shared/git';
/** Registered commit graph composition. Parent object IDs, never visual guesses, define its edges. */
export class GitHistoryGraph extends LitElement {
 static properties={rows:{attribute:false},selected:{}};rows:GitRow[]=[];selected='';
 static styles=css`:host{display:block;min-width:0}.graph{overflow:auto;scrollbar-width:thin;scrollbar-color:var(--md-sys-color-primary,#006b55) transparent}.entry{height:48px;display:flex;gap:8px;align-items:center;min-width:0}.copy{min-width:0;flex:1}.subject{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:100%}.chart{display:grid;grid-template-columns:96px minmax(220px,1fr);min-width:316px}svg{overflow:visible}line,path{stroke:var(--md-sys-color-outline,#6c7b72);stroke-width:2;fill:none}circle{fill:var(--md-sys-color-primary,#006b55);stroke:var(--md-sys-color-surface,#f5faf4);stroke-width:3}circle.selected{fill:var(--md-sys-color-secondary,#4e6356)}md-text-button{max-width:100%;--md-text-button-label-text-font:inherit}`;
 render(){const positions=new Map(this.rows.map((row,index)=>[row.id,index]));const lanes:string[]=[];const edges:{from:number;to:number;start:number;end:number}[]=[];const nodes:{lane:number;index:number}[]=[];for(let index=0;index<this.rows.length;index++){const row=this.rows[index];let lane=lanes.indexOf(row.id);if(lane<0){lane=lanes.findIndex(value=>!value);if(lane<0)lane=lanes.length;lanes[lane]=row.id;}nodes.push({lane,index});const parents=(row.data?.parents||'').split(' ').filter(Boolean);lanes[lane]='';parents.forEach((parent,offset)=>{let destination=lanes.indexOf(parent);if(destination<0){destination=offset===0?lane:lanes.findIndex(value=>!value);if(destination<0)destination=lanes.length;lanes[destination]=parent;}edges.push({from:index,to:positions.get(parent)??this.rows.length,start:lane,end:destination});});}const maxLane=Math.max(0,...nodes.map(node=>node.lane),...edges.map(edge=>edge.end));const width=Math.max(96,(maxLane+1)*20+16);return html`<mg-surface><div class="graph"><div class="chart" style=${`grid-template-columns:${width}px minmax(220px,1fr)`}><svg width=${width} height=${this.rows.length*48} role="img" aria-label="Commit ancestry graph"><title>Commit ancestry, oldest visible ancestors continue below the current page</title>${edges.map(edge=>svg`<path d=${`M ${16+edge.start*20} ${edge.from*48+24} C ${16+edge.start*20} ${edge.from*48+48}, ${16+edge.end*20} ${edge.to*48}, ${16+edge.end*20} ${edge.to*48+24}`}></path>`)}${nodes.map(node=>svg`<circle class=${this.rows[node.index].id===this.selected?'selected':''} cx=${16+node.lane*20} cy=${node.index*48+24} r="6"></circle>`)}</svg><div>${this.rows.map(row=>html`<div class="entry"><div class="copy"><div class="subject"><md-text-button @click=${()=>this.dispatchEvent(new CustomEvent('commit-select',{detail:{revision:row.id},bubbles:true,composed:true}))}>${row.label}</md-text-button></div><mg-text kind="muted">${row.data?.short} · ${row.data?.author}${row.data?.decorations?' · '+row.data.decorations:''}</mg-text></div></div>`)}</div></div>${!this.rows.length?html`<mg-text kind="muted">No commits on this page.</mg-text>`:nothing}</div></mg-surface>`;}
}
customElements.define('mg-git-history-graph',GitHistoryGraph);
