import type {GitTask} from '../shared/git';
export interface GitEditorField {key:string;label:string;type?:'boolean'|'multiline'|'number'|'choice'|'branches'|'remotes'|'tags';choices?:string[];default?:string|boolean|number;help?:string;}
export interface GitEditor {title:string;description:string;fields:GitEditorField[];}
const branch={key:'name',label:'Branch',type:'branches'} as const,revision={key:'revision',label:'Commit or reference',default:'HEAD'};
export const gitEditors:Partial<Record<GitTask,GitEditor>>={
 init:{title:'Create repository',description:'Choose a native parent directory and create a new repository folder.',fields:[{key:'name',label:'New repository folder'},{key:'branch',label:'Initial branch',default:'main'}]},clone:{title:'Clone repository',description:'Choose a native parent directory and clone an HTTPS or SSH remote into a new folder.',fields:[{key:'name',label:'New repository folder'},{key:'url',label:'HTTPS or SSH URL'},{key:'branch',label:'Optional remote branch'},{key:'depth',label:'Optional shallow history depth',type:'number'},{key:'partial',label:'Fetch file contents on demand',type:'boolean'},{key:'singleBranch',label:'Fetch a single branch',type:'boolean'}]},
 commit:{title:'Commit staged changes',description:'Create a commit from the index. Unstaged files remain in the working tree.',fields:[{key:'message',label:'Commit message',type:'multiline'},{key:'amend',label:'Amend latest commit',type:'boolean'},{key:'sign',label:'Sign commit using configured signing tool',type:'boolean'},{key:'author',label:'Override author (Name <email>)'}]},
 'branch-create':{title:'Create branch',description:'Name a branch and select its starting commit.',fields:[{key:'name',label:'New branch name'},{key:'start',label:'Starting commit or reference',default:'HEAD'},{key:'switch',label:'Switch to the new branch',type:'boolean',default:true}]},
 'branch-rename':{title:'Rename branch',description:'Rename the selected local branch.',fields:[branch,{key:'newName',label:'New branch name'}]},
 merge:{title:'Merge branch',description:'Integrate the selected branch into the current branch.',fields:[revision,{key:'mode',label:'Merge strategy',type:'choice',choices:['merge','ff-only','squash','no-ff'],default:'merge'}]},rebase:{title:'Rebase branch',description:'Replay current commits onto the selected reference. This rewrites commit identities.',fields:[revision]},'cherry-pick':{title:'Apply commit',description:'Copy the selected commit changes onto the current branch.',fields:[revision]},revert:{title:'Revert commit',description:'Create a commit that reverses the selected commit.',fields:[revision]},
 fetch:{title:'Fetch remote changes',description:'Update remote tracking references without changing local files.',fields:[{key:'remote',label:'Remote',type:'remotes'},{key:'refspec',label:'Optional source:destination refspec'},{key:'prune',label:'Prune deleted remote tracking references',type:'boolean'},{key:'tags',label:'Fetch tags',type:'boolean'}]},
 pull:{title:'Pull into current branch',description:'Fetch and integrate a selected remote branch.',fields:[{key:'remote',label:'Remote',type:'remotes'},{key:'branch',label:'Remote branch',default:'main'},{key:'mode',label:'Integration mode',type:'choice',choices:['ff-only','rebase','merge'],default:'ff-only'}]},
 push:{title:'Publish selected reference',description:'Push a single explicit source and destination. No force option is used.',fields:[{key:'remote',label:'Remote',type:'remotes'},{key:'source',label:'Local source',default:'HEAD'},{key:'destination',label:'Remote destination',default:'refs/heads/main'},{key:'setUpstream',label:'Set upstream tracking',type:'boolean'}]},
 'remote-add':{title:'Add remote',description:'Connect this repository to an HTTPS or SSH remote.',fields:[{key:'name',label:'Remote name',default:'origin'},{key:'url',label:'HTTPS or SSH URL'}]},'remote-url':{title:'Change remote URL',description:'Change the selected remote connection.',fields:[{key:'name',label:'Remote name',type:'remotes'},{key:'url',label:'HTTPS or SSH URL'}]},'remote-rename':{title:'Rename remote',description:'Rename a configured remote and its tracking references.',fields:[{key:'name',label:'Remote name',type:'remotes'},{key:'newName',label:'New remote name'}]},
 'tag-create':{title:'Create tag',description:'Mark a selected commit with a lightweight or annotated tag.',fields:[{key:'name',label:'Tag name'},revision,{key:'message',label:'Annotation message',type:'multiline'},{key:'sign',label:'Sign using configured signing tool',type:'boolean'}]},
 'stash-save':{title:'Save work in a stash',description:'Save tracked changes and restore their current base.',fields:[{key:'message',label:'Stash message'},{key:'untracked',label:'Include untracked files',type:'boolean'}]},
 'worktree-add':{title:'Add working tree',description:'A native folder picker chooses its parent. Existing files are preserved.',fields:[{key:'name',label:'New folder name'},{key:'branch',label:'Branch',type:'branches'},{key:'create',label:'Create this branch',type:'boolean'}]},'worktree-lock':{title:'Lock working tree',description:'Prevent automatic pruning or removal while the working tree is unavailable.',fields:[{key:'reason',label:'Lock reason'}]},
 'submodule-add':{title:'Add submodule',description:'Clone a nested repository and record its location.',fields:[{key:'url',label:'HTTPS or SSH URL'},{key:'path',label:'Relative submodule directory'}]},'submodule-update':{title:'Update submodule',description:'Check out the recorded nested repository revision.',fields:[{key:'path',label:'Submodule path'},{key:'init',label:'Initialize if needed',type:'boolean',default:true},{key:'recursive',label:'Include nested submodules',type:'boolean'}]},
 'bisect-start':{title:'Find regression',description:'Begin a binary search between a known good and bad commit. Check each candidate manually.',fields:[{key:'good',label:'Known good commit'},{key:'bad',label:'Known bad commit',default:'HEAD'}]},
 'sparse-set':{title:'Choose sparse directories',description:'Keep only selected tracked directory cones in this working tree.',fields:[{key:'directories',label:'Directories, one per line',type:'multiline'}]},deepen:{title:'Deepen shallow history',description:'Fetch more ancestors from a selected remote.',fields:[{key:'remote',label:'Remote',type:'remotes'},{key:'depth',label:'Additional history depth',type:'number',default:100}]},
 'patch-apply':{title:'Apply imported patch',description:'Apply the reviewed patch bytes to working files or the index.',fields:[{key:'cached',label:'Apply to index only',type:'boolean'},{key:'reverse',label:'Reverse the patch',type:'boolean'}]},'patch-am':{title:'Import mailbox commits',description:'Create commits from the imported mailbox patch. Conflicts enter the recovery workflow.',fields:[]},'format-patch':{title:'Export commit patches',description:'Write email patches to a relative directory inside the working tree.',fields:[revision,{key:'count',label:'Commit count',type:'number',default:1},{key:'directory',label:'Output directory',default:'patches'}]},
 'config-set':{title:'Set Git configuration',description:'Edit any configuration key with explicit scope. Executable settings remain visibly marked.',fields:[{key:'key',label:'Section.key'},{key:'value',label:'Value',type:'multiline'},{key:'scope',label:'Scope',type:'choice',choices:['local','worktree','global'],default:'local'}]},'config-unset':{title:'Remove Git configuration',description:'Remove the selected key only in the chosen scope.',fields:[{key:'key',label:'Section.key'},{key:'scope',label:'Scope',type:'choice',choices:['local','worktree','global'],default:'local'}]},
 maintenance:{title:'Run repository maintenance',description:'Use Git retention settings to maintain repository objects.',fields:[{key:'mode',label:'Maintenance task',type:'choice',choices:['gc','commit-graph','loose-objects','incremental-repack'],default:'commit-graph'}]},'reflog-expire':{title:'Expire old recovery entries',description:'Remove reflog entries older than a selected retention interval.',fields:[{key:'days',label:'Retention in days',type:'number',default:90}]},
 'notes-add':{title:'Add commit note',description:'Attach a note without replacing the commit.',fields:[revision,{key:'message',label:'Note',type:'multiline'}]},'notes-remove':{title:'Remove commit note',description:'Remove the selected commit note.',fields:[revision]},'replace-create':{title:'Create object replacement',description:'Redirect local object traversal through an alternate object.',fields:[revision,{key:'replacement',label:'Replacement object'}]},'replace-delete':{title:'Remove object replacement',description:'Restore normal traversal for a replaced object.',fields:[revision]},'update-ref':{title:'Update reference with expected value',description:'Atomically update a full reference only when its old object matches.',fields:[{key:'ref',label:'Full refs/ reference'},{key:'newValue',label:'New object ID'},{key:'oldValue',label:'Expected old object ID'}]},reset:{title:'Reset current branch',description:'Move HEAD to a selected commit using an explicit index and working tree mode.',fields:[revision,{key:'mode',label:'Reset mode',type:'choice',choices:['soft','mixed','hard','keep','merge'],default:'mixed'}]}
};
