import {LitElement,html,css,nothing} from './material';import './components';import {resolvedGitSettingChoices} from '../shared/git-reference-inspect';import type {GitRow} from '../shared/git';
const yue:Record<string,string>={'Reference name to validate':'要檢查嘅參照名稱','Validate a branch name':'檢查分支名稱','Normalize a full reference':'整理完整參照','Selected branch references':'所選分支參照','List tips without history':'只列出末端版本','Additional commits (1 to 30)':'額外提交數目（1 至 30）','Resolved repository setting':'實際儲存庫設定','These values may include identity or local file paths. Inspect them only when needed; editor and pager programs are not launched.':'呢啲值可能包含身份或者本機路徑。按需要先檢查；唔會執行編輯器或者分頁器。','Difference presentation':'差異顯示方式','Summary':'摘要','Names and states':'名稱同狀態','Object and mode records':'物件同模式記錄','Patch':'修補內容','Ignore whitespace changes':'忽略空白變更','Compare the selected tree to the index':'將所選樹同索引比較'};
export class GitReferenceControls extends LitElement {
 static properties={kind:{},fields:{attribute:false},branches:{attribute:false},disabled:{type:Boolean},language:{}};kind='';fields:Record<string,unknown>={};branches:GitRow[]=[];disabled=false;language='en';
 static styles=css`:host{display:block;min-width:0;color:var(--md-sys-color-on-surface,#18201b)}.fields,.references{display:grid;gap:12px}.fields{grid-template-columns:repeat(2,minmax(0,1fr))}.flag{display:flex;gap:8px;align-items:center}.references{max-height:240px;overflow:auto;scrollbar-width:thin;scrollbar-color:var(--md-sys-color-primary,#006b55) transparent}.references::-webkit-scrollbar{width:8px}.references::-webkit-scrollbar-thumb{background:var(--md-sys-color-primary,#006b55);border-radius:8px}md-outlined-select,md-outlined-text-field{min-width:0;width:100%}@media(max-width:680px){.fields{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*{transition:none!important;animation:none!important}}`;
 private label(text:string){return this.language==='yue'?yue[text]||text:this.language==='both'&&yue[text]?text+' · '+yue[text]:text;}
 private set(key:string,value:unknown){this.dispatchEvent(new CustomEvent('inspection-fields',{detail:{fields:{...this.fields,[key]:value}},bubbles:true,composed:true}));}
 private flag(key:string,label:string,fallback=false){return html`<label class="flag"><md-checkbox aria-label=${this.label(label)} ?checked=${this.fields[key]===undefined?fallback:!!this.fields[key]} ?disabled=${this.disabled} @change=${(event:Event)=>this.set(key,(event.target as HTMLInputElement).checked)}></md-checkbox>${this.label(label)}</label>`;}
 render(){if(this.kind==='validate-reference')return html`<div class="fields"><md-outlined-text-field label=${this.label('Reference name to validate')} .value=${String(this.fields.candidate??'refs/heads/main')} ?disabled=${this.disabled} @input=${(event:Event)=>this.set('candidate',(event.target as HTMLInputElement).value)}></md-outlined-text-field></div>${this.flag('branch','Validate a branch name')}${this.flag('normalize','Normalize a full reference')}`;
 if(this.kind==='branch-summary'){const selected=(this.fields.references as string[]|undefined)??['HEAD'];return html`<mg-text kind="title-small">${this.label('Selected branch references')}</mg-text><div class="references">${[{id:'HEAD',label:'HEAD',detail:''},...this.branches].map(row=>html`<label class="flag"><md-checkbox aria-label=${row.label} ?checked=${selected.includes(row.id)} ?disabled=${this.disabled||(!selected.includes(row.id)&&selected.length>=10)} @change=${(event:Event)=>this.set('references',(event.target as HTMLInputElement).checked?[...selected,row.id]:selected.filter(value=>value!==row.id))}></md-checkbox>${row.label}</label>`)}</div>${this.flag('list','List tips without history')}<md-outlined-text-field type="number" min="1" max="30" label=${this.label('Additional commits (1 to 30)')} .value=${String(this.fields.more??10)} ?disabled=${this.disabled} @input=${(event:Event)=>this.set('more',Number((event.target as HTMLInputElement).value))}></md-outlined-text-field>`;}
 if(this.kind==='resolved-setting')return html`<mg-text kind="muted">${this.label('These values may include identity or local file paths. Inspect them only when needed; editor and pager programs are not launched.')}</mg-text><md-outlined-select label=${this.label('Resolved repository setting')} .value=${String(this.fields.setting??'GIT_DEFAULT_BRANCH')} ?disabled=${this.disabled} @change=${(event:Event)=>this.set('setting',(event.target as HTMLSelectElement).value)}>${resolvedGitSettingChoices.map(([value,en,translated])=>html`<md-select-option value=${value}><div slot="headline">${this.language==='yue'?translated:this.language==='both'?en+' · '+translated:en}</div></md-select-option>`)}</md-outlined-select>`;
 if(this.kind==='index-working-diff'||this.kind==='tree-index-diff')return html`<md-outlined-select label=${this.label('Difference presentation')} .value=${String(this.fields.output??'stat')} ?disabled=${this.disabled} @change=${(event:Event)=>this.set('output',(event.target as HTMLSelectElement).value)}>${[['stat','Summary'],['name-status','Names and states'],['raw','Object and mode records'],['patch','Patch']].map(([value,label])=>html`<md-select-option value=${value}><div slot="headline">${this.label(label)}</div></md-select-option>`)}</md-outlined-select>${this.flag('ignoreWhitespace','Ignore whitespace changes')}${this.kind==='tree-index-diff'?this.flag('cached','Compare the selected tree to the index',true):nothing}`;return nothing;}
}
customElements.define('mg-git-reference-controls',GitReferenceControls);
