import {LitElement,html,css,nothing} from './material';
import {keyed} from 'lit/directives/keyed.js';
import './components';import './git-workspace';
import {defaults} from '../shared/preferences';
import type {AppSettings} from '../shared/types';
import type {GitHubLocalSourceAction,GitHubPayload} from '../shared/github';
import {localizePair} from './localization';

export interface GitHubGitSelection {action:GitHubLocalSourceAction;payload:GitHubPayload;title:string}
interface SourceSummary {providerTargetId:string;kind:'repository'|'gist'|'pull-request';hostname:string;name:string;expiresAt:string;repository?:string;number?:number;headSha?:string}
interface ScopedGitElement extends HTMLElement {discardDraft:()=>Promise<boolean>}
/** Selected provider records feed reviewed native Git tasks through opaque source receipts. */
export class MaterialGitHubGitHandoff extends LitElement {
 static properties={selection:{attribute:false},settings:{attribute:false},schoolMode:{type:Boolean},summary:{state:true},loading:{state:true},busy:{state:true},dirty:{state:true},discarding:{state:true},error:{state:true}};
 selection?:GitHubGitSelection;settings:AppSettings={...defaults};schoolMode=false;summary?:SourceSummary;loading=false;busy=false;dirty=false;discarding=false;error='';private seed?:{name:string};private generation=0;private loadedSelection?:GitHubGitSelection;
 static styles=css`:host{display:block;min-width:0}.handoff{display:grid;gap:12px;min-width:0}mg-text{overflow-wrap:anywhere}.error{color:var(--md-sys-color-error)}mg-git-workspace{display:block;min-height:480px;height:720px;max-height:80vh}.actions{display:flex;gap:8px;flex-wrap:wrap}`;
 private copy(en:string,yue:string){return localizePair(en,yue,this.schoolMode?{...this.settings,language:'en'}:this.settings);}
 private get working(){return this.loading||this.busy||this.discarding;}
 private state(){this.dispatchEvent(new CustomEvent('github-git-handoff-work-state',{detail:{busy:this.working,dirty:this.dirty},bubbles:true,composed:true}));}
 protected updated(changes:Map<PropertyKey,unknown>){if(changes.has('selection')&&this.selection&&this.selection!==this.loadedSelection){if(this.loadedSelection&&(this.working||this.dirty)){this.selection=this.loadedSelection;this.error=this.copy('Finish or discard the current local task before replacing its selected source.','更換所選來源前，請完成或放棄目前本地工作。');return;}this.loadedSelection=this.selection;void this.readSource();}}
 disconnectedCallback(){this.generation++;if(this.summary)void window.material.github('provider-source-discard',{id:this.summary.providerTargetId}).catch(()=>{});super.disconnectedCallback();}
 private async readSource(){if(!this.selection||this.working||this.dirty)return;const selection=this.selection,generation=++this.generation;this.loading=true;this.error='';this.state();try{if(this.summary){await window.material.github('provider-source-discard',{id:this.summary.providerTargetId});this.summary=undefined;this.seed=undefined;}const response=await window.material.github(selection.action,selection.payload),row=response.detail;const expected=selection.action==='repositories.clone-source'?'repository':selection.action==='gists.clone-source'?'gist':'pull-request';if(!row||typeof row.providerTargetId!=='string'||row.kind!==expected||row.hostname!==selection.payload.hostname||typeof row.name!=='string'||typeof row.expiresAt!=='string')throw Error('The native provider source receipt is unavailable. Refresh the selected record.');if(generation!==this.generation){void window.material.github('provider-source-discard',{id:row.providerTargetId}).catch(()=>{});return;}this.summary=row as unknown as SourceSummary;this.seed={name:row.name};this.dirty=true;}catch(error){if(generation===this.generation)this.error=error instanceof Error?error.message:String(error);}finally{if(generation===this.generation){this.loading=false;this.state();}}}
 private childState(event:CustomEvent<{busy:boolean;dirty:boolean}>){event.stopPropagation();this.busy=event.detail.busy;this.dirty=event.detail.dirty;this.state();}
 /** Call only after the owning workspace has saved its native discard receipt. */
 async discardDrafts():Promise<boolean>{if(this.working)return false;this.discarding=true;this.state();try{if(this.summary)await window.material.github('provider-source-discard',{id:this.summary.providerTargetId});const child=this.renderRoot.querySelector('mg-git-workspace') as ScopedGitElement|null;if(child&&!await child.discardDraft())return false;this.summary=undefined;this.seed=undefined;this.dirty=false;this.error='';return true;}catch(error){this.error=error instanceof Error?error.message:this.copy('The local draft could not be discarded. Its editor remains open.','無法放棄本地草稿，編輯器會保持開啟。');return false;}finally{this.discarding=false;this.state();}}
 render(){const checkout=this.selection?.action==='pulls.checkout-source';return html`<div class="handoff"><mg-text kind="title">${checkout?this.copy('Check out the selected pull request','檢出所選拉取要求'):this.copy('Clone the selected source locally','將所選來源複製到本地')}</mg-text><mg-text>${this.selection?.title}</mg-text><mg-text kind="muted">${this.copy('GitHub API sign-in identifies this source. Git uses its own transport credentials. Private repositories may require reviewed trust in configured credential helpers and Accounts → Set up Git authentication. Credential and transport failures remain failed operations.','GitHub API 登入用於識別來源。Git 使用自己嘅傳輸憑證。私人儲存庫可能需要檢查並信任已設定憑證助手，再喺帳戶設定 Git 驗證。憑證或傳輸失敗會維持失敗結果。')}</mg-text><mg-text kind="muted">${checkout?this.copy('Review selects an existing local repository with the native folder picker, verifies its remote and clean state, then prepares the exact selected PR head. Fetching and switching require Apply; no branch is forced or existing work discarded.','檢查會透過原生資料夾選擇器揀現有本地儲存庫，驗證遠端同乾淨狀態，再準備所選 PR 嘅確切提交。擷取同切換需要套用，唔會強制分支或丟棄現有工作。'):this.copy('Review chooses a parent directory with the native picker. Apply creates a new folder; an existing destination is preserved. The selected provider URL is fixed by the native receipt.','檢查會透過原生選擇器揀父資料夾，套用後建立新資料夾，保留現有目的地。所選提供者網址由原生記錄固定。')}</mg-text>${this.loading?html`<md-linear-progress indeterminate aria-label=${this.copy('Reading selected local source','讀取所選本地來源')}></md-linear-progress>`:nothing}${this.error?html`<mg-text class="error" role="alert">${this.error}</mg-text>`:nothing}<div class="actions"><md-outlined-button ?disabled=${this.working||this.dirty} @click=${()=>this.readSource()}>${this.copy('Refresh source','重新整理來源')}</md-outlined-button><md-outlined-button ?disabled=${this.working} @click=${()=>window.dispatchEvent(new CustomEvent('open-accounts'))}>${this.copy('Accounts and Git authentication','帳戶同 Git 驗證')}</md-outlined-button></div>${this.summary?html`<mg-text kind="muted">${this.summary.hostname} · ${this.summary.repository||this.summary.name}${this.summary.number?` · #${this.summary.number}`:''}</mg-text>${this.summary.headSha?html`<mg-text kind="code">${this.summary.headSha}</mg-text>`:nothing}<mg-text kind="muted">${this.copy('Source review expires','來源檢查到期時間')}: ${this.summary.expiresAt}</mg-text>${keyed(this.summary.providerTargetId,html`<mg-git-workspace .providerTargetId=${this.summary.providerTargetId} .task=${checkout?'provider-checkout':'clone'} .fields=${this.seed} .settings=${this.schoolMode?{...this.settings,language:'en'}:(this.settings||defaults)} @git-work-state=${this.childState}></mg-git-workspace>`)} `:nothing}</div>`;}
}
customElements.define('mg-github-git-handoff',MaterialGitHubGitHandoff);
