import {LitElement,html,css,nothing} from 'lit';
import '@material/web/textfield/outlined-text-field.js';
import '@material/web/select/outlined-select.js';
import '@material/web/select/select-option.js';
import '@material/web/slider/slider.js';
import '@material/web/switch/switch.js';
import '@material/web/button/filled-button.js';
import '@material/web/button/text-button.js';
import type {AppSettings} from '../shared/types.js';
import {defaults} from '../shared/preferences.js';
import {t,setPersonalVocabulary} from './localization.js';
import './components.js';
export class MaterialSettings extends LitElement {
 static properties={settings:{attribute:false},schoolMode:{type:Boolean},query:{state:true},searchResults:{state:true},voices:{state:true},status:{state:true},loaded:{state:true},busy:{state:true}};
 settings:AppSettings={...defaults};schoolMode=false;query='';searchResults:Record<string,boolean>={};voices:SpeechSynthesisVoice[]=[];status='';loaded=false;busy=false;
 static styles=css`
 :host{display:block;min-width:0;color:var(--md-sys-color-on-surface);font-family:var(--md-ref-typeface-plain,system-ui,sans-serif);font-size:var(--mg-body-size,.8125rem);line-height:1.5}
 *,*::before,*::after{box-sizing:border-box}mg-layout,mg-surface,mg-text,mg-search{min-width:0;max-width:100%}mg-text,p,h2,h3,label,small{overflow-wrap:anywhere}
 md-outlined-text-field,md-outlined-select,md-filled-select{min-width:0;max-width:100%;--md-outlined-text-field-container-shape:8px;--md-outlined-select-text-field-container-shape:8px;--md-filled-select-text-field-container-shape:8px;--md-outlined-text-field-input-text-size:var(--mg-body-size,.8125rem);--md-outlined-select-text-field-input-text-size:var(--mg-body-size,.8125rem)}
 md-filled-button,md-outlined-button,md-text-button{max-width:100%;--md-filled-button-container-shape:8px;--md-outlined-button-container-shape:8px;--md-text-button-container-shape:8px;--md-filled-button-label-text-size:var(--mg-body-size,.8125rem);--md-outlined-button-label-text-size:var(--mg-body-size,.8125rem);--md-text-button-label-text-size:var(--mg-body-size,.8125rem)}
 md-dialog{max-width:calc(100vw - 32px);--md-dialog-container-shape:12px;--md-dialog-container-color:var(--md-sys-color-surface-container-high)}
 ::-webkit-scrollbar{width:10px;height:10px}::-webkit-scrollbar-track{background:var(--md-sys-color-surface-container-low)}::-webkit-scrollbar-thumb{background:var(--md-sys-color-outline-variant);border:2px solid var(--md-sys-color-surface-container-low);border-radius:8px}::-webkit-scrollbar-thumb:hover{background:var(--md-sys-color-outline)}
section{display:grid;gap:12px;padding:16px}.row{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.row>*{min-width:0}md-outlined-text-field,md-outlined-select{width:100%}md-slider{min-width:min(100%,160px);max-width:100%;flex:1}p{margin:0}label{flex:1;min-width:min(100%,140px)}`;
 private enumerate=()=>{this.voices=window.speechSynthesis?.getVoices()??[];};
 connectedCallback(){super.connectedCallback();this.enumerate();window.speechSynthesis?.addEventListener('voiceschanged',this.enumerate);void window.material.vocabulary('status').then(s=>{this.loaded=s.loaded;}).catch(()=>{this.status=this.schoolMode?'':'Local vocabulary status unavailable';});}
 disconnectedCallback(){window.speechSynthesis?.removeEventListener('voiceschanged',this.enumerate);super.disconnectedCallback();}
 private async change(key:keyof AppSettings,value:unknown){try{this.settings=await window.material.settings({[key]:value});this.dispatchEvent(new CustomEvent('settings-change',{detail:this.settings,bubbles:true,composed:true}));this.status=t('saved',this.presentation);}catch(error){this.status=`${t('error',this.presentation)}: ${error instanceof Error?error.message:'Unavailable'}`;}}
 protected updated(changes:Map<PropertyKey,unknown>){if(changes.has('schoolMode')&&this.schoolMode)this.status='';}
 private get presentation():AppSettings{return this.schoolMode?{...this.settings,language:'en',englishHumor:1,cantoneseHumor:1}:this.settings;}
 private visible(key:string){if(this.schoolMode&&['language','englishHumor','cantoneseHumor','vocabulary','cantoneseVoice','narrationLanguage'].includes(key))return false;if(Object.hasOwn(this.searchResults,key))return this.searchResults[key];return (key+' '+t(key,this.presentation)).toLocaleLowerCase().includes(this.query.toLocaleLowerCase());}
 private select(key:keyof AppSettings,options:[string,string][]){return this.visible(key)?html`<md-outlined-select label=${t(key,this.presentation)} .value=${String(this.settings[key])} @change=${(e:Event)=>this.change(key,(e.target as HTMLSelectElement).value)}>${options.map(([value,label])=>html`<md-select-option value=${value}><div slot="headline">${label}</div></md-select-option>`)}</md-outlined-select>`:nothing;}
 private toggle(key:keyof AppSettings){return this.visible(key)?html`<mg-layout class="row"><mg-text id=${key}>${t(key,this.presentation)}</mg-text><md-switch aria-labelledby=${key} .selected=${Boolean(this.settings[key])} @change=${(e:Event)=>this.change(key,(e.target as unknown as {selected:boolean}).selected)}></md-switch></mg-layout>`:nothing;}
 private slider(key:keyof AppSettings,min:number,max:number,step:number){return this.visible(key)?html`<mg-layout class="row"><mg-text id=${key}>${t(key,this.presentation)}: ${this.settings[key]}</mg-text><md-slider aria-labelledby=${key} min=${min} max=${max} step=${step} .value=${Number(this.settings[key])} @change=${(e:Event)=>this.change(key,Number((e.target as HTMLInputElement).value))}></md-slider></mg-layout>`:nothing;}
 private text(key:keyof AppSettings){return this.visible(key)?html`<md-outlined-text-field label=${t(key,this.presentation)} .value=${String(this.settings[key])} @change=${(e:Event)=>this.change(key,(e.target as HTMLInputElement).value)}></md-outlined-text-field>`:nothing;}
 private async vocabulary(action:'import'|'clear'){if(this.busy)return;this.busy=true;try{const state=await window.material.vocabulary(action);this.loaded=state.loaded;setPersonalVocabulary(state.entries??{});this.dispatchEvent(new CustomEvent('vocabulary-change',{detail:state.entries??{},bubbles:true,composed:true}));this.status=t(state.loaded?'loaded':'empty',this.presentation);}catch{this.status='Invalid or unavailable local vocabulary; previous valid vocabulary retained.';}finally{this.busy=false;}}
 render(){const english=this.voices.filter(v=>/^en(?:-|$)/i.test(v.lang));const cantonese=this.voices.filter(v=>/^(yue|zh-HK)(?:-|$)/i.test(v.lang));return html`<mg-layout column aria-label=${t('settings',this.presentation)}><mg-text kind="title">${t('settings',this.presentation)}</mg-text><mg-search label=${t('search',this.presentation)} @search-change=${async(e:CustomEvent)=>{const keys=[...Object.keys(defaults),'vocabulary'];this.query=e.detail.query;const values=await (e.target as HTMLElement & {matchValues(values:string[]):Promise<boolean[]>}).matchValues(keys.map(k=>k+' '+t(k,this.presentation)));this.searchResults=Object.fromEntries(keys.map((k,i)=>[k,values[i]]));}}></mg-search>
 ${this.select('language',[['en','English'],['yue','廣東話'],['both','English · 廣東話']])}${this.select('theme',[['system','System'],['light','Light'],['dark','Dark']])}${this.select('density',[['comfortable','Comfortable'],['compact','Compact']])}${this.text('seed')}${this.text('fontFamily')}${this.slider('fontScale',.75,2,.05)}${this.text('displayName')}${this.toggle('motion')}${this.schoolMode?nothing:html`<mg-text>${t('humorDisclosure',this.presentation)}</mg-text>`}${this.slider('englishHumor',1,5,1)}${this.slider('cantoneseHumor',1,5,1)}${this.toggle('emojis')}${this.toggle('narrator')}${this.select('narrationLanguage',[['en','English'],['yue','廣東話'],['both','English · 廣東話']])}${this.select('englishVoice',[['',t('automatic',this.presentation)],...english.map(v=>[v.voiceURI,v.name+' ('+v.lang+')'] as [string,string])])}${this.select('cantoneseVoice',[['',t('automatic',this.presentation)],...cantonese.map(v=>[v.voiceURI,v.name+' ('+v.lang+')'] as [string,string])])}<mg-text>Installed English voices: ${english.length}${this.schoolMode?'':`; Hong Kong Cantonese voices: ${cantonese.length}`}. Unavailable saved voices use automatic selection.</mg-text>${this.slider('speechRate',.5,2,.1)}${this.slider('speechPitch',0,2,.1)}${['focus','lowStimulation','timeAwareness','oneThing','momentum'].map(k=>this.toggle(k as keyof AppSettings))}${this.text('currentTask')}
 ${this.visible('vocabulary')?html`<mg-text kind="title">${t('vocabulary',this.settings)}</mg-text><mg-text>${t(this.loaded?'loaded':'empty',this.settings)}. Local only; vocabulary is omitted from history and exports.</mg-text><mg-layout class="row"><md-filled-button ?disabled=${this.busy} @click=${()=>this.vocabulary('import')}>${t('import',this.settings)}</md-filled-button><md-text-button ?disabled=${this.busy||!this.loaded} @click=${()=>this.vocabulary('clear')}>${t('clear',this.settings)}</md-text-button></mg-layout>`:nothing}<mg-text role="status">${this.status}</mg-text></mg-layout>`;}
}
customElements.define('mg-settings',MaterialSettings);
