import {LitElement,html,css,nothing} from './material';
import './components';
import type {AppSettings} from '../shared/types';
import {defaults} from '../shared/preferences';
import {TaskClock,elapsedLabel,nextPendingTask,momentumChoice,momentumDefaults,showMomentum,MOMENTUM_DEFER_MS,type PendingTask} from '../shared/task-support';
import {localizePair,publishMessage} from './localization';

/** Factual session cues, independent of provider writes and persisted preference choices. */
export class TaskSupport extends LitElement {
 static properties={settings:{attribute:false},context:{type:String},lane:{type:String},label:{type:String},tasks:{attribute:false},elapsed:{state:true},paused:{state:true},cueMinutes:{state:true},cue:{state:true},changedAt:{type:Number},now:{state:true},choice:{state:true},storageError:{state:true}};
 settings:AppSettings={...defaults};context='';lane='';label='';tasks:PendingTask[]=[];elapsed=0;paused=false;cueMinutes=0;cue='';changedAt=Date.now();now=Date.now();choice={...momentumDefaults};storageError='';
 private readonly openedAt=Date.now();private clock=new TaskClock();private timer?:ReturnType<typeof setInterval>;private lastCue=0;
 static styles=css`:host{display:block;min-width:0;border-bottom:1px solid var(--md-sys-color-outline-variant);background:var(--md-sys-color-surface-container-low)}:host([hidden]){display:none}.support,.time,.next{display:flex;align-items:center;gap:8px;flex-wrap:wrap;min-width:0}.support{padding:6px 12px;transition:background-color 160ms ease}.time,.next{flex:1}.elapsed{font-variant-numeric:tabular-nums}md-outlined-select{min-width:150px;--md-outlined-select-text-field-container-shape:12px}mg-text{overflow-wrap:anywhere}.cue{flex-basis:100%}@media(prefers-reduced-motion:reduce){*{transition:none}}:host([quiet]) *{transition:none}`;
 connectedCallback(){super.connectedCallback();try{this.choice=momentumChoice(JSON.parse(localStorage.getItem('material-git.task-support.v1')||'null'));}catch{this.choice={...momentumDefaults};}this.timer=setInterval(()=>this.tick(),1000);}
 disconnectedCallback(){clearInterval(this.timer);this.clock.suspend();super.disconnectedCallback();}
 protected willUpdate(changes:Map<PropertyKey,unknown>){this.hidden=!this.settings.timeAwareness&&!this.settings.momentum;this.toggleAttribute('quiet',this.settings.lowStimulation||!this.settings.motion);this.clock.select(this.context,this.settings.timeAwareness&&this.isConnected);if(changes.has('context')){this.lastCue=0;this.cue='';}this.elapsed=this.clock.elapsed;this.paused=this.clock.paused;}
 private copy(en:string,yue:string){return localizePair(en,yue,this.settings);}
 private tick(){this.now=Date.now();this.elapsed=this.clock.elapsed;if(!this.settings.timeAwareness||!this.cueMinutes||this.paused)return;const interval=this.cueMinutes*60000,step=Math.floor(this.elapsed/interval);if(step>this.lastCue){this.lastCue=step;const minutes=step*this.cueMinutes;this.cue=this.copy(`${minutes} minutes of active time on this task.`, `呢個工作已用咗 ${minutes} 分鐘活動時間。`);if(!this.settings.lowStimulation)publishMessage(this,'progress',{en:`${minutes} minutes of active time on this task.`,yue:`呢個工作已用咗 ${minutes} 分鐘活動時間。`});}}
 private defer(dismiss=false){this.now=Date.now();this.choice={version:1,deferUntil:dismiss?0:this.now+MOMENTUM_DEFER_MS,dismissedChange:dismiss?this.changedAt:0};try{localStorage.setItem('material-git.task-support.v1',JSON.stringify(this.choice));this.storageError='';}catch{this.storageError=this.copy('This choice applies in this window only because local storage is unavailable.','本機儲存無法使用，呢個選擇只會喺目前視窗生效。');}}
 private navigate(id:string){this.dispatchEvent(new CustomEvent('workspace-navigate',{detail:id,bubbles:true,composed:true}));}
 render(){if(this.hidden)return nothing;const pending=nextPendingTask(this.tasks,this.lane),prompt=showMomentum(this.now,this.changedAt,this.choice,this.tasks.some(task=>task.busy));return html`<div class="support" role="region" aria-label=${this.copy('Task support','工作支援')}>
 ${this.settings.timeAwareness?html`<div class="time"><mg-icon name="history"></mg-icon><mg-text class="elapsed" aria-live="off">${this.copy('Session open','工作階段已開啟')} ${elapsedLabel(this.now-this.openedAt)} · ${this.copy('Since last change','距離上次變更')} ${elapsedLabel(this.now-this.changedAt)}</mg-text><mg-text class="elapsed" aria-live="off">${this.copy('Active time','活動時間')} ${elapsedLabel(this.elapsed)} · ${this.label}</mg-text><md-text-button @click=${()=>{if(this.clock.paused)this.clock.resume();else this.clock.pause();this.paused=this.clock.paused;}}>${this.paused?this.copy('Resume timer','繼續計時'):this.copy('Pause timer','暫停計時')}</md-text-button><md-text-button @click=${()=>{this.clock.reset();this.elapsed=0;this.lastCue=0;this.cue='';}}>${this.copy('Reset timer','重設計時')}</md-text-button><md-chip-set aria-label=${this.copy('Session time cue','今次時間提示')}>${[0,5,15,30,60].map(minutes=>html`<md-filter-chip ?selected=${this.cueMinutes===minutes} label=${minutes?this.copy(`Every ${minutes} minutes`,`每 ${minutes} 分鐘`):this.copy('No time cue','唔提示時間')} @click=${()=>{this.cueMinutes=minutes;this.lastCue=minutes?Math.floor(this.elapsed/(minutes*60000)):0;this.cue='';}}></md-filter-chip>`)}</md-chip-set></div>`:nothing}
 ${this.settings.momentum?html`<div class="next"><mg-icon name="forward"></mg-icon>${prompt?html`<mg-text>${this.copy(`Nothing has changed here for ${Math.floor((this.now-this.changedAt)/60000)} minutes.`,`呢度已經 ${Math.floor((this.now-this.changedAt)/60000)} 分鐘冇變更。`)} ${pending?this.copy(`An unfinished task is open in ${pending.label}.`,`「${pending.label}」有未完成工作。`):this.copy('Your current workspace remains open.','目前工作區仍然開啟。')}</mg-text>${pending?html`<md-text-button @click=${()=>this.navigate(pending.id)}>${this.copy('Open task','開啟工作')}</md-text-button>`:nothing}<md-text-button @click=${()=>this.defer()}>${this.copy('Not now, for one hour','一個鐘內唔提示')}</md-text-button><md-text-button @click=${()=>this.defer(true)}>${this.copy('Dismiss until the next change','下次變更前唔提示')}</md-text-button>`:html`<mg-text kind="muted">${this.choice.deferUntil>this.now?this.copy('Momentum paused until ','持續推進提示暫停至 ')+new Date(this.choice.deferUntil).toLocaleTimeString():this.choice.dismissedChange>=this.changedAt?this.copy('Momentum dismissed until the next change.','下次變更前唔會顯示持續推進提示。'):this.copy('Momentum gives a quiet prompt after 15 minutes without a change.','15 分鐘冇變更後，持續推進會顯示簡短提示。')}</mg-text>`}${this.storageError?html`<mg-text role="status">${this.storageError}</mg-text>`:nothing}</div>`:nothing}
 ${this.cue&&this.settings.timeAwareness?html`<mg-text class="cue" role="status">${this.cue}</mg-text>`:nothing}</div>`;}
}
customElements.define('mg-task-support',TaskSupport);
