import {LitElement,html,css} from './material';
import './components';
import './converters';
import './ollama';
import './copilot';
import type {AppSettings} from '../shared/types';
import {defaults} from '../shared/preferences';
import {localizePair} from './localization';
export class MaterialTools extends LitElement{
 static properties={hostname:{type:String},settings:{attribute:false},schoolMode:{type:Boolean},sample:{state:true},regexResult:{state:true},regexStatus:{state:true},tab:{state:true}};
 hostname='github.com';settings:AppSettings={...defaults};schoolMode=false;sample='';regexResult='';regexStatus:'empty'|'matches'|'none'|'error'='empty';tab=0;
 private childStates:Record<string,{busy:boolean;dirty:boolean}>={};
 private childState(scope:string,event:CustomEvent<{busy?:boolean;dirty?:boolean}>){event.stopPropagation();this.childStates={...this.childStates,[scope]:{busy:event.detail.busy===true,dirty:event.detail.dirty===true}};this.dispatchEvent(new CustomEvent('tools-work-state',{detail:{busy:Object.values(this.childStates).some(state=>state.busy),dirty:Object.values(this.childStates).some(state=>state.dirty)},bubbles:true,composed:true}));}
 public discardDrafts(){(this.renderRoot.querySelector('mg-copilot-workspace') as HTMLElement&{discardDrafts():void}|null)?.discardDrafts();}
 private copy(en:string,yue:string){return localizePair(en,yue,this.schoolMode?{...this.settings,language:'en'}:this.settings);}
 static styles=css`
 :host{display:block;min-width:0;color:var(--md-sys-color-on-surface);font-family:var(--md-ref-typeface-plain,system-ui,sans-serif);font-size:var(--mg-body-size,.8125rem);line-height:1.5}
 *,*::before,*::after{box-sizing:border-box}mg-layout,mg-surface,mg-text,mg-search{min-width:0;max-width:100%}mg-text,p,h2,h3,label,small{overflow-wrap:anywhere}
 md-outlined-text-field,md-outlined-select,md-filled-select{min-width:0;max-width:100%;--md-outlined-text-field-container-shape:8px;--md-outlined-select-text-field-container-shape:8px;--md-filled-select-text-field-container-shape:8px;--md-outlined-text-field-input-text-size:var(--mg-body-size,.8125rem);--md-outlined-select-text-field-input-text-size:var(--mg-body-size,.8125rem)}
 md-filled-button,md-outlined-button,md-text-button{max-width:100%;--md-filled-button-container-shape:8px;--md-outlined-button-container-shape:8px;--md-text-button-container-shape:8px;--md-filled-button-label-text-size:var(--mg-body-size,.8125rem);--md-outlined-button-label-text-size:var(--mg-body-size,.8125rem);--md-text-button-label-text-size:var(--mg-body-size,.8125rem)}
 md-dialog{max-width:calc(100vw - 32px);--md-dialog-container-shape:12px;--md-dialog-container-color:var(--md-sys-color-surface-container-high)}
 ::-webkit-scrollbar{width:10px;height:10px}::-webkit-scrollbar-track{background:var(--md-sys-color-surface-container-low)}::-webkit-scrollbar-thumb{background:var(--md-sys-color-outline-variant);border:2px solid var(--md-sys-color-surface-container-low);border-radius:8px}::-webkit-scrollbar-thumb:hover{background:var(--md-sys-color-outline)}
[hidden]{display:none!important}mg-layout{gap:12px;padding:16px}mg-layout mg-layout{padding:0}md-outlined-text-field{width:100%}md-tabs{max-width:100%;margin-bottom:0;--md-primary-tab-label-text-size:var(--mg-body-size,.8125rem)}`;
 render(){return html`<mg-layout column aria-label=${this.copy('Local tools','本機工具')}><md-tabs role="tablist" aria-label=${this.copy('Local tool workspaces','本機工具工作區')} .activeTabIndex=${this.tab} @change=${(event:Event)=>this.tab=(event.target as HTMLElement&{activeTabIndex:number}).activeTabIndex}><md-primary-tab role="tab" aria-selected=${this.tab===0?'true':'false'} .active=${this.tab===0}>${this.copy('Regular expressions','正則表達式')}</md-primary-tab><md-primary-tab role="tab" aria-selected=${this.tab===1?'true':'false'} .active=${this.tab===1}>${this.copy('Converters','轉換工具')}</md-primary-tab><md-primary-tab role="tab" aria-selected=${this.tab===2?'true':'false'} .active=${this.tab===2}>${this.copy('Local models','本機模型')}</md-primary-tab><md-primary-tab role="tab" aria-selected=${this.tab===3?'true':'false'} .active=${this.tab===3}>${this.copy('Copilot','Copilot')}</md-primary-tab></md-tabs><mg-layout column ?hidden=${this.tab!==0}><mg-text kind="title">${this.copy('Local regex workbench','本機正則表達式工作台')}</mg-text><mg-text kind="muted">${this.copy('Use the expression builder for groups, flags, captures, replacements and local snippets.','用表達式編輯器設定群組、旗標、擷取、取代同本機片段。')}</mg-text><md-outlined-text-field type="textarea" label=${this.copy('Text to test locally','喺本機測試嘅文字')} .value=${this.sample} @input=${(e:Event)=>{this.sample=(e.target as HTMLInputElement).value;}}></md-outlined-text-field><mg-search label=${this.copy('Text or regular expression','文字或正則表達式')} @search-change=${async(e:CustomEvent)=>{try{const matches=await(e.target as HTMLElement&{matchValues(values:string[]):Promise<boolean[]>}).matchValues(this.sample.split('\n'));this.regexResult=this.sample.split('\n').filter((_,i)=>matches[i]).join('\n');const error=(e.target as HTMLElement&{error?:string}).error;this.regexStatus=error?'error':matches.some(Boolean)?'matches':'none';if(error)this.regexResult=error;}catch{this.regexStatus='error';this.regexResult='';}}}></mg-search><mg-text kind="code" role="status">${this.regexStatus==='none'?this.copy('No matching lines.','未有符合嘅行。'):this.regexStatus==='error'?this.copy('Invalid or timed out expression.','表達式無效或者處理逾時。')+(this.regexResult?' '+this.regexResult:''):this.regexResult}</mg-text></mg-layout><mg-converters @tools-work-state=${(event:CustomEvent)=>this.childState('converters',event)} ?hidden=${this.tab!==1} .settings=${this.settings}></mg-converters><mg-ollama @tools-work-state=${(event:CustomEvent)=>this.childState('models',event)} ?hidden=${this.tab!==2} .settings=${this.settings} .schoolMode=${this.schoolMode}></mg-ollama><mg-copilot-workspace ?hidden=${this.tab!==3} .settings=${this.settings} .schoolMode=${this.schoolMode} .hostname=${this.hostname} @copilot-work-state=${(event:CustomEvent)=>this.childState('copilot',event)}></mg-copilot-workspace></mg-layout>`;}
}
customElements.define('mg-tools',MaterialTools);
