import {LitElement,html,css,nothing} from './material';import './components';
import type {Search} from './components';import type {AppSettings} from '../shared/types';
import {defaults,validateSettings} from '../shared/preferences';import {settingDescriptor} from '../shared/workspace-discovery';
import {localizePair,t,voiceState} from './localization';import {settingsHelp} from './settings-help';
export interface WorkspaceChoice {value:string;label:string;detail?:string}
/** An anchored, independently searched choice list. Filtering never replaces the selected value. */
export class WorkspaceChoiceControl extends LitElement {
 static properties={value:{type:String},label:{type:String},controlId:{type:String},options:{attribute:false},settings:{attribute:false},open:{state:true},matchIds:{state:true},page:{state:true},disabled:{type:Boolean}};
 value='';label='';controlId='choice';options:WorkspaceChoice[]=[];settings?:AppSettings;open=false;matchIds:string[]|null=null;page=1;disabled=false;private generation=0;
 static styles=css`:host{display:block;position:relative;min-width:0}.popup{position:absolute;inset-inline-start:0;top:100%;z-index:10;background:var(--md-sys-color-surface-container-high);border:1px solid var(--md-sys-color-outline);border-radius:12px;padding:12px;width:min(360px,calc(100vw - 60px));max-height:60vh;overflow:auto;box-shadow:var(--mg-shadow,0 6px 24px #0005)}md-list{background:transparent}md-list-item{min-height:48px;cursor:pointer}.row{display:flex;gap:8px;flex-wrap:wrap}:focus-visible{outline:2px solid var(--md-sys-color-primary)}`;
 private copy(en:string,yue:string){return localizePair(en,yue,this.settings??defaults);}
 private async toggle(){this.open=!this.open;if(this.open){await this.updateComplete;(this.renderRoot.querySelector('mg-search') as HTMLElement)?.focus();}}
 private close(){this.open=false;void this.updateComplete.then(()=>this.renderRoot.querySelector<HTMLElement>('md-outlined-button')?.focus());}
 private async search(event:Event){const generation=++this.generation,matches=await(event.target as Search).matchValues(this.options.map(option=>`${option.label} ${option.value} ${option.detail??''}`));if(generation===this.generation){this.matchIds=this.options.filter((_,i)=>matches[i]).map(option=>option.value);this.page=1;}}
 private select(value:string){this.value=value;this.dispatchEvent(new CustomEvent('value-change',{detail:value,bubbles:true,composed:true}));this.close();}
 private key(event:KeyboardEvent){if(event.key==='Escape'){event.stopPropagation();this.close();return;}if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;const options=[...this.renderRoot.querySelectorAll<HTMLElement>('[role=option]')];if(!options.length)return;event.preventDefault();const index=options.findIndex(option=>event.composedPath().includes(option));options[event.key==='Home'?0:event.key==='End'?options.length-1:(Math.max(-1,index)+(event.key==='ArrowDown'?1:-1)+options.length)%options.length]?.focus();}
 render(){const options=this.options.filter(option=>this.matchIds===null||this.matchIds.includes(option.value)),pages=Math.max(1,Math.ceil(options.length/20)),page=Math.min(this.page,pages);return html`<md-outlined-button aria-label=${this.label} aria-haspopup="listbox" aria-expanded=${this.open} ?disabled=${this.disabled} @click=${()=>this.toggle()}>${this.label}: ${this.options.find(option=>option.value===this.value)?.label??this.value??this.copy('Choose','選擇')}</md-outlined-button>${this.open?html`<div class="popup" @keydown=${this.key}><mg-search search-id=${`choice-${this.controlId}`} .label=${this.copy('Filter choices','篩選選項')} @search-change=${this.search}></mg-search><md-list role="listbox" aria-label=${this.label}>${options.slice((page-1)*20,page*20).map(option=>html`<md-list-item type="button" role="option" tabindex="0" aria-selected=${option.value===this.value} @click=${()=>this.select(option.value)} @keydown=${(event:KeyboardEvent)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();this.select(option.value);}}}><span slot="headline">${option.label}</span>${option.detail?html`<span slot="supporting-text">${option.detail}</span>`:nothing}</md-list-item>`)}</md-list><span role="status">${options.length} ${this.copy('choices','個選項')} · ${page}/${pages}</span>${!options.length?html`<p>${this.copy('No choices match this search.','冇選項符合搜尋。')}</p>`:nothing}<div class="row"><md-text-button ?disabled=${page<=1} @click=${()=>this.page=page-1}>${this.copy('Previous','上一頁')}</md-text-button><md-text-button ?disabled=${page>=pages} @click=${()=>this.page=page+1}>${this.copy('Next','下一頁')}</md-text-button><md-text-button @click=${()=>this.close()}>${this.copy('Close','關閉')}</md-text-button></div></div>`:nothing}`;}
}
customElements.define('mg-workspace-choice',WorkspaceChoiceControl);
/** The originating settings schema and native persistence path are shared by inline results. */
export class WorkspacePreferenceControl extends LitElement {
 static properties={settingKey:{type:String},settings:{attribute:false},fonts:{attribute:false},persisted:{type:Boolean},busy:{state:true},error:{state:true},voices:{state:true}};
 settingKey:keyof AppSettings='theme';settings:AppSettings={...defaults};fonts:string[]=['system-ui'];persisted=false;busy=false;error='';voices:SpeechSynthesisVoice[]=[];
 static styles=css`:host{display:block;min-width:0;max-width:100%}.row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}md-slider{min-width:180px;flex:1}md-outlined-text-field{min-width:0;max-width:240px}.hint{font-size:.75rem;color:var(--md-sys-color-on-surface-variant)}.error{color:var(--md-sys-color-error)}`;
 private enumerate=()=>{this.voices=window.speechSynthesis?.getVoices()??[];};
 connectedCallback(){super.connectedCallback();this.enumerate();window.speechSynthesis?.addEventListener('voiceschanged',this.enumerate);}
 disconnectedCallback(){window.speechSynthesis?.removeEventListener('voiceschanged',this.enumerate);super.disconnectedCallback();}
 private async change(value:unknown){if(this.busy)return;this.busy=true;this.error='';try{const patch=validateSettings({[this.settingKey]:value});this.settings=await window.material.settings(patch);this.persisted=true;this.dispatchEvent(new CustomEvent('settings-change',{detail:this.settings,bubbles:true,composed:true}));}catch{this.error=localizePair('The value is outside the settings schema. The saved value remains active.','數值超出設定規格；保留已儲存數值。',this.settings);}finally{this.busy=false;}}
 render(){const key=this.settingKey,meta=settingDescriptor(key),value=this.settings[key],label=t(key,this.settings);let options=meta.choices?.map(value=>({value,label:t(value,this.settings)}));if(key==='fontFamily')options=[...new Set([...this.fonts,String(value)])].map(value=>({value,label:value}));if(key==='englishVoice'||key==='cantoneseVoice'){const voice=voiceState(key==='englishVoice'?'en':'yue',this.settings,this.voices);options=[{value:'',label:t('automatic',this.settings)},...voice.voices.map(v=>({value:v.voiceURI,label:v.name+' ('+v.lang+')'})),...(voice.missing?[{value:String(value),label:t('voiceMissing',this.settings)}]:[])];}
 const control=typeof value==='boolean'?html`<md-switch aria-label=${label} .selected=${value} ?disabled=${this.busy} @change=${(event:Event)=>void this.change((event.target as HTMLElement&{selected:boolean}).selected)}></md-switch>`:options?html`<mg-workspace-choice .controlId=${`setting-${key}`} .label=${label} .value=${String(value)} .options=${options} .settings=${this.settings} .disabled=${this.busy} @value-change=${(event:CustomEvent<string>)=>void this.change(event.detail)}></mg-workspace-choice>`:typeof value==='number'?html`<div class="row"><md-slider aria-label=${label} .min=${meta.min!} .max=${meta.max!} .step=${meta.step} .value=${value} ?disabled=${this.busy} @change=${(event:Event)=>void this.change((event.target as HTMLElement&{value:number}).value)}></md-slider><md-outlined-text-field type="number" .label=${label} .min=${String(meta.min)} .max=${String(meta.max)} .step=${String(meta.step)} .value=${String(value)} ?disabled=${this.busy} @change=${(event:Event)=>void this.change(Number((event.target as HTMLInputElement).value))}></md-outlined-text-field></div>`:key==='logoImage'?html`<md-text-button @click=${()=>this.dispatchEvent(new CustomEvent('control-route',{detail:{lane:'settings',setting:key},bubbles:true,composed:true}))}>${t('uploadLogo',this.settings)}</md-text-button><p class="hint">${t('logoNotice',this.settings)}</p>`:html`<div class="row">${key==='seed'?html`<label>${label}<input type="color" aria-label=${label} .value=${String(value)} ?disabled=${this.busy} @change=${(event:Event)=>void this.change((event.target as HTMLInputElement).value)}></label>`:nothing}<md-outlined-text-field .label=${label} .value=${String(value)} ?disabled=${this.busy} @change=${(event:Event)=>void this.change((event.target as HTMLInputElement).value)}></md-outlined-text-field></div>`;
 const help=settingsHelp[key];return html`${control}<p class="hint">${this.persisted?localizePair('Saved on this device','已儲存喺呢部裝置',this.settings):localizePair('Compiled default','內置預設',this.settings)}: ${key==='logoImage'?(value?t('loaded',this.settings):t('empty',this.settings)):String(value)}</p>${help?html`<details><summary>${localizePair('Help','說明',this.settings)}</summary>${localizePair(help[0],help[1],this.settings)}</details>`:nothing}${this.error?html`<p class="error" role="alert">${this.error}</p>`:nothing}`;}
}
customElements.define('mg-workspace-preference',WorkspacePreferenceControl);
